force-app/main/default/objects/Client_Capital_and_Revenue__c/Client_Capital_and_Revenue__c.object-meta.xml
<CustomObject>
    <description>Case #1263 - Client Overview - Stores Client Capital Utilization and ROE / CROC data that is fed into salesforce on a monthly basis by CRT. The data from this object should only be shown on the client overview page and only be visible to the client owner and members on the client service team.</description>
    <label>Client Capital and Revenue</label>
    <nameField>
        <displayFormat>CCR-{0000000000}</displayFormat>
        <label>Client Capital and Revenue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Capital and Revenue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Capital_and_Revenue__c/fields/Capital_Utilisation_USD__c.field-meta.xml
<CustomField>
    <fullName>Capital_Utilisation_USD__c</fullName>
    <description>Used to store the Capital Utilisation in ZAR</description>
    <label>Capital Utilisation USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Capital_and_Revenue__c/fields/Capital_Utilisation_ZAR__c.field-meta.xml
<CustomField>
    <fullName>Capital_Utilisation_ZAR__c</fullName>
    <description>Used to store the Capital Utilisation in ZAR</description>
    <label>Capital Utilisation ZAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Capital_and_Revenue__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to Client Object</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Capital and Revenue</relationshipLabel>
    <relationshipName>Client_Capital_and_Revenue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Capital_and_Revenue__c/fields/CROC_ZAR__c.field-meta.xml
<CustomField>
    <fullName>CROC_ZAR__c</fullName>
    <description>Used to store CROC in ZAR</description>
    <label>CROC ZAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Financial_Analysis__c/Client_Financial_Analysis__c.object-meta.xml
<CustomObject>
    <description>Object to capture the Publicly available financial information for the client to be displayed on the Client Plan</description>
    <label>Client Financial Analysis</label>
    <nameField>
        <displayFormat>PFA-{0000}</displayFormat>
        <label>Client Financial Analysis Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Financial Analysis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Financial_Analysis__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <description>Lookup to the client to create the relationship between Client</description>
    <inlineHelpText>Return on Equity - provide the details as produced by the Client Management Information or TCM teams</inlineHelpText>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Public_Financial_Analysis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Financial_Analysis__c/fields/Statement_Date__c.field-meta.xml
<CustomField>
    <fullName>Statement_Date__c</fullName>
    <description>Financial Year</description>
    <inlineHelpText>The Statement Date is the date at which the public financial analysis information is published</inlineHelpText>
    <label>Statement Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Financial_Analysis__c/fields/Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Revenue__c</fullName>
    <description>Total Client Revenue</description>
    <inlineHelpText>Total Client Revenue</inlineHelpText>
    <label>Total Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Client_Plan__c/Client_Plan__c.object-meta.xml
<CustomObject>
    <label>Client Plan</label>
    <nameField>
        <label>Client Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Plan__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <description>Field that stores Client Plan object relationship with Client Object</description>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Plan</relationshipLabel>
    <relationshipName>Client_Plan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Credit_Line__c/Credit_Line__c.object-meta.xml
<CustomObject>
    <description>Credit Lines will be added to the Client page and displayed on the Client Plan.</description>
    <label>Credit Line</label>
    <nameField>
        <displayFormat>CL-{000}</displayFormat>
        <label>Credit Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Line__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Lines</relationshipLabel>
    <relationshipName>Credit_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Line__c/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <description>Total Credit Limit of the Facilty on this Client - provide the details as recorded in Adaptive</description>
    <inlineHelpText>Total Credit Limit of the Facilty on this Client - provide the details as recorded in Adaptive</inlineHelpText>
    <label>Credit Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Related Product on which we hold this Facility - provide the details as recorded in Adaptive</description>
    <inlineHelpText>Related Product on which we hold this Facility - provide the details as recorded in Adaptive</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>American Depository Receipt</fullName>
            </value>
            <value>
                <fullName>Bond Position</fullName>
            </value>
            <value>
                <fullName>Cape</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debtor Finance</fullName>
            </value>
            <value>
                <fullName>Deposits Held</fullName>
            </value>
            <value>
                <fullName>Equity Position</fullName>
            </value>
            <value>
                <fullName>Financial Guarantee - Given</fullName>
            </value>
            <value>
                <fullName>Fleet Management Card</fullName>
            </value>
            <value>
                <fullName>Foreign Notes</fullName>
            </value>
            <value>
                <fullName>Forfaiting</fullName>
            </value>
            <value>
                <fullName>General Short Term Banking Facilities</fullName>
            </value>
            <value>
                <fullName>Guarantee - Inward</fullName>
            </value>
            <value>
                <fullName>LC</fullName>
            </value>
            <value>
                <fullName>Metal Lease</fullName>
            </value>
            <value>
                <fullName>Money Market</fullName>
            </value>
            <value>
                <fullName>Net Trading Positions</fullName>
            </value>
            <value>
                <fullName>Non-Disclosed Finance</fullName>
            </value>
            <value>
                <fullName>Payment Settlement</fullName>
            </value>
            <value>
                <fullName>Performance Guarantee - Given</fullName>
            </value>
            <value>
                <fullName>Residential Mortgage</fullName>
            </value>
            <value>
                <fullName>Risk Participation Agreement</fullName>
            </value>
            <value>
                <fullName>Risk Transfers</fullName>
            </value>
            <value>
                <fullName>Securities Financing</fullName>
            </value>
            <value>
                <fullName>Structured Loans</fullName>
            </value>
            <value>
                <fullName>TPFA Property Guarantee-Given</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>Vehicle And Asset Finance</fullName>
            </value>
            <value>
                <fullName>Working Capital Facilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Line__c/fields/Total_utilisation__c.field-meta.xml
<CustomField>
    <fullName>Total_utilisation__c</fullName>
    <description>Total utilisation of the Facility on this Client - provide the details as recorded in Adaptive</description>
    <inlineHelpText>Total utilisation of the Facility on this Client - provide the details as recorded in Adaptive</inlineHelpText>
    <label>Total Utilisation</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FinancialAnalysisController_TestCP.cls
/*************************************************************************\
    @ Author        :     Aneske Meiring
    @ Date          :     26/09/2013
    @ Description   :     Test Class for PublicFinancialAnalysisController
    
    @ Author        :     Charles Mutsu
    @ Date          :     28/02/2013
    @description    :     Updated API version from 28 to 29
**************************************************************************/
@isTest
public class FinancialAnalysisController_TestCP{
 
    @IsTest
    static void publicFinancialAnalysisController() {
        
        TEST_DataFactory.generateConfiguration();
        
        // create standard user 
        User admUser = (User) new BLD_USER().useSysAdmin().getRecord();
        system.runAs(new User(Id = UserInfo.getUserId())){
        	insert admUser;
        }

        //create account
        List<Account> lstAcc = new List<Account> {
            (Account) new BLD_Account()
                .clientCoordinator(admUser)
                .getRecord()
        };
        insert lstAcc;
         Client_Financial_Analysis__c pfa = New Client_Financial_Analysis__c(
         Client_Name__c = lstAcc[0].Id,
         Statement_Date__c = Date.newInstance(1980 , 10 ,20),
         Total_Revenue__c = 50000
         );
           insert pfa;
           
           Client_Plan__c cplan = new Client_Plan__c();
            cplan.Client_Name__c =lstAcc[0].Id;
            insert cplan;
            
            Client_Capital_and_Revenue__c ccr = new Client_Capital_and_Revenue__c();
            ccr.Client__c = lstAcc[0].Id;
            ccr.Capital_Utilisation_USD__c =  12.23 ;
            ccr.Capital_Utilisation_ZAR__c = 23.21;
            ccr.CROC_ZAR__c = 23.33 ;
            
            insert ccr ;
           
            ccr.Client__c = lstAcc[0].Id;
            update ccr;
            
            Credit_Line__c cLine = new Credit_Line__c();
            cLine.Client_Name__c = lstAcc[0].Id;
            cLine.Credit_Limit__c = 20.22;
            cLine.Product__c = 'GBB';
            cLine.Total_utilisation__c = 22.32 ; 
            
            insert cLine ;

        Boolean isExceptionThrown = false;
        test.startTest();
        try {
            PageReference pageRef = Page.ClientPlan;
            Test.setCurrentPage(pageRef);

            ApexPages.currentPage().getParameters().put('id', lstAcc[0].Id);

            PublicFinancialAnalysisController pfaComponent = new PublicFinancialAnalysisController();
            pfaComponent.cplanFinResult = pfaComponent.getFin();
            pfaComponent.thisFinAnalysisDataId = string.valueof(lstAcc[0].Id);

            list<PublicFinancialAnalysisController.cPlanCreditLines> cPlanCL = pfaComponent.getcl();

            ApexPages.StandardController controller = new ApexPages.StandardController(lstAcc[0]);
            PublicFinancialAnalysisController pFAClass = new PublicFinancialAnalysisController(controller);
        }
        catch(Exception ex) {
            isExceptionThrown = true;
        }
        System.assert(!isExceptionThrown);
        test.stopTest();
        
    }
    
    @IsTest
    static void publicFinancialAnalysisController2() {
        
        TEST_DataFactory.generateConfiguration();
        
        // create standard user 
        User admUser = (User) new BLD_USER().useSysAdmin().getRecord();
        system.runAs(new User(Id = UserInfo.getUserId())){
        	insert admUser;
        }
        
        //create account
        List<Account> lstAcc = new List<Account> {
            (Account) new BLD_Account()
                .clientCoordinator(admUser)
                .getRecord()
        };
        insert lstAcc;
        
         Client_Financial_Analysis__c pfa = New Client_Financial_Analysis__c(
         Client_Name__c = lstAcc[0].Id, 
      //   Public_Information__c = True,
         Statement_Date__c = Date.newInstance(1980 , 10 ,20),
         Total_Revenue__c = 50000
         );
           insert pfa;
           
            Client_Plan__c cplan = new Client_Plan__c();
            cplan.Client_Name__c =lstAcc[0].Id;
            cPlan.CurrencyIsoCode = 'USD';
            insert cplan;
            
            Client_Capital_and_Revenue__c ccr = new Client_Capital_and_Revenue__c();
            ccr.Client__c = lstAcc[0].Id;
            ccr.Capital_Utilisation_USD__c =  12.23 ;
            ccr.Capital_Utilisation_ZAR__c = 23.21;
            ccr.CROC_ZAR__c = 23.33 ;
            
            insert ccr ;
           
            ccr.Client__c = lstAcc[0].Id;
            update ccr;
            
            Credit_Line__c cLine = new Credit_Line__c();
            cLine.Client_Name__c = lstAcc[0].Id;
            cLine.Credit_Limit__c = 20.22;
            cLine.Product__c = 'GBB';
            cLine.Total_utilisation__c = 22.32 ; 
            
            insert cLine ;

            Boolean isExceptionThrown = false;
            test.startTest();
            try {
                PageReference pageRef = Page.ClientPlan;
                Test.setCurrentPage(pageRef);

                ApexPages.currentPage().getParameters().put('id', lstAcc[0].Id);


                PublicFinancialAnalysisController pfaComponent = new PublicFinancialAnalysisController();
                pfaComponent.cplanFinResult = pfaComponent.getFin();
                pfaComponent.thisFinAnalysisDataId = string.valueof(lstAcc[0].Id);

                PublicFinancialAnalysisController.cPlanCreditLines cCredit = new PublicFinancialAnalysisController.cPlanCreditLines();

                PublicFinancialAnalysisController.cPlanFinAnalysis cFin = new PublicFinancialAnalysisController.cPlanFinAnalysis();

                list<PublicFinancialAnalysisController.cPlanCreditLines> cPlanCL = pfaComponent.getcl();

                ApexPages.StandardController controller = new ApexPages.StandardController(lstAcc[0]);
                PublicFinancialAnalysisController pFAClass = new PublicFinancialAnalysisController(controller);
            }
            catch(Exception ex) {
                isExceptionThrown = true;
            }
            test.stopTest();
        System.assert(!isExceptionThrown);
        
    } // end testMethod  
}