force-app/main/default/objects/Draw_Down_Profile__c/Draw_Down_Profile__c.object-meta.xml
<CustomObject>
    <description>Case#141 - When an Opportunity and a qualifying Product (Lending / Deposits / Commitments) has been loaded then the user needs to be able to capture the flows / drawdowns and the dates of these transactions on the Product.</description>
    <label>Draw Down Profile</label>
    <nameField>
        <displayFormat>DDP-{0000000000}</displayFormat>
        <label>Draw Down Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Draw Down Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Environment_Variable__c/Environment_Variable__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Environment Variables</label>
</CustomObject>

force-app/main/default/objects/Environment_Variable__c/fields/serverURL__c.field-meta.xml
<CustomField>
    <fullName>serverURL__c</fullName>
    <label>serverURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/SB_Product__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Products as Standard Bank have requirements that cannot be met with standard object.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Prod-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SB_Product__c/fields/Current_Year_CommB_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_CommB_Revenue__c</fullName>
    <description>The current year revenue that is anticipated for this product on this opportunity (EN-896).</description>
    <inlineHelpText>The current year revenue that is anticipated for this product on this opportunity.</inlineHelpText>
    <label>Current Year Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Total_Fees__c.field-meta.xml
<CustomField>
    <fullName>Total_Fees__c</fullName>
    <inlineHelpText>The Estimated Total Fees that is anticipated for this product on this opportunity.</inlineHelpText>
    <label>Total Fees</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/total_revenue_amount__c.field-meta.xml
<CustomField>
    <fullName>total_revenue_amount__c</fullName>
    <description>The revenue that is anticipated for this product&apos;s lifetime on this opportunity (EN-896).</description>
    <inlineHelpText>The revenue that is anticipated for this product&apos;s lifetime on this opportunity.</inlineHelpText>
    <label>Total Revenue (Amount)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DrawDownProductRedirect_Vf_Ext_TEST.cls
/**
 * Test class for DrawDownProductRedirect_Vf_Ext
 *
 * @author Bartosz Sliwinski (bsliwinski@deloittece.com)
 * @date December 2020
 */
@IsTest (IsParallel = true)
private with sharing class DrawDownProductRedirect_Vf_Ext_TEST {

    private static SB_Product__c prodRec {
        get {
            if (prodRec == null) {
                prodRec = [SELECT Id FROM SB_Product__c];
            }
            return prodRec;
        }
        set;
    }

    @TestSetup
    static void setupData() {
        TEST_DataFactory.insertSettings(new List<Object> {
            TEST_DataFactory.getEnvironmentVariable()
        });

        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
        new BLD_Product(uow)
            .linkToOpp(
                new BLD_Opportunity(uow)
            )
            .addDrawDownProfile(
                new BLD_DrawDownProfile(uow)
            );
        uow.commitWork();
    }

    @IsTest
    static void shouldInitializeVariables() {
        Test.startTest();
        DrawDownProductRedirect_Vf_Ext ctrl = new DrawDownProductRedirect_Vf_Ext(new ApexPages.StandardController(prodRec));
        Test.stopTest();

        System.assertEquals(1, ctrl.lstProduct.size());
        System.assertEquals(prodRec.Id, ctrl.lstProduct[0].Id);
        System.assertEquals(1, ctrl.lstDrawDown.size());
        System.assertEquals(0, ctrl.newProduct);
    }

    @IsTest
    static void shouldRecognizeProductCreationProcess() {
        PageReference pageRef = Page.DrawDownProductRedirect_Vf;
        pageRef.getHeaders().put('Referer', Environment_Variable__c.getInstance().serverURL__c + '/a0g/e');
        Test.setCurrentPage(pageRef);

        Test.startTest();
        DrawDownProductRedirect_Vf_Ext ctrl = new DrawDownProductRedirect_Vf_Ext(new ApexPages.StandardController(prodRec));
        Test.stopTest();

        System.assertEquals(1, ctrl.newProduct);
    }

    @IsTest
    static void shouldRedirectToProductViewBecauseDrawDownsExist() {
        PageReference pageRef = Page.DrawDownProductRedirect_Vf;
        Test.setCurrentPage(pageRef);

        DrawDownProductRedirect_Vf_Ext ctrl = new DrawDownProductRedirect_Vf_Ext(new ApexPages.StandardController(prodRec));

        Test.startTest();
        PageReference result = ctrl.redirect();
        Test.stopTest();

        System.assertEquals('/' + prodRec.Id + '?nooverride=1', result.getUrl());
    }

    @IsTest
    static void shouldRedirectToDrawDownCreationBecauseNoDrawDowns() {
        delete [SELECT Id FROM Draw_Down_Profile__c];

        PageReference pageRef = Page.DrawDownProductRedirect_Vf;
        Test.setCurrentPage(pageRef);

        DrawDownProductRedirect_Vf_Ext ctrl = new DrawDownProductRedirect_Vf_Ext(new ApexPages.StandardController(prodRec));

        Test.startTest();
        PageReference result = ctrl.redirect();
        Test.stopTest();

        System.assertEquals('/apex/DrawDownProfile_Vf?Id=' + prodRec.Id + '&recs=0', result.getUrl());
    }

    @IsTest
    static void shouldRedirectToProductViewBecauseRtNotInEnvironmentVariable() {
        prodRec.RecordTypeId = UTL_RecordType.getRecordTypeId(DMN_SB_Product.OBJ_NAME, DMN_SB_Product.RT_COMMB_LENDING);
        prodRec.Current_Year_CommB_Revenue__c = 2;
        prodRec.total_revenue_amount__c = 2;
        prodRec.Total_Fees__c = 3;
        update prodRec;
        prodRec = null;

        PageReference pageRef = Page.DrawDownProductRedirect_Vf;
        Test.setCurrentPage(pageRef);

        DrawDownProductRedirect_Vf_Ext ctrl = new DrawDownProductRedirect_Vf_Ext(new ApexPages.StandardController(prodRec));

        Test.startTest();
        PageReference result = ctrl.redirect();
        Test.stopTest();

        System.assertEquals('/' + prodRec.Id + '?nooverride=1', result.getUrl());
    }

}