force-app/main/default/objects/Draw_Down_Profile__c/Draw_Down_Profile__c.object-meta.xml
<CustomObject>
    <description>Case#141 - When an Opportunity and a qualifying Product (Lending / Deposits / Commitments) has been loaded then the user needs to be able to capture the flows / drawdowns and the dates of these transactions on the Product.</description>
    <label>Draw Down Profile</label>
    <nameField>
        <displayFormat>DDP-{0000000000}</displayFormat>
        <label>Draw Down Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Draw Down Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Draw_Down_Profile__c/fields/Draw_Date__c.field-meta.xml
<CustomField>
    <fullName>Draw_Date__c</fullName>
    <description>Case#141 - Rudolf Niehaus</description>
    <label>Draw Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Draw_Down_Profile__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Case#141 - Rudolf Niehaus
Master detail relationship to product (Lending / Deposits / Commitments)</description>
    <label>Product</label>
    <referenceTo>SB_Product__c</referenceTo>
    <relationshipLabel>Draw Down Profiles</relationshipLabel>
    <relationshipName>Draw_Down_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Earliest_Draw_Date_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Draw_Date_Rollup__c</fullName>
    <description>Case#141 - Rudolf Niehaus
Rollup earliest draw date of all the products</description>
    <label>Earliest Draw Date</label>
    <summarizedField>SB_Product__c.Earliest_Draw_Date_Rollup__c</summarizedField>
    <summaryForeignKey>SB_Product__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SFP-9327 [c] - A lookup field to allow the relationship manager to select the appropriate product for the opportunity</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/SB_Product__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Products as Standard Bank have requirements that cannot be met with standard object.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Prod-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SB_Product__c/fields/Draw_Date__c.field-meta.xml
<CustomField>
    <fullName>Draw_Date__c</fullName>
    <label>Draw Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Earliest_Draw_Date_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Draw_Date_Rollup__c</fullName>
    <description>Case#141 - Rudolf Niehaus Rollup to the earliest draw date this value is used to validate that the user do not enter an Estimated Close date on the Opportunity that is after the smallest draw date on the draw down profile records of the oppo product</description>
    <label>Earliest Draw Date</label>
    <summarizedField>Draw_Down_Profile__c.Draw_Date__c</summarizedField>
    <summaryForeignKey>Draw_Down_Profile__c.Product__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/DMN_DrawDownProfile.cls
/**
 * @description SFP-3882 Added syncDrawdownDatesToOppEstClosedDate to update draw down dates n relaton to the opp est closed date.
 * @author Wayne Solomon
 * @date Feb 2021
 */
@SuppressWarnings('PMD.CyclomaticComplexity,PMD.StdCyclomaticComplexity')
public class DMN_DrawDownProfile {
    public static final String FREQUENCIES_PICKLIST_CATEGORY = 'Frequency in months';

    /**
     * SGPRT-4189Keep opportunity product drawdowns in sync with changes to opportunity estimated closed date
     * @param id2NewRecords map of Trigger.new
     * @param id2OldRecords map of Trigger.old
     */
    public static void syncDrawdownDatesToOppEstClosedDate(Map<Id, Opportunity> id2NewRecords, Map<Id, Opportunity> id2OldRecords) {
        Map<Id, Draw_Down_Profile__c> oppProdDrawdownsMap = new Map<Id, Draw_Down_Profile__c>(
                SEL_DrawdownProfiles.newInstance().selectByIdsAndParentProduct(id2NewRecords.keySet())
        );
        List<Draw_Down_Profile__c> updDrawDownProfiles = new List<Draw_Down_Profile__c>();
        for (Opportunity opp : id2NewRecords.values()) {
            Date newDate = id2NewRecords.get(opp.Id).CloseDate;
            Date oldDate = id2OldRecords.get(opp.Id).CloseDate;
            Boolean closeDateChanged = newDate != oldDate;
            if (closeDateChanged) {
                for (Draw_Down_Profile__c d : oppProdDrawdownsMap.values()) {
                    Date firstDrawDate = d.Product__r.Earliest_Draw_Date_Rollup__c;
                    Boolean validDateMove = newDate > firstDrawDate;
                    if (validDateMove) {
                        Integer difference = firstDrawDate.daysBetween(newDate);
                        Date drawDate = d.Draw_Date__c;
                        updDrawDownProfiles.add(new Draw_Down_Profile__c(
                                Id = d.Id,
                                Draw_Date__c = (drawDate == firstDrawDate) ? newDate : drawDate.addDays(difference)));
                    }
                }
            }
        }
        if (!updDrawDownProfiles.isEmpty()) {
            fflib_ISObjectUnitOfWork uow = ORG_Application.unitOfWork.newInstance();
            uow.registerDirty(updDrawDownProfiles);
            uow.commitWork();
        }
    }
}