force-app/main/default/objects/Draw_Down_Profile__c/Draw_Down_Profile__c.object-meta.xml
<CustomObject>
    <description>Case#141 - When an Opportunity and a qualifying Product (Lending / Deposits / Commitments) has been loaded then the user needs to be able to capture the flows / drawdowns and the dates of these transactions on the Product.</description>
    <label>Draw Down Profile</label>
    <nameField>
        <displayFormat>DDP-{0000000000}</displayFormat>
        <label>Draw Down Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Draw Down Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Draw_Down_Profile__c/fields/Draw_Date__c.field-meta.xml
<CustomField>
    <fullName>Draw_Date__c</fullName>
    <description>Case#141 - Rudolf Niehaus</description>
    <label>Draw Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Draw_Down_Profile__c/fields/Draw_Down_Number__c.field-meta.xml
<CustomField>
    <fullName>Draw_Down_Number__c</fullName>
    <description>Case#141 - Rudolf Niehaus
This field increments for each draw down record per parent product.</description>
    <label>Draw Down Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Draw_Down_Profile__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Case#141 - Rudolf Niehaus
Master detail relationship to product (Lending / Deposits / Commitments)</description>
    <label>Product</label>
    <referenceTo>SB_Product__c</referenceTo>
    <relationshipLabel>Draw Down Profiles</relationshipLabel>
    <relationshipName>Draw_Down_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Helper_Object__c/Helper_Object__c.object-meta.xml
<CustomObject>
    <label>Helper Object</label>
    <nameField>
        <label>Helper Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helper Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DrawDownProfileDatePopulator_Ctrlr.cls
public with sharing class DrawDownProfileDatePopulator_Ctrlr {
    public Draw_Down_Profile__c[] ddProfiles {
        get;
        set {
            ddProfiles = value;
            if (existingProfiles == null) {
                existingProfiles = new Draw_Down_Profile__c[] {};
                existingProfiles.addAll(ddProfiles);
            }
        }
    }
    @TestVisible private Draw_Down_Profile__c[] existingProfiles;
    public Id prodId { get; set; }
    public String CurrencyCode { get;set; }
    public Boolean isLightning {
        get {
            return UTL_User.isLightnigUser();
        }
    }
    public Helper_Object__c startDate {
        get {
            if (startDate == null) {
                startDate = new Helper_Object__c();
            } return startDate;
        }
        set;
    }
    public Helper_Object__c endDate {
        get {
            if (endDate == null) {
                endDate = new Helper_Object__c();
            } return endDate;
        }
        set;
    }
    public SelectOption[] drawDownProfilesFrequencies { get; set; }
    public Integer selectedFrequency { get; set; }
    public Integer dDPsToBeCreated {
        get {
            if (selectedFrequency != 0
                && startDate != null && startDate.Date_Field__c != null
                && endDate != null && endDate.Date_Field__c != null) {
                Integer monthsBetween = startDate.Date_Field__c.monthsBetween(endDate.Date_Field__c);
                if (monthsBetween < 0) {
                    return 0;
                }
                dDPsToBeCreated = monthsBetween / selectedFrequency;
                Date startDatePlusMonths = startDate.Date_Field__c.addMonths(monthsBetween);
                if (startDatePlusMonths.day() <= endDate.Date_Field__c.day()) {
                    dDPsToBeCreated++;
                }
            }
            return dDPsToBeCreated;
        }
        set;
    }

    public DrawDownProfileDatePopulator_Ctrlr() {
        drawDownProfilesFrequencies = new SelectOption[] {
            new SelectOption('0', '-- SELECT ONE --')
        };
        drawDownProfilesFrequencies.addAll(
            UTL_GlobalPicklistValues.getPicklist(DMN_DrawDownProfile.FREQUENCIES_PICKLIST_CATEGORY));
    }

    public void createDrawDownProfiles() {
        if (startDate.Date_Field__c == null || endDate.Date_Field__c == null || selectedFrequency == null || selectedFrequency == 0) {
            ApexPages.addMessage(
                new ApexPages.Message(
                    ApexPages.Severity.ERROR, 'Please ensure First Draw Date, Last Draw Date and Frequency fields are completed'));
            return;
        }

        Draw_Down_Profile__c[] refreshedList = new Draw_Down_Profile__c[] {};
        for (Integer i = 0; i < dDPsToBeCreated; i++) {
            Draw_Down_Profile__c dd;
            if (i < existingProfiles.size()) {
                dd = existingProfiles[i];
            }
            else if (i < ddProfiles.size()) {
                dd = ddProfiles[i];
            }
            else {
                dd = new Draw_Down_Profile__c(
                    Product__c = prodId,
                    currencyIsoCode = CurrencyCode,
                    Draw_Down_Number__c = i+1
                );
            }
            dd.Draw_Date__c = startDate.Date_Field__c.addMonths(selectedFrequency * i);
            refreshedList.add(dd);
        }
        ddProfiles.clear();
        ddProfiles.addAll(refreshedList);
    }

}