force-app/main/default/objects/Draw_Down_Profile__c/Draw_Down_Profile__c.object-meta.xml
<CustomObject>
    <description>Case#141 - When an Opportunity and a qualifying Product (Lending / Deposits / Commitments) has been loaded then the user needs to be able to capture the flows / drawdowns and the dates of these transactions on the Product.</description>
    <label>Draw Down Profile</label>
    <nameField>
        <displayFormat>DDP-{0000000000}</displayFormat>
        <label>Draw Down Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Draw Down Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Draw_Down_Profile__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Case#141 - Rudolf Niehaus
Master detail relationship to product (Lending / Deposits / Commitments)</description>
    <label>Product</label>
    <referenceTo>SB_Product__c</referenceTo>
    <relationshipLabel>Draw Down Profiles</relationshipLabel>
    <relationshipName>Draw_Down_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DrawDownRedirect_Vf_Ext_Test.cls
@isTest
public with sharing class DrawDownRedirect_Vf_Ext_Test {
    private static final String USER_NAME = 'DrawDownRedirect_Vf_Ext_Test@example.com';
    private static User testUser {
        get {
            if (testUser == null) {
                testUser = [SELECT Id FROM User WHERE Username = :USER_NAME];
            }
            return testUser;
        }
        set;
    }

    @TestSetup
    static void setup() {

        new BLD_USER(USER_NAME).useCib().commitWork();

        System.runAs(testUser) {
            fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
            BLD_Product prodBld = new BLD_Product(uow)
                .linkToOpp(new BLD_Opportunity(uow));

            for (Integer i = 0; i < 5; i++) {
                new BLD_DrawDownProfile(uow).linkToProduct(prodBld);
            }
            uow.commitWork();
        }
    }

    @IsTest
    static void shouldInitializeController() {
        Draw_Down_Profile__c ddProfile = [SELECT Id, Product__c FROM Draw_Down_Profile__c LIMIT 1];
      
        Test.setCurrentPage(Page.DrawDownRedirect_Vf);        
        ApexPages.currentPage().getParameters().put('id', ddProfile.Product__c);
        DrawDownRedirect_Vf_Ext drawDownRedirect_Vf_Ext;

        Test.startTest();

        ApexPages.StandardController controller;

        System.runAs(testUser) {
        controller = new ApexPages.StandardController(ddProfile);
        drawDownRedirect_Vf_Ext = new DrawDownRedirect_Vf_Ext(controller);    
        drawDownRedirect_Vf_Ext.redirect();
        }     

        Id currentPageId = ApexPages.currentPage().getParameters().get('id');

        System.assertEquals(currentPageId, ddProfile.Product__c);

        Test.stopTest();
    }

}