force-app/main/default/objects/Draw_Down_Profile__c/Draw_Down_Profile__c.object-meta.xml
<CustomObject>
    <description>Case#141 - When an Opportunity and a qualifying Product (Lending / Deposits / Commitments) has been loaded then the user needs to be able to capture the flows / drawdowns and the dates of these transactions on the Product.</description>
    <label>Draw Down Profile</label>
    <nameField>
        <displayFormat>DDP-{0000000000}</displayFormat>
        <label>Draw Down Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Draw Down Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Draw_Down_Profile__c/fields/Draw_Date__c.field-meta.xml
<CustomField>
    <fullName>Draw_Date__c</fullName>
    <description>Case#141 - Rudolf Niehaus</description>
    <label>Draw Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Draw_Down_Profile__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Case#141 - Rudolf Niehaus
Master detail relationship to product (Lending / Deposits / Commitments)</description>
    <label>Product</label>
    <referenceTo>SB_Product__c</referenceTo>
    <relationshipLabel>Draw Down Profiles</relationshipLabel>
    <relationshipName>Draw_Down_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/SB_Product__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Products as Standard Bank have requirements that cannot be met with standard object.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Prod-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SB_Product__c/fields/Draw_Date__c.field-meta.xml
<CustomField>
    <fullName>Draw_Date__c</fullName>
    <label>Draw Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Earliest_Draw_Date_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Draw_Date_Rollup__c</fullName>
    <description>Case#141 - Rudolf Niehaus Rollup to the earliest draw date this value is used to validate that the user do not enter an Estimated Close date on the Opportunity that is after the smallest draw date on the draw down profile records of the oppo product</description>
    <label>Earliest Draw Date</label>
    <summarizedField>Draw_Down_Profile__c.Draw_Date__c</summarizedField>
    <summaryForeignKey>Draw_Down_Profile__c.Product__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SEL_DrawdownProfiles.cls
/**
* @description Drawdown Selector Layer class.
*
* @author Wayne Solomon
* @date Feb 2021
*/
public inherited sharing class SEL_DrawdownProfiles extends fflib_SObjectSelector {

    /**
     * getSObjectFieldList
     * @return List<Schema.SObjectField>
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Draw_Down_Profile__c.Id,
                Draw_Down_Profile__c.Name,
                Draw_Down_Profile__c.Draw_Date__c,
                Draw_Down_Profile__c.Product__c
        };
    }

    /**
     * getSObjectType
     * @return Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Draw_Down_Profile__c.SObjectType;
    }

    /**
     * newInstance
     * @return SEL_DrawdownProfiles
     */
    public static SEL_DrawdownProfiles newInstance() {
        return(SEL_DrawdownProfiles) ORG_Application.selector.newInstance(Draw_Down_Profile__c.SObjectType);
    }

    /**
     * Get the earliest draw down dates across opportunities
     * <br/>SGPRT-4189
     *
     * @param recIds for the inscope records
     * @return the list od drawdowns
     */
    public List<Draw_Down_Profile__c> selectByIdsAndParentProduct(Set<Id> recIds) {
        return (List<Draw_Down_Profile__c>) Database.query(
                newQueryFactory(false, false, true)
                        .selectField('Product__r.Earliest_Draw_Date_Rollup__c')
                        .setCondition('Product__r.Opportunity__c in :recIds')
                        .toSOQL());
    }
}