force-app/main/default/objects/Draw_Down_Profile__c/Draw_Down_Profile__c.object-meta.xml
<CustomObject>
    <description>Case#141 - When an Opportunity and a qualifying Product (Lending / Deposits / Commitments) has been loaded then the user needs to be able to capture the flows / drawdowns and the dates of these transactions on the Product.</description>
    <label>Draw Down Profile</label>
    <nameField>
        <displayFormat>DDP-{0000000000}</displayFormat>
        <label>Draw Down Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Draw Down Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Draw_Down_Profile__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Case#141 - Rudolf Niehaus
Master detail relationship to product (Lending / Deposits / Commitments)</description>
    <label>Product</label>
    <referenceTo>SB_Product__c</referenceTo>
    <relationshipLabel>Draw Down Profiles</relationshipLabel>
    <relationshipName>Draw_Down_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Estimated_Revenue_Schedule__c/Estimated_Revenue_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object to store Estimated Revenue Schedule for Products</description>
    <label>Estimated Revenue Schedule</label>
    <nameField>
        <displayFormat>ERS-{0000}</displayFormat>
        <label>Estimated Revenue Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimated Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimated_Revenue_Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Master-Detail relationship to Advisory product</description>
    <label>Product</label>
    <referenceTo>SB_Product__c</referenceTo>
    <relationshipLabel>Estimated Revenue Schedules</relationshipLabel>
    <relationshipName>Estimated_Revenue_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Distribution__c/Product_Distribution__c.object-meta.xml
<CustomObject>
    <description>Advisory Product Distribution</description>
    <label>Product Distribution</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Product Distribution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Distribution__c/fields/Facility_Size__c.field-meta.xml
<CustomField>
    <fullName>Facility_Size__c</fullName>
    <description>The size of the facility that the client needs. Each facility required should be its own product. If the SB participation needs to be booked across multiple balance sheets, then the facility size should be split pro-rata into multiple products. SGPRT-1229</description>
    <formula>Product__r.Facility_Size__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The size of the facility that the client needs. Each facility required should be its own product. If the SB participation needs to be booked across multiple balance sheets, then the facility size should be split pro-rata into multiple products.</inlineHelpText>
    <label>Facility Size</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Distribution__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Product__r.Opportunity__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Distribution__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>SB_Product__c</referenceTo>
    <relationshipLabel>Product Distributions</relationshipLabel>
    <relationshipName>Product_Distributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Distribution__c/fields/SB_Hold__c.field-meta.xml
<CustomField>
    <fullName>SB_Hold__c</fullName>
    <description>SB&apos;s credit approved hold amount in relation to the specific facility SGPRT-624</description>
    <formula>Product__r.SB_Hold__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>SB&apos;s credit approved hold amount in relation to the specific facility</inlineHelpText>
    <label>SB Hold (at financial close)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Distribution__c/fields/SB_Sell_Down__c.field-meta.xml
<CustomField>
    <fullName>SB_Sell_Down__c</fullName>
    <description>The amount of SB&apos;s Gross Participation in the facility to be sold down post close SGPRT-624</description>
    <formula>Product__r.SB_Sell_Down__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The amount of SB&apos;s Gross Participation in the facility to be sold down post close</inlineHelpText>
    <label>SB Sell Down (at financial close)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Distribution__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Indicate the context in which the transaction is taking place. SGPRT-624</description>
    <formula>TEXT(Product__r.Transaction_Type__c )</formula>
    <inlineHelpText>Indicate the context in which the transaction is taking place</inlineHelpText>
    <label>Transaction Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/SB_Product__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Products as Standard Bank have requirements that cannot be met with standard object.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Prod-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SB_Product__c/fields/Balance_Sheet_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Balance_Sheet_of_Booking__c</fullName>
    <description>Field contains a list of Standard Bank Legal Entities - C-00000456. Field Label changed.</description>
    <inlineHelpText>The Standard Bank Legal Entity is where Asset / Revenue will be booked. If divided between more than one Legal Entity, please create a separate Product for each.</inlineHelpText>
    <label>Legal Entity of Booking</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Angola - Standard Bank de Angola S.A.</fullName>
            </value>
            <value>
                <fullName>Botswana - Stanbic Bank Botswana Limited</fullName>
            </value>
            <value>
                <fullName>Brazil - Banco Standard de Investimentos S.A.</fullName>
            </value>
            <value>
                <fullName>China - Standard Resources (China) Limited</fullName>
            </value>
            <value>
                <fullName>Côte d&apos;Ivoire - Stanbic Bank</fullName>
            </value>
            <value>
                <fullName>D R Congo - Stanbic Bank RDC s.a.r.l.</fullName>
            </value>
            <value>
                <fullName>Ghana - Stanbic Bank Ghana Limited</fullName>
            </value>
            <value>
                <fullName>Hong Kong - Standard Bank Asia Limited</fullName>
            </value>
            <value>
                <fullName>Isle of Man - Standard Bank Isle of Man Branch</fullName>
            </value>
            <value>
                <fullName>Isle of Man - Standard Bank Isle of Man Limited</fullName>
            </value>
            <value>
                <fullName>Isle of Man - Standard Finance (Isle of Man) Ltd</fullName>
            </value>
            <value>
                <fullName>Jersey - Standard Bank Jersey Limited</fullName>
            </value>
            <value>
                <fullName>Kenya - Stanbic Bank Kenya Limited</fullName>
            </value>
            <value>
                <fullName>Lesotho - Standard Lesotho Bank Limited</fullName>
            </value>
            <value>
                <fullName>Malawi - Standard Bank Limited</fullName>
            </value>
            <value>
                <fullName>Mauritius - Standard Bank (Mauritius) Limited</fullName>
            </value>
            <value>
                <fullName>Mozambique - Standard Bank s.a.r.l.</fullName>
            </value>
            <value>
                <fullName>Namibia - Standard Bank Namibia Limited</fullName>
            </value>
            <value>
                <fullName>Nigeria - Stanbic IBTC Bank PLC</fullName>
            </value>
            <value>
                <fullName>Singapore - Standard Merchant Bank (Asia) Limited</fullName>
            </value>
            <value>
                <fullName>South Africa - The Standard Bank of South Africa Limited</fullName>
            </value>
            <value>
                <fullName>Swaziland - Standard Bank Swaziland Limited</fullName>
            </value>
            <value>
                <fullName>Tanzania - Stanbic Bank Tanzania Limited</fullName>
            </value>
            <value>
                <fullName>Uganda - Stanbic Bank Uganda Limited</fullName>
            </value>
            <value>
                <fullName>United Kingdom - Standard Bank Plc</fullName>
            </value>
            <value>
                <fullName>United States of America - Standard Americas, Inc.</fullName>
            </value>
            <value>
                <fullName>Zambia - Stanbic Bank Zambia Limited</fullName>
            </value>
            <value>
                <fullName>Zimbabwe - Stanbic Bank Zimbabwe Limited</fullName>
            </value>
            <value>
                <fullName>Standard Bank Insurance Brokers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Current_Year_Fees__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Fees__c</fullName>
    <inlineHelpText>The Estimated Current Year Revenue that is anticipated for this product on this opportunity.</inlineHelpText>
    <label>Current Year Fees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Current_Year_Margin__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Margin__c</fullName>
    <inlineHelpText>The Estimated Current Year Margin that is anticipated for this product on this opportunity.</inlineHelpText>
    <label>Current Year Margin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Facility_Size__c.field-meta.xml
<CustomField>
    <fullName>Facility_Size__c</fullName>
    <description>The size of the facility that the client needs. Field name changes - Notional Field values. SGPRT-1229</description>
    <inlineHelpText>The size of the facility that the client needs. Each facility required should be its own product. If the SB participation needs to be booked across multiple balance sheets, then the facility size should be split pro-rata into multiple products.</inlineHelpText>
    <label>Facility Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/SB_Hold__c.field-meta.xml
<CustomField>
    <fullName>SB_Hold__c</fullName>
    <description>SB&apos;s credit approved hold amount in relation to the specific facility SGPRT-625</description>
    <inlineHelpText>SB&apos;s credit approved hold amount in relation to the specific facility.</inlineHelpText>
    <label>SB Hold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/SB_Sell_Down__c.field-meta.xml
<CustomField>
    <fullName>SB_Sell_Down__c</fullName>
    <description>The amount of SB&apos;s gross participation in the facility to be sold down post close. SGPRT-625</description>
    <inlineHelpText>The amount of SB&apos;s gross participation in the facility to be sold down post close</inlineHelpText>
    <label>SB Sell Down</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Total_Fees__c.field-meta.xml
<CustomField>
    <fullName>Total_Fees__c</fullName>
    <inlineHelpText>The Estimated Total Fees that is anticipated for this product on this opportunity.</inlineHelpText>
    <label>Total Fees</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Total_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Margin__c</fullName>
    <inlineHelpText>The Estimated Total Margin that is anticipated for this product on this opportunity.</inlineHelpText>
    <label>Total Margin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Indicate the context in which the transaction is taking place. SGPRT-3960, SGPRT-625</description>
    <inlineHelpText>Indicate the context in which the transaction is taking place.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debt advisory only</fullName>
            </value>
            <value>
                <fullName>Syndicated-Best Efforts</fullName>
            </value>
            <value>
                <fullName>Syndicated-Unfunded Underwrite</fullName>
            </value>
            <value>
                <fullName>Bi-Lateral</fullName>
            </value>
            <value>
                <fullName>Club</fullName>
            </value>
            <value>
                <fullName>Syndicated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BLD_Product.cls
/**
 * Builder class for SB_Product SObject
*/
@IsTest
@SuppressWarnings('PMD.ExcessivePublicCount')
public without sharing class BLD_Product extends ABS_ObjectBuilderBase {

	public static final Decimal DEF_TOTAL = 100;

	public BLD_Product() { 
		this(getNewUnitOfWork());        
	}

    public BLD_Product(fflib_SObjectUnitOfWork workUnit) { 
        super(SB_Product__c.SObjectType, workUnit);
    }

    private BLD_Product(SB_Product__c sObj, fflib_SObjectUnitOfWork workUnit) {
        super(sObj,workUnit);
    }

	protected override void setDefaultData(){
		setField(SB_Product__c.Total_Margin__c, DEF_TOTAL)
		.setField(SB_Product__c.Current_Year_Margin__c, DEF_TOTAL)
		.setField(SB_Product__c.Total_Fees__c, DEF_TOTAL)
		.setField(SB_Product__c.Current_Year_Fees__c, DEF_TOTAL);
	}

	public BLD_Product useAdvisory() {
		return (BLD_Product) setField(SB_Product__c.RecordTypeId,
			UTL_RecordType.getRecordTypeId(DMN_SB_Product.OBJ_NAME, DMN_SB_Product.RT_ADVISORY));
	}

	public BLD_Product useCapitalMarkets() {
		return (BLD_Product) setField(SB_Product__c.RecordTypeId,
				UTL_RecordType.getRecordTypeId(DMN_SB_Product.OBJ_NAME, DMN_SB_Product.RT_CAPITAL_MARKETS));
	}

	public BLD_Product linkToOpp(String oppId){
		return (BLD_Product)setField(SB_Product__c.Opportunity__c, oppId);
	}

	public BLD_Product linkToOpp(BLD_Opportunity bOpp){
		return (BLD_Product)setRelation(SB_Product__c.Opportunity__c, bOpp);
	}

	public BLD_Product notionalValue(Decimal value){
		return (BLD_Product)setField(SB_Product__c.Facility_Size__c, value);
	}

	public BLD_Product sbHold(Decimal value){
		return (BLD_Product)setField(SB_Product__c.SB_Hold__c, value);
	}

	public BLD_Product sbSellDown(Decimal value){
		return (BLD_Product)setField(SB_Product__c.SB_Sell_Down__c, value);
	}

	public BLD_Product balanceSheetOfBooking(String bsob){
		return (BLD_Product) setField(SB_Product__c.Balance_Sheet_of_Booking__c, bsob);
	}

	public BLD_Product transactionType(String transactionType){
		return (BLD_Product) setField(SB_Product__c.Transaction_Type__c, transactionType);
	}

	public BLD_Product currentYearFees(Decimal currentYearFees){
	  return (BLD_Product) setField(SB_Product__c.Current_Year_Fees__c, currentYearFees);
	}

	public BLD_Product currentYearMargin(Decimal currentYearMargin){
	  return (BLD_Product) setField(SB_Product__c.Current_Year_Margin__c, currentYearMargin);
	}

	public BLD_Product notionalValueCurrency(Decimal value){
		return (BLD_Product)setField(SB_Product__c.SB_Gross_Participation__c, value);
	}

	public BLD_Product currency(String isoCode){
		return (BLD_Product)setField(SB_Product__c.CurrencyIsoCode, isoCode);
	}

	public BLD_Product grandParentProduct(String gpp){
		return (BLD_Product) setField(SB_Product__c.Grand_Parent_Product__c, gpp);
	}

	public BLD_Product riskWeightedValue(Decimal riskWeightedValue){
		return (BLD_Product) setField(SB_Product__c.Risk_Weighted_Value__c, riskWeightedValue);
	}

	public BLD_Product totalFees(Decimal totalFees){
		return (BLD_Product) setField(SB_Product__c.Total_Fees__c, totalFees);
	}

	public BLD_Product feeFrequency(String feeFreq){
		return (BLD_Product) setField(SB_Product__c.Fee_Frequency__c, feeFreq);
	}

	public BLD_Product feeAmount(Decimal feeAmount){
		return (BLD_Product) setField(SB_Product__c.Fee_Amount__c, feeAmount);
	}

	public BLD_Product billingStartDate(Date billingStart){
		return (BLD_Product) setField(SB_Product__c.Billing_Start_Date__c, billingStart);
	}

	public BLD_Product billingEndDate(Date billingEnd){
		return (BLD_Product) setField(SB_Product__c.Billing_End_Date__c, billingEnd);
	}

	public BLD_Product termTenor(Integer term){
		return (BLD_Product) setField(SB_Product__c.Term_Tenor__c, term);
	}

	public BLD_Product estRevSchUpdated(Boolean estUpdated){
		return (BLD_Product) setField(SB_Product__c.EstRevSch_Updated__c, estUpdated);
	}
	public BLD_Product bankRole(String bankRole){
		return (BLD_Product) setField(SB_Product__c.Bank_Role__c, bankRole);
	}

	public BLD_Product addDrawDownProfile(BLD_DrawDownProfile ddpBld) {
		return (BLD_Product) addChild(Draw_Down_Profile__c.Product__c, ddpBld);
	}

	public BLD_Product addEstimatedRevenueSchedule(BLD_EstimatedRevenueSchedule bldErs) {
		return (BLD_Product) addChild(Estimated_Revenue_Schedule__c.Product__c, bldErs);
	}
	public BLD_Product addProductDistribution(BLD_Product_Distribution bldPd) {
		return (BLD_Product) addChild(Product_Distribution__c.Product__c, bldPd);
	}

}