force-app/main/default/objects/Estimated_Revenue_Schedule__c/Estimated_Revenue_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object to store Estimated Revenue Schedule for Products</description>
    <label>Estimated Revenue Schedule</label>
    <nameField>
        <displayFormat>ERS-{0000}</displayFormat>
        <label>Estimated Revenue Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimated Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimated_Revenue_Schedule__c/fields/Estimated_Revenue_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Revenue_Date__c</fullName>
    <label>Estimated Revenue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Estimated_Revenue_Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Master-Detail relationship to Advisory product</description>
    <label>Product</label>
    <referenceTo>SB_Product__c</referenceTo>
    <relationshipLabel>Estimated Revenue Schedules</relationshipLabel>
    <relationshipName>Estimated_Revenue_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/SB_Product__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Products as Standard Bank have requirements that cannot be met with standard object.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Prod-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SB_Product__c/fields/Current_Year_Fees__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Fees__c</fullName>
    <inlineHelpText>The Estimated Current Year Revenue that is anticipated for this product on this opportunity.</inlineHelpText>
    <label>Current Year Fees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/EstRevSch_Updated__c.field-meta.xml
<CustomField>
    <fullName>EstRevSch_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if Estimated Revenue Schedule is updated</description>
    <label>EstRevSch_Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <description>Enter the expected fee amount based on the frequency.</description>
    <inlineHelpText>Enter the expected fee amount based on the frequency.</inlineHelpText>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Total_Fees__c.field-meta.xml
<CustomField>
    <fullName>Total_Fees__c</fullName>
    <inlineHelpText>The Estimated Total Fees that is anticipated for this product on this opportunity.</inlineHelpText>
    <label>Total Fees</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Update_Estimated_Rev_Schedule.cls
/**
 * Created by khonology on 14/08/2018.
 */

global without sharing class Update_Estimated_Rev_Schedule {
    @InvocableMethod(Label='Update Estimated Revenue Schedule')
    global static void updateEstimatedRevSch(List<genERSReq> ersReq) {
        System.debug('We are being imvoked');
        for (genERSReq request : ersReq ) {
            id pID = request.prodID;
            computeEstimatedRevenueSchedule(request);

        }
        return;
    }

    public static void computeEstimatedRevenueSchedule(genERSReq request) {
        id pID = request.prodID;

        try {
            SB_Product__c sb_rec = [SELECT id, Current_Year_Fees__c,Total_Fees__c FROM SB_Product__c WHERE id = :pID limit 1];
            sb_rec.Current_Year_Fees__c=getCurrentYearFees(pID);
            sb_rec.Total_Fees__c=getTotalFees(pID);
            sb_rec.EstRevSch_Updated__c=true;
            update sb_rec;
        } catch(Exception e) {
            System.debug('An exception occured in Once off populating Fee Totals');
        }

        return;
    }

    global class genERSReq {
        @InvocableVariable(label='Fee Amount' required=true)
        global double feeAmount;
        @InvocableVariable(label='Product ID' required=true)
        global id prodID;
        @InvocableVariable(label='Fee Frequency' required=true)
        global string feeFrequency;
    }

    //Get Current Year Revenues
    public static double getCurrentYearFees(id recordId)
    {
        double fees = 0;
        integer currentYear = System.today().Year();
        List < Estimated_Revenue_Schedule__c > lstOfSchedule =
        [
                select Fee_Amount__c, Estimated_Revenue_Date__c
                from Estimated_Revenue_Schedule__c
                where Product__c =: recordId
                and CALENDAR_YEAR(Estimated_Revenue_Date__c) =: currentYear
        ];

        for (Estimated_Revenue_Schedule__c sch: lstOfSchedule) {
            fees = fees + sch.Fee_Amount__c;
        }

        return fees;
    }

    //Get Total Revenues
    public static double getTotalFees(id recordId)
    {
        double fees = 0;
        List < Estimated_Revenue_Schedule__c > lstOfSchedule =
        [
                select Fee_Amount__c, Estimated_Revenue_Date__c
                from Estimated_Revenue_Schedule__c
                where Product__c =: recordId
        ];

        for (Estimated_Revenue_Schedule__c sch: lstOfSchedule) {
            fees = fees + sch.Fee_Amount__c;
        }

        return fees;
    }
}