force-app/main/default/objects/Estimated_Revenue_Schedule__c/Estimated_Revenue_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object to store Estimated Revenue Schedule for Products</description>
    <label>Estimated Revenue Schedule</label>
    <nameField>
        <displayFormat>ERS-{0000}</displayFormat>
        <label>Estimated Revenue Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimated Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimated_Revenue_Schedule__c/fields/Estimated_Revenue_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Revenue_Date__c</fullName>
    <label>Estimated Revenue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Estimated_Revenue_Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Master-Detail relationship to Advisory product</description>
    <label>Product</label>
    <referenceTo>SB_Product__c</referenceTo>
    <relationshipLabel>Estimated Revenue Schedules</relationshipLabel>
    <relationshipName>Estimated_Revenue_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Estimated_Revenue_Schedule__c/fields/Risk_Weighted_Value__c.field-meta.xml
<CustomField>
    <fullName>Risk_Weighted_Value__c</fullName>
    <label>Risk Weighted Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/SB_Product__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Products as Standard Bank have requirements that cannot be met with standard object.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Prod-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SB_Product__c/fields/Billing_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_End_Date__c</fullName>
    <description>Enter the last billing date</description>
    <inlineHelpText>Enter the last billing date</inlineHelpText>
    <label>Billing End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Billing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Start_Date__c</fullName>
    <description>Enter the first billing date</description>
    <inlineHelpText>Enter the first billing date</inlineHelpText>
    <label>Billing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Current_Year_Fees__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Fees__c</fullName>
    <inlineHelpText>The Estimated Current Year Revenue that is anticipated for this product on this opportunity.</inlineHelpText>
    <label>Current Year Fees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/EstRevSch_Updated__c.field-meta.xml
<CustomField>
    <fullName>EstRevSch_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if Estimated Revenue Schedule is updated</description>
    <label>EstRevSch_Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <description>Enter the expected fee amount based on the frequency.</description>
    <inlineHelpText>Enter the expected fee amount based on the frequency.</inlineHelpText>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Fee_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Fee_Frequency__c</fullName>
    <description>How often will fees be received?</description>
    <inlineHelpText>How often will fees be received?</inlineHelpText>
    <label>Fee Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Bi-annual</fullName>
            </value>
            <value>
                <fullName>Once off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Grand_Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Grand_Parent_Product__c</fullName>
    <description>Grand Parent Product</description>
    <label>Grand Parent Product (GPP)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Advisory Fees</fullName>
            </value>
            <value>
                <fullName>Agricultural Products</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Bank Sector Services</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Bills of exchange discounted</fullName>
            </value>
            <value>
                <fullName>Bonds</fullName>
            </value>
            <value>
                <fullName>Bulk and Steel</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Commitments</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Core Custody</fullName>
            </value>
            <value>
                <fullName>Cost Overrun Facility</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Credit Finance &amp; Leverage</fullName>
            </value>
            <value>
                <fullName>Credit Linked Notes &amp; Depo</fullName>
            </value>
            <value>
                <fullName>Cross Border Finance</fullName>
            </value>
            <value>
                <fullName>Custody Services</fullName>
            </value>
            <value>
                <fullName>Customer foreign currency accounts (CFC)</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Debtor Finance</fullName>
            </value>
            <value>
                <fullName>Debt Structuring</fullName>
            </value>
            <value>
                <fullName>Deposits</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Drafts issues</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Risk_Weighted_Value__c.field-meta.xml
<CustomField>
    <fullName>Risk_Weighted_Value__c</fullName>
    <description>Enter the probability of receiving this fee</description>
    <inlineHelpText>Enter the probability of receiving this fee</inlineHelpText>
    <label>Risk Weighted Value (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Total_Fees__c.field-meta.xml
<CustomField>
    <fullName>Total_Fees__c</fullName>
    <inlineHelpText>The Estimated Total Fees that is anticipated for this product on this opportunity.</inlineHelpText>
    <label>Total Fees</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/recordTypes/Advisory.recordType-meta.xml
<RecordType>
    <fullName>Advisory</fullName>
    <active>true</active>
    <label>Advisory</label>
</RecordType>

force-app/main/default/classes/Generate_Estimated_Rev_Schedule.cls
global without sharing class Generate_Estimated_Rev_Schedule {
    @InvocableMethod(Label='Generate Estimated Revenue Schedule')
    global static void generateEstimatedReveSch(List<genERSReq> ersReq) {
        String grandParent;

        set<id> productIDSet = new set<id>();
        set<id> advisoryProdsSet = new set<id>();
        set<id> UpdatedProds = new set<id>();

        for (genERSReq request : ersReq ) {
            productIDSet.add(request.prodID);
        }
        list<SB_Product__c> sb_rec;
        List<Estimated_Revenue_Schedule__c> doomedERS;
        System.debug('We are being invoked ' + productIDSet.size());
        if (productIDSet.size() > 0) {
            sb_rec = [SELECT id, EstRevSch_Updated__c, Grand_Parent_Product__c, CurrencyISOCode, Fee_Amount__c,
                      Billing_Start_Date__c, Billing_End_Date__c, Fee_Frequency__c, Risk_Weighted_Value__c
                      FROM SB_Product__c
                      WHERE id in :productIDSet AND Grand_Parent_Product__c = 'Advisory Fees' ]; //AND EstRevSch_Updated__c = false];
            if (sb_rec != null) {
                for (SB_Product__c prodrec : sb_rec) {
                    advisoryProdsSet.add(prodrec.id);
                    if (prodrec.EstRevSch_Updated__c == false) {
                        UpdatedProds.add(prodrec.id);
                    }
                }
            }
            doomedERS = new List<Estimated_Revenue_Schedule__c>(
                [SELECT Name FROM Estimated_Revenue_Schedule__c WHERE Product__c IN :UpdatedProds]);
            if (doomedERS != null) {
                try {
                    delete doomedERS;
                    computeEstimatedRevenueSchedule(sb_rec);
                    //update sb_rec;
                } catch (DmlException e) {
                    System.debug('There is an error in deletion of ERS records');
                }
            }
        }

        return;
    }

    public static void computeEstimatedRevenueSchedule(List<SB_Product__c> productList) {
        //id sb_product.id = sb_product.id;
        date fDate;
        List<Estimated_Revenue_Schedule__c> estRevList = new List<Estimated_Revenue_Schedule__c>();
        List<SB_Product__c> updateProductList = new List<SB_Product__c>();
        for (SB_Product__c sb_product : productList) {
            switch on sb_product.Fee_Frequency__c {
                when 'Once off' {
                    Estimated_Revenue_Schedule__c ers = new Estimated_Revenue_Schedule__c(Fee_Amount__c=sb_product.Fee_Amount__c,
                                                                                          Estimated_Revenue_Date__c=sb_product.Billing_Start_Date__c,
                                                                                          Product__c=sb_product.id,
                                                                                          Risk_Weighted_Value__c=sb_product.Risk_Weighted_Value__c*sb_product.Fee_Amount__c,
                                                                                          CurrencyISOCode=sb_product.CurrencyISOCode);
                    if (sb_product.EstRevSch_Updated__c == false) {
                        estRevList.add(ers);
                    }
                    sb_product.Current_Year_Fees__c=0;
                    if (sb_product.Billing_Start_Date__c.year() == Date.today().year()) {
                        sb_product.Current_Year_Fees__c=sb_product.Fee_Amount__c;
                    }
                    sb_product.Total_Fees__c=sb_product.Fee_Amount__c;
                    sb_product.EstRevSch_Updated__c=false;
                    //updateProductList.add(sb_product);
                }
                when 'Monthly' {
                    system.debug('It is monthly');
                    integer numberOfMonths = sb_product.Billing_Start_Date__c.monthsBetween(sb_product.Billing_End_Date__c);
                    fDate = sb_product.Billing_Start_Date__c;
                    if (sb_product.EstRevSch_Updated__c == false) {
                        for (integer i = 1; i <= numberOfMonths; i++) {
                            estRevList.add(new Estimated_Revenue_Schedule__c(Fee_Amount__c=sb_product.Fee_Amount__c,
                                                                             Estimated_Revenue_Date__c=fDate,
                                                                             Product__c=sb_product.id,
                                                                             Risk_Weighted_Value__c=sb_product.Risk_Weighted_Value__c*sb_product.Fee_Amount__c,
                                                                             CurrencyISOCode=sb_product.CurrencyISOCode));
                            fDate = sb_product.Billing_Start_Date__c.addMonths(i);
                        }
                        system.debug(fDate + ' fDate sb_product.Billing_End_Date__c ' + sb_product.Billing_End_Date__c);
                        if ((fDate <= sb_product.Billing_End_Date__c) || (fDate.day() > sb_product.Billing_End_Date__c.day())) {
                            estRevList.add(new Estimated_Revenue_Schedule__c(Fee_Amount__c=sb_product.Fee_Amount__c,
                                                                             Estimated_Revenue_Date__c=sb_product.Billing_End_Date__c,
                                                                             Product__c=sb_product.id,
                                                                             Risk_Weighted_Value__c=sb_product.Risk_Weighted_Value__c*sb_product.Fee_Amount__c,
                                                                             CurrencyISOCode=sb_product.CurrencyISOCode));
                        }
                    }
                }
                when 'Quarterly' {
                    integer numberOfMonths = sb_product.Billing_Start_Date__c.monthsBetween(sb_product.Billing_End_Date__c);
                    fDate = sb_product.Billing_Start_Date__c;
                    //List<Estimated_Revenue_Schedule__c> ersList = new List<Estimated_Revenue_Schedule__c>();
                    for (integer i = 0; i <= numberOfMonths; i=i+3) {
                        fDate = sb_product.Billing_Start_Date__c.addMonths(i);
                        estRevList.add(new Estimated_Revenue_Schedule__c(Fee_Amount__c=sb_product.Fee_Amount__c,
                                                                         Estimated_Revenue_Date__c=fDate,
                                                                         Product__c=sb_product.id,
                                                                         Risk_Weighted_Value__c=sb_product.Risk_Weighted_Value__c*sb_product.Fee_Amount__c,
                                                                         CurrencyISOCode=sb_product.CurrencyISOCode));
                    }
                    if (fDate < sb_product.Billing_End_Date__c) {
                        estRevList.add(new Estimated_Revenue_Schedule__c(Fee_Amount__c=sb_product.Fee_Amount__c,
                                                                         Estimated_Revenue_Date__c=sb_product.Billing_End_Date__c,
                                                                         Product__c=sb_product.id,
                                                                         Risk_Weighted_Value__c=sb_product.Risk_Weighted_Value__c*sb_product.Fee_Amount__c,
                                                                         CurrencyISOCode=sb_product.CurrencyISOCode));
                    }
                }
                when 'Annual' {
                    integer numberOfMonths = sb_product.Billing_Start_Date__c.monthsBetween(sb_product.Billing_End_Date__c);
                    fDate = sb_product.Billing_Start_Date__c;
                    //List<Estimated_Revenue_Schedule__c> ersList = new List<Estimated_Revenue_Schedule__c>();
                    for (integer i = 0; i <= numberOfMonths; i=i+12) {
                        fDate = sb_product.Billing_Start_Date__c.addMonths(i);
                        if (fdate <= sb_product.Billing_End_Date__c ) {
                            estRevList.add(new Estimated_Revenue_Schedule__c(Fee_Amount__c=sb_product.Fee_Amount__c,
                                                                             Estimated_Revenue_Date__c=fDate,
                                                                             Product__c=sb_product.id,
                                                                             Risk_Weighted_Value__c=sb_product.Risk_Weighted_Value__c*sb_product.Fee_Amount__c,
                                                                             CurrencyISOCode=sb_product.CurrencyISOCode));
                        }
                    }
                    if (fDate > sb_product.Billing_End_Date__c) {
                        estRevList.add(new Estimated_Revenue_Schedule__c(Fee_Amount__c=sb_product.Fee_Amount__c,
                                                                         Estimated_Revenue_Date__c=fdate,
                                                                         Product__c=sb_product.id,
                                                                         Risk_Weighted_Value__c=sb_product.Risk_Weighted_Value__c*sb_product.Fee_Amount__c,
                                                                         CurrencyISOCode=sb_product.CurrencyISOCode));
                    }
                }
                When 'Bi-annual' {
                    integer numberOfMonths = sb_product.Billing_Start_Date__c.monthsBetween(sb_product.Billing_End_Date__c);
                    fDate = sb_product.Billing_Start_Date__c;
                    //List<Estimated_Revenue_Schedule__c> ersList = new List<Estimated_Revenue_Schedule__c>();
                    for (integer i = 0; i <= numberOfMonths; i=i+6) {
                        fDate = sb_product.Billing_Start_Date__c.addMonths(i);
                        estRevList.add(new Estimated_Revenue_Schedule__c(Fee_Amount__c=sb_product.Fee_Amount__c,
                                                                         Estimated_Revenue_Date__c=fdate,
                                                                         Product__c=sb_product.id,
                                                                         Risk_Weighted_Value__c=sb_product.Risk_Weighted_Value__c*sb_product.Fee_Amount__c,
                                                                         CurrencyISOCode=sb_product.CurrencyISOCode));
                    }
                    if (fDate < sb_product.Billing_End_Date__c) {
                        estRevList.add(new Estimated_Revenue_Schedule__c(Fee_Amount__c=sb_product.Fee_Amount__c,
                                                                         Estimated_Revenue_Date__c=sb_product.Billing_End_Date__c,
                                                                         Product__c=sb_product.id,
                                                                         Risk_Weighted_Value__c=sb_product.Risk_Weighted_Value__c*sb_product.Fee_Amount__c,
                                                                         CurrencyISOCode=sb_product.CurrencyISOCode));
                    }
                }
                when else {
                    // There shouldnt be an else, it just means the Fee Frequency picklist has been updated with a new value not catered for in this switch statement
                    System.debug('There should not be an else, it just means the Fee Frequency picklist has been updated with a new value not catered for in this switch statement');
                } // End when else
            } // End switch on feeFreq
            if (estRevList.size() == 80) {
            insert estRevList;
        }
        }
        if (estRevList.size() > 0) {
            insert estRevList;
        }
        for (SB_Product__c sb_product : productList) {
            sb_product.Current_Year_Fees__c=getCurrentYearFees(sb_product.id);
            sb_product.Total_Fees__c=getTotalFees(sb_product.id);
            sb_product.EstRevSch_Updated__c=false;
            updateProductList.add(sb_product);
            if (updateProductList.size() == 80) {
            update updateProductList;
        }
        }
        if (updateProductList.size() > 0) {
            update updateProductList;
        }

        return;
    }

    //Get Current Year Revenues
    public static double getCurrentYearFees(id recordId)
    {
        double fees = 0;
        integer currentYear = System.today().Year();
        List < Estimated_Revenue_Schedule__c > lstOfSchedule =
            [
                select Fee_Amount__c, Estimated_Revenue_Date__c
                from Estimated_Revenue_Schedule__c
                where Product__c =: recordId
                and CALENDAR_YEAR(Estimated_Revenue_Date__c) =: currentYear
            ];

        for (Estimated_Revenue_Schedule__c sch: lstOfSchedule) {
            fees = fees + sch.Fee_Amount__c;
        }

        return fees;
    }

    //Get Total Revenues
    public static double getTotalFees(id recordId)
    {
        double fees = 0;
        List < Estimated_Revenue_Schedule__c > lstOfSchedule =
            [
                select Fee_Amount__c, Estimated_Revenue_Date__c
                from Estimated_Revenue_Schedule__c
                where Product__c =: recordId
            ];

        for (Estimated_Revenue_Schedule__c sch: lstOfSchedule) {
            fees = fees + sch.Fee_Amount__c;
        }

        return fees;
    }

    global class genERSReq {
        @InvocableVariable(label='Billing Start Date' required=true)
        global date billingStartDate;
        @InvocableVariable(label='Billing End Date' required=true)
        global date billingEndDate;
        @InvocableVariable(label='Fee Amount' required=true)
        global double feeAmount;
        @InvocableVariable(label='Fee Frequency' required=true)
        global string feeFrequency;
        @InvocableVariable(label='Risk Weighted Value' required=true)
        global double riskWeightedValue;        
        @InvocableVariable(label='Product ID' required=true)
        global id prodID; 
        @InvocableVariable(label='Estimated Revenue Schedule Updated' required=true)
        global boolean EstRevSch_Updated; 
    }
}