force-app/main/default/objects/Case/fields/Case_Owner_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_Business_Unit__c</fullName>
    <description>User Business Unit of the Case Owner</description>
    <inlineHelpText>User Business Unit of the Case Owner</inlineHelpText>
    <label>Case Owner Business Unit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Owner_CIB_Global_Area__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_CIB_Global_Area__c</fullName>
    <description>CIB Global Area of the Case Owner</description>
    <inlineHelpText>CIB Global Area of the Case Owner</inlineHelpText>
    <label>Case Owner CIB Global Area</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Owner_City__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_City__c</fullName>
    <description>User City of the Case Owner</description>
    <inlineHelpText>User City of the Case Owner</inlineHelpText>
    <label>Case Owner City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Owner_Country__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_Country__c</fullName>
    <description>User Country of the Case Owner</description>
    <inlineHelpText>User Country of the Case Owner</inlineHelpText>
    <label>Case Owner Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Owner_Division__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_Division__c</fullName>
    <description>User Division of the Case Owner</description>
    <inlineHelpText>User Division of the Case Owner</inlineHelpText>
    <label>Case Owner Division</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Owner_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_State_Province__c</fullName>
    <description>User State/Province of the Case Owner</description>
    <inlineHelpText>User State/Province of the Case Owner</inlineHelpText>
    <label>Case Owner State/Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Owner_Team__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_Team__c</fullName>
    <description>User Team of the Case Owner</description>
    <inlineHelpText>User Team of the Case Owner</inlineHelpText>
    <label>Case Owner Team</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Birth_Day_Month__c.field-meta.xml
<CustomField>
    <fullName>Birth_Day_Month__c</fullName>
    <description>Please enter the day and the month of the contact&apos;s birthday. Format dd/mm</description>
    <inlineHelpText>Please enter the day and the month of the Contact&apos;s birthday. Format dd/mm (5 characters or less)</inlineHelpText>
    <label>Birth Day/Month</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Outlook_Exchange_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Outlook_Exchange_System_ID__c</fullName>
    <description>This is the Unique System Generated ID getting it from Source System Exchange.
This replaces SAM ACCOUNT NAME
Case Number:Case C-00000178</description>
    <externalId>true</externalId>
    <inlineHelpText>This field can only be updated from the source system which is Outlook Exchange. Please contact the Outlook Exchange team to make any updates to the field (250 characters or less)</inlineHelpText>
    <label>Outlook Exchange System ID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Birth_Day_Month__c.field-meta.xml
<CustomField>
    <fullName>Birth_Day_Month__c</fullName>
    <description>Stores the Users birthday in the format dd/mm

            (CRM Birthday Reminder Case# 207 C Reinecke 2010/09)</description>
    <inlineHelpText>Please enter the day and the month of the User&apos;s birthday. Format dd/mm (5 characters or less)</inlineHelpText>
    <label>Birth Day/Month</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>User Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>User_Division__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Bank Sector</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Br71C Regional Sales</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Business Acquisition</fullName>
            </value>
            <value>
                <fullName>Business Banking Channel</fullName>
            </value>
            <value>
                <fullName>Business Banking Channel Head Office</fullName>
            </value>
            <value>
                <fullName>Business Banking Head Office</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Buy-Side</fullName>
            </value>
            <value>
                <fullName>Cape Head</fullName>
            </value>
            <value>
                <fullName>Capital Markets</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>CDG</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>China/Africa</fullName>
            </value>
            <value>
                <fullName>CIB</fullName>
            </value>
            <value>
                <fullName>Client Access</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
            <value>
                <fullName>Client Onboarding</fullName>
            </value>
            <value>
                <fullName>Client Service</fullName>
            </value>
            <value>
                <fullName>Client Services Operation</fullName>
            </value>
            <value>
                <fullName>Client Solutions</fullName>
            </value>
            <value>
                <fullName>Coastal Region</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Channel</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Channel Head Office</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Head Office</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Non_SBG_User__c.field-meta.xml
<CustomField>
    <fullName>Non_SBG_User__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to track a Non-SBG User</description>
    <inlineHelpText>Field to track a Non-SBG User</inlineHelpText>
    <label>Non-SBG User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Outlook_Exchange_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Outlook_Exchange_System_ID__c</fullName>
    <description>This is the Unique System Generated ID getting it from Source System Exchange.
            This replaces SAM ACCOUNT NAME
            Case Number:Case C-00000178</description>
    <inlineHelpText>This field can only be updated from the source system which is Outlook Exchange. Please contact the Outlook Exchange team to make any updates to the field (250 characters or less)</inlineHelpText>
    <label>Outlook Exchange System ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SA_Cost_Centre__c.field-meta.xml
<CustomField>
    <fullName>SA_Cost_Centre__c</fullName>
    <inlineHelpText>Recorded for acknowledgement of licence cost, and this should be aligned with the User&apos;s team  (255 characters or less)</inlineHelpText>
    <label>Cost Centre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sync_with_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sync_with_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>SHAVEEN06DEC2010 CASE599 &gt; Create a new contact for this USER, else find the BANK CONTACT based on SAM ACCOUNT name and link its BANK CONTACT&apos;s ID to this USER.</description>
    <label>Sync with Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/User_CIB_Global_Area__c.field-meta.xml
<CustomField>
    <fullName>User_CIB_Global_Area__c</fullName>
    <label>User CIB Global Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Africa Regions</fullName>
            </value>
            <value>
                <fullName>CIBI</fullName>
            </value>
            <value>
                <fullName>CIBROA</fullName>
            </value>
            <value>
                <fullName>CIBSA</fullName>
            </value>
            <value>
                <fullName>CIB Global</fullName>
            </value>
            <value>
                <fullName>BCC</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>PBB SA</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_City__c.field-meta.xml
<CustomField>
    <fullName>User_City__c</fullName>
    <formula>City</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The User&apos;s City location (80 characters or less)</inlineHelpText>
    <label>User City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/User_Country__c.field-meta.xml
<CustomField>
    <fullName>User_Country__c</fullName>
    <formula>Country</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The User&apos;s Country location (80 characters or less)</inlineHelpText>
    <label>User Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/User_Division__c.field-meta.xml
<CustomField>
    <fullName>User_Division__c</fullName>
    <label>User Division</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>User_CIB_Global_Area__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Banking</fullName>
            </value>
            <value>
                <fullName>Business Enablers</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
            <value>
                <fullName>Client Services</fullName>
            </value>
            <value>
                <fullName>Client Solutions</fullName>
            </value>
            <value>
                <fullName>Commercial Banking</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>Entrepreneur</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>Global Markets</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Small Enterprise</fullName>
            </value>
            <value>
                <fullName>Transactional Products and Services</fullName>
            </value>
            <value>
                <fullName>Vehicle and Asset Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_Franco__c.field-meta.xml
<CustomField>
    <fullName>User_Franco__c</fullName>
    <description>this field is to set the Franco the user belongs to</description>
    <label>User Franco</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Developed Markets</fullName>
            </value>
            <value>
                <fullName>DRC</fullName>
            </value>
            <value>
                <fullName>East Africa</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>Nigeria</fullName>
            </value>
            <value>
                <fullName>South and Central Africa</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>West Africa</fullName>
            </value>
            <value>
                <fullName>Uganda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_State_Province__c.field-meta.xml
<CustomField>
    <fullName>User_State_Province__c</fullName>
    <formula>State</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The User&apos;s State / Province location (80 characters or less)</inlineHelpText>
    <label>User State/Province</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserTriggerUtility.cls
/*************************************************************************\
    @ Author        :     Anurag Jain
    @ Date          :     23 June 2011
    @ Test File     :     UserClassAndTriggerTests
    @description   :     General trigger utility class for User Object.
                          Set the Case Owner user details on the User Object custom fields.        
                          
    @ Last Modified By  : Anurag Jain    
    @ Last Modified On  : 17 August 2011
    @ Last Modified Reason  : The users were encountering the Mixed DMl operation error while 
                              updating the user records who is the owner of any open case. 
                              To fix the error the 'handleUserBeforeUpdateTrigger' has been made @future. Also the parameter has been chnaged to Primitive type Set<ID> 
    @ Last Modified By  : Balabramham.y    
    @ Last Modified On  : 23 August 2011
    @ Last Modified Reason: removed break from if condition.
                            modified the variable names as per the coding standards.        
                                 
****************************************************************************/
public with sharing class UserTriggerUtility {

    /**
    * handleUserBeforeUpdateTrigger
    * @param ids2Users
    */
    public static void handleUserBeforeUpdateTrigger(Map<Id, User> ids2Users) {


        /**************************************************************************\
        A new field Case Owner is created on Case object that shall be populated with the value in Case Owner 
        standard field. This will help in defining the formula fields on the Case object 
        viz. User CIB Global Area, User Division, User Business Unit, User Team, User City, User State/Province, User Country
        ****************************************************************************/

        List<Case> openCases = [
            SELECT Id, OwnerId, Case_Owner_Business_Unit__c,Case_Owner_CIB_Global_Area__c,
                Case_Owner_City__c,Case_Owner_Country__c,Case_Owner_Division__c,
                Case_Owner_State_Province__c, Case_Owner_Team__c
            FROM Case
            WHERE OwnerId IN :ids2Users.keySet()
                AND Status != :DMN_Case.STATUS_CLOSED
        ];

        for(Case openCase : openCases){
            openCase.Case_Owner_Business_Unit__c = ids2Users.get(openCase.OwnerId).Business_Unit__c;
            openCase.Case_Owner_CIB_Global_Area__c = ids2Users.get(openCase.OwnerId).User_CIB_Global_Area__c;
            openCase.Case_Owner_City__c = ids2Users.get(openCase.OwnerId).User_City__c;
            openCase.Case_Owner_Country__c = ids2Users.get(openCase.OwnerId).User_Country__c;
            openCase.Case_Owner_Division__c = ids2Users.get(openCase.OwnerId).User_Division__c;
            openCase.Case_Owner_State_Province__c = ids2Users.get(openCase.OwnerId).User_State_Province__c;
            openCase.Case_Owner_Team__c = ids2Users.get(openCase.OwnerId).User_Team__c;
        }
        
        try{
            update openCases;
        }catch(DMLException ex){
            SRV_Logger.newInstance().log(ex, DMN_Log.TYPE_ERROR, UserTriggerUtility.class.getName());
        }

    }

    /**
	* handleWelcomeNotificationInsert
	* @param newUserIdSet Set of user ids.
	*/
    public static void handleWelcomeNotificationInsert(Set<Id> newUserIdSet){
        DMN_User.handleWelcomeNotificationInsert(newUserIdSet);
    }

    /**
     * Checks if relevant fields on User have been changed
     *
     * @param userOld
     * @param userNew
     *
     * @return Boolean
     **/
    public static Boolean isFieldOnUserChanged(User userOld, User userNew) {
        return userOld.Department != userNew.Department ||
                userOld.Email != userNew.Email ||
                userOld.Fax != userNew.Fax ||
                userOld.FirstName != userNew.FirstName ||
                userOld.LastName != userNew.LastName ||
                userOld.Street != userNew.Street ||
                userOld.State != userNew.State ||
                userOld.PostalCode != userNew.PostalCode ||
                userOld.Country != userNew.Country ||
                userOld.City != userNew.City ||
                userOld.MobilePhone != userNew.MobilePhone ||
                userOld.Phone != userNew.Phone ||
                userOld.Title != userNew.Title ||
                userOld.Birth_Day_Month__c != userNew.Birth_Day_Month__c ||
                userOld.User_Division__c != userNew.User_Division__c ||
                userOld.User_Team__c != userNew.User_Team__c ||
                userOld.User_Franco__c != userNew.User_Franco__c ||
                userOld.User_CIB_Global_Area__c != userNew.User_CIB_Global_Area__c ||
                userOld.Business_Unit__c != userNew.Business_Unit__c ||
                userOld.User_Country__c != userNew.User_Country__c ||
                userOld.Outlook_Exchange_System_ID__c != userNew.Outlook_Exchange_System_ID__c ||
                userOld.IsActive != userNew.IsActive ||
                userOld.EmployeeNumber != userNew.EmployeeNumber ||
                userOld.SA_Cost_Centre__c != userNew.SA_Cost_Centre__c ||
                userOld.Non_SBG_User__c != userNew.Non_SBG_User__c;
    }

    /**
     * Checks if Contact needs to be updated
     *
     * @param userNew
     * @param isTriggerInsert - value for Trigger.isInsert
     * @param id2userOld - value for Trigger.oldMap
     *
     * @return Boolean
     **/
    public static Boolean needsContactUpdate(User userNew, Boolean isTriggerInsert, Map<Id, User> id2userOld) {
        User userOld;
        if(!isTriggerInsert) {
            userOld = id2userOld.get(userNew.Id);
        }
        return userNew.Sync_with_Contact__c && (isTriggerInsert || isFieldOnUserChanged(userOld, userNew));
    }
}