force-app/main/default/objects/Case/fields/Custody_Category__c.field-meta.xml
<CustomField>
    <fullName>Custody_Category__c</fullName>
    <description>24/10/17 (MS) - New Case field for Client Services Cases.</description>
    <label>Custody Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Amendments</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Africa Desk</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Cash Payment</fullName>
            </value>
            <value>
                <fullName>CCOMS / BOL</fullName>
            </value>
            <value>
                <fullName>Corporate Actions</fullName>
            </value>
            <value>
                <fullName>Global Custody</fullName>
            </value>
            <value>
                <fullName>IS Information</fullName>
            </value>
            <value>
                <fullName>Legislation and Legal</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Reports</fullName>
            </value>
            <value>
                <fullName>Swift Messages</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Custody_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Custody_Sub_Category__c</fullName>
    <description>24/10/17 (MS) - New case field created for the Client Services Case layout.</description>
    <label>Custody Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Custody_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa Region query</fullName>
            </value>
            <value>
                <fullName>ARM Codes</fullName>
            </value>
            <value>
                <fullName>Audit report</fullName>
            </value>
            <value>
                <fullName>Authorised Signatory Lists</fullName>
            </value>
            <value>
                <fullName>BEE Trade report</fullName>
            </value>
            <value>
                <fullName>Billing Invoice Payment Method</fullName>
            </value>
            <value>
                <fullName>CA Calculations</fullName>
            </value>
            <value>
                <fullName>CA cash not received</fullName>
            </value>
            <value>
                <fullName>CA Claims</fullName>
            </value>
            <value>
                <fullName>CA Diary</fullName>
            </value>
            <value>
                <fullName>CA Election Instruction</fullName>
            </value>
            <value>
                <fullName>CA Entitlement Confirmations</fullName>
            </value>
            <value>
                <fullName>CA Event Details</fullName>
            </value>
            <value>
                <fullName>CA Income and Dividend</fullName>
            </value>
            <value>
                <fullName>CA Meeting Details</fullName>
            </value>
            <value>
                <fullName>CA Proxy</fullName>
            </value>
            <value>
                <fullName>CA rate request</fullName>
            </value>
            <value>
                <fullName>Cash Accounts Not Loaded On Cashman</fullName>
            </value>
            <value>
                <fullName>Cash Accrued Interest</fullName>
            </value>
            <value>
                <fullName>Cash Add Account to BOL</fullName>
            </value>
            <value>
                <fullName>Cash Amend Cash Account</fullName>
            </value>
            <value>
                <fullName>Cash Audit Req Balance Certificate</fullName>
            </value>
            <value>
                <fullName>Cash Bank Statement Request</fullName>
            </value>
            <value>
                <fullName>Cash - CATS Entries</fullName>
            </value>
            <value>
                <fullName>Cash Forecast</fullName>
            </value>
            <value>
                <fullName>Cash Interest Rate Request</fullName>
            </value>
            <value>
                <fullName>Cashman Account Process</fullName>
            </value>
            <value>
                <fullName>Cash Market Information</fullName>
            </value>
            <value>
                <fullName>Cash Missing Mt950</fullName>
            </value>
            <value>
                <fullName>Cash Panel Verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MergeCaseController.cls
/*************************************************************************
@ Author        : Rinkita Patil
@ Date          : May 2019
@ Description   : US-3886:Angola - Phase 4A | Adding "Search" within the Case Record
*************************************************************************/
public class MergeCaseController {
    @AuraEnabled
    public static List < sObject > fetchLookUpValues(String searchKeyWord, String ObjectName, List<sObject> ExcludeitemsList,String parentCaseId) {
        SEL_Cases selector = new SEL_Cases();
        List<Case> parentCase = selector.selectByCaseId(parentCaseId);
        Id accRec=parentCase[0].AccountId;
        String closedStatus='Closed';
        String searchKey = '%' + searchKeyWord + '%';
        List < sObject > returnList = new List < sObject > ();
        List<string> lstExcludeitems = new List<string>();
        for(sObject item : ExcludeitemsList ){
            lstExcludeitems.add(item.id);
        }
        // Query Related case with status is not closed and same account
        String sQuery =  'select CaseNumber,Subject,Status from ' +ObjectName + ' where (CaseNumber LIKE: searchKey OR Subject LIKE: searchKey) AND Id NOT IN : lstExcludeitems AND AccountId = : accRec AND status != :closedStatus AND Id != :parentCaseId and ParentId = null order by createdDate DESC limit 5';
        List < sObject > lstOfRecords = Database.query(sQuery);
        for (sObject obj: lstOfRecords) {
            returnList.add(obj);
        }
        return returnList;
    }
     @AuraEnabled
    public static List <Case> getRelatedCase(String parentCaseId){
        list<Case> lstCases = new list<Case>();
        SEL_Cases selector = new SEL_Cases();
        List<Case> parentCase = selector.selectByParentCaseId(parentCaseId);
        if(parentCase.size() > 0){
            lstCases = [Select Id, CaseNumber, Subject, Status, Account.Name, Contact.Name, 
                       Origin, Owner.Name, Custody_Sub_Category__c, Custody_Category__c  
                       From Case 
                       Where AccountId = :parentCase[0].AccountId and Status !='Closed' and 
                       Id != :parentCaseId and 
                       ParentId = null  
                       Order by CreatedDate Desc limit 10 ];
        }
        return lstCases;
    }
    @AuraEnabled
    public static Case mergeCase(String newParent, String newChild){
        SEL_Cases selector = new SEL_Cases();
        Case c = selector.mergeCase(newChild);
        c.ParentId = newParent;
        c.Status = 'Duplicate';        
        update c;
        return c; 
    }
    @AuraEnabled
    public static List<Case> mergeMultipleCase(String newParent, List<Sobject> newChildList){
        List<string> newChildListUpdate = new List<string>();
        for(sObject item : newChildList ){
            newChildListUpdate.add(item.id);
        }
        SEL_Cases selector = new SEL_Cases();
        List<case> caseList=selector.mergeMultipleCase(newChildList);
        List<Case> updateCaseList=new List<case>();
        for(Case c:caseList){
            c.ParentId = newParent;
            c.Status = 'Duplicate'; 
            updateCaseList.add(c);
        }
        update updateCaseList;
        return updateCaseList; 
    }
}