force-app/main/default/objects/Case/fields/ICBC_Contact__c.field-meta.xml
<CustomField>
    <fullName>ICBC_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ICBC Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.ICBC_Contact__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.ICBC_Case__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resolved_By__c.field-meta.xml
<CustomField>
    <fullName>Resolved_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resolved By</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bank Contact Record Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Resolved By)</relationshipLabel>
    <relationshipName>ResolvedByContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Birth_Day_Month__c.field-meta.xml
<CustomField>
    <fullName>Birth_Day_Month__c</fullName>
    <description>Please enter the day and the month of the contact&apos;s birthday. Format dd/mm</description>
    <inlineHelpText>Please enter the day and the month of the Contact&apos;s birthday. Format dd/mm (5 characters or less)</inlineHelpText>
    <label>Birth Day/Month</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CIF_Number__c.field-meta.xml
<CustomField>
    <fullName>CIF_Number__c</fullName>
    <description>This is helper field which stored Account.CIF__c value and it is populated via trigger (US-1643).</description>
    <label>CIF Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Category__c.field-meta.xml
<CustomField>
    <fullName>Contact_Category__c</fullName>
    <description>Allows for easier filtering of contacts</description>
    <inlineHelpText>Allows for easier filtering of contacts</inlineHelpText>
    <label>Contact Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>Group Treasurer</fullName>
            </value>
            <value>
                <fullName>Senior Executive</fullName>
            </value>
            <value>
                <fullName>Senior Manager</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Accounts Clerk</fullName>
            </value>
            <value>
                <fullName>Global Trader</fullName>
            </value>
            <value>
                <fullName>Agri</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Role_s_at_Client__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role_s_at_Client__c</fullName>
    <description>The functional role(s) performed by the Client Contact in dealing with Standard Bank. C-00000333</description>
    <inlineHelpText>The functional role(s) performed by the Client Contact in dealing with Standard Bank</inlineHelpText>
    <label>Contact Role(s) at Client</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved Dealer</fullName>
            </value>
            <value>
                <fullName>Authorised Person</fullName>
            </value>
            <value>
                <fullName>CC Survey Contact</fullName>
            </value>
            <value>
                <fullName>CommB Survey Contact</fullName>
            </value>
            <value>
                <fullName>Direct Shareholder</fullName>
            </value>
            <value>
                <fullName>GM Survey Contact</fullName>
            </value>
            <value>
                <fullName>Group KYC Contact</fullName>
            </value>
            <value>
                <fullName>IB Survey Contact</fullName>
            </value>
            <value>
                <fullName>Indirect Shareholder</fullName>
            </value>
            <value>
                <fullName>KYC Contact</fullName>
            </value>
            <value>
                <fullName>Pricing Contact</fullName>
            </value>
            <value>
                <fullName>Primary GM Research Contact</fullName>
            </value>
            <value>
                <fullName>TPS Survey Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ICBC_Contact__c.field-meta.xml
<CustomField>
    <fullName>ICBC_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ICBC Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Identity_Number__c.field-meta.xml
<CustomField>
    <fullName>Identity_Number__c</fullName>
    <description>Digital Onboarding: This field stores the Authorised Person&apos;s ID number and is used by the KYC Consultants during the KYC Process. This field is only visible to the Custom KYC User Profile and the Onboarding API profile.</description>
    <label>Identity Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the status of the contact at the client. This status is used to improve contact searches .Inactive Contacts are excluded from lookup searches</description>
    <inlineHelpText>Indicates the status of the contact at the client. This status is used to improve contact searches.</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OSB_Community_Access_Manager__c.field-meta.xml
<CustomField>
    <fullName>OSB_Community_Access_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OneHub: This field is used to store who the Authorised Person or Designated Person is that sent the user an invite to sign up for the OneHub Community. (US-4589)</description>
    <inlineHelpText>Contact that is responsible for the access for the OneHub community</inlineHelpText>
    <label>Community Access Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Community Access manager</relationshipLabel>
    <relationshipName>Community_access_manager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OSB_Community_Access_Role__c.field-meta.xml
<CustomField>
    <fullName>OSB_Community_Access_Role__c</fullName>
    <description>OneHub: This field is used to store the Role that a Client user has on the OneHub Community.(US-4589)</description>
    <inlineHelpText>Role of the client on the OneHub community</inlineHelpText>
    <label>Community Access Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Authorised Person</fullName>
            </value>
            <value>
                <fullName>Designated Person</fullName>
            </value>
            <value>
                <fullName>Nominated Person</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/OSB_Community_Access_Status__c.field-meta.xml
<CustomField>
    <fullName>OSB_Community_Access_Status__c</fullName>
    <description>OneHub: This field is used to store the status of the users access to the OneHub Community.(US-4589)</description>
    <label>Community Access Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invite Sent</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/OSB_Company_name__c.field-meta.xml
<CustomField>
    <fullName>OSB_Company_name__c</fullName>
    <description>OneHub: Company name for the client to be used on OneHub Community. (US-4589)</description>
    <inlineHelpText>Company Name for the Client used to update Ping</inlineHelpText>
    <label>Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OSB_Operating_Country__c.field-meta.xml
<CustomField>
    <fullName>OSB_Operating_Country__c</fullName>
    <description>This field is used to define a OneHub user&apos;s Operating Country/s which will drive visibility of Solutions &amp; API&apos;s on the users dashboard.</description>
    <inlineHelpText>Which country/s does the user operating in?</inlineHelpText>
    <label>Operating Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OSB_Operating_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Ping_Id__c.field-meta.xml
<CustomField>
    <fullName>Ping_Id__c</fullName>
    <description>OneHub: Ping Integration Identity Number. (US-4589)</description>
    <externalId>true</externalId>
    <inlineHelpText>Used for the Ping Integration</inlineHelpText>
    <label>Ping ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Reason_for_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Inactive__c</fullName>
    <description>Reason as to why a Contact is Inactive on Salesforce</description>
    <label>Reason for Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Inactive__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Client Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Internal Transfer</fullName>
            </value>
            <value>
                <fullName>Resigned</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Retrenched</fullName>
            </value>
            <value>
                <fullName>Previous Owner Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Key_Client_Contact__c/Key_Client_Contact__c.object-meta.xml
<CustomObject>
    <description>This object stores the info of important contacts related with a client.</description>
    <label>Key Client Contact</label>
    <nameField>
        <label>Key Client Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Client Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Client_Contact__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related contact</description>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Key Client Contacts</relationshipLabel>
    <relationshipName>Key_Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SA_Contact_Team_Member__c/SA_Contact_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Contact Team Member</label>
    <nameField>
        <displayFormat>CTM-{00000}</displayFormat>
        <label>Contact Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SA_Contact_Team_Member__c/fields/SA_Contact__c.field-meta.xml
<CustomField>
    <fullName>SA_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Team Members</relationshipLabel>
    <relationshipName>Contact_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BLD_Contact.cls
/**
 * Builder class for Contact SObject
 */
@IsTest
@SuppressWarnings('PMD.ExcessivePublicCount')
public without sharing class BLD_Contact extends ABS_ObjectBuilderBase{

    public static final String DEF_FIRST_NAME = 'testFirstName';
    public static final String DEF_LAST_NAME = 'testContact';
    public static final String DEF_EMAIL = 'test@Contact.testcom';
    public static final String DEF_PHONE = '192837465';
    public static final String DEF_PHONE_COUNTRY = 'South Africa';
    public static final String DEF_OPERATING_COUNTRY = 'Angola;South Africa';

    private static Integer counter = 0;

    private static Boolean allowDuplicates = false;

    public BLD_Contact() {
        this(getNewUnitOfWork());
    }

    public BLD_Contact(fflib_SObjectUnitOfWork workUnit) {
        super(Contact.SObjectType, workUnit);
    }

    public BLD_Contact(Contact sObj, fflib_SObjectUnitOfWork workUnit) {
        super(sObj, workUnit);
    }

    protected override void setDefaultData() {
        setField(Contact.LastName,  counter + DEF_LAST_NAME + counter)
                .setField(Contact.Phone, counter + DEF_PHONE + counter)
                .setField(Contact.Email, counter + DEF_EMAIL + counter);
        counter++;
    }

    public BLD_Contact birthDayMonth(String birthDayMonth) {
        return(BLD_Contact) setField(Contact.Birth_Day_Month__c, birthDayMonth);
    }

    public BLD_Contact cifNumber(String cifNumber) {
        return(BLD_Contact) setField(Contact.CIF_Number__c, cifNumber);
    }

    public BLD_Contact email(String email) {
        return(BLD_Contact)setField(Contact.Email, email);
    }

    public BLD_Contact mobilePhone(String mobilePhone) {
        return(BLD_Contact)setField(Contact.MobilePhone, mobilePhone);
    }

    public BLD_Contact phone(String phone) {
        return(BLD_Contact)setField(Contact.Phone, phone);
    }

    public BLD_Contact fax(String fax) {
        return (BLD_Contact) setField(Contact.Fax, fax);
    }

    public BLD_Contact name(String firstName, String lastName) {
        return(BLD_Contact)setField(Contact.LastName, lastName).setField(Contact.FirstName, firstName);
    }

    public BLD_Contact lastName(String lastName) {
        return(BLD_Contact)setField(Contact.LastName, lastName);
    }

    public BLD_Contact mailingAddress(String mailingStreet, String mailingCity, String mailingCountry, String mailingPostalCode){
        return(BLD_Contact)setField(Contact.MailingStreet, mailingStreet).setField(Contact.MailingCity, mailingCity)
                .setField(Contact.MailingCountry, mailingCountry)
                .setField(Contact.MailingPostalCode, mailingPostalCode);
    }

    public BLD_Contact recordTypeId(Id recordTypeId){
        return(BLD_Contact) setField(Contact.RecordTypeId, recordTypeId);
    }

    public BLD_Contact contactCategory(String title) {
        return(BLD_Contact)setField(Contact.Contact_Category__c, title);

    }

    public BLD_Contact icbcContact(Boolean icbcContact) {
        return(BLD_Contact)setField(Contact.ICBC_Contact__c, icbcContact);

    }

    public BLD_Contact inactive(Boolean inactive) {
        return(BLD_Contact)setField(Contact.Inactive__c, inactive);

    }

    public BLD_Contact reasonForInactive(String reasonForInactive) {
        return(BLD_Contact)setField(Contact.Reason_for_Inactive__c, reasonForInactive);

    }

    public BLD_Contact roleAtClient(String role){
        return(BLD_Contact)setField(Contact.Contact_Role_s_at_Client__c, role);
    }

    public BLD_Contact useBankContact(){
        return (BLD_Contact)setField(Contact.RecordTypeId,
                UTL_RecordType.getRecordTypeId(DMN_Contact.OBJ_NAME, DMN_Contact.RTD_BANK));
    }

    public BLD_Contact useClientContact(){
        return (BLD_Contact)setField(Contact.RecordTypeId,
                UTL_RecordType.getRecordTypeId(DMN_Contact.OBJ_NAME, DMN_Contact.RTD_CLIENT));
    }

    public BLD_Contact accountId(Id accountId){
        return (BLD_Contact)setField(Contact.AccountId, accountId);
    }

    public BLD_Contact account(ABS_ObjectBuilderBase accountBld){
        return (BLD_Contact) setRelation(Contact.AccountId, accountBld);
    }

    public BLD_Contact ownerId(Id ownerId){
        return (BLD_Contact) setField(Contact.OwnerId, ownerId);
    }

    public BLD_Contact addKeyClientContact(BLD_KeyClientContact keyClientContactBuilder) {
        return (BLD_Contact) addChild(Key_Client_Contact__c.Contact_Name__c, keyClientContactBuilder);
    }

    public BLD_Contact addResolvedCase(BLD_Case caseBuilder) {
        return (BLD_Contact) addChild(Case.Resolved_By__c, caseBuilder);
    }

    public BLD_Contact addTeamMember(BLD_ContactTeamMember contactBuilder) {
        return (BLD_Contact) addChild(SA_Contact_Team_Member__c.SA_Contact__c, contactBuilder);
    }

    public BLD_Contact addTask(BLD_Task taskBuilder) {
        return (BLD_Contact) addChild(Task.WhoId, taskBuilder);
    }

    public BLD_Contact allowDuplicates(){
        allowDuplicates = true;
        return this;
    }

    public BLD_Contact pingId(String pingId){
        return (BLD_Contact) setField(Contact.Ping_Id__c, pingId);
    }

    public BLD_Contact companyName(String companyName){
        return (BLD_Contact) setField(Contact.OSB_Company_name__c, companyName);
    }

    public BLD_Contact communityAccessManager(Id communityAccessManager){
        return (BLD_Contact) setField(Contact.OSB_Community_Access_Manager__c, communityAccessManager);
    }

    public BLD_Contact communityAccessManager(BLD_Contact communityManager){
        return (BLD_Contact) setRelation(Contact.OSB_Community_Access_Manager__c, communityManager);
    }

    public BLD_Contact communityAccessRole(String communityAccessRole){
        return (BLD_Contact) setField(Contact.OSB_Community_Access_Role__c, communityAccessRole);
    }

    public BLD_Contact identityNumber(String identityNumber){
        return (BLD_Contact) setField(Contact.Identity_Number__c, identityNumber);
    }

    public BLD_Contact communityAccessStatus(String communityAccessStatus){
        return (BLD_Contact) setField(Contact.OSB_Community_Access_Status__c, communityAccessStatus);
    }

    public BLD_Contact operatingCountry(String operatingCountry){
        return (BLD_Contact) setField(Contact.OSB_Operating_Country__c, operatingCountry);
    }

    public BLD_Contact setOSBDefaultData(String communityAccessRole, String communityAccessStatus){
        return (BLD_Contact)
                setField(Contact.FirstName, DEF_FIRST_NAME)
                        .setField(Contact.LastName, DEF_LAST_NAME)
                        .setField(Contact.Email, DEF_EMAIL)
                        .setField(Contact.MobilePhone, DEF_PHONE)
                        .setField(Contact.Phone, DEF_PHONE)
                        .setField(Contact.Phone_Country__c, DEF_PHONE_COUNTRY)
                        .setField(Contact.OSB_Community_Access_Role__c, communityAccessRole)
                        .setField(Contact.OSB_Community_Access_Status__c, communityAccessStatus)
                        .setField(Contact.OSB_Operating_Country__c, DEF_OPERATING_COUNTRY);
    }

    public override ABS_ObjectBuilderBase commitWork(){

        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.AllowSave = allowDuplicates;
        dml.OptAllOrNone = false;
        Contact con = (Contact)getRecord();
        if(con.Id == null){
            Database.insert(con, dml);
        }
        else{
            Database.update(con, dml);
        }
        return this;
    }


}