force-app/main/default/objects/Case/fields/Main_Category__c.field-meta.xml
<CustomField>
    <fullName>Main_Category__c</fullName>
    <description>The Primary category by which the case is classified (Kele 2013/12)</description>
    <inlineHelpText>Primary Case Classification</inlineHelpText>
    <label>Main Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>Other External</fullName>
            </value>
            <value>
                <fullName>Other Internal</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
                <default>true</default>
                <label>Payments</label>
            </value>
            <value>
                <fullName>Trade Finance</fullName>
            </value>
            <value>
                <fullName>User Management</fullName>
            </value>
            <value>
                <fullName>Client On boarding</fullName>
            </value>
            <value>
                <fullName>Trailhead</fullName>
            </value>
            <value>
                <fullName>Internal Org</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <description>(US-4200)This object is used to store survey response data and link it to related Client or Case</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SurveyResponseReceiverService_Test.cls
/***
@ Func Area     	:  CTI Softphone Integration
@ Author        	:  Created by Mykhailo
@ Date          	:  10.09.2019
@ User Story        :  US-4200 IVR Client survey responses
@ Description 	    :  Store survey data when invoked by external system into Survey_Response__c
@ Modified          : Emmanuel Mulea(Nocks)
***/

@IsTest
private class SurveyResponseReceiverService_Test {

    @IsTest
    static void testBlankQuestionError() {
        String returnResult = SurveyResponseReceiverService.createSurveyResponse('', 9, '5001x000003hcXeAAI', null);
        System.assertEquals('Question field can not be empty or null', returnResult);
    }
    @IsTest
    static void testQuestionIsNullError() {
        String returnResult = SurveyResponseReceiverService.createSurveyResponse(null, 9, '5001x000003hcXeAAI', null);
        System.assertEquals('Question field can not be empty or null', returnResult);
    }
    @IsTest
    static void testNpsAnswerLengthError() {
        String returnResult = SurveyResponseReceiverService.createSurveyResponse('How do you do?', 12, '5001x000003hcXeAAI', null);
        System.assertEquals('NPS Answer max length is 1 character', returnResult);
    }
    @IsTest
    static void testNpsAnswerIsNullError() {
        String returnResult = SurveyResponseReceiverService.createSurveyResponse('How do you do?', null, '5001x000003hcXeAAI', null);
        System.assertEquals('NPS Answer field can not be null', returnResult);
    }

    @IsTest
    static void testNoCaseWithSuchIdFoundError() {
        String returnResult = SurveyResponseReceiverService.createSurveyResponse('How do you do?', 9, '5001x000003hcXeAAI', null);
        System.assertEquals('Case with such Id (5001x000003hcXeAAI) doesn\'t exist', returnResult);
    }
    @IsTest
    static void testNoClientWithSuchIdFoundError() {
        String returnResult = SurveyResponseReceiverService.createSurveyResponse('How do you do?', 9, null, '0011x00000Sw17gAAB');
        System.assertEquals('Contact with such Id (0011x00000Sw17gAAB) doesn\'t exist', returnResult);
    }
    @IsTest
    static void testSuccessfulSureveyResponseCreation() {
        Case newCase = new Case(Status = 'New', Main_Category__c='Data Managment', Origin = 'Client Email');
        Account  newAccount = new Account(name='test');
        insert newAccount;
        Contact newContact = new Contact(lastName='test',email='trest@test.com',AccountId=newAccount.id);
        insert newContact;
        insert newCase;
        Case[] allCases = [SELECT Id From Case];
//        System.debug('SELECTING CASES FROM TEST');
//        System.debug(allCases);
//        System.debug(allCases[0].Id);
        String returnResult = SurveyResponseReceiverService.createSurveyResponse('How do you do?', 9, allCases[0].Id, newContact.id);
        System.assertEquals('New Survey Response was successfully added', returnResult.split(':')[0]);
    }

}