force-app/main/default/objects/Case/fields/Main_Category__c.field-meta.xml
<CustomField>
    <fullName>Main_Category__c</fullName>
    <description>The Primary category by which the case is classified (Kele 2013/12)</description>
    <inlineHelpText>Primary Case Classification</inlineHelpText>
    <label>Main Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>Other External</fullName>
            </value>
            <value>
                <fullName>Other Internal</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
                <default>true</default>
                <label>Payments</label>
            </value>
            <value>
                <fullName>Trade Finance</fullName>
            </value>
            <value>
                <fullName>User Management</fullName>
            </value>
            <value>
                <fullName>Client On boarding</fullName>
            </value>
            <value>
                <fullName>Trailhead</fullName>
            </value>
            <value>
                <fullName>Internal Org</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <description>The Secondary category by which the case is classified (Kele 2013/12)</description>
    <inlineHelpText>Case Sub Category for the segmentation of the support queries</inlineHelpText>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Main_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Activities Management</fullName>
            </value>
            <value>
                <fullName>Background Checks</fullName>
            </value>
            <value>
                <fullName>BCNR</fullName>
            </value>
            <value>
                <fullName>Beneficiary Bank Unable to Apply</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Campaign Management</fullName>
            </value>
            <value>
                <fullName>CC &amp; CCBM</fullName>
            </value>
            <value>
                <fullName>Cheque Receipt</fullName>
            </value>
            <value>
                <fullName>CIB to PBB Migration</fullName>
            </value>
            <value>
                <fullName>CIF Rejection</fullName>
            </value>
            <value>
                <fullName>Client Closure</fullName>
            </value>
            <value>
                <fullName>Client Hierarchy</fullName>
            </value>
            <value>
                <fullName>Client Management</fullName>
            </value>
            <value>
                <fullName>Client Merging</fullName>
            </value>
            <value>
                <fullName>Client Plan</fullName>
            </value>
            <value>
                <fullName>Client Plan Dashboard</fullName>
            </value>
            <value>
                <fullName>Client Sector</fullName>
            </value>
            <value>
                <fullName>Client Unsubscribe/Re-subscribe</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Confirmations</fullName>
            </value>
            <value>
                <fullName>Contact Management</fullName>
            </value>
            <value>
                <fullName>Contacts</fullName>
            </value>
            <value>
                <fullName>Core CST Update</fullName>
            </value>
            <value>
                <fullName>CST Update</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
            <value>
                <fullName>Direct Debits</fullName>
            </value>
            <value>
                <fullName>Discounting</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Documentation Collections</fullName>
            </value>
            <value>
                <fullName>Documentation Credits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewCaseComment_Controller_Test.cls
@isTest
private Class NewCaseComment_Controller_Test{

    @IsTest
    static void myUnitTest() {
        
        string comment = 'Test Comment';
        
        Case cs = new Case();
        cs.Status ='New';
        cs.Priority = 'Medium';
        cs.Origin = 'Email';
        cs.Main_Category__c = 'General Management';
        cs.Sub_Category__c = 'Activities Management';
        cs.Subject = 'Test Case';
        cs.Description = 'Test Description';
        insert cs;

        Test.startTest();
        NewCaseComment_Controller.saveCaseComment(cs.id,comment);
        Test.stopTest();

        List<CaseComment> comments = [SELECT Id FROM CaseComment];
        System.assert(!comments.isEmpty());
    }
}