force-app/main/default/objects/Case/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <description>US-3669 This is an email alert indicator for open cases, each time an email is received on an open case, then the case owner is notified.</description>
    <inlineHelpText>This is an email alert indicator for open cases, each time an email is received on an open case, then the case owner is notified.</inlineHelpText>
    <label>Notification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unread Email</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Company_Industry__c.field-meta.xml
<CustomField>
    <fullName>Company_Industry__c</fullName>
    <description>OneHub: This field is used to store the Company Industry which is used to personalise the users News on their dashboard. (US-4589)</description>
    <label>Company Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Business Services and Consulting</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Manufacturing and Construction</fullName>
            </value>
            <value>
                <fullName>Marketing and Communications</fullName>
            </value>
            <value>
                <fullName>Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Oil and Gas</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Wholesale/Retail Trade</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/OSB_Community_Access_Status__c.field-meta.xml
<CustomField>
    <fullName>OSB_Community_Access_Status__c</fullName>
    <description>OneHub: This field is used to store the status of the users access to the OneHub Community.(US-4589)</description>
    <label>Community Access Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invite Sent</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/OSB_Operating_Country__c.field-meta.xml
<CustomField>
    <fullName>OSB_Operating_Country__c</fullName>
    <description>This field is used to define a OneHub user&apos;s Operating Country/s which will drive visibility of Solutions &amp; API&apos;s on the users dashboard.</description>
    <inlineHelpText>Which country/s does the user operating in?</inlineHelpText>
    <label>Operating Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OSB_Operating_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/OSB_Persona__c.field-meta.xml
<CustomField>
    <fullName>OSB_Persona__c</fullName>
    <description>This field is used to define a OneHub user&apos;s Persona which will drive visibility of Solutions &amp; API&apos;s on the users dashboard.</description>
    <formula>IF( Account.Name = &apos;Standard Bank Employees&apos;, &apos;Staff&apos;, &apos;Client&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>What is the persona of this user? IE staff or client</inlineHelpText>
    <label>Persona</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/OSB_Persona__c.field-meta.xml
<CustomField>
    <fullName>OSB_Persona__c</fullName>
    <description>This field is used to define the persona/s which Solutions &amp; API&apos;s are available to, this will drive visibility on the dashboard.</description>
    <inlineHelpText>Which persona/s is the Solution/API available to?</inlineHelpText>
    <label>Persona</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge_Entitlement_Exception__c/Knowledge_Entitlement_Exception__c.object-meta.xml
<CustomObject>
    <description>This object is used to define exceptions to the OneHub entitlements for Solutions and API&apos;s and will drive visibility on the users dashboard</description>
    <label>Knowledge Entitlement Exception</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Knowledge Entitlement Exception</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Entitlement Exceptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge_Entitlement_Exception__c/fields/OSB_Knowledge_Article__c.field-meta.xml
<CustomField>
    <fullName>OSB_Knowledge_Article__c</fullName>
    <description>This field is used to link the Knowledge Entitlement Exception record to the specific Knowledge Article it is applicable to. (SGPRT-2974)</description>
    <inlineHelpText>Select the Knowledge Article this exception is applicable to.</inlineHelpText>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Knowledge Entitlement Exceptions</relationshipLabel>
    <relationshipName>Knowledge_Entitlement_Exceptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>OneHub: This object is used to send broadcast messages to users on their OneHub dashboard. (US-4388)</description>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>OneHub: This field stores the content of the notification sent to users on their OneHub dashboard. (US-4388)</description>
    <inlineHelpText>Enter Notification Content</inlineHelpText>
    <label>Content</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Is_Unread__c.field-meta.xml
<CustomField>
    <fullName>Is_Unread__c</fullName>
    <defaultValue>true</defaultValue>
    <description>OneHub: This field indicates if the message was read or unread by users on the OneHub dashboard.(US-4388)</description>
    <label>Is Unread</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <description>OneHub: This field stored the Subtitle of the Notification that is displayed to users on the OneHub dashboard.
(US-4388)</description>
    <inlineHelpText>Enter Notification Subtitle</inlineHelpText>
    <label>Subtitle</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>OneHub: This field stored the Title of the Notification that is displayed to users on the OneHub dashboard. 
(US-4388)</description>
    <inlineHelpText>Enter Notification Title</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Users__c.field-meta.xml
<CustomField>
    <fullName>Users__c</fullName>
    <description>OneHub: This field stored the names of all active users on OneHub to select who a notification should be sent to on the OneHub dashboard.(US-4388)</description>
    <inlineHelpText>Select Users this Notification should be sent to.</inlineHelpText>
    <label>Users</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All Users</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscribed_Solutions__c/Subscribed_Solutions__c.object-meta.xml
<CustomObject>
    <description>OneHub: This object is used to manage the Solutions a user has signed up for and create the tile on the dashboard.</description>
    <label>Subscribed Solution</label>
    <nameField>
        <displayFormat>SS{00000}</displayFormat>
        <label>Subscribed Solutions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscribed_Solutions__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OneHub: This field stores which Knowledge Article the Solution is linked to.(US-4712)</description>
    <inlineHelpText>Search for the Knowledge Article to link to this record.</inlineHelpText>
    <label>Solution</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Subscribed Solutions</relationshipLabel>
    <relationshipName>Subscribed_Solutions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Solutions__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OneHub: This field stores which User  the Solution is linked to.(US-4712)</description>
    <inlineHelpText>Search for the User to link to this record.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Subscribed_Solutions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OSB_CommunityContent.cls
/**
 * OSB_CommunityContent class used in OneHub community
 *
 * @author Ayush Garg (ayusgarg@deloitte.com)
 * @date April 2020
 *
 **/
public with sharing class OSB_CommunityContent {
    private static String endpoint = null;
    private static final String PING_URL = '/services/auth/sso/';
	private static final String OFFSET_API = '&offset=';
    private static final String COUNT_API = '&count=20';
    private static final String API_SEARCH = '&safeSearch=strict&originalImg=true';
    private static final String API_ATTRIBUTE = 'callout:Bing_Api?mkt=en-US&Category=';
    private static final String ALL_USERS = 'All Users';
    private static final String CATEGORY_TECHNOLOGY = 'Technology';
    private static final String CATEGORY_BUSINESS = 'Business';
    private static final String DOCUMENT_INITIAL_URL = '/servlet/servlet.FileDownload?file=';
    
    /**
     * Redirects the user to the login page if not logged into community.
     * Prevents ilegal access if the user knows the URL
     *
     * @return PageReference
     **/
    public PageReference doRedirectToPing(){
        PageReference pageRef = new PageReference(PING_URL+OSB_SRV_PingIntegration.AUTH_PROVIDER_NAME);
        pageRef.setRedirect(true);
        return pageRef;
    }

    /**
     * Returns a list of knowledge articles for the available APIS
     *
     * @param apiId knowledge article Id
     *
     * @return List of Knowledge_kav
     **/
    @AuraEnabled(Cacheable=true)
    public static List<Knowledge__kav> getApiDetails(Id apiId) {
        return SEL_KnowledgeArticleVersions.newInstance().selectByPublishStatusIdAndRecordTypeIdWoSharing(
                new Set<String>{DMN_Knowledge.PUBLISH_STATUS_ONLINE},
                new Set<Id>{apiId},
                new Set<Id>{UTL_RecordType.getRecordTypeId(DMN_Knowledge.OBJ_NAME, DMN_Knowledge.RT_API)}
        );
    }

    /**
     * Users for the a specific Notification
     *
     * @param notificationId id of notification
     *
     * @return String
     **/
    @AuraEnabled(Cacheable=true)
    public static String getAssignedUsers(Id notificationId){
        return SEL_Notifications.newInstance().selectById(new Set<Id>{notificationId})[0].Users__c;
    }

    /**
     * map of user names and ids
     *
     * @return Map<Id, String> containing user ID as key and user name as value
     **/
    @AuraEnabled(Cacheable=true)
    public static Map<Id, String> getAvailableUsers() {
        List<User> userList = SEL_Users.newInstance().selectByIsActiveAndProfileNameWoSharing(new Set<String>{DMN_Profile.ONE_HUB_COMMUNITY});
        Map<Id, String> userMap = new Map<Id, String>();
        for(User u:userList){
            userMap.put(u.Id,u.Name);
        }
        return userMap;
    }

    /**
     * Returns a list of notifications for user
     *
     * @return List<object> feedItems
     **/
    @AuraEnabled(Cacheable=true)
    public static List<Object> getFeedItemsForUser() {
        Id userId=UserInfo.getUserId();
        List<Object> feedItems = [
                SELECT Id, Title__c, Content__c, CreatedDate, Subtitle__c, Is_Unread__c
                FROM Notification__c
                WHERE OwnerId = :userId OR Users__c INCLUDES(:userId, :ALL_USERS)
                ORDER BY CreatedDate DESC
        ];
        return feedItems;
    }

    /**
     * Returns a list for the industry picklist on the community
     *
     * @return List<string> options
     **/
    @AuraEnabled(Cacheable=true)
    public static List<String> getIndustryPicklistValues() {
        List<String> options = new List<String>();
        for( Schema.PicklistEntry f : UTL_Picklist.getPicklistValues(Contact.Company_Industry__c)) {
            options.add(f.getValue());
        }
        return options;
    }

    /**
     * Provides OSBMarketgramProducts component with information required for displaying different
     * knowledge articles, comments and votes
     * 
     * @author Wojciech Kowalczyk
     * 
     * @return map of Knowledge articles,Votes, Feed items and current user's Id
     */
    @AuraEnabled
    public static Map<String, Object> getProductsAndVotes() {
        Id userId = UserInfo.getUserId();
        Contact con = SEL_Contacts.newInstance().selectByUserId(New Set<Id>{userId})[0]; 
        Set <Id> exceptionArticleIds = new Set<Id>();
        List<Knowledge__kav> finalProductsList = new List<Knowledge__kav> ();
        List<Knowledge__kav> finalarticlesWithActivitiesList = new List<Knowledge__kav> ();
        
        for(Knowledge_Entitlement_Exception__c expRecord : SEL_KnowledgeExceptions.newInstance().selectByContactIdWoSharing(new Set<Id>{con.Id})){
            exceptionArticleIds.add(expRecord.OSB_Knowledge_Article__c);
        }
        Set<String> publishStatusSet = new Set<String>{
            DMN_Knowledge.PUBLISH_STATUS_ONLINE
        };
        Set<Id> recordTypesIds = new Set<Id>{
            UTL_RecordType.getRecordTypeId(DMN_Knowledge.OBJ_NAME, DMN_Knowledge.RT_API),
            UTL_RecordType.getRecordTypeId(DMN_Knowledge.OBJ_NAME, DMN_Knowledge.RT_Solution)
        };  

        List<Knowledge__kav> apiArticles;
        apiArticles = SEL_KnowledgeArticleVersions.newInstance().selectByPublishStatusAndRecordTypeIdPersonaApiWoSharing(
                    new Set<String>{DMN_Knowledge.PUBLISH_STATUS_ONLINE},
                    new Set<Id>{UTL_RecordType.getRecordTypeId(DMN_Knowledge.OBJ_NAME, DMN_Knowledge.RT_API)},
                    con.OSB_Persona__c,
                    con.OSB_Operating_Country__c,
                    exceptionArticleIds
            );
        
        List<Knowledge__kav> solutionArticles;
        solutionArticles = SEL_KnowledgeArticleVersions.newInstance().selectByPublishStatusAndRecordTypeIdPersonaSolutionWoSharing(
                    new Set<String>{DMN_Knowledge.PUBLISH_STATUS_ONLINE},
                    new Set<Id>{UTL_RecordType.getRecordTypeId(DMN_Knowledge.OBJ_NAME, DMN_Knowledge.RT_SOLUTION)},
            		new Set<Id>{},
                    con.OSB_Persona__c,
                    con.OSB_Operating_Country__c,
                    exceptionArticleIds
            );
        finalProductsList.addAll(apiArticles);
        finalProductsList.addAll(solutionArticles);
        
        Map<Id, Knowledge__ka> articlesWithActivities = new Map<Id, Knowledge__ka>(
                new SEL_KnowledgeArticles().selectWithVotesAndFeedsByVersionRecordTypePersona(
                        recordTypesIds,
                        publishStatusSet,
                    	exceptionArticleIds,
                    	con.OSB_Persona__c,
                    	con.OSB_Operating_Country__c
                )
        );
        
        Map<String, Object> name2Object = new Map<String, Object>();
        name2Object.put('products', finalProductsList);
        name2Object.put('articlesWithActivities', articlesWithActivities);
        name2Object.put('userId', userId);
        return name2Object;
    }

    /**
     * Checks if the user has been logged in for the first time for guided tour
     *
     * @return Contact
     **/
    @AuraEnabled(Cacheable=false)
    public static Contact getOnboardingDetails() {
        try{
            if (UTL_User.isLoggedInUser()) {
                Contact contacts = SEL_Contacts.newInstance().selectByUserId(new Set<Id>{UserInfo.getUserId()})[0];
                return contacts;
            }
            return null;
        }
        catch(Exception ex){
            return null;
        }
    }

    /**
     * Gets the users email
     *
     * @return String email
     **/
    @AuraEnabled(Cacheable=true)
    public static String getUserEmail() {
        return UserInfo.getUserEmail();
    }

    /**
     * Checks if the current user is login to community
     *
     * @return Boolean
     **/
    @AuraEnabled(Cacheable=true)
    public static Boolean isUserLoggedIn() {
        return UTL_User.isLoggedInUser();
    }

    /**
     * Updates the notification as read
     *
     * @param recordId of Notification__c
     * @return error message if update fails
     **/
    @AuraEnabled(Cacheable=false)
    public static String markReadNotification(Id recordId) {
        fflib_ISObjectUnitOfWork uow = ORG_Application.unitOfWork.newInstance();
        Notification__c notif = new Notification__c(Id =  recordId, Is_Unread__c = false);
        try {
            uow.registerDirty(notif);
            uow.commitWork();
        } catch(Exception ex) {
            return ex.getMessage();
        }
        return '';
    }

    /**
     * Updates knowledge article scoring after user's interaction in OSBMarketgramProduct component
     *
     * @param voteId if it is not null, then method updates existing vote, in other case, it's creating new one
     * @param knowledgeId id of Knowledge__ka that is being scored
     * @param operationType LIKE or DISLIKE
     *
     * @return vote's Id
     */
    @AuraEnabled(Cacheable=false)
    public static String updateScoring(Id voteId, Id knowledgeId, String operationType) {
        fflib_ISObjectUnitOfWork uow = ORG_Application.unitOfWork.newInstance();
        
        String voteType = operationType == 'LIKE' ? '5' : '1';
        Vote userVote = new Vote(Id = voteId, ParentId = knowledgeId, Type = voteType);
        uow.registerUpsert(userVote);
        uow.commitWork();
		
        return userVote.Id;
    }
    
    /**
     * Inserts a new Subscribed Solution record and returns true if successful and false if not
     * 
     * @param  solutionId String
     *
     **/
    @AuraEnabled(Cacheable=false)
    public static void createUserSubscribedSolution(Id solutionId) {
        fflib_ISObjectUnitOfWork uow = ORG_Application.unitOfWork.newInstance(); 
        Subscribed_Solutions__c subscribedSolution = new Subscribed_Solutions__c();
        subscribedSolution.User__c = UserInfo.getUserId();
        subscribedSolution.Solution__c = solutionId; 
        uow.registerNew(subscribedSolution);
        uow.commitWork();
    }
    
    /**
     * Deletes a Subscribed Solution record and returns true if successful and false if not
     * 
     * @param  solutionId String
     *
     **/
    @AuraEnabled(Cacheable=false)
    public static void removeUserSubscribedSolution(String solutionId) {
        fflib_ISObjectUnitOfWork uow = ORG_Application.unitOfWork.newInstance(); 
        List<Subscribed_Solutions__c> subscribedSolution  = SEL_SubscribedSolutions.newInstance().selectByUserIdAndSolutionId(new set<Id> {solutionId}, new set<Id> {UserInfo.getUserId()});
        uow.registerDeleted(subscribedSolution);
        uow.commitWork();
    }

    /**
     * Used to display team profile to the correct users 
     * 
     * @return Boolean true if user access is approved
     **/
    @AuraEnabled(Cacheable=true)
    public static Boolean getContactAuth() {
        Boolean authorisation = false;
        List <Contact> contactList = SEL_Contacts.newInstance().selectByUserId(new Set<Id>{UserInfo.getUserId()});
        if(!contactList.isEmpty()){
            if(contactList[0].OSB_Community_Access_Status__c == DMN_Contact.OSB_COMMUNITY_ACCESS_STATUS_APPROVED){
                authorisation = true;
            }
    	}
        return authorisation;
    }

}