force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Category of Product, based on the Parent Product, for which this case has been opened</description>
    <inlineHelpText>Category of Product, based on the Parent Product, for which this case has been opened</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Parent_Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Draw_Down_Profile__c/Draw_Down_Profile__c.object-meta.xml
<CustomObject>
    <description>Case#141 - When an Opportunity and a qualifying Product (Lending / Deposits / Commitments) has been loaded then the user needs to be able to capture the flows / drawdowns and the dates of these transactions on the Product.</description>
    <label>Draw Down Profile</label>
    <nameField>
        <displayFormat>DDP-{0000000000}</displayFormat>
        <label>Draw Down Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Draw Down Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Draw_Down_Profile__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Case#141 - Rudolf Niehaus
Master detail relationship to product (Lending / Deposits / Commitments)</description>
    <label>Product</label>
    <referenceTo>SB_Product__c</referenceTo>
    <relationshipLabel>Draw Down Profiles</relationshipLabel>
    <relationshipName>Draw_Down_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Environment_Variable__c/Environment_Variable__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Environment Variables</label>
</CustomObject>

force-app/main/default/objects/Environment_Variable__c/fields/Draw_Down_Grand_Parent_Products__c.field-meta.xml
<CustomField>
    <fullName>Draw_Down_Grand_Parent_Products__c</fullName>
    <description>Case#141 - Rudolf Niehaus. 
Draw down profiles records and rules are only applicable for Grand Parent Product (GPP) pick list values in this field. Semi-colon separate multiple GPP pick list values.</description>
    <inlineHelpText>Use a semi-colon to separate multiple Grand Parent Products.</inlineHelpText>
    <label>Draw Down Grand Parent Products</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Environment_Variable__c/fields/Draw_Down_Product_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Draw_Down_Product_Record_Types__c</fullName>
    <description>Case#141 - Rudolf Niehaus.
Draw down profiles records and rules are only applicable for product record types in this field. Comma separate multiple record type names. The name and NOT the API name is used to make it easier for non developers to update the values.</description>
    <inlineHelpText>Use a semi-colon to separate multiple product record types.</inlineHelpText>
    <label>Draw Down Product Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Environment_Variable__c/fields/serverURL__c.field-meta.xml
<CustomField>
    <fullName>serverURL__c</fullName>
    <label>serverURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SFP-9327 [c] - A lookup field to allow the relationship manager to select the appropriate product for the opportunity</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/SB_Product__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Products as Standard Bank have requirements that cannot be met with standard object.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Prod-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SB_Product__c/fields/Grand_Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Grand_Parent_Product__c</fullName>
    <description>Grand Parent Product</description>
    <label>Grand Parent Product (GPP)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Advisory Fees</fullName>
            </value>
            <value>
                <fullName>Agricultural Products</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Bank Sector Services</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Bills of exchange discounted</fullName>
            </value>
            <value>
                <fullName>Bonds</fullName>
            </value>
            <value>
                <fullName>Bulk and Steel</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Commitments</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Core Custody</fullName>
            </value>
            <value>
                <fullName>Cost Overrun Facility</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Credit Finance &amp; Leverage</fullName>
            </value>
            <value>
                <fullName>Credit Linked Notes &amp; Depo</fullName>
            </value>
            <value>
                <fullName>Cross Border Finance</fullName>
            </value>
            <value>
                <fullName>Custody Services</fullName>
            </value>
            <value>
                <fullName>Customer foreign currency accounts (CFC)</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Debtor Finance</fullName>
            </value>
            <value>
                <fullName>Debt Structuring</fullName>
            </value>
            <value>
                <fullName>Deposits</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Drafts issues</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DrawDownProductRedirect_Vf_Ext.cls
/*****************************************************************************************************\
    @ Func Area     : Opportunities, Products (SB_Product__c) & Draw Down Profile

    -------------------------------------------------------------------------------------
    @description      Case#141, This is the controller class for the visualforce page "DrawDownProductRedirect_Vf".
                      The controller / page redirects a user to the draw down page from the
                      product page if:
                        - The product record type is in the custom setting "Draw_Down_Product_Record_Types__c"
                        - The product Grand Parent Product (GPP) pick list value is in the custom setting "Draw_Down_Grand_Parent_Products__c"
                        - There are no Draw Down Profile ralted records currently linked to the
                          specific product.
    @author Rudolf Niehaus
    @date 27/06/2012
                                
******************************************************************************************************/
public with sharing class DrawDownProductRedirect_Vf_Ext {
    private Id productId;
    private Id oppId;
    @TestVisible private list<SB_Product__c> lstProduct;
    @TestVisible private list<Draw_Down_Profile__c> lstDrawDown;
    private Environment_Variable__c settings = null;
    @TestVisible private Integer newProduct;

    /**
     * Method gets the referer URL in order to redirect to opportunity
     *
     * @return
     */
    public String getReferer() {
        return ApexPages.currentPage().getHeaders().get('Referer');
    }

    /**
     * Constructor for controller extension
     *
     * @param stdCon
     */
    public DrawDownProductRedirect_Vf_Ext(ApexPages.StandardController stdCon) {
        //Get the environment values that indictes if this product must adhear to the business rules for draw down's
        this.settings = Environment_Variable__c.getInstance();
        productId = stdCon.getId();
        lstProduct = [select Id, RecordType.Name, Grand_Parent_Product__c, Opportunity__c from SB_product__c where Id = :productId limit 1];
        lstDrawDown = [select Id from Draw_Down_Profile__c where Product__c = :productId];


        System.debug('Current request URL: ' + getReferer());

        //Sets newProduct flag to avoid override if applicable
        if (getReferer() == settings.serverURL__c + '/a0g/e') {
            newProduct = 1;
        } else {
            newProduct = 0;
        }
    }

    /**
     * This method will redirect the user from the product page based on the business rules
     *
     * @return PageReference
     */
    public PageReference redirect() {
        PageReference pageRef = null;

        // If product is not found redirect to standard view to display 'Data not available' message
        if (lstProduct.isEmpty()) {
            pageRef = new PageReference('/' + productId + '?nooverride=1');
            return pageRef;
        }

        String productRecordTypes = settings.Draw_Down_Product_Record_Types__c;
        String gppPickListValues = settings.Draw_Down_Grand_Parent_Products__c;

        //the default is NO overriding and navigate back to the related Opportunity.
        pageRef = new PageReference('/' + lstProduct[0].Opportunity__c + '?nooverride=1');

        //If this product record type and parent product name falls into the rule category, enforce rule.
        if ((productRecordTypes.contains(lstProduct[0].RecordType.Name)) &&
                (gppPickListValues.contains(lstProduct[0].Grand_Parent_Product__c))) {
                //If there are no draw down records for the product enforce the business rules 
                if(lstDrawDown.size() == 0){    
                    pageRef = new PageReference('/apex/DrawDownProfile_Vf?Id=' + productId + '&recs=' + lstDrawDown.size());
                }else{
                    pageRef = new PageReference('/' + productId + '?nooverride=1');
                }
        }else{
                if(newProduct == 0){
                    pageRef = new PageReference('/' + productId + '?nooverride=1');
                }
        }
        
        return pageRef;
     }
}