force-app/main/default/objects/CMN_PostCopyTask__mdt/CMN_PostCopyTask__mdt.object-meta.xml
<CustomObject>
    <description>Use the to register the available post sandbox copy worker classes and also whether they should be executed during sandbox creation; i.e. depending on scenario it may be appropriate to disable some worker class execution prior to sandbox creation. NB this must be done in the sandbox source org.</description>
    <label>Post Copy Task</label>
    <pluralLabel>Post Copy Tasks</pluralLabel>
</CustomObject>

force-app/main/default/objects/CMN_PostCopyTask__mdt/fields/CMN_Active__c.field-meta.xml
<CustomField>
    <fullName>CMN_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CMN_PostCopyTask__mdt/fields/CMN_OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>CMN_OrderNumber__c</fullName>
    <label>Order Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CMN_DAL_PostCopyTask.cls
/**
 * @description Public class to as part of post copy script to query metadata
 *
 * @author Accenture
 *
 * @date 2020
 */
public inherited sharing class CMN_DAL_PostCopyTask
{
	/**
	 * @description Method to query post copy metadata type
	 *
	 * @return List
	 */
	public static List<CMN_PostCopyTask__mdt> getAll()
	{
		return
		[
				SELECT
						Id,
						DeveloperName,
						CMN_Active__c,
						CMN_OrderNumber__c
				FROM CMN_PostCopyTask__mdt
				WHERE CMN_Active__c = TRUE
				ORDER BY CMN_OrderNumber__c ASC
				LIMIT :CMN_DAL_SObjectDomain.LIMIT_NUMBER_OF_RECORDS

		];

	}
}