force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Event Report Object to store the Event Information and associate Attendees and Send Email to them.</description>
    <label>Event Report</label>
    <nameField>
        <label>Event Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Relate_to_Client__c.field-meta.xml
<CustomField>
    <fullName>Relate_to_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link related client to event report</description>
    <inlineHelpText>The Client that was ‘discussed at / included in’ the meeting. You are required to provide a Related to Client when the Meeting Audience is Internal, and there is no Related to Opportunity, Case or Campaign</inlineHelpText>
    <label>Related to Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Reports (Relate to Client)</relationshipLabel>
    <relationshipName>Event_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Report_Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Report_Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact / Lead Lookup for the Report</description>
    <inlineHelpText>Contact at the Client with whom the meeting ‘will be / was’ held. You are required to provide the main Client Contact when the Meeting Audience is External, and there is no Related to Opportunity, Case or Campaign</inlineHelpText>
    <label>Client Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3 AND 4)</booleanFilter>
        <errorMessage>Please enter an active Client Contact for External Meetings only. Bank Contacts (Employees) or inactive contacts cannot be captured.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Contact Record Type</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Inactive Client Contact Record Type</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Reports (Client Contact)</relationshipLabel>
    <relationshipName>Event_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/Call_Report_Attendees__c.object-meta.xml
<CustomObject>
    <description>Case 4296 Changed Name field from text to autonumber</description>
    <label>Event Report Attendees</label>
    <nameField>
        <displayFormat>ERA-{0000000000}</displayFormat>
        <label>Event Report Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Report Attendeess</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Call_Report__c.field-meta.xml
<CustomField>
    <fullName>Call_Report__c</fullName>
    <label>Event Report</label>
    <referenceTo>Call_Report__c</referenceTo>
    <relationshipLabel>Event Report Attendees</relationshipLabel>
    <relationshipName>Call_Report_Attendeess</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Client_Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Client_Team_Role__c</fullName>
    <description>Will contain the role corresponding to the CST user in the related Client w.r.t to EN 661</description>
    <label>Client Team Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Contact_id__c.field-meta.xml
<CustomField>
    <fullName>Contact_id__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <description>Case 4296 Changed label</description>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Contact must be active.</errorMessage>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Reports Associated</relationshipLabel>
    <relationshipName>Call_Report_Attendeess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Related_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Related_Agenda__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <description>Agenda to which the submission attendees are associated to</description>
    <inlineHelpText>Agenda to which the submission attendees are associated to</inlineHelpText>
    <label>Related Agenda</label>
    <referenceTo>Agenda__c</referenceTo>
    <relationshipLabel>Event Report Attendees</relationshipLabel>
    <relationshipName>Call_Report_Attendeess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Email__c</fullName>
    <description>To store the status of Email being sent to Invited Attendees

Case 4296 : Event Report Enhancements: Relabeled Field from Send Email to Distribution</description>
    <label>Distribution</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
                <default>true</default>
                <label>Invited</label>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Distribute Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Type_of_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Attendee__c</fullName>
    <description>US-1212: Created for Meeting Console in order to identify the type of Attendee that we select via console</description>
    <label>Type of Attendee</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Committee Attendee</fullName>
            </value>
            <value>
                <fullName>Submission Attendee</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the status of the contact at the client. This status is used to improve contact searches .Inactive Contacts are excluded from lookup searches</description>
    <inlineHelpText>Indicates the status of the contact at the client. This status is used to improve contact searches.</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CSTTeamRoleRanking__c/CSTTeamRoleRanking__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CST Team Role Ranking is for ranking to the core team members.</description>
    <label>CST Team Role Ranking</label>
</CustomObject>

force-app/main/default/objects/CSTTeamRoleRanking__c/fields/CSTTeamRoleRanking__c.field-meta.xml
<CustomField>
    <fullName>CSTTeamRoleRanking__c</fullName>
    <description>CST Team Role Ranking is for ranking to the core team members.</description>
    <inlineHelpText>CST Team Role Ranking value , unique value used to sort Core Team Roles. Values to be numeric from 01-99, or ranking will not work correctly.</inlineHelpText>
    <label>CSTTeamRoleRanking</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/Custom_Client_Team__c.object-meta.xml
<CustomObject>
    <label>Client Team</label>
    <nameField>
        <displayFormat>Client-{0000}</displayFormat>
        <label>Client Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Client_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/TeamRoleSortValue__c.field-meta.xml
<CustomField>
    <fullName>TeamRoleSortValue__c</fullName>
    <description>CST Phase (3)  - Core team role ranking values .</description>
    <label>Sort</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Contact_Sync_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_Sync_ID__c</fullName>
    <description>Field that holds the contact ID for the user. Case# 150 - manual update currently for Event Reporting, created by Rudolf Niehaus. Will eventually gets updated by a trigger implemented with Case# 530</description>
    <inlineHelpText>Field that holds the Contact ID for the User (18 characters or less)</inlineHelpText>
    <label>Contact Sync ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SubmissionAttendee_ctrl.cls
/***
@ Func Area     	:  NBAC
@ Author        	:  Emmanuel Nocks Mulea
@ Date          	:  01.16.2020
@User Story    	    :  US-4260
@ Description 	    :  pulling all submission Attendees and creating them if not exist
***/
public without sharing class SubmissionAttendee_ctrl{
    public ID currentAgendaIdsub {get;  set;}
    public ID currentERIdsub {get;  set;}
    public boolean showintattpanelsub{get;  set;}  
    public boolean showerrormsgsub{get;  set;}
    public String strReportCurrencysub {get;set;}
    public List<InternalAttendeeWrappersub> lstAttendeessub {get;set;}
    public Call_Report__c sobjEventReportsub {get;set;}
    public User sObjEventOwnersub {get;set;}
    private Set<Id> setCheckContactIdsub;  
    private Set<Id> setCheckcommattId; 
    public boolean hasAccesssub{get;  set;}
    public boolean iscommattinsub{get;  set;}
    public boolean issubattinsub{get;  set;}
    public String errorMsginaddsubatt{get;set;}
    
    public SubmissionAttendee_ctrl(){
        showintattpanelsub = false;
        showerrormsgsub = false;
        errorMsginaddsubatt = '';
    }
    
    public List<Call_report_attendees__c> eralstsub{
        get{
            eralstsub = new List<Call_report_attendees__c>();
            if(currentAgendaIdsub != null){
                eralstsub = [Select Id, Contact_Id__c, Contact_Id__r.Id, Contact_Id__r.Name, Contact_Id__r.RecordType.DeveloperName, Send_Email__c, Status__c,Client_Team_Role__c
                                                                    FROM Call_Report_Attendees__c where Related_Agenda__c=:currentAgendaIdsub];
            }
            return eralstsub;
        } set;
        
    }
    /***
Use
@param  	    :  String agendaId
@return   	    :  List of Call_report_attendees__c
@ Description 	:  get a list of Call_report_attendees__c by agendaId
***/
    @AuraEnabled
    public Static List<Call_report_attendees__c> getListOfAttendees(String agendaId){

        List<Call_report_attendees__c> AttendeeList = new List<Call_report_attendees__c>();

        AttendeeList = [Select Id,Type_of_Attendee__c, Contact_Id__c, Contact_Id__r.Id, Contact_Id__r.Name, Contact_Id__r.RecordType.DeveloperName, Send_Email__c, Status__c,Client_Team_Role__c
        FROM Call_Report_Attendees__c where Related_Agenda__c=:agendaId];

        return AttendeeList;


    }
    public PageReference showinternalattendeesub(){
        NBACMeetingController.errorMsginssub ='';
        if(currentAgendaIdsub != null){
            sobjEventReportsub = [Select Id, OwnerId, CurrencyIsoCode, Name,Report_Client_Contact__r.AccountId, Relate_to_Client__c from Call_Report__c where Id =: currentERIdsub ];
            sObjEventOwnersub = [Select Id, Contact_Sync_ID__c from User where Id =:sobjEventReportsub.OwnerId];
            strReportCurrencysub = sobjEventReportsub.CurrencyIsoCode;
            lstAttendeessub = new List<InternalAttendeeWrappersub>();
            getEventReportAttendeesub();
            getClientTeamMemberssub();
            addRowsub();
            lstAttendeessub.sort();
            showintattpanelsub = true;
        }else{
            showerrormsgsub = True;
        }
        return null;
    }
    /***
Use
@param  	    :  String currentERIdsub,String currentAgendaIdsub
@return   	    :  String
@ Description 	:  get a list of InternalAttendeeWrappersub using EventReportID and that has been Agenda selected
***/
    @AuraEnabled
    public Static String showinternalattendeesub(String currentERIdsub,String currentAgendaIdsub){

        Call_Report__c sobjEventReportsub = [Select Id, OwnerId, CurrencyIsoCode, Name,Report_Client_Contact__r.AccountId, Relate_to_Client__c from Call_Report__c where Id =: currentERIdsub ];
        User sObjEventOwnersub = [Select Id, Contact_Sync_ID__c from User where Id =:sobjEventReportsub.OwnerId];
        String strReportCurrencysub = sobjEventReportsub.CurrencyIsoCode;

        List<InternalAttendeeWrappersub>   lstAttendees = SubmissionAttendee_ctrl.getEventReportAttendeeSubAura(currentAgendaIdsub,currentERIdsub,sObjEventOwnersub,strReportCurrencysub,sobjEventReportsub);


        return JSON.serialize(lstAttendees);
    }

    /***
Use
@param  	    :  String currentAgendaIdsub,String currentERId,User sObjEventOwnersub,String strReportCurrency,Call_Report__c sobjEventReport
@return   	    :  List of InternalAttendeeWrappersub
@ Description 	:  method to get already existing event report attendees
***/
    public Static List<InternalAttendeeWrappersub> getEventReportAttendeeSubAura(String currentAgendaIdsub,String currentERId,User sObjEventOwnersub,String strReportCurrency,Call_Report__c sobjEventReport){

        List<InternalAttendeeWrappersub>   lstAttendeessub = new List<InternalAttendeeWrappersub>();
        for(Call_Report_Attendees__c sObjReportAttendees : [Select Id, Contact_Id__c, Contact_Id__r.Id, Contact_Id__r.Name, Contact_Id__r.RecordType.DeveloperName, Send_Email__c, Status__c,Client_Team_Role__c
        FROM Call_Report_Attendees__c where Related_Agenda__c =:currentAgendaIdsub]){

            InternalAttendeeWrappersub objAttendees = new InternalAttendeeWrappersub(sObjReportAttendees);
            if(sObjEventOwnersub.Contact_Sync_ID__c == sObjReportAttendees.Contact_Id__c){
                objAttendees.intOrder = '0';
            }
            lstAttendeessub.add(objAttendees);
        }
        lstAttendeessub.addAll(SubmissionAttendee_ctrl.getClientTeamMemberSubAura(strReportCurrency,currentAgendaIdsub,currentERId,sobjEventReport));
        return lstAttendeessub;
    }

    // method to get the list of Client Team members
    public Static List<InternalAttendeeWrappersub>  getClientTeamMemberSubAura(String strReportCurrencysub,String currentAgendaIdsub,String currentERIdsub,Call_Report__c sobjEventReportsub){
        Set<Id> setCheckContactIdsub = SubmissionAttendee_ctrl.getCheckContactId(currentERIdsub);
        List<InternalAttendeeWrappersub>   lstAttendeessub = new List<InternalAttendeeWrappersub>();
        Map<Id, AccountTeamMember> mapContactId = new Map<Id, AccountTeamMember>();
        for(AccountTeamMember sObjAccTeamMember : [Select Id, User.Contact_Sync_ID__c, TeamMemberRole, AccountId
        from AccountTeamMember where AccountId =:sobjEventReportsub.Relate_to_Client__c]){
            if(setCheckContactIdsub.add(sObjAccTeamMember.User.Contact_Sync_ID__c))
                mapContactId.put(sObjAccTeamMember.User.Contact_Sync_ID__c, sObjAccTeamMember);
        }

        if(!mapContactId.isEmpty()){

            Custom_Client_Team__c[] lstClientTeam= [Select Team_Member__r.Contact_Sync_ID__c, TeamRoleSortValue__c From Custom_Client_Team__c  where Account__c =: sobjEventReportsub.Relate_to_Client__c and Team_Member__r.Contact_Sync_ID__c IN :mapContactId.keyset()];
            map<Id, String> mapClientTeam = new map<Id, String>();
            for(Custom_Client_Team__c cct : lstClientTeam)
                mapClientTeam.put(cct.Team_Member__r.Contact_Sync_ID__c, cct.TeamRoleSortValue__c);

            for(Contact sObjContact: [Select Id, Name, Inactive__c From Contact where Id IN :mapContactId.keyset()]){
                CSTTeamRoleRanking__c sObjRanking = CSTTeamRoleRanking__c.getValues(mapContactId.get(sObjContact.Id).TeamMemberRole);
                String teamRole = mapContactId.get(sObjContact.Id).TeamMemberRole;
                String rank = '49';
                rank = mapClientTeam.containsKey(sObjContact.Id) ?  mapClientTeam.get(sObjContact.Id) : '49';
                rank = rank.contains('_') ? '49' : rank;
                lstAttendeessub.add(new InternalAttendeeWrappersub(false, sObjContact, currentERIdsub, currentAgendaIdsub, strReportCurrencysub, teamRole, rank));
            }
        }

        return lstAttendeessub;
    }
    public static Set<Id> getChecksubattId(String currentERId){

        Set<Id> setChecksubattId = new Set<Id>();
        for(Call_Report_Attendees__c subattendees :[Select Id, Contact_Id__c, Contact_Id__r.Id, Contact_Id__r.Name, Contact_Id__r.RecordType.DeveloperName, Send_Email__c, Status__c,Client_Team_Role__c
        FROM Call_Report_Attendees__c where Call_Report__c=:currentERId and Contact_Id__r.RecordType.DeveloperName='SA_Bank_Contact_Record_Type' and Type_of_Attendee__c = 'Submission Attendee']){
            setChecksubattId.add(subattendees.Contact_Id__c);
        }

        return setChecksubattId;
    }

    public static Set<Id> getCheckcommattId(String currentERIdsub){

        Set<Id> setCheckcommattId = new Set<Id>();
        for(Call_Report_Attendees__c committeeattendees :[Select Id, Contact_Id__c, Contact_Id__r.Id, Contact_Id__r.Name, Contact_Id__r.RecordType.DeveloperName, Send_Email__c, Status__c,Client_Team_Role__c
        FROM Call_Report_Attendees__c where Call_Report__c=:currentERIdsub and Contact_Id__r.RecordType.DeveloperName='SA_Bank_Contact_Record_Type' and Type_of_Attendee__c = 'Committee Attendee']){
        setCheckcommattId.add(committeeattendees.Contact_Id__c);
        }

        return setCheckcommattId;
    }

    public static Set<Id> getCheckContactId(String currentERId){

        Set<Id> setCheckContactId = new Set<Id>();
        for(Call_Report_Attendees__c sObjReportAttendees : [Select Id, Contact_Id__c, Contact_Id__r.Id, Contact_Id__r.Name, Contact_Id__r.RecordType.DeveloperName, Send_Email__c, Status__c,Client_Team_Role__c
        FROM Call_Report_Attendees__c where Call_Report__c=:currentERId and Contact_Id__r.RecordType.DeveloperName='SA_Bank_Contact_Record_Type' and Type_of_Attendee__c = 'Committee Attendee']){

            setCheckContactId.add(sObjReportAttendees.Contact_Id__c);
        }

        return setCheckContactId;
    }
    // method to get already existing event report attendees
    public void getEventReportAttendeesub(){
        
        setCheckContactIdsub = new Set<Id>();
        setCheckcommattId = new Set<Id>();
        for(Call_Report_Attendees__c committeeattendees :[Select Id, Contact_Id__c, Contact_Id__r.Id, Contact_Id__r.Name, Contact_Id__r.RecordType.DeveloperName, Send_Email__c, Status__c,Client_Team_Role__c
                                                                    FROM Call_Report_Attendees__c where Call_Report__c=:currentERIdsub and Contact_Id__r.RecordType.DeveloperName='SA_Bank_Contact_Record_Type' and Type_of_Attendee__c = 'Committee Attendee']){
               setCheckcommattId.add(committeeattendees.Contact_Id__c);                                    
        }
        
        for(Call_Report_Attendees__c sObjReportAttendees : [Select Id, Contact_Id__c, Contact_Id__r.Id, Contact_Id__r.Name, Contact_Id__r.RecordType.DeveloperName, Send_Email__c, Status__c,Client_Team_Role__c
                                                                    FROM Call_Report_Attendees__c where Related_Agenda__c =:currentAgendaIdsub]){
            
            InternalAttendeeWrappersub objAttendees = new InternalAttendeeWrappersub(sObjReportAttendees);
            if(sObjEventOwnersub.Contact_Sync_ID__c == sObjReportAttendees.Contact_Id__c){
                objAttendees.intOrder = '0';
            }
            lstAttendeessub.add(objAttendees);
            setCheckContactIdsub.add(sObjReportAttendees.Contact_Id__c);
        }
    }
    // method to get the list of Client Team members
    public void getClientTeamMemberssub(){
        
        Map<Id, AccountTeamMember> mapContactId = new Map<Id, AccountTeamMember>();
        for(AccountTeamMember sObjAccTeamMember : [Select Id, User.Contact_Sync_ID__c, TeamMemberRole, AccountId 
                                                    from AccountTeamMember where AccountId =:sobjEventReportsub.Relate_to_Client__c]){
            if(setCheckContactIdsub.add(sObjAccTeamMember.User.Contact_Sync_ID__c))
                mapContactId.put(sObjAccTeamMember.User.Contact_Sync_ID__c, sObjAccTeamMember);
        }
        
        if(!mapContactId.isEmpty()){

          Custom_Client_Team__c[] lstClientTeam= [Select Team_Member__r.Contact_Sync_ID__c, TeamRoleSortValue__c From Custom_Client_Team__c  where Account__c =: sobjEventReportsub.Relate_to_Client__c and Team_Member__r.Contact_Sync_ID__c IN :mapContactId.keyset()];
          map<Id, String> mapClientTeam = new map<Id, String>();
          for(Custom_Client_Team__c cct : lstClientTeam)
            mapClientTeam.put(cct.Team_Member__r.Contact_Sync_ID__c, cct.TeamRoleSortValue__c);

            for(Contact sObjContact: [Select Id, Name, Inactive__c From Contact where Id IN :mapContactId.keyset()]){
                CSTTeamRoleRanking__c sObjRanking = CSTTeamRoleRanking__c.getValues(mapContactId.get(sObjContact.Id).TeamMemberRole);
                String teamRole = mapContactId.get(sObjContact.Id).TeamMemberRole;
                String rank = '49';
                rank = mapClientTeam.containsKey(sObjContact.Id) ?  mapClientTeam.get(sObjContact.Id) : '49';
                rank = rank.contains('_') ? '49' : rank;
                lstAttendeessub.add(new InternalAttendeeWrappersub(false, sObjContact, currentERIdsub, currentAgendaIdsub, strReportCurrencysub, teamRole, rank));
            }
        }
    }
    
    
    public Pagereference addRowsub(){
        for(Integer i=0;i<4;i++){
            lstAttendeessub.add(new InternalAttendeeWrappersub(false, null, currentERIdsub, currentAgendaIdsub, strReportCurrencysub, null ,'50'));
        }
        return null;
    }
    /***
Use
@param  	    :  string currentERIdsub,string currentAgendaIdsub
@return   	    :  JSON List of InternalAttendeeWrappersub as a string
@ Description 	:  create virtual object of InternalAttendeeWrappersub for cmp to use it as a new row
***/
    @AuraEnabled
    public Static String addRowAura(string currentERIdsub,string currentAgendaIdsub){
        Call_Report__c eventReport= [Select Id, OwnerId, CurrencyIsoCode, Name,Report_Client_Contact__r.AccountId, Relate_to_Client__c from Call_Report__c where Id =: currentERIdsub ];
        InternalAttendeeWrappersub newSub= new InternalAttendeeWrappersub(false, null, currentERIdsub, currentAgendaIdsub, eventReport.CurrencyIsoCode, null ,'50');

        return JSON.serialize(newSub);
    }
    /***
Use
@param  	    :  string currentERIdsub,string currentAgendaIdsub
@return   	    :  JSON List of InternalAttendeeWrappersub as a string
@ Description 	:  create virtual object of InternalAttendeeWrappersub for cmp to use it as a new 4 rows
***/
    @AuraEnabled
    public Static String add_4_RowAura(string currentERIdsub,string currentAgendaIdsub){
        Call_Report__c eventReport= [Select Id, OwnerId, CurrencyIsoCode, Name,Report_Client_Contact__r.AccountId, Relate_to_Client__c from Call_Report__c where Id =: currentERIdsub ];
        List<InternalAttendeeWrappersub> newSubList = new List<InternalAttendeeWrappersub>();
        for(integer x=0;x<4;x++) {

        InternalAttendeeWrappersub newSub = new InternalAttendeeWrappersub(false, null, currentERIdsub, currentAgendaIdsub, eventReport.CurrencyIsoCode, null, '50');
            newSubList.add(newSub);
        }
        return JSON.serialize(newSubList);
    }
    public Pagereference addRowsubonlink(){
        for(Integer i=0;i<4;i++){
            lstAttendeessub.add(new InternalAttendeeWrappersub(false, null, currentERIdsub, currentAgendaIdsub, strReportCurrencysub, null ,'50'));
        }
        showintattpanelsub = true;
        errorMsginaddsubatt = '';
        return null;
    }
    /***
Use
@param  	    :  string currentERIdsub,string submissionList
@return   	    :  JSON as a string
@ Description 	:  Create or edit Submission Attendees
***/
    @AuraEnabled
    public Static String saveSubmissionAttendee(string currentERIdsub,string submissionList){
        JSONGenerator jsonGen = JSON.createGenerator(true);
        try{
            List<Call_Report_Attendees__c> lstUpsertAttendee = new List<Call_Report_Attendees__c>();
            List<Call_Report_Attendees__c> lstRemoveAttendee = new List<Call_Report_Attendees__c>();
            Set<Id> setCheckContactIdsub = SubmissionAttendee_ctrl.getCheckContactId(currentERIdsub);
            Set<Id> setCheckcommattId = SubmissionAttendee_ctrl.getCheckcommattId(currentERIdsub);
            Set<Id> setCheck = new Set<Id>();
            Boolean isErrors = false;
            List<InternalAttendeeWrappersub> lstAttendeessub = (List<InternalAttendeeWrappersub>)JSON.deserialize(submissionList, List<InternalAttendeeWrappersub>.class);
            for(InternalAttendeeWrappersub objAttendee: lstAttendeessub){
            if(objAttendee.bChecked){
                if(objAttendee.sobjAttendee.Contact_Id__c==null){
                    objAttendee.isError=true;
                    objAttendee.errorMessage= 'Attendee Name cannot be blank';
                    isErrors =true;
                }
                else if(setCheckcommattId.contains(objAttendee.sobjAttendee.Contact_Id__c)){

                    objAttendee.isError=true;
                    objAttendee.errorMessage= Label.Submission_already_a_Committee;
                    isErrors =true;
                }
                else if(setCheckContactIdsub.add(objAttendee.sobjAttendee.Contact_Id__c)) {
                    setCheck.add(objAttendee.sobjAttendee.Contact_Id__c);
                    lstUpsertAttendee.add(objAttendee.sobjAttendee);
                }
                else if(!setCheckContactIdsub.add(objAttendee.sobjAttendee.Contact_Id__c)){
                    objAttendee.bChecked = false;
                    objAttendee.isError=true;
                    objAttendee.errorMessage= 'You cannot select same Contact more than once, duplicate contact is unchecked.';
                    isErrors =true;
                }


            } else {
                if(setCheckContactIdsub.add(objAttendee.sobjAttendee.Contact_Id__c) && objAttendee.sobjAttendee.Id != null) {
                    lstRemoveAttendee.add(objAttendee.sobjAttendee);
                }
            }
            }
            if(isErrors){

            return System.JSON.serialize(lstAttendeessub);
            }
            List<Contact> lstCon = [Select Name From Contact where Id IN :setCheck and Inactive__c = true];
            if(!lstCon.isEmpty()){

            for(InternalAttendeeWrappersub objAttendee: lstAttendeessub) {

                for (Contact sObjContact : lstCon) {

                    if (objAttendee.sobjAttendee.Contact_Id__c == sObjContact.Id) {
                        objAttendee.isError=true;
                        objAttendee.errorMessage= 'You cannot add an Inactive contact.';
                    }
                }
            }

            return System.JSON.serialize(lstAttendeessub);
            }
            List<Contact> lstExternalCon = [Select Name, Inactive__c From Contact where Id IN :setCheck and RecordType.DeveloperName = 'SA_Client_Contact_Record_Type'];
            if(!lstExternalCon.isEmpty()){
            for(InternalAttendeeWrappersub objAttendee: lstAttendeessub) {

                for (Contact sObjContact : lstExternalCon) {

                    if (objAttendee.sobjAttendee.Contact_Id__c == sObjContact.Id) {
                        objAttendee.isError=true;
                        objAttendee.errorMessage= 'You cannot add an external contact.';
                    }
                }
            }
            return System.JSON.serialize(lstAttendeessub);
            }


            Delete lstRemoveAttendee;
            Upsert lstUpsertAttendee;
            jsonGen.writeStartObject();
            jsonGen.writeBooleanField('isError',false);
            jsonGen.writeStringField('msg','');
            jsonGen.writeEndObject();
            return jsonGen.getAsString();
        } catch (Exception e){
            jsonGen.writeStartObject();
            jsonGen.writeBooleanField('isError',true);
            jsonGen.writeStringField('msg', e.getMessage());
            jsonGen.writeEndObject();
            return jsonGen.getAsString();
        }

    }

    public PageReference savesub(){
        errorMsginaddsubatt = '';
        List<Call_Report_Attendees__c> lstUpsertAttendee = new List<Call_Report_Attendees__c>();
        List<Call_Report_Attendees__c> lstRemoveAttendee = new List<Call_Report_Attendees__c>();
        setCheckContactIdsub = new Set<Id>();
        Set<Id> setCheck = new Set<Id>();
        
        for(InternalAttendeeWrappersub objAttendee: lstAttendeessub){
                if(objAttendee.bChecked){
                    if(objAttendee.sobjAttendee.Contact_Id__c==null){
                         errorMsginaddsubatt = '';
                         errorMsginaddsubatt = 'Attendee Name cannot be blank';
                         return null;
                    }
                    else if(setCheckcommattId.contains(objAttendee.sobjAttendee.Contact_Id__c)){
                        objAttendee.bChecked = false;
                        errorMsginaddsubatt = '';
                        errorMsginaddsubatt = Label.Submission_already_a_Committee;
                        return null;
                    }
                    else if(setCheckContactIdsub.add(objAttendee.sobjAttendee.Contact_Id__c)) {
                                setCheck.add(objAttendee.sobjAttendee.Contact_Id__c);
                                lstUpsertAttendee.add(objAttendee.sobjAttendee);
                    } 
                    else if(!setCheckContactIdsub.add(objAttendee.sobjAttendee.Contact_Id__c)){
                        objAttendee.bChecked = false;
                        errorMsginaddsubatt = '';
                        errorMsginaddsubatt = 'You cannot select same Contact more than once, duplicate contact is unchecked.';
                        return null;
                    }
                    
                   
                } else {
                    if(setCheckContactIdsub.add(objAttendee.sobjAttendee.Contact_Id__c) && objAttendee.sobjAttendee.Id != null) {
                        lstRemoveAttendee.add(objAttendee.sobjAttendee);
                    }
                }
        }
        List<Contact> lstCon = [Select Name From Contact where Id IN :setCheck and Inactive__c = true];
        if(!lstCon.isEmpty()){
            errorMsginaddsubatt = '';
            errorMsginaddsubatt = 'You cannot add an Inactive contact.';
            for(Contact sObjContact : lstCon){
                errorMsginaddsubatt +=  '<br/>'+ sObjContact.Name;
            }
        return null;
        }
        List<Contact> lstExternalCon = [Select Name, Inactive__c From Contact where Id IN :setCheck and RecordType.DeveloperName = 'SA_Client_Contact_Record_Type'];
        if(!lstExternalCon.isEmpty()){
            errorMsginaddsubatt = '';
            errorMsginaddsubatt = 'You cannot add an external contact.';
            for(Contact sObjContact : lstExternalCon){
                errorMsginaddsubatt +=  '<br/>'+ sObjContact.Name;
            }
        return null;
        }
        try{
            Delete lstRemoveAttendee;
            Upsert lstUpsertAttendee;
            showintattpanelsub = false;
            errorMsginaddsubatt = '';
            return null;
        } catch (Exception e){
            ApexPages.getMessages().clear();
            errorMsginaddsubatt = '';
            errorMsginaddsubatt = 'An error occured. '+ e.getMessage();
        }
        return null;
    }
    
   
    public class InternalAttendeeWrappersub implements Comparable {
        
      public String intOrder {get;set;}
      public Boolean bChecked  {get;set;}
      public Call_Report_Attendees__c sobjAttendee {get;set;}
      public String teamRole {get;set;}
        public Boolean isError {get;set;}
        public String errorMessage {get;set;}
      public InternalAttendeeWrappersub(Boolean bChecked, Contact sObjContact, Id idEventReport, Id idAgenda, String strReportCurrencysub, String teamRole, String intOrder){
          this.bChecked = bChecked;
          this.intOrder = intOrder;
          this.teamRole = teamRole;
          this.isError = false;
          this.errorMessage = '';
          sobjAttendee = new Call_Report_Attendees__c();
          if(sObjContact!=null)
              sobjAttendee.Contact_Id__c = sObjContact.Id;
          sobjAttendee.Status__c = 'Invited';
          sobjAttendee.CurrencyIsoCode = strReportCurrencysub;
          sobjAttendee.Call_Report__c = idEventReport;
          sobjAttendee.Related_Agenda__c = idAgenda;
          sobjAttendee.Send_Email__c = 'Yes';
          sobjAttendee.Type_of_Attendee__c = 'Submission Attendee';
      }
      
      public InternalAttendeeWrappersub(Call_Report_Attendees__c sobjAttendee){
          bChecked = true;
          intOrder = '00';
          this.sobjAttendee = sobjAttendee;
          teamRole = sobjAttendee.Client_Team_Role__c;
      }
      
      public Integer compareTo(Object obj){
          InternalAttendeeWrappersub compareToAttendee = (InternalAttendeeWrappersub)obj;
          if(this.intOrder == compareToAttendee.intOrder)
              return 0;
          else
              if(this.intOrder > compareToAttendee.intOrder)
                  return 1;
              else
                    return -1;
      }
    }
    
    public Pagereference intattclosesub(){
        showintattpanelsub = false;
        errorMsginaddsubatt = '';
        return null;
    }
    
    public Pagereference errclosesub(){
        showerrormsgsub = false;
        errorMsginaddsubatt = '';
        return null;
    }
    /***
Use
@param  	    :  none
@return   	    :  JSON as a string
@ Description 	:  get pickList values of the status
***/
    @AuraEnabled
    public static String getSubmissionAttendeesStatusOptions() {
        Schema.DescribeFieldResult f = Call_Report_Attendees__c.Status__c.getDescribe();
        return system.JSON.serialize(prepareSubmissionAttendeesStatusFromDescribeFieldResult(f));
    }
    /***
Use
@param  	    :  Schema.DescribeFieldResult f
@return   	    :  List of Mapped strings
@ Description 	:  get pickList values of the status
***/
    private Static List<Map<string,string>> prepareSubmissionAttendeesStatusFromDescribeFieldResult(Schema.DescribeFieldResult f) {

        List<Schema.PicklistEntry> p = f.getPicklistValues();
        Map<string,string> options = new Map<string,string>();
        List<Map<string,string>> optionList = new List<Map<string,string>>();
        options.put('--None--', '--None--');
        optionList.add(options);
        for (Schema.PicklistEntry e: p) {

            options = new Map<string,string>();
            options.put(String.ValueOf(e.getLabel()),String.ValueOf(e.getValue()));
            optionList.add(options);
        }
        return optionList;
    }
    /***
Use
@param  	    :  string nbacID,string agendaId,string ERID,boolean hasAccess
@return   	    :  String
@ Description 	:  create Submission Attendees
***/
    @AuraEnabled
    public Static String insertsubattendees(string nbacID,string agendaId,string ERID,boolean hasAccess) {
        JSONGenerator jsonGen = JSON.createGenerator(true);
try{
        List<Call_Report_Attendees__c> subattfinal = new List<Call_Report_Attendees__c>();
        Map<ID, String> checkdupera = new Map<ID, String>();
        Map<ID, String> checkduperainit = new Map<ID, String>();
        List<ID> consyncIds = new List<ID>();
        Map<ID, Call_Report_Attendees__c> existingagenda = new Map<ID, Call_Report_Attendees__c>();
        Map<ID, String> consyncpropermap = new Map<ID, String>();
        List<User> otmlst = new List<User>();
        String existsascomatt = '';
        String invalidconsync = '';
        List<UserRecordAccess> lstura = new List<UserRecordAccess>();
        Set<ID> manageset = new Set<ID>();
        lstura = [Select RecordId,HasReadAccess, HasEditAccess, MaxAccessLevel from UserRecordAccess WHERE UserId = :UserInfo.getUserId() AND RecordId = :nbacID];


        if (hasAccess || (lstura.size() > 0 && lstura[0].HasReadAccess == True)) {
            if (agendaId != null) {
                for (Call_Report_Attendees__c agendarec : [Select ID, Contact_id__c from Call_Report_Attendees__c where Related_Agenda__c = :agendaId]) {
                    existingagenda.put(agendarec.Contact_id__c, agendarec);
                }
            }

            if (manageset.add(agendaId) && existingagenda.size() < 1) {

                    for (Call_Report_Attendees__c cra : [Select ID, Contact_id__c, Contact_id__r.Name, Type_of_Attendee__c from Call_Report_Attendees__c where Call_Report__c = :ERID and Type_of_Attendee__c = 'Committee Attendee']) {
                        checkdupera.put(cra.Contact_id__c, cra.Contact_id__r.Name);
                        checkduperainit.put(cra.Contact_id__c, cra.Contact_id__r.Name);
                    }

                    if (nbacID != null) {
                        otmlst = [Select Id, Contact_Sync_ID__c, Name From User Where Id IN (Select UserOrGroupId From Business_Assessment__Share Where ParentId = :nbacID)];
                        for (User otm : otmlst) {
                            if (otm.Contact_Sync_ID__c != null) {
                                consyncIds.add(otm.Contact_Sync_ID__c);
                            }
                        }
                        for (Contact con : [Select ID, name from Contact where Id in :consyncIds]) {
                            consyncpropermap.put(con.ID, con.Name);
                        }
                    }

                    for (User otm : otmlst) {
                        if (otm.Contact_Sync_ID__c != null && consyncpropermap.containskey(otm.Contact_Sync_ID__c)) {
                            if (!checkduperainit.containskey(otm.Contact_Sync_ID__c)) {
                                if (!checkdupera.containskey(otm.Contact_Sync_ID__c) && (!existingagenda.containskey(otm.Contact_Sync_ID__c))) {
                                    checkdupera.put(otm.Contact_Sync_ID__c, consyncpropermap.get(otm.Contact_Sync_ID__c));
                                    Call_Report_Attendees__c crarec = new Call_Report_Attendees__c();
                                    crarec.Contact_Id__c = otm.Contact_Sync_ID__c;
                                    crarec.Status__c = 'Invited';
                                    crarec.Call_Report__c = ERID;
                                    crarec.Related_Agenda__c = agendaId;
                                    crarec.Send_Email__c = 'Yes';
                                    crarec.Type_of_Attendee__c = 'Submission Attendee';
                                    subattfinal.add(crarec);
                                }
                            } else {
                                if (!existsascomatt.contains(consyncpropermap.get(otm.Contact_Sync_ID__c))) {
                                    existsascomatt += ', ' + consyncpropermap.get(otm.Contact_Sync_ID__c);
                                }
                            }
                        } else {
                            invalidconsync += ', ' + otm.Name ;
                        }
                    }
                    if (existsascomatt != '') {

                        jsonGen.writeStartObject();
                        jsonGen.writeBooleanField('isError', true);
                        jsonGen.writeStringField('msg', Label.OppTeam_Committee + existsascomatt);
                        jsonGen.writeEndObject();
                        return jsonGen.getAsString();
                    }
                    if (invalidconsync != '') {
                        jsonGen.writeStartObject();
                        jsonGen.writeBooleanField('isError', true);
                        jsonGen.writeStringField('msg', Label.OppTeam_noBankContact + invalidconsync);
                        jsonGen.writeEndObject();
                        return jsonGen.getAsString();
                    }


            }
            else {

                jsonGen.writeStartObject();
                jsonGen.writeBooleanField('isError', true);
                jsonGen.writeStringField('msg', 'we have existing agenda ');
                jsonGen.writeEndObject();
                return jsonGen.getAsString();
            }

            if (subattfinal.size() > 0) {
                try {
                    insert subattfinal;
                    jsonGen.writeStartObject();
                    jsonGen.writeBooleanField('isError', true);
                    jsonGen.writeStringField('msg', 'success');
                    jsonGen.writeEndObject();
                    return jsonGen.getAsString();
                } catch (DmlException e) {
                    system.debug('An exception during saving Agenda data ...' + e.getdmlMessage(0));
                    //errorMsg = e.getdmlMessage(0);
                    jsonGen.writeStartObject();
                    jsonGen.writeBooleanField('isError', true);
                    jsonGen.writeStringField('msg', e.getdmlMessage(0));
                    jsonGen.writeEndObject();
                    return jsonGen.getAsString();
                }
            }
            else {
                jsonGen.writeStartObject();
                jsonGen.writeBooleanField('isError', true);
                jsonGen.writeStringField('msg', 'No Submission attendees');
                jsonGen.writeEndObject();
                return jsonGen.getAsString();
            }

            //}
        } else {

            jsonGen.writeStartObject();
            jsonGen.writeBooleanField('isError', true);
            jsonGen.writeStringField('msg', Label.Console_Manage_No_Access);
            jsonGen.writeEndObject();
            return jsonGen.getAsString();

        }
    }
        catch(Exception e){
        jsonGen.writeStartObject();
        jsonGen.writeBooleanField('isError', true);
        jsonGen.writeStringField('msg', e.getMessage());
        jsonGen.writeEndObject();
        return jsonGen.getAsString();
    }
    }
}