force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Event Report Object to store the Event Information and associate Attendees and Send Email to them.</description>
    <label>Event Report</label>
    <nameField>
        <label>Event Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>US-3400 - Field is visible to all users who have access to the related parent record within Salesforce. Information is to be limited to Agenda detail. Field is synced with the Description field on the standard Event.</description>
    <inlineHelpText>Agenda items to be discussed at the meeting. Commentary added here will be included in the notification email.</inlineHelpText>
    <label>Agenda</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/EventId__c.field-meta.xml
<CustomField>
    <fullName>EventId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Stores Event Id</description>
    <externalId>true</externalId>
    <label>EventId</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Meeting_Audience__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Audience__c</fullName>
    <description>The nature of the meeting and its participants. E.g. Internal would represent a client team meeting about this Client, not with the Client</description>
    <inlineHelpText>The nature of the meeting and its participants. E.g. Internal would represent a client team meeting about this Client, not with the Client</inlineHelpText>
    <label>Meeting Audience</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Meeting_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Purpose__c</fullName>
    <description>The specific type of meeting that was held internally or externally. E.g. An Internal meeting can be further defined as a core client team meeting or a day to day meeting</description>
    <inlineHelpText>The specific type of meeting that was held internally or externally. E.g. An Internal meeting can be further defined as a core client team meeting or a day to day meeting</inlineHelpText>
    <label>Meeting Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Meeting_Audience__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Client Discussion/Insights</fullName>
            </value>
            <value>
                <fullName>Client Execution</fullName>
            </value>
            <value>
                <fullName>Client Pitch</fullName>
            </value>
            <value>
                <fullName>Client Road Show</fullName>
            </value>
            <value>
                <fullName>Client Service</fullName>
            </value>
            <value>
                <fullName>Client Training</fullName>
            </value>
            <value>
                <fullName>Market Research Update</fullName>
            </value>
            <value>
                <fullName>Core Client Team Meeting</fullName>
            </value>
            <value>
                <fullName>Day To Day Meeting</fullName>
            </value>
            <value>
                <fullName>NBAC Meeting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Relate_to_Client__c.field-meta.xml
<CustomField>
    <fullName>Relate_to_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link related client to event report</description>
    <inlineHelpText>The Client that was ‘discussed at / included in’ the meeting. You are required to provide a Related to Client when the Meeting Audience is Internal, and there is no Related to Opportunity, Case or Campaign</inlineHelpText>
    <label>Related to Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Reports (Relate to Client)</relationshipLabel>
    <relationshipName>Event_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Visible_to_Internal_Attendees_only__c.field-meta.xml
<CustomField>
    <fullName>Visible_to_Internal_Attendees_only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-3401 - Field used to restrict the apex sharing to the owner, internal attendees and their role hierarchy managers of the event report. Any other sharing will be removed if it already exists.</description>
    <inlineHelpText>Select this if you want to restrict the access of this event report to the internal attendees only.</inlineHelpText>
    <label>Visible to Internal Attendees only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Contact_Sync_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_Sync_ID__c</fullName>
    <description>Field that holds the contact ID for the user. Case# 150 - manual update currently for Event Reporting, created by Rudolf Niehaus. Will eventually gets updated by a trigger implemented with Case# 530</description>
    <inlineHelpText>Field that holds the Contact ID for the User (18 characters or less)</inlineHelpText>
    <label>Contact Sync ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Outlook_Exchange_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Outlook_Exchange_System_ID__c</fullName>
    <description>This is the Unique System Generated ID getting it from Source System Exchange.
            This replaces SAM ACCOUNT NAME
            Case Number:Case C-00000178</description>
    <inlineHelpText>This field can only be updated from the source system which is Outlook Exchange. Please contact the Outlook Exchange team to make any updates to the field (250 characters or less)</inlineHelpText>
    <label>Outlook Exchange System ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sync_with_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sync_with_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>SHAVEEN06DEC2010 CASE599 &gt; Create a new contact for this USER, else find the BANK CONTACT based on SAM ACCOUNT name and link its BANK CONTACT&apos;s ID to this USER.</description>
    <label>Sync with Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DMN_CallReport_TEST.cls
@isTest
private class DMN_CallReport_TEST {
	
	private static ABS_ObjectBuilderBase accBld;
	private static ABS_ObjectBuilderBase conBld;
	private static ABS_ObjectBuilderBase oppBld;
	private static ABS_ObjectBuilderBase eveBld;
	private static ABS_ObjectBuilderBase callBld;
	private static User testUsr;
	public static final String TEST_USER_NAME = 'test.DMN_CallReport_TEST@test.com';

	@TestSetup
	private static void createDate(){
		System.runAs(new User(Id = UserInfo.getUserId())){
			TEST_DataFactory.generateConfiguration();
		}
		Test.startTest();
			System.runAs(new User(Id = UserInfo.getUserId())){
				new BLD_USER(TEST_USER_NAME).useCommB().syncContact().setField(User.Outlook_Exchange_System_ID__c, '11')
				.commitWork().getRecord(); 
			}
		Test.stopTest(); 
	}

	private static void fetchData(){

		for(User usr : [SELECT Contact_Sync_ID__c, UserName, Sync_with_Contact__c
						FROM User
						WHERE UserName =: TEST_USER_NAME]){
			if(usr.UserName == TEST_USER_NAME){
				testUsr = usr;
			}
		}
	}

	private static testmethod void eventCreationTest() {

		fetchData();
		System.assertNotEquals(null, testUsr.Contact_Sync_ID__c);
		System.runAs(testUsr){
			Test.startTest();
				accBld = new BLD_Account().useCommB().useGroupParent().commitWork(); 
				
				callBld = new BLD_CallReport().internal().meetingPurpose(DMN_CallReport.DAY_TO_DAY_MEETING)
									.startDate(System.now()).endDate(System.now().addHours(1))
									.assign(testUsr.Id).linkWithParent(accBld.getRecordId()).commitWork();

			Test.stopTest(); 
		} 
	}
	
	private static testmethod void removeRelatedToEvents_NoDml() {

		fetchData();
		System.runAs(testUsr){
			accBld = new BLD_Account().useCommB().useGroupParent().commitWork(); 

			eveBld = new BLD_Event()
								.internalMeeting().meetingPurpose(DMN_Event.CORE_TEAM_MEETING)
								.startDate(System.now()).stopDate(System.now().addHours(1))
								.linkToParent(accBld.getRecordId()).commitWork();
		} 

		Event eve = (Event)eveBld.refreshFromDB(new Set<String>{'WhatId', 'WhoId'}).getRecord();

		Event[] events = [	SELECT Id, WhatId, WhoId, Related_Event_Report__c
							FROM Event 
							WHERE Id =: eve.Id];

		Call_Report__c[] eveMeetings = [SELECT Id, EventId__c 
										FROM Call_Report__c
										WHERE EventId__c =: eve.Id];

		System.assertEquals(accBld.getRecordId(), eve.WhatId); 
		System.assertEquals(null, eve.WhoId);
		System.assertEquals(1, eveMeetings.size());
		System.assertEquals(1, events.size()); 
		System.assertEquals(events[0].Id, eveMeetings[0].EventId__c);
		System.assertEquals(eveMeetings[0].Id, events[0].Related_Event_Report__c); 

		System.runAs(testUsr){
			Test.startTest();
				DMN_CallReport.removeRelatedToEvents(new Event[]{eve});
			Test.stopTest();
		} 

		events = [	SELECT Id, WhatId, WhoId, Related_Event_Report__c
					FROM Event 
					WHERE Id =: eve.Id];

		eveMeetings = [	SELECT Id, EventId__c 
						FROM Call_Report__c
						WHERE EventId__c =: eve.Id];

		System.assertEquals(0, eveMeetings.size());
		System.assertEquals(0, events.size());  
	}

	private static testmethod void removeRelatedToEvents_Dml() {

		fetchData();
		System.runAs(testUsr){
			accBld = new BLD_Account().useCommB().useGroupParent().commitWork(); 

			eveBld = new BLD_Event()
								.internalMeeting().meetingPurpose(DMN_Event.CORE_TEAM_MEETING)
								.startDate(System.now()).stopDate(System.now().addHours(1))
								.linkToParent(accBld.getRecordId()).commitWork();
		}

		Event eve = (Event)eveBld.refreshFromDB(new Set<String>{'WhatId', 'WhoId'}).getRecord();

		Event[] events = [	SELECT Id, WhatId, WhoId, Related_Event_Report__c
							FROM Event 
							WHERE Id =: eve.Id];

		Call_Report__c[] eveMeetings = [SELECT Id, EventId__c 
										FROM Call_Report__c
										WHERE EventId__c =: eve.Id];

		System.assertEquals(accBld.getRecordId(), eve.WhatId); 
		System.assertEquals(null, eve.WhoId);
		System.assertEquals(1, eveMeetings.size());
		System.assertEquals(1, events.size()); 
		System.assertEquals(events[0].Id, eveMeetings[0].EventId__c);
		System.assertEquals(eveMeetings[0].Id, events[0].Related_Event_Report__c); 

		System.runAs(testUsr){
			Test.startTest();
				delete eve;
			Test.stopTest();
		} 

		events = [	SELECT Id, WhatId, WhoId, Related_Event_Report__c
					FROM Event 
					WHERE Id =: eve.Id];

		eveMeetings = [	SELECT Id, EventId__c 
						FROM Call_Report__c
						WHERE EventId__c =: eve.Id];

		System.assertEquals(0, eveMeetings.size());
		System.assertEquals(0, events.size()); 
	}
	
	private static testmethod void buildReport_Account() {

		fetchData();
		Datetime startTime = System.now();
		Datetime endTime = System.now().addHours(1);

		System.runAs(testUsr){
			accBld = new BLD_Account().useCommB().useGroupParent().commitWork(); 

			eveBld = new BLD_Event()
								.internalMeeting().meetingPurpose(DMN_Event.CORE_TEAM_MEETING)
								.startDate(startTime).stopDate(endTime)
								.linkToParent(accBld.getRecordId()).commitWork();
		}

		Event eve = (Event)eveBld.refreshFullFromDB().getRecord();
		Account acc = (Account)accBld.refreshFullFromDB().getRecord();
		Call_Report__c callRep;
		Map<Id, Sobject> id2Sobject = new Map<Id, Sobject>{acc.Id => acc};
		

		System.runAs(testUsr){
			Test.startTest();
				callRep = DMN_CallReport.buildReport(eve, id2Sobject);
			Test.stopTest();
		} 

		//System.assertEquals(eve.WhoId, 						callRep.Relate_to_Client__c);
		System.assertEquals(eve.OwnerId, 					callRep.OwnerId);
		System.assertEquals(eve.Subject + ' - '+ acc.Name, 	callRep.Name);
		System.assertEquals(eve.Meeting_Purpose__c, 		callRep.Meeting_Purpose__c);
		System.assertEquals(eve.Id, 						callRep.EventId__c);
		System.assertEquals(eve.Subject, 					callRep.Subject__c);
		System.assertEquals(eve.Meeting_Audience__c, 		callRep.Meeting_Audience__c);
		System.assertEquals(eve.Description, 				callRep.Description__c);
		System.assertEquals(eve.Visible_to_Internal_Attendees_only__c, 	callRep.Visible_to_Internal_Attendees_only__c);

		System.assertEquals(startTime, 						callRep.Start__c);
		System.assertEquals(endTime, 						callRep.End__c);
	}
}