force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Event Report Object to store the Event Information and associate Attendees and Send Email to them.</description>
    <label>Event Report</label>
    <nameField>
        <label>Event Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact this call report relates to</description>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Reports (Contact)</relationshipLabel>
    <relationshipName>R00N20000001GAr1EAG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Core_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Core_Meeting__c</fullName>
    <description>Event Management - Core Indicator (EN-0877), Modified to check for 2 Core Client Team Attendees (US-1414) - currently excluded for Commercial Banking</description>
    <formula>IF(
    OR(
       ISPICKVAL(Meeting_Purpose__c, &apos;Client Discussion/Insights&apos;),
       ISPICKVAL(Meeting_Purpose__c, &apos;Client Execution&apos;),
       ISPICKVAL(Meeting_Purpose__c, &apos;Client Pitch&apos;),
       ISPICKVAL(Meeting_Purpose__c, &apos;Client Road Show&apos;),
       ISPICKVAL(Meeting_Purpose__c, &apos;Market Research Update&apos;),
       ISPICKVAL(Meeting_Purpose__c, &apos;Core Client Team Meeting&apos;)
      )
    &amp;&amp;
    OR(
       Core_Client_Team_Attendees__c &gt; 1,
       ISPICKVAL(Relate_to_Client__r.Primary_Relationship_Holder__c, &apos;Commercial Banking&apos;)
      ),
    True,
    False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Interactions where at least 2 core client team members attended the meeting. This applies to the following internal meeting: Core Client Team Meeting &amp; the following external: Client Entertainment, Client Meeting, Client Roadshow &amp; Market Research Update</inlineHelpText>
    <label>Core Meeting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The Start Date of the event derived from the Start Date field. Shows only Date information. Please see C-00000886 for more details.</description>
    <formula>DATEVALUE( Start__c )</formula>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>US-3400 - Field is visible to all users who have access to the related parent record within Salesforce. Information is to be limited to Agenda detail. Field is synced with the Description field on the standard Event.</description>
    <inlineHelpText>Agenda items to be discussed at the meeting. Commentary added here will be included in the notification email.</inlineHelpText>
    <label>Agenda</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Meeting_Audience__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Audience__c</fullName>
    <description>The nature of the meeting and its participants. E.g. Internal would represent a client team meeting about this Client, not with the Client</description>
    <inlineHelpText>The nature of the meeting and its participants. E.g. Internal would represent a client team meeting about this Client, not with the Client</inlineHelpText>
    <label>Meeting Audience</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Outcomes__c.field-meta.xml
<CustomField>
    <fullName>Outcomes__c</fullName>
    <label>Outcomes</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Relate_to_Client__c.field-meta.xml
<CustomField>
    <fullName>Relate_to_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link related client to event report</description>
    <inlineHelpText>The Client that was ‘discussed at / included in’ the meeting. You are required to provide a Related to Client when the Meeting Audience is Internal, and there is no Related to Opportunity, Case or Campaign</inlineHelpText>
    <label>Related to Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Reports (Relate to Client)</relationshipLabel>
    <relationshipName>Event_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Relate_to_Opp__c.field-meta.xml
<CustomField>
    <fullName>Relate_to_Opp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link opportunity to event report</description>
    <inlineHelpText>The Opportunity to which the meeting is applicable.</inlineHelpText>
    <label>Related to Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Event Reports</relationshipLabel>
    <relationshipName>Event_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Report_Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Report_Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact / Lead Lookup for the Report</description>
    <inlineHelpText>Contact at the Client with whom the meeting ‘will be / was’ held. You are required to provide the main Client Contact when the Meeting Audience is External, and there is no Related to Opportunity, Case or Campaign</inlineHelpText>
    <label>Client Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3 AND 4)</booleanFilter>
        <errorMessage>Please enter an active Client Contact for External Meetings only. Bank Contacts (Employees) or inactive contacts cannot be captured.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Contact Record Type</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Inactive Client Contact Record Type</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Reports (Client Contact)</relationshipLabel>
    <relationshipName>Event_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Birth_Day_Month__c.field-meta.xml
<CustomField>
    <fullName>Birth_Day_Month__c</fullName>
    <description>Please enter the day and the month of the contact&apos;s birthday. Format dd/mm</description>
    <inlineHelpText>Please enter the day and the month of the Contact&apos;s birthday. Format dd/mm (5 characters or less)</inlineHelpText>
    <label>Birth Day/Month</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Country__c.field-meta.xml
<CustomField>
    <fullName>Phone_Country__c</fullName>
    <inlineHelpText>Indication of the phone country</inlineHelpText>
    <label>Phone Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas, The</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Burma</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_Status__c/KYC_Status__c.object-meta.xml
<CustomObject>
    <description>KYC Status Object Updated in 2015 (EN-0670) as part of the Data Project and KYC Workstream Updates</description>
    <label>KYC Status</label>
    <nameField>
        <displayFormat>KYC-{000000}</displayFormat>
        <label>KYC Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYC Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KYC_Status__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KYC Statuses</relationshipLabel>
    <relationshipName>KYC_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Birth_Day_Month__c.field-meta.xml
<CustomField>
    <fullName>Birth_Day_Month__c</fullName>
    <description>Stores the Users birthday in the format dd/mm

            (CRM Birthday Reminder Case# 207 C Reinecke 2010/09)</description>
    <inlineHelpText>Please enter the day and the month of the User&apos;s birthday. Format dd/mm (5 characters or less)</inlineHelpText>
    <label>Birth Day/Month</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CI_ClientInfoController.cls
/*************************************************************************\
    @ Author        : Dane Williams (Deloitte)
    @ Date          : July-2017
    @ Test File     : CI_ClientInfoControllerTest
    @ Description   : This class contains all methods used by the "Client Info" section of the Client Insights app
    @ Last Modified By  :   Dane Williams
    @ Last Modified On  :   05-Oct-2017
    @ Last Modified Reason  :   Added getKYC
****************************************************************************/

public without sharing class CI_ClientInfoController {

    @AuraEnabled
    public static CI_ResponseDto getEngagements(String clientId, String audienceType) {
        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardListObjectModel clom = new CI_CardListObjectModel();
        
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Call_Report__c.fields.getMap(), new String[] {'Meeting_Audience__c', 'End__c', 'Contact__c', 'Core_Meeting__c', 'Date__c', 'Subject__c', 'Description__c'})){ 
            return new CI_ResponseDto(false, 'You do not have the required permissions to view this data');
        }
        
        clom.cardObjectList = [SELECT Meeting_Audience__c, End__c, Report_Client_Contact__r.Name, Core_Meeting__c, Date__c, Subject__c, Description__c, Outcomes__c 
                        FROM Call_Report__c
                        WHERE (Relate_to_Client__r.Id =: clientId 
                        OR Relate_to_Opp__r.Account.Id =: clientId)
                        AND Meeting_Audience__c =: audienceType];

        return new CI_ResponseDto(clom);
    }     

    @AuraEnabled
    public static CI_ResponseDto getClientContacts(String clientId) {
        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardListObjectModel clom = new CI_CardListObjectModel();
        
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Contact.fields.getMap(), new String[] {'Name', 'Title', 'Email', 'Phone', 'Birthdate', 'AssistantName', 'AssistantPhone','Assistant_Email__c', 'MailingAddress', 'Phone_Country__c'})){ 
            return new CI_ResponseDto(false, 'You do not have the required permissions to view this data');
        }
        
        clom.cardObjectList = [SELECT Name, Title, Email, Phone, Birth_Day_Month__c, AssistantName, AssistantPhone, Assistant_Email__c, MailingAddress, Phone_Country__c  
                        FROM Contact 
                        WHERE AccountId =: clientId];

        return new CI_ResponseDto(clom);
    }  

    @AuraEnabled
    public static CI_ResponseDto getClientServiceTeam(String clientId) {
        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardListObjectModel clom = new CI_CardListObjectModel();
        
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Custom_Client_Team__c.fields.getMap(), new String[] {'Client_Role__c', 'User_Country__c', 'Team_Member__c'})){ 
            return new CI_ResponseDto(false, 'You do not have the required permissions to view this data');
        }
        
        clom.cardObjectList = [SELECT Team_Member__r.Name, Client_Role__c, User_Country__c,Team_Member__r.Email , Team_Member__r.Phone  
                        FROM Custom_Client_Team__c 
                        WHERE Account__c =: clientId];

        return new CI_ResponseDto(clom);
    }  

    @AuraEnabled
    public static CI_ResponseDto getKYCAtRisk(String clientId) {
        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_SharedUtilities.ClientHierarchyTools clientHierarchyTools = new CI_SharedUtilities.ClientHierarchyTools();
        CI_CardListObjectModel clom = new CI_CardListObjectModel();

        if(!sharedUtils.canAccessFields(Schema.SObjectType.Custom_Client_Team__c.fields.getMap(), new String[] {'Account__c', 'Team_Member__c'})){ 
            return new CI_ResponseDto(false, 'You do not have the required permissions to view this Custom_Client_Team__c data');
        }

        //Get client IDs in user's CST
        Id userID = UserInfo.getUserId();
        List<Account> cstClientList = [SELECT Id
                            FROM Account
                            WHERE Id IN 
                            (SELECT Account__c 
                            FROM Custom_Client_Team__c 
                            WHERE Team_Member__c =: userID)];
        Set<Id> cstClientIds = (new Map<Id,Account>(cstClientList)).keySet();

        //System.debug ('getKYCAtRisk UserInfo.getName(): ' + UserInfo.getName());
        //System.debug ('getKYCAtRisk clientId: ' + clientId);
        //System.debug ('getKYCAtRisk cstClientIds: ' + cstClientIds);

        //Get client IDs in the client's hierarchy
        Set<String> hierClientIds = new Set<String>(clientHierarchyTools.getClientIdsInHierarchy(CI_ClientSearchController.getClientHierarchy(clientId)));

        //System.debug ('getKYCAtRisk hierClientIds: ' + hierClientIds);

        List<String> allowedClientIds = new List<String>();
        //Loop through client IDs in the hierarchy and add the ones found in the cstClientIds
        for(String hierClientId : hierClientIds)
        {
            if(cstClientIds.contains(hierClientId))
            {
                allowedClientIds.add(hierClientId);
            }
        }

        //System.debug ('getKYCAtRisk allowedClientIds: ' + allowedClientIds);

        if(!sharedUtils.canAccessFields(Schema.SObjectType.KYC_Status__c.fields.getMap(), new String[] {'Client__c', 'Provisional_Suspension_Date__c'})){ 
            return new CI_ResponseDto(false, 'You do not have the required permissions to view this KYC_Status__c data');
        }

        //Get KYC status with the minimum Provisional_Suspension_Date__c for each client
        List<AggregateResult> clientKYCStatuses = [SELECT 
                                                Client__c, 
                                                Client__r.Name,
                                                MIN(Provisional_Suspension_Date__c) Provisional_Suspension_Date__c
                                                FROM KYC_Status__c
                                                WHERE Client__c IN: allowedClientIds
                                                AND KYC_Status__c = 'Not Complete'
                                                GROUP BY Client__c, Client__r.Name];

        //System.debug ('getKYCAtRisk clientKYCStatuses: ' + clientKYCStatuses);
        //System.debug ('getKYCAtRisk clientRevenueTotals: ' + clientRevenueTotals);

        //Loop through clientKYCStatuses and clientRevenueTotals and build the CI_CardMapModel where client's match
        for(AggregateResult kycStatus : clientKYCStatuses)
        {
            Map<String, String> kycAtRiskMap = new Map<String, String>();
            Boolean clientRevenueFound = false;       
            if(!clientRevenueFound)
            {
                kycAtRiskMap.put('clientName', String.valueOf(kycStatus.get('Name')));
                kycAtRiskMap.put('revenue', '0');
                kycAtRiskMap.put('suspensionDate', String.valueOf(kycStatus.get('Provisional_Suspension_Date__c')));
            }

            clom.cardObjectList.add(kycAtRiskMap);
        }

        //System.debug ('getKYCAtRisk clom: ' + clom);
        
        return new CI_ResponseDto(clom);
    }   
}