force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Event Report Object to store the Event Information and associate Attendees and Send Email to them.</description>
    <label>Event Report</label>
    <nameField>
        <label>Event Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Enforce_Core_Attendee_Validation__c.field-meta.xml
<CustomField>
    <fullName>Enforce_Core_Attendee_Validation__c</fullName>
    <description>The field decides whether the validation of at least 2 core attendees on an internal core meeting is applied or not (US-1414).</description>
    <formula>ISPICKVAL(Meeting_Audience__c, &apos;Internal&apos;)
&amp;&amp; ISPICKVAL(Meeting_Purpose__c, &apos;Core Client Team Meeting&apos;)
&amp;&amp; (ISBLANK(Relate_to_Client__c) || !ISPICKVAL(Relate_to_Client__r.Primary_Relationship_Holder__c, &apos;Commercial Banking&apos;))</formula>
    <inlineHelpText>Enforce the 2-core-attendees based on &apos;Meeting Audience&apos;, &apos;Meeting Type&apos;, and the client&apos;s &apos;Primary Relationship Holder&apos;.</inlineHelpText>
    <label>Enforce Core Attendee Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RedirectToAddAttendeesExtension.cls
/*************************************************************************
    @ Author        :     Petr Svestka
    @ Date          :     June 20, 2016
    @ Test File     :     RedirectToAddAttendeesExtensionTest.cls
    @ Description   :     US-1355 - Ensuring at least 2 Core Team Members exist on Internal Core Meetings

	@ Last Modified By  : Petr Svestka
    @ Last Modified On  : July 7, 2016
    @ Last Modified Reason  : US-1414 - changing the condition when the check on 2 core team members happens
****************************************************************************/
public with sharing class RedirectToAddAttendeesExtension {
    
    private final Call_Report__c er;
    private final ApexPages.StandardController stdCont;
    
    public RedirectToAddAttendeesExtension(ApexPages.StandardController stdCont) {
        this.stdCont = stdCont;
        
        if (ApexPages.CurrentPage().getParameters().containsKey('newId')) {
            List<Call_Report__c> ers = [SELECT id, enforce_core_attendee_validation__c FROM Call_Report__c WHERE id = :ApexPages.CurrentPage().getParameters().get('newId')];
            if (ers.size() != 0) {
                this.er = ers.get(0);
            }
        }
    }
    
    public PageReference redirect() {
        PageReference pageRef;
        
        // combines new logic from  US-1355 and existing logic from Call_Report__c.Add_Update_Internal_Attendees Custom Button
        if (er != null && er.enforce_core_attendee_validation__c == true && ButtonAccess.checkInternalAttendeeButton(UserInfo.getUserId(), er.id)) {
            pageRef = Page.AddInternalAttendee;
            pageRef.getParameters().put('reportid', er.id);
            pageRef.setRedirect(true);
        } else if (er != null) {
            pageRef = new ApexPages.StandardController(er).view();
            pageRef.setRedirect(true);
        }
        
        return pageRef;
    }
}