force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Event Report Object to store the Event Information and associate Attendees and Send Email to them.</description>
    <label>Event Report</label>
    <nameField>
        <label>Event Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Relate_to_Client__c.field-meta.xml
<CustomField>
    <fullName>Relate_to_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link related client to event report</description>
    <inlineHelpText>The Client that was ‘discussed at / included in’ the meeting. You are required to provide a Related to Client when the Meeting Audience is Internal, and there is no Related to Opportunity, Case or Campaign</inlineHelpText>
    <label>Related to Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Reports (Relate to Client)</relationshipLabel>
    <relationshipName>Event_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Report_Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Report_Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact / Lead Lookup for the Report</description>
    <inlineHelpText>Contact at the Client with whom the meeting ‘will be / was’ held. You are required to provide the main Client Contact when the Meeting Audience is External, and there is no Related to Opportunity, Case or Campaign</inlineHelpText>
    <label>Client Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3 AND 4)</booleanFilter>
        <errorMessage>Please enter an active Client Contact for External Meetings only. Bank Contacts (Employees) or inactive contacts cannot be captured.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Contact Record Type</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Inactive Client Contact Record Type</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Reports (Client Contact)</relationshipLabel>
    <relationshipName>Event_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/Call_Report_Attendees__c.object-meta.xml
<CustomObject>
    <description>Case 4296 Changed Name field from text to autonumber</description>
    <label>Event Report Attendees</label>
    <nameField>
        <displayFormat>ERA-{0000000000}</displayFormat>
        <label>Event Report Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Report Attendeess</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Call_Report__c.field-meta.xml
<CustomField>
    <fullName>Call_Report__c</fullName>
    <label>Event Report</label>
    <referenceTo>Call_Report__c</referenceTo>
    <relationshipLabel>Event Report Attendees</relationshipLabel>
    <relationshipName>Call_Report_Attendeess</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Contact_id__c.field-meta.xml
<CustomField>
    <fullName>Contact_id__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <description>Case 4296 Changed label</description>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Contact must be active.</errorMessage>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Reports Associated</relationshipLabel>
    <relationshipName>Call_Report_Attendeess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
                <default>true</default>
                <label>Invited</label>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Distribute Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the status of the contact at the client. This status is used to improve contact searches .Inactive Contacts are excluded from lookup searches</description>
    <inlineHelpText>Indicates the status of the contact at the client. This status is used to improve contact searches.</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AddExternalAttendeesController.cls
/*************************************************************************\
    @ Author        :     Prabhanshu Agrawal
    @ Date          :     Apr 2015
    @ Test File     :     AddExternalAttendeesController_Test
    @ Description   :     Controller to add and update external attendees

    @ Last Modified By  	: 
    @ Last Modified On  	: 
    @ Last Modified Reason  : 
****************************************************************************/ 
public class AddExternalAttendeesController {
    
    public Id idEventReport {get;set;}
    public List<externalAttendeeWrapper> lstAttendees {get;set;}
    public Call_Report__c sobjEventReport {get;set;}
    private Set<Id> setCheckContactId;
    
    
    public AddExternalAttendeesController(){
        
		idEventReport = ApexPages.currentPage().getParameters().get('reportid');
        sobjEventReport = [Select Id, OwnerId, Name, Report_Client_Contact__c, Report_Client_Contact__r.AccountId, 
        							Relate_to_Client__c from Call_Report__c where Id =: idEventReport];
        lstAttendees = new List<externalAttendeeWrapper>();
        getEventReportAttendee();
        getClientContacts();
        addRow();
    }
    // method to get already existing event report attendees
    public void getEventReportAttendee(){
        
        setCheckContactId = new Set<Id>();
        
        for(Call_Report_Attendees__c sObjReportAttendees : [Select Id, Contact_Id__c, Contact_Id__r.Id, Contact_Id__r.Name, Contact_Id__r.Title, 
        															Contact_Id__r.RecordType.DeveloperName, Status__c
        															FROM Call_Report_Attendees__c 
        															where Call_Report__c =: idEventReport 
        															and Contact_Id__r.RecordType.DeveloperName='SA_Client_Contact_Record_Type']){
            
            externalAttendeeWrapper objAttendees = new externalAttendeeWrapper(sObjReportAttendees);
            if(sobjEventReport.Report_Client_Contact__c == sObjReportAttendees.Contact_Id__c)
                objAttendees.bReportOwner = true;
            lstAttendees.add(objAttendees);
            setCheckContactId.add(sObjReportAttendees.Contact_Id__c);
        }
    }
    // method to get the list of Client Contact
    public void getClientContacts(){
        
		for(Contact sObjContact: [Select Id, Name, Inactive__c, Title From Contact 
									where AccountId =: sobjEventReport.Relate_to_Client__c 
									and RecordType.DeveloperName='SA_Client_Contact_Record_Type'
									and Inactive__c != true
									and Id Not IN : setCheckContactId
									order by SystemModstamp Desc limit 100]){
        	lstAttendees.add(new externalAttendeeWrapper(false, sObjContact, idEventReport, sObjContact.Title));
        }
    }
        
    public void addRow(){
        for(Integer i=0;i<4;i++){
            lstAttendees.add(new externalAttendeeWrapper(false, null, idEventReport, ''));
        }
    }
    
    public PageReference save(){
        List<Call_Report_Attendees__c> lstUpsertAttendee = new List<Call_Report_Attendees__c>();
        List<Call_Report_Attendees__c> lstRemoveAttendee = new List<Call_Report_Attendees__c>();
        setCheckContactId = new Set<Id>();
        Set<Id> setCheck = new Set<Id>();
        
        for(externalAttendeeWrapper objAttendee: lstAttendees){
                if(objAttendee.bChecked){
                    if(objAttendee.sobjAttendee.Contact_Id__c == null){
                        objAttendee.sobjAttendee.Contact_Id__c.addError('Please enter a value');
                    }
                    else if(setCheckContactId.add(objAttendee.sobjAttendee.Contact_Id__c)) {
                    	setCheck.add(objAttendee.sobjAttendee.Contact_Id__c);
                        lstUpsertAttendee.add(objAttendee.sobjAttendee);
                    } else {
                        objAttendee.bChecked = false;
                        ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.Error, 'You cannot select same Contact more than once, duplicate contact is unchecked.'));
    					return null;
                    }
                } else {
                    if(setCheckContactId.add(objAttendee.sobjAttendee.Contact_Id__c) && objAttendee.sobjAttendee.Id != null) {
                        lstRemoveAttendee.add(objAttendee.sobjAttendee);
                    }
                }
        }
        List<Contact> lstCon = [Select Name From Contact where Id IN : setCheck and Inactive__c = true];
        if(!lstCon.isEmpty()){
            ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.Error, 'You cannot add an Inactive contact.'));
            for(Contact sObjContact : lstCon){
                ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.Error, sObjContact.Name));
            }
    		return null;
        }
        List<Contact> lstInternalCon = [Select Name, Inactive__c From Contact where Id IN :setCheck and RecordType.DeveloperName = 'SA_Bank_Contact_Record_Type'];
        if(!lstInternalCon.isEmpty()){
            ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.Error, 'You cannot add an internal contact.'));
            for(Contact sObjContact : lstInternalCon){
                ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.Error, sObjContact.Name));
            }
    		return null;
        }
        try{
            Delete lstRemoveAttendee;
            Upsert lstUpsertAttendee;
            return new PageReference('/'+idEventReport);
        } catch (Exception e){
            ApexPages.getMessages().clear();
            ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.Error, 'An error occured. '+ e.getMessage()));
        }
        return null;
    }
    
    public PageReference cancel(){
        return new PageReference('/'+idEventReport);
    }
    
    public class externalAttendeeWrapper{
        
        public Boolean bChecked	{get;set;}
        public Call_Report_Attendees__c sobjAttendee {get;set;}
    	public Boolean bReportOwner {get;set;}
    	public String Title {get;set;}
    	
    	public externalAttendeeWrapper(Boolean bChecked, Contact sObjContact, Id idEventReport, String Title){
	    	
            this.bChecked = bChecked;
    	    this.sobjAttendee = new Call_Report_Attendees__c();
    	    this.Title = Title;
    	    if(sObjContact!=null)
    	        this.sobjAttendee.Contact_Id__c = sObjContact.Id;
	        this.sobjAttendee.Status__c = 'Invited';
    	    this.sobjAttendee.Call_Report__c = idEventReport;
    	}
    	
    	public externalAttendeeWrapper(Call_Report_Attendees__c sobjAttendee){
    	    bChecked = true;
    	    this.sobjAttendee = sobjAttendee;
    	    this.Title = sobjAttendee.Contact_id__r.Title;
    	}
    }
}