force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Event Report Object to store the Event Information and associate Attendees and Send Email to them.</description>
    <label>Event Report</label>
    <nameField>
        <label>Event Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The Start Date of the event derived from the Start Date field. Shows only Date information. Please see C-00000886 for more details.</description>
    <formula>DATEVALUE( Start__c )</formula>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/EventId__c.field-meta.xml
<CustomField>
    <fullName>EventId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Stores Event Id</description>
    <externalId>true</externalId>
    <label>EventId</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Meeting_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Purpose__c</fullName>
    <description>The specific type of meeting that was held internally or externally. E.g. An Internal meeting can be further defined as a core client team meeting or a day to day meeting</description>
    <inlineHelpText>The specific type of meeting that was held internally or externally. E.g. An Internal meeting can be further defined as a core client team meeting or a day to day meeting</inlineHelpText>
    <label>Meeting Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Meeting_Audience__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Client Discussion/Insights</fullName>
            </value>
            <value>
                <fullName>Client Execution</fullName>
            </value>
            <value>
                <fullName>Client Pitch</fullName>
            </value>
            <value>
                <fullName>Client Road Show</fullName>
            </value>
            <value>
                <fullName>Client Service</fullName>
            </value>
            <value>
                <fullName>Client Training</fullName>
            </value>
            <value>
                <fullName>Market Research Update</fullName>
            </value>
            <value>
                <fullName>Core Client Team Meeting</fullName>
            </value>
            <value>
                <fullName>Day To Day Meeting</fullName>
            </value>
            <value>
                <fullName>NBAC Meeting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/recordTypes/Meeting.recordType-meta.xml
<RecordType>
    <fullName>Meeting</fullName>
    <active>true</active>
    <description>Select to create a meeting where a client is attending (External) or a client is being discussed (Internal)</description>
    <label>Meeting</label>
</RecordType>

force-app/main/default/classes/EventReport_Navigate.cls
/***************************************
Created By: Abhishek V
Created on: 06/07/2016
Description: US - 1379: Class to redirect Event report based on Record type

Last Modified By: Manoj Gupta
Description: DEF-002349,Prepopulation of Event Report fields not populating when creating from Event Report tab
Last Modified Date: 19 Jan 2017

Last Modified By : Upender Nath Sharma
Description : US-1823
Last Modified Date : 09 Feb 2017

Last Modified By : Upender Nath Sharma
Description : US-1864
Last Modified Date : 20 Feb 2017

Last Modified By : Maciej Jaźnicki
Description : US-3650
Last Modified Date : 05 Apr 2019

********************************************/

public without sharing class EventReport_Navigate{

    public String reportId = '';
    public String eventId = '';
    public String newURLedit{get;set;}
    public ID newURLRTID{get; set;}
    public boolean isNBAC{get; set;}
    public boolean isMeeting{get;set;}
    public String newURLnew{get;set;}
    private final Boolean isLightning;
    public boolean lightningEnv{get;set;}
    public String selectedRT {get;set;}
    
    public List<RecordType> rtlstdetails{
        get{
            List<RecordType> rtlst = new List<RecordType>();
            List<String> namesRt = new List<String>();
            List<RecordTypeInfo> rtlsttemp = Schema.Call_Report__c.SObjectType.getDescribe().getRecordTypeInfos();
            for(RecordTypeInfo rti : rtlsttemp){
                if(rti.isAvailable()){
                    namesRt.add(rti.getName());
                }
            }
            rtlst = [Select ID, Name, Description from RecordType where SobjectType = 'Call_Report__c' and Name IN :namesRt];
            return rtlst ;
        } set;
    }
    
    public Boolean getIsLightning() {
        return this.isLightning;
    }

    public Boolean getIsClassic() {
        return !this.isLightning;
    }
    
    public List<SelectOption> getrecordtypevalues() {
        List<SelectOption> options = new List<SelectOption>();
        for(RecordType rt: rtlstdetails){
            options.add(new SelectOption(rt.Name,rt.Name));
        }
        return options;
    }

    
    private Boolean isPageOriginLightning(Map<String, Object> params) {
        if (params.get('sfdcIFrameHost') != null ||
            params.get('sfdcIFrameOrigin') != null ||
            params.get('isdtp') == 'p1') {      
                return true;
            } else {      
                return false;
            }
    }
    
    public EventReport_Navigate(ApexPages.StandardController stdController){
        this.isLightning = isPageOriginLightning(ApexPages.currentPage().getParameters());
        if(rtlstdetails.size() == 1) {
            selectedRT = rtlstdetails[0].Name;
            continuemethod();
        }
    }
    
    public void continuemethod(){
        if(isLightning){
            lightningEnv = true;
        }
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Call_Report__c;
        Map<String, Schema.RecordTypeInfo> EventRecordTypeInfo = cfrSchema.getRecordTypeInfosByName();
        Id nbacMeetingRtId = EventRecordTypeInfo.get('NBAC Meeting').getRecordTypeId();
        Id emrtId = EventRecordTypeInfo.get('Meeting').getRecordTypeId();
        if(selectedRT == 'Meeting') {
            ApexPages.currentPage().getParameters().put('RecordType',emrtId);
        }else {
            ApexPages.currentPage().getParameters().put('RecordType', nbacMeetingRtId);
        }
        navigateNew();
    }
    
    public void navigateNew(){

            Boolean boolentered = false;
            Map<String,String> paramMap = ApexPages.currentPage().getParameters();
            Schema.DescribeSObjectResult d = Schema.SObjectType.Call_Report__c;
            String keyPrefix = d.getKeyPrefix();
            String newURL =  '/';
            
            Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Call_Report__c;
            Map<String, Schema.RecordTypeInfo> EventRecordTypeInfo = cfrSchema.getRecordTypeInfosByName();
            Id nbacrtId = EventRecordTypeInfo.get('NBAC Meeting').getRecordTypeId();
            Id emrtId = EventRecordTypeInfo.get('Meeting').getRecordTypeId();
        String loggedInUserName = userInfo.getName() ;
            DateTime startDateTime = system.now();
            DateTime endDateTime = startDateTime.addHours(1);
            String startDateStr = startDateTime.format() ;
            String endDateStr = endDateTime.format();
            
            if(paramMap.containsKey('RecordType')){
                if((ApexPages.currentPage().getParameters().get('RecordType') == nbacrtId)){
                    newURL = newURL + 'apex/MeetingConsole';
                    newURLRTID = nbacrtId;
                    isNBAC = True;
                    isMeeting = false;
                }else{
                    newURL +=  keyPrefix +'/e?';
                    newURLRTID = emrtId;
                    isNBAC = false;
                    isMeeting = True;
                    for(String pars: paramMap.keyset()){
                        if(pars != 'save_new' && pars != 'sfdc.override'){
                            newURL += pars + '=' +  paramMap.get(pars);
                            newURL += '&';
                        }
                    }
                    
                    if(!newURL.contains('RecordType')){
                        boolentered = true;
                        newURL = newURL  + 'RecordType=' + emrtId;
                    }
                    
                    if(boolentered == True){
                        newURL += '&nooverride=1';
                    }else{
                        newURL += '&CF00N200000024QsA='+ loggedInUserName + '&00N200000024RDK=' + startDateStr  + '&00N200000024RD7=' + endDateStr  + '&Name=' + label.EventReportDefaultName +'&nooverride=1';
                        newURL = newURL + '&saveURL=/apex/RedirectToAddAttendees';
                    }
                }
            }else{
                newURLRTID = null;
            }
            newURLnew = newURL;

    }
        
    public void navigateEdit(){
        
            ID EventReportID = ApexPages.currentPage().getParameters().get('id');
            Map<String,String> paramMapedit = ApexPages.currentPage().getParameters();
            newURLedit =  '/';
            String ERRecTypeName = getEventReportRT(EventReportID);
            
            
            if(ERRecTypeName == 'NBAC Meeting'){
                newURLedit = newURLedit + 'apex/MeetingConsole?id='+EventReportID;
                isMeeting = false;
            }else{
                newURLedit +=  EventReportID +'/e?';
                
                for(String pars: paramMapedit.keyset()){
                    if(pars != 'save_new' && pars != 'sfdc.override' && pars != 'id'){
                        newURLedit += pars + '=' +  paramMapedit.get(pars);
                        newURLedit += '&';
                    }
                }
                
               newURLedit += 'nooverride=1';
               isMeeting = true;
               
            }
    }
    
    public String navigateViewURL{
        get{


            Map<String,String> paramMap = ApexPages.currentPage().getParameters();

            String newURL = buildURL();

            if (!(newUrl.length() < 15)) {
                if(paramMap.containsKey('retURL')){
                    if(!newURL.containsAny('?')){
                        newURL = newURL + '?retURL=' + EncodingUtil.urlEncode(ApexPages.currentPage().getParameters().get('retURL'),'UTF-8');
                    }else{
                        newURL = newURL + '&retURL=' + EncodingUtil.urlEncode(ApexPages.currentPage().getParameters().get('retURL'),'UTF-8');
                    }
                }
                
            }
            
            return newURL; 
        }
        set; 
    }
    
    public String buildURL(){
        
        String URL = '/';
        reportId = ApexPages.currentPage().getParameters().get('id');
        Call_Report__c cr = [SELECT Meeting_Purpose__c, Date__c FROM Call_Report__c WHERE Id = :reportId];


        String RECtypeName = getEventReportRT(reportId);

        if(RECtypeName != '' && RECtypeName == 'NBAC Meeting'){
            URL = URL + 'apex/MeetingConsole?id='+reportId;
        } else {
            URL = URL + reportId+'?nooverride=1';
        }
        return URL;
        
    }
    
    public String getEventReportRT(String eventID){
        
        String rectypename = '';

        List<Call_Report__c> eventReportList = new List<Call_Report__c>([select id,Eventid__c, RecordType.Name from Call_Report__c where ID =:eventID]);
        
        if(eventReportList.size() > 0){
            rectypename = eventReportList[0].RecordType.Name;

        }
        if(rectypename != null && rectypename != ''){
            return rectypename;
        }else{
            return '';
        }
    } 

}