force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Event Report Object to store the Event Information and associate Attendees and Send Email to them.</description>
    <label>Event Report</label>
    <nameField>
        <label>Event Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Attendee_Reminder_Required__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Reminder_Required__c</fullName>
    <description>NO_NEED - no need for reminder
            NEED_REMINDER - reminder task will be created
            HAS_REMINDER_NEED - reminder task exists and active
            HAS_REMINDER_NO_NEED - reminder task exists and compleated
            NOT_REQUIRED - event created before US-3323 go live</description>
    <label>Attendee Reminder Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NO_NEED</fullName>
                <default>true</default>
                <label>NO_NEED</label>
            </value>
            <value>
                <fullName>NEED_REMINDER</fullName>
            </value>
            <value>
                <fullName>HAS_REMINDER_NEED</fullName>
            </value>
            <value>
                <fullName>HAS_REMINDER_NO_NEED</fullName>
            </value>
            <value>
                <fullName>NOT_REQUIRED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The Start Date of the event derived from the Start Date field. Shows only Date information. Please see C-00000886 for more details.</description>
    <formula>DATEVALUE( Start__c )</formula>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Meeting_Format__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Format__c</fullName>
    <description>This field describes the format in which the meeting was conducted (SGPRT-1258)</description>
    <inlineHelpText>This field describes the format in which the meeting was conducted.</inlineHelpText>
    <label>Meeting Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conference Call</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Total_Event_Costs__c.field-meta.xml
<CustomField>
    <fullName>Total_Event_Costs__c</fullName>
    <inlineHelpText>Value represents the Total Event Cost that is split between all the attendees who attended this meeting.</inlineHelpText>
    <label>Total Event Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/Call_Report_Attendees__c.object-meta.xml
<CustomObject>
    <description>Case 4296 Changed Name field from text to autonumber</description>
    <label>Event Report Attendees</label>
    <nameField>
        <displayFormat>ERA-{0000000000}</displayFormat>
        <label>Event Report Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Report Attendeess</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Call_Report__c.field-meta.xml
<CustomField>
    <fullName>Call_Report__c</fullName>
    <label>Event Report</label>
    <referenceTo>Call_Report__c</referenceTo>
    <relationshipLabel>Event Report Attendees</relationshipLabel>
    <relationshipName>Call_Report_Attendeess</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Costs_Per_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Costs_Per_Attendee__c</fullName>
    <formula>IF(ISPICKVAL(Status__c, &apos;Attended&apos;) , Call_Report__r.Total_Event_Costs__c/ Call_Report__r.Number_Of_Attended_Attendees__c   , null )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost Per Attendee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
                <default>true</default>
                <label>Invited</label>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Distribute Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BCH_AttendeeReminder.cls
public with sharing class BCH_AttendeeReminder implements Database.Batchable<SObject>, Schedulable{
    private static String HAS_REMINDER_NEED		= 'HAS_REMINDER_NEED';
    private static String HAS_REMINDER_NO_NEED	= 'HAS_REMINDER_NO_NEED';
    private static String NO_NEED			    = 'NO_NEED';
    private static String NEED_REMINDER		    = 'NEED_REMINDER';


    public void execute(Database.BatchableContext param1, List<Call_Report_Attendees__c> attendees) {
        Set<Id> reportIds = new Set<Id>();
        for(Call_Report_Attendees__c cra: attendees) {
            reportIds.add(cra.Call_Report__c);
        }
        List<Call_Report__c> events = [SELECT Attendee_Reminder_Required__c, OwnerId FROM Call_Report__c WHERE Id IN: reportIds AND Total_Event_Costs__c = NULL];
        for(Call_Report__c cr: events){
            WRP_User wrpUser = new WRP_User(UTL_User.getCachedUser(cr.OwnerId));
            if(!wrpUser.isCommB()){
                cr.Attendee_Reminder_Required__c = changeReminderStatus(cr);
            }
        }
        update events;
    }

    public void finish(Database.BatchableContext param1) {
    }

    public Iterable<SObject> start(Database.BatchableContext param1) {
        return Database.query('SELECT Id, Costs_Per_Attendee__c, Call_Report__c FROM Call_Report_Attendees__c ' +
                'WHERE Call_Report__r.Date__c < TODAY AND  Call_Report__r.Meeting_Format__c = \'Entertainment\' AND Call_Report__r.Total_Event_Costs__c = NULL AND Status__c = \'Attended\' ' +
                'AND (Call_Report__r.Attendee_Reminder_Required__c = \'NO_NEED\' OR Call_Report__r.Attendee_Reminder_Required__c = null OR Call_Report__r.Attendee_Reminder_Required__c = \'HAS_REMINDER_NO_NEED\')');
    }

    public void execute(SchedulableContext param1) {
        BCH_AttendeeReminder batchJob = new BCH_AttendeeReminder();
        Database.executeBatch(batchJob);
    }

    private String changeReminderStatus(Call_Report__c event){
        return event.Attendee_Reminder_Required__c == NO_NEED ? NEED_REMINDER : event.Attendee_Reminder_Required__c == null ?
                NO_NEED : event.Attendee_Reminder_Required__c == HAS_REMINDER_NO_NEED ? HAS_REMINDER_NEED : NEED_REMINDER;
    }
}