force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Event Report Object to store the Event Information and associate Attendees and Send Email to them.</description>
    <label>Event Report</label>
    <nameField>
        <label>Event Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <description>A list of possible high level business topics that have been discussed at a meeting</description>
    <inlineHelpText>A list of possible high level business topics that have been discussed at a meeting. Select all that apply.</inlineHelpText>
    <label>Topics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>Africa Focus</fullName>
            </value>
            <value>
                <fullName>Brainstorming</fullName>
            </value>
            <value>
                <fullName>China Focus</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Consolidations</fullName>
            </value>
            <value>
                <fullName>E-Channels</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>Exchange Control</fullName>
            </value>
            <value>
                <fullName>Financial Engineering</fullName>
            </value>
            <value>
                <fullName>Financial Structuring</fullName>
            </value>
            <value>
                <fullName>Forex</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Interest Rate</fullName>
            </value>
            <value>
                <fullName>International Payment Systems</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>Money Markets</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Reference Rate Reform</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Special Initiatives</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report_Attendees__c/Call_Report_Attendees__c.object-meta.xml
<CustomObject>
    <description>Case 4296 Changed Name field from text to autonumber</description>
    <label>Event Report Attendees</label>
    <nameField>
        <displayFormat>ERA-{0000000000}</displayFormat>
        <label>Event Report Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Report Attendeess</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report_Attendees__c/fields/Call_Report__c.field-meta.xml
<CustomField>
    <fullName>Call_Report__c</fullName>
    <label>Event Report</label>
    <referenceTo>Call_Report__c</referenceTo>
    <relationshipLabel>Event Report Attendees</relationshipLabel>
    <relationshipName>Call_Report_Attendeess</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Environment_Variable__c/Environment_Variable__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Environment Variables</label>
</CustomObject>

force-app/main/default/classes/EventReportAttendee_test.cls
/*****************************************************************************************************\                      
    @ Last Modified By  : Wayne Gray
    @ Last Modified On  : June 2012
    @ Modification Description : Case #6521- Change contact to use TestFatcory
                                  API Version moved from 23 to 25 
                                  
    @ Last Modified By  : Nitish Kumar
    @ Last Modified On  : 21 Feb 2013
    @ Modification Description : EN -31 - Added best practices to the test class
                                 Improved Code coverage and Used TestDataUtility Class
                                 API Version moved from 25 to 27
    @description Test class for Event Report Attendee functionalities
******************************************************************************************************/
@isTest
Public Class EventReportAttendee_test {

    //Static data Member
    public static list < Contact > olstContact;
    public static List < Account > olstTestAccount;
    public static List < Call_Report__c > olstTestEventReport;
    public static List<ID> bankContactIds ;
    public static List<ID> eventReportIds ;
    public static list<Call_Report_Attendees__c> olstEventReportAttendees ;
    public static Environment_Variable__c oEnvironmentVariable ;

    public static void testSetup() {

        oEnvironmentVariable = TEST_DataFactory.getEnvironmentVariable();
        insert oEnvironmentVariable;

        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
        BLD_Account accBld = new BLD_Account(uow).useChild().name(DMN_Account.STANDARD_BANK_EMPLOYEES);

        olstContact = new List<Contact>();
        for (Integer i = 0; i < 6; i++) {
            olstContact.add((Contact) new BLD_Contact(uow).useBankContact()
                    .account(accBld)
                    .getRecord());
        }

        olstTestEventReport = new List<Call_Report__c>();
        for (Integer i = 0; i < 6; i++) {
            olstTestEventReport.add((Call_Report__c) new BLD_CallReport(uow)
                    .linkWithParent(accBld)
                    .topics('Relationship')
                    .getRecord());
        }
        uow.commitWork();


        olstEventReportAttendees = new List<Call_Report_Attendees__c>();

        for (Integer i = 0; i < 6; i++) {
            olstEventReportAttendees.add((Call_Report_Attendees__c) new BLD_CallReportAttendee(uow)
                    .contactId(olstContact.get(i).Id)
                    .callReportId(olstTestEventReport.get(i).Id)
                    .getRecord());
        }
        uow.commitWork();

    }

    @IsTest
    public static void testCheckPermissions() {

        testSetup();

        bankContactIds = new List<Id>();
        eventReportIds = new List<Id>();
        Set<Id> eventReportSet = new Set<Id>();

        for (integer i = 0; i < olstContact.size(); i++) {
            bankContactIds.add(olstContact[i].Id);
            eventReportIds.add(olstTestEventReport[i].Id);
            eventReportSet.add(olstTestEventReport[i].Id);
        }

        Test.StartTest();
        //Check Access to Event Report Object & Record
        Boolean hasPermission = false;

        CheckPermissions_glbl dummyCodeCoverage = new CheckPermissions_glbl();

        hasPermission = CheckPermissions_glbl.hasModifyRecordPermission(olstTestEventReport[0].Id, UserInfo.getUserId());

        System.assert(hasPermission);

        hasPermission = CheckPermissions_glbl.hasModifyObjectPermission('Call_Report__c');

        System.assert(hasPermission);

        SA_EventReportAttendeeFutureUpdate.addEventReportAttendees(bankContactIds, eventReportIds);

        SA_EventReportAttendeeFutureUpdate.refreshEventReportAttendeeShares(eventReportIds);

        SA_EventTriggerHelperClass.createTopic(eventReportSet, olstEventReportAttendees);

        olstTestEventReport[0].Topics__c = '';
        update olstTestEventReport[0];

        olstTestEventReport[1].Topics__c = 'Research';
        update olstTestEventReport[1];

        Test.stopTest();
    }

    @IsTest
    public static void testSAEventFutUpdate() {

        testSetup();

        bankContactIds = new List<Id>();
        eventReportIds = new List<Id>();

        for (integer i = 0; i < olstContact.size(); i++) {
            bankContactIds.add(olstContact[i].Id);
            eventReportIds.add(olstTestEventReport[i].Id);
        }

        Test.StartTest();
        //Check Access to Event Report Object & Record
        Boolean hasPermission = false;
        String oBjectName ;

        ApexPages.Standardsetcontroller controller = new ApexPages.Standardsetcontroller(olstTestEventReport);

        CheckPermissions_glbl dummyCodeCoverage = new CheckPermissions_glbl(controller);

        hasPermission = CheckPermissions_glbl.hasModifyAllProfilePermission();

        System.assert(hasPermission);

        oBjectName = CheckPermissions_glbl.getObjectName('Error');

        SA_EventReportAttendeeFutureUpdate.refreshEventReportAttendeeShares(eventReportIds);

        Test.stopTest();
    }
}