force-app/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Used to publish events describing logs regardless the transaction succeeds.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Event__e/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>Related stream/functional area.</description>
    <label>Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Context_User__c.field-meta.xml
<CustomField>
    <fullName>Context_User__c</fullName>
    <description>Id of executing user, when error occurred.</description>
    <label>Context User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Description of a log.</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Defines a place where a significant action occurred.</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_trace__c</fullName>
    <description>Exception stack trace.</description>
    <label>Stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of log</description>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SRV_Logger.cls
/**
 * Service class for publishing Log_Event__e platform events.
 * <br/> US-4824
 *
 * @author Wojciech Kowalczyk (wkowalczyk@deloittece.com)
 * @date June 2020
 */
public without sharing class SRV_Logger implements IService {
	fflib_ISObjectUnitOfWork uow = ORG_Application.unitOfWork.newInstance();
	public interface IService {
		void log(Exception ex, String area);
		void log(Exception ex, String area, String source);
		void log(String ex, String area, String source);
		void log(Exception ex, String area, String source, List<String> additionalMessages);
		void log(List<Database.SaveResult> results, String area);
		void log(List<Database.SaveResult> results, String area, String source);
		void log(List<Database.UpsertResult> results, String area);
		void log(List<Database.UpsertResult> results, String area, String source);
		void log(List<Database.DeleteResult> results, String area);
		void log(List<Database.DeleteResult> results, String area, String source);
	}
	public static IService newInstance() {
		return (IService) ORG_Application.service.newInstance(IService.class);
	}
	public void log(Object ex, String area) {
		log((Exception) ex, area, null);
	}
	public void log(Object ex, String area, String source) {
		log((Exception) ex, area, source, new List<String>());
	}
	public void log(Object ex, String area, String source, List<String> additionalMessages) {
		Exception caughtException = (Exception) ex;
		Log_Event__e event = new Log_Event__e(
				Area__c = area,
				Context_User__c = UserInfo.getUserId(),
				Message__c = caughtException.getTypeName() + ': ' + caughtException.getMessage(),
				Source__c = source,
				Stack_trace__c = caughtException.getStackTraceString(),
				Type__c = DMN_Log.TYPE_ERROR
		);
		for (String message : additionalMessages) {
			event.Message__c += '\n' + message;
		}
		uow.registerPublishBeforeTransaction(event);
		uow.commitWork();
	}
    public void log(String error, String area, String source) {
		Log_Event__e event = new Log_Event__e(
				Area__c = area,
				Context_User__c = UserInfo.getUserId(),
				Message__c = error,
				Source__c = source,
				Type__c = DMN_Log.TYPE_ERROR
		);
		uow.registerPublishBeforeTransaction(event);
		uow.commitWork();
	}
	public void log(List<Database.SaveResult> results, String area) {
		log(results, area, null);
	}
	public void log(List<Database.SaveResult> results, String area, String source) {
		for (Integer i = 0, j = results.size(); i<j; i++) {
			if (!results[i].isSuccess()) {
				uow.registerPublishBeforeTransaction(
						createDmlLog(area, source, results[i].getErrors())
				);
			}
		}
		uow.commitWork();
	}
	public void log(List<Database.UpsertResult> results, String area) {
		log(results, area, null);
	}
	public void log(List<Database.UpsertResult> results, String area, String source) {
		for (Integer i = 0, j = results.size(); i<j; i++) {
			if (!results[i].isSuccess()) {
				uow.registerPublishBeforeTransaction(
						createDmlLog(area, source, results[i].getErrors())
				);
			}
		}
		uow.commitWork();
	}
	public void log(List<Database.DeleteResult> results, String area) {
		log(results, area, null);
	}
	public void log(List<Database.DeleteResult> results, String area, String source) {
		for (Integer i = 0, j = results.size(); i<j; i++) {
			if (!results[i].isSuccess()) {
				uow.registerPublishBeforeTransaction(
						createDmlLog(area, source, results[i].getErrors())
				);
			}
		}
		uow.commitWork();
	}
	private Log_Event__e createDmlLog(String area, String source, List<Database.Error> errors) {
		return new Log_Event__e(
				Area__c = area,
				Context_User__c = UserInfo.getUserId(),
				Message__c = generateDmlMessageCore(errors),
				Source__c = source,
				Type__c = DMN_Log.TYPE_ERROR
		);
	}
	private String generateDmlMessageCore(List<Database.Error> errors) {
		String messageCore = '';
		for (Integer i = 0, l = errors.size(); i<l; i++) {
			Database.Error err = errors[i];
			messageCore += '\nError ' + (i + 1) + ' details:';
			messageCore += '\nFields that affected the error condition: ';
			messageCore += err.getFields().size()> 0 ? err.getFields() + '\n' : 'N/A';
			messageCore += '\nError message: ' + err.getMessage() + '\n';
			messageCore += '\nError status code: ' + err.getStatusCode();
		}
		return messageCore;
	}
}