force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>OneHub: This object is used to send broadcast messages to users on their OneHub dashboard. (US-4388)</description>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Is_Unread__c.field-meta.xml
<CustomField>
    <fullName>Is_Unread__c</fullName>
    <defaultValue>true</defaultValue>
    <description>OneHub: This field indicates if the message was read or unread by users on the OneHub dashboard.(US-4388)</description>
    <label>Is Unread</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Users__c.field-meta.xml
<CustomField>
    <fullName>Users__c</fullName>
    <description>OneHub: This field stored the names of all active users on OneHub to select who a notification should be sent to on the OneHub dashboard.(US-4388)</description>
    <inlineHelpText>Select Users this Notification should be sent to.</inlineHelpText>
    <label>Users</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All Users</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OSB_URLs__c/OSB_URLs__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will be used to store the OneSpace URLs</description>
    <label>OSB_URLs</label>
</CustomObject>

force-app/main/default/classes/OSB_HeaderDropdown_CTRL.cls
/**
 * Controller class for OSBHeaderDropdown component
 * 
 * @author Denys Yelchaninov (dyelchaninov@deloittece.com)
 * @date October 2020
 * 
 */
public with sharing class OSB_HeaderDropdown_CTRL {
    /**
     * Returns integer count for notification bell
     * 
     * @return List<object> feedItems unread
     */
    @AuraEnabled
    public static Integer getUnreadFeedItemsNumberForUser() {
        String userId=UserInfo.getUserId();
        return [SELECT COUNT() FROM Notification__c WHERE (OwnerId = :userId OR Users__c INCLUDES(:userId,:OSB_Header_CTRL.ALL_USERS)) AND Is_Unread__c = TRUE];
    } 

    /**
    * Return the Login URL
    * 
    * @return String URL
    */ 
    @AuraEnabled(Cacheable=true)
    public static String getLoginURL() {
        return OSB_Header_CTRL.LOGIN_URL;
    }

        /**
     * Return the Change Password URL of loggen in User
     * 
     * @return String URL
     */ 
    @AuraEnabled(Cacheable=true)
    public static String getChangePasswordUrlPing() {
        String userName;
        String adapterId = 'AdapterId';
        String pingUrlExtention = OSB_URLs__c.getValues(adapterId).Value__c;
        if (UTL_User.isLoggedInUser()) {
            userName = UserInfo.getUserEmail();
            String pingBaseUrl = [SELECT DeveloperName, Endpoint FROM NamedCredential where DeveloperName =:OSB_Header_CTRL.PING_DIRECTORY LIMIT 1].Endpoint;
            return pingBaseUrl+pingUrlExtention+username;
        }
        return null;
    }
    
    /**
     * Queriers for knowledge articles for the insights and also gets the website url from OSB_urls custom setting
     *
     * @return map<String,object> of knowledge articles and the custom website url
     **/
    @AuraEnabled(Cacheable=true)
    public static Map<String,object> getInsights() {
        Map<String,object> insightsMap = new Map<String,object>();
        String url = OSB_URLs__c.getValues(OSB_InsightsHub_CTRL.INSIGHT_URL).Value__c;
        List<Knowledge__kav> unorderList = SEL_KnowledgeArticleVersions.newInstance().selectByPublishStatusAndRecordTypeIdWoSharing(
                new Set<String>{DMN_Knowledge.PUBLISH_STATUS_ONLINE},
                new Set<Id>{UTL_RecordType.getRecordTypeId(DMN_Knowledge.OBJ_NAME, DMN_Knowledge.RT_INSIGHT)},
                new Set<Id>{} );
        unorderList.sort();
        insightsMap.put('KnowledgeList', unorderList);
        insightsMap.put('WebUrl', url);
        return insightsMap;
    }
}