force-app/main/default/objects/ArticleNews__c/ArticleNews__c.object-meta.xml
<CustomObject>
    <label>News</label>
    <nameField>
        <label>News</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ArticleNews__c/fields/An__c.field-meta.xml
<CustomField>
    <fullName>An__c</fullName>
    <label>An</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArticleNews__c/fields/Pred__c.field-meta.xml
<CustomField>
    <fullName>Pred__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this article may (prediction) be a lead or not</description>
    <label>Pred</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ArticleNews__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of news article</description>
    <label>Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CI_Gem__c/CI_Gem__c.object-meta.xml
<CustomObject>
    <description>A gem in the context of Client Insights is a valuable nugget or gem of information associated to a particular user</description>
    <label>CI Gem</label>
    <nameField>
        <label>CI Gem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CI Gems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CI_Gem__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Client which the Gem relates to</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CI Gems</relationshipLabel>
    <relationshipName>CI_Gems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CI_Gem__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>Used to store custom data if needed, depending on the record type</description>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CI_Gem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Text to describe Gem</description>
    <label>Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CI_Gem__c/fields/Dismissed__c.field-meta.xml
<CustomField>
    <fullName>Dismissed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the user has dismissed the Gem notification</description>
    <label>Dismissed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CI_Gem__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CI_Gems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CI_GemLeadController.cls
public with sharing class CI_GemLeadController {
    public static List<CI_Gem__c> getLeadGems(String clientId) {   
        Date publicationDate = Date.today().addDays(-15);
        Integer numOfArticlesPerType = 20;
        Integer numberOfLastViewClients = 50;
        String probability = 'medium';
        Boolean isGettingClientSectorNews = false;
        Boolean sortingArticles = false;

        CI_ResponseDto newsResp = CI_NewsController.getClientNews(clientId, numOfArticlesPerType, String.valueOf(publicationDate), numberOfLastViewClients, probability, isGettingClientSectorNews, sortingArticles);

        if(!newsResp.IsSuccess)
            throw new AuraHandledException('Could not get news articles for lead gems. Error: ' + newsResp.Message);

        Map<String, List<ArticleNews__c>> newsByTypeMap = (Map<String, List<ArticleNews__c>>)newsResp.Data;

        checkAndInsertLeadGems(newsByTypeMap.get('newsByClientName'), clientId);

        List<CI_Gem__c> leadGems;
        if(clientId == null)
            leadGems = [SELECT Description__c, Dismissed__c, CreatedDate, Data__c, Deleted__c, RecordType.Name, Client__c, Client__r.Name
                                    FROM CI_Gem__c 
                                    WHERE RecordType.Name = 'News Lead' 
                                    AND User__c =: UserInfo.getUserId() 
                                    ORDER BY CreatedDate DESC];
        else
            leadGems = [SELECT Description__c, Dismissed__c, CreatedDate, Data__c, Deleted__c, RecordType.Name, Client__c, Client__r.Name
                                    FROM CI_Gem__c 
                                    WHERE RecordType.Name = 'News Lead' 
                                    AND User__c =: UserInfo.getUserId() 
                                    AND Client__c =: clientId 
                                    ORDER BY CreatedDate DESC];

        return leadGems;
    }

    public static List<CI_Gem__c> checkAndInsertLeadGems(List<ArticleNews__c> leadArticleList, String clientId) {   
        //Get existing news lead gems, regardless of client, to check for duplicates
        List<CI_Gem__c> extantNewsLeadGems = [SELECT Description__c, Dismissed__c, CreatedDate, Data__c, Deleted__c, RecordType.Name, Client__c 
                                                FROM CI_Gem__c 
                                                WHERE RecordType.Name = 'News Lead' 
                                                AND User__c =: UserInfo.getUserId()];
        
        List<ArticleNews__c> leadGemArticleList = new List<ArticleNews__c>();
        //Loop through news items
        for(ArticleNews__c newsArticle : leadArticleList) {
            system.debug(newsArticle.Pred__c + ' ' + newsArticle.Title__c);
            //check for lead
            if(newsArticle.Pred__c){
                //check if we already have the news lead as a gem
                Boolean gemFound = false;
                for(CI_Gem__c newsLeadGem : extantNewsLeadGems){
                    if(newsArticle.An__c == (String)((Map<String, Object>)JSON.deserializeUntyped(newsLeadGem.Data__c)).get('articleId'))
                        gemFound = true;
                }
                //if not then add
                if(!gemFound)
                    leadGemArticleList.add(newsArticle);
            }
        }

        //get client name if we have a client ID
        Account client = clientId == null ? null : [SELECT Name FROM Account WHERE Id =: clientId];
        
        //Create our new news lead gems
        Id newsLeadRecordTypeId = Schema.SObjectType.CI_Gem__c.getRecordTypeInfosByName().get('News Lead').getRecordTypeId();
        List<CI_Gem__c> newNewsLeadGems = new List<CI_Gem__c>();
        for(ArticleNews__c leadGemArticle : leadGemArticleList){
            JSONGenerator jsonGen = JSON.createGenerator(false);
            jsonGen.writeStartObject();
            jsonGen.writeStringField('articleId', leadGemArticle.An__c);
            jsonGen.writeStringField('articleTitle', leadGemArticle.Title__c);
            jsonGen.writeEndObject();
            
            CI_Gem__c newsLeadGem = new CI_Gem__c();
            newsLeadGem.RecordTypeId = newsLeadRecordTypeId;
            newsLeadGem.User__c = UserInfo.getUserId();
            newsLeadGem.Data__c = jsonGen.getAsString();
            newsLeadGem.Client__c = client ==  null ? null : client.Id;

            newNewsLeadGems.add(newsLeadGem);
        }
        insert newNewsLeadGems;

        return newNewsLeadGems;
    }
}