force-app/main/default/objects/Agenda__c/Agenda__c.object-meta.xml
<CustomObject>
    <description>Junction object to allow many-to-many relation between Event Report and PCC</description>
    <label>Agenda</label>
    <nameField>
        <displayFormat>Agenda-{0000}</displayFormat>
        <label>Agenda Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agenda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agenda__c/fields/Chairperson__c.field-meta.xml
<CustomField>
    <fullName>Chairperson__c</fullName>
    <description>DEF - 001928: Added this field to refer Chairperson on Event report</description>
    <formula>Event_Report__r.Chairperson__r.FirstName +&apos; &apos;+  Event_Report__r.Chairperson__r.LastName</formula>
    <label>Chairperson</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agenda__c/fields/Event_Report__c.field-meta.xml
<CustomField>
    <fullName>Event_Report__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <description>Event Report to which NBAC records are associated</description>
    <inlineHelpText>Event Report to which NBAC records are associated</inlineHelpText>
    <label>Event Report</label>
    <referenceTo>Call_Report__c</referenceTo>
    <relationshipLabel>Agenda</relationshipLabel>
    <relationshipName>Agenda</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agenda__c/fields/Related_NBAC__c.field-meta.xml
<CustomField>
    <fullName>Related_NBAC__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>US-2607 Phase 2: DM NBAC - Meeting Console - Update Agenda Section for NBAC</description>
    <label>Related NBAC</label>
    <referenceTo>Business_Assessment__c</referenceTo>
    <relationshipLabel>Agenda</relationshipLabel>
    <relationshipName>Agenda</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/Business_Assessment__c.object-meta.xml
<CustomObject>
    <label>Business Assessment</label>
    <nameField>
        <displayFormat>BA{0000000}</displayFormat>
        <label>Business Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Assessment__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transaction Overview</fullName>
                <default>true</default>
                <label>Transaction Overview</label>
            </value>
            <value>
                <fullName>Stakeholder Contribution</fullName>
            </value>
            <value>
                <fullName>Finalisation</fullName>
            </value>
            <value>
                <fullName>Supported</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/MNPI__c.field-meta.xml
<CustomField>
    <fullName>MNPI__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether there is an MNPI opportunity included on the NBAC</description>
    <inlineHelpText>Indicates whether there is an MNPI opportunity included on the NBAC</inlineHelpText>
    <label>MNPI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/NBAC_Committee__c.field-meta.xml
<CustomField>
    <fullName>NBAC_Committee__c</fullName>
    <description>The NBAC committee who is responsible for the approval of NBAC Applications.</description>
    <inlineHelpText>The NBAC committee who is responsible for the approval of NBAC Applications.</inlineHelpText>
    <label>NBAC Committee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NBAC_Committee</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/NBAC_Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>NBAC_Meeting_Date__c</fullName>
    <description>The actual date the NBAC form is expected to be presented to the committee</description>
    <inlineHelpText>Date of which the NBAC application will be presented to the Committee</inlineHelpText>
    <label>NBAC Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Submission_Type__c</fullName>
    <description>The decision category to which the business assessment applies.
            Type 1: Low transaction risk and complexity with adequate client or transaction returns;
            Type 2: Low transaction risk and complexity but inadequate client or transaction returns;
            Type 3: High transaction risk and complexity but adequate client or transaction returns;
            Type 4: High transaction risk and complexity and inadequate client or transaction returns.</description>
    <label>Submission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Type 1: For noting purposes</fullName>
            </value>
            <value>
                <fullName>Type 2: Emphasis on client strategy / returns</fullName>
            </value>
            <value>
                <fullName>Type 3: Emphasis on risk / complexity</fullName>
            </value>
            <value>
                <fullName>Type 4: Full discussion</fullName>
            </value>
            <value>
                <fullName>Commercial Banking</fullName>
            </value>
            <value>
                <fullName>Type 1</fullName>
                <isActive>false</isActive>
                <label>Type 1</label>
            </value>
            <value>
                <fullName>Type 2</fullName>
                <isActive>false</isActive>
                <label>Type 2</label>
            </value>
            <value>
                <fullName>Type 3</fullName>
                <isActive>false</isActive>
                <label>Type 3</label>
            </value>
            <value>
                <fullName>Type 4</fullName>
                <isActive>false</isActive>
                <label>Type 4</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/recordTypes/NBAC.recordType-meta.xml
<RecordType>
    <fullName>NBAC</fullName>
    <active>true</active>
    <description>US-2450</description>
    <label>NBAC</label>
</RecordType>

force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Event Report Object to store the Event Information and associate Attendees and Send Email to them.</description>
    <label>Event Report</label>
    <nameField>
        <label>Event Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Chairperson__c.field-meta.xml
<CustomField>
    <fullName>Chairperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person chairing the NBAC Meeting(US-1370).</description>
    <inlineHelpText>Person chairing the NBAC Meeting.</inlineHelpText>
    <label>Chairperson</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Event_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Meeting_Notes__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Notes__c</fullName>
    <description>US-3273</description>
    <inlineHelpText>Section for Secretaries to add notes about the Meeting. These notes will be sent out with the Meeting Agenda.</inlineHelpText>
    <label>Meeting Notes</label>
    <length>3500</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/NBAC_Committee__c.field-meta.xml
<CustomField>
    <fullName>NBAC_Committee__c</fullName>
    <description>The NBAC committee who is responsible for the approval of NBAC Applications.</description>
    <inlineHelpText>The NBAC committee who is responsible for the approval of NBAC Applications.</inlineHelpText>
    <label>NBAC Committee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NBAC_Committee</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/NBACMeetingAgendaVFComController.cls
public without sharing class NBACMeetingAgendaVFComController {
public id callreport{get;set;}

public String otmString{get;set;}
public String otmLocation{get;set;}
public String omtNBACCommite{get;set;}
public Id outputId{get;set;}
public string startDateOutput{get;set;}
public list<Business_Assessment__c> NBACs {get;set;}

public string startTimeOutput{get;set;}
public string endTimeOutput{get;set;}
public string timeZoneFullName{get;set;}

public string chairpersonOutput{get;set;}
public string nbacSecretaryoutput{get;set;}

public date agendaMeetingDate{get;set;}

public string outputSubject{get;set;}
public string meetingNotes{get;set;}

public list<wrapperAgenda> datas{
    get {
            if(datas != null) {
                return datas;
            }
            else {
                datas = getData();
                return datas;
            }
        }
    set;
}

    private Map<String, String> value2TimeZones {
        get {
            if(value2TimeZones != null) {
                return value2TimeZones;
            } else {
                List<Schema.PicklistEntry> entries = User.TimeZoneSidKey.getDescribe().getPicklistValues();
                value2TimeZones = new Map<String, String>();
                for(Schema.PicklistEntry entry : entries) {
                    value2TimeZones.put(entry.getValue(), entry.getLabel());
                }
                return value2TimeZones;
            }
        } private set;
    }

    public String timeZone {get;set;}

    list<Business_Assessment__c> listOppMembers {get;set;}
    public list<Call_Report__c> listCallReports {get;set;}
    public list<wrapperAgenda> lstAgendas {get;set;}
    private final Set<String> submissionForNoting = new Set<String> {'Type 1: For noting purposes'};

     public class wrapperAgenda{
          public Agenda__c agenda{get;set;}
          public String oppTeamMembers{get;set;}
          public String attId{get;set;}

          public wrapperAgenda(Agenda__c thisAgenda){
              agenda = thisAgenda;
              oppTeamMembers = '';
          }
     }

    public list<wrapperAgenda> getNBACSforApproval() {
        list<wrapperAgenda> NBACSforApproval = new list<wrapperAgenda> ();
        for(WrapperAgenda nbac : datas)  {
            if(!submissionForNoting.contains(nbac.agenda.Related_NBAC__r.Submission_Type__c)) {
                NBACSforApproval.add(nbac);
            }
        }
        return NBACSforApproval;
    }

    public list<wrapperAgenda> getNBACSforNoting() {
        list<wrapperAgenda> NBACSforNoting = new list<wrapperAgenda> ();
        for(WrapperAgenda nbac : datas) {
            if(submissionForNoting.contains(nbac.agenda.Related_NBAC__r.Submission_Type__c)) {
                NBACSforNoting.add(nbac);
            }
        }
        return NBACSforNoting;
    }

    @TestVisible
    private list<wrapperAgenda> getData(){
    if(callreport==null){
        return null;
    }else{
        Map<Id, wrapperAgenda> mapOfAgendsByOppIds;
     
        listCallReports = [SELECT NBAC_Committee__c,
                                  Location__c,  
                                  Start__c, 
                                  End__c,
                                  Subject__c,
                                  Meeting_Notes__c,
                                  Chairperson__r.Name,
                                      (Select Name, 
                                              Related_NBAC__r.Name,
                                              Related_NBAC__r.Id,
                                              Related_NBAC__r.MNPI__c,
                                              Related_NBAC__r.NBAC_Meeting_Date__c,
                                              Related_NBAC__r.Submission_Type__c,
                                              Related_NBAC__r.Milestone__c
                                                  FROM Agenda__r
                                                      WHERE Event_Report__c =: callreport AND (Related_NBAC__r.Milestone__c = 'Submitted' or Related_NBAC__r.Milestone__c = 'Supported' or Related_NBAC__r.Milestone__c = 'Approval'))
                                  FROM Call_Report__c WHERE id =:callreport];

        omtNBACCommite = listCallReports[0].NBAC_Committee__c;
        list<Id>relatedOppId = new list<Id>();
        otmLocation = listCallReports[0].Location__c;
        DateTime otmStart = listCallReports[0].Start__c;
        
        chairpersonOutput = listCallReports[0].Chairperson__r.Name;
        
        startDateOutput = otmStart.format('EEEEE, dd MMM yyyy');
        startTimeOutput = otmStart.format('hh:mm a');
        
        DateTime otmEnd = listCallReports[0].End__c;
        endTimeOutput = otmEnd.format('hh:mm a');

        timeZone = value2TimeZones.get(UserInfo.getTimeZone().toString());
        
        outputSubject = listCallReports[0].Subject__c;
        meetingNotes = listCallReports[0].Meeting_Notes__c;
        
        mapOfAgendsByOppIds = new Map<Id, wrapperAgenda>(); 
        for(Agenda__c objAgenda :listCallReports[0].Agenda__r){
            mapOfAgendsByOppIds.put(objAgenda.Related_NBAC__r.Id,new wrapperAgenda(objAgenda));
            relatedOppId.add(objAgenda.Related_NBAC__r.Id);
            
        }
        if(relatedOppId == null){
            return null;
        }else{
            listOppMembers = [Select Id, (Select Id From Attachments Order By lastModifiedDate DESC LIMIT 1),
                                        (Select UserOrGroup.Name, UserOrGroup.Id, ParentId From Shares)
                            From Business_Assessment__c
                            Where Id IN :mapOfAgendsByOppIds.keySet()];
            Map<Id ,contentDocumentLink > mappedConDoc = new Map<Id ,contentDocumentLink >();
            Map<Id ,String > mappedEntityIdConvsionId = new Map<Id ,String>();
            List<ContentDocumentLink> contentDocumentLink = [SELECT ContentDocumentId ,LinkedEntityId FROM ContentDocumentLink
                                                        WHERE LinkedEntityId IN:mapOfAgendsByOppIds.keySet()];
            for (ContentDocumentLink conDoc :contentDocumentLink){
                mappedConDoc.put(conDoc.ContentDocumentId,conDoc);

            }
            List<Contentversion> conVersionList = [Select id,ContentDocumentId, lastModifiedDate from Contentversion
                                                    where ContentDocumentId IN:mappedConDoc.keySet() AND IsLatest=true Order By lastModifiedDate DESC ];
            for (Contentversion convsion :conVersionList){
                ContentDocumentLink conDocLink =  mappedConDoc.get(convsion.ContentDocumentId);
                if(mappedEntityIdConvsionId.get(conDocLink.LinkedEntityId)==null) {
                    mappedEntityIdConvsionId.put(conDocLink.LinkedEntityId,convsion.id);
                }
            }
            //atts = [SELECT id, name, parentId, owner.name, ownerId, createdBy.name, lastModifiedBy.name, lastModifiedDate FROM Attachment WHERE parentId IN :mapOfAgendsByOppIds.keySet() ORDER BY lastModifiedDate DESC];
            otmString = '';
                wrapperAgenda temp;
                for(Business_Assessment__c otm : listOppMembers){
                    temp = mapOfAgendsByOppIds.get(otm.Id);
                    if(temp !=null){
                        //temp.oppTeamMembers +=  otm.UserOrGroup.Name+ ', ';
                        if(String.isBlank(mappedEntityIdConvsionId.get(otm.Id))) {
                            for (Attachment att : otm.Attachments) {
                                temp.attId = '/servlet/servlet.FileDownload?file='+ att.Id;
                            }
                        }
                        else {
                            temp.attId = '/sfc/servlet.shepherd/version/download/'+mappedEntityIdConvsionId.get(otm.Id);
                        }
                        Set<Id> nbacTeamIds = new Set<Id>();
                        for(Business_Assessment__Share baShare : otm.Shares) {
                            if(!nbacTeamIds.contains(baShare.UserOrGroup.Id)) {
                                nbacTeamIds.add(baShare.UserOrGroup.Id);
                                if(String.isNotBlank(baShare.UserOrGroup.Name))
                                    temp.oppTeamMembers += baShare.UserOrGroup.Name + ', ';
                            }
                        }
                    }

                }
                for(wrapperAgenda resultMembers: mapOfAgendsByOppIds.values()){
                    resultMembers.oppTeamMembers = resultMembers.oppTeamMembers.removeEnd(', ');
                
                }
               
                return mapOfAgendsByOppIds.values();
          }
        }
    }  
}