force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>CDCS-70 This object is used to store bank account number and name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>CDCS-70 This field links financial account to Client object.</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Financial_Account_Permission__c/Financial_Account_Permission__c.object-meta.xml
<CustomObject>
    <description>CDCS-70 Junction object representing that the specific user/contact has the access to a specific type of service on a specific financial account.</description>
    <label>Financial Account Permission</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Financial Account Permission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account_Permission__c/fields/Authorized_Person__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Person__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CDCS-70 This field links financial account permission to the person who was granted permission.</description>
    <label>Authorized Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Financial Account Permissions</relationshipLabel>
    <relationshipName>Financial_Account_Permissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account_Permission__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CDCS-70 This field links financial account permission to the financial account on which permission is granted.</description>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Account Permissions</relationshipLabel>
    <relationshipName>Financial_Account_Permissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OSB_VA_AvailableClients.cls
/**
 * Controller class with logic invoked from the OneHub chat bot
 *
 * @author Konrad Bruszewski (konrad.bruszewski@standardbank.co.za)
 * @date March 2021
 */
public with sharing class OSB_VA_AvailableClients {

    /**
     * DTO class with input for getting clients for which user can query account information
     */
    public class GetClientSInput{
        @InvocableVariable
        public String contactId;
        @InvocableVariable
        public String serviceType;
    }

    /**
     * Invocable method for getting clients for which user can query account information
     *
     * @param inputs List<GetClientSInput>
     *
     * @return List<List<String>>
     */
    @InvocableMethod(Label='VA get available clients')
    public static List<List<String>> getClients(List<GetClientSInput> inputs) {
        List<List<String>> result = new List<List<String>>();
        Set<Id> contactIdSet = new Set<Id>();
        Map<String, Set<String>> contact2Clients = new Map<String, Set<String>>();
        for (GetClientSInput input : inputs) {
            contactIdSet.add(Id.valueOf(input.contactId));
        }
        SEL_FinancialAccountPermissions selector = SEL_FinancialAccountPermissions.newInstance();
        List<Financial_Account_Permission__c> permissions = selector.selectActiveByAuthorizedPersonsWithClientName(contactIdSet, inputs.get(0).serviceType);
        for (Financial_Account_Permission__c permission : permissions) {
            Set<String> clients = contact2Clients.get(permission.Authorized_Person__c);
            if (clients == null) {
                clients = new Set<String>();
                contact2Clients.put(permission.Authorized_Person__c, clients);
            }
            clients.add(permission.Financial_Account__r.Client__r.Name);
        }
        for (GetClientSInput input : inputs) {
            List<String> clientNames = new List<String>();
            Set<String> clientNamesSet = contact2Clients.get(input.contactId);
            if(clientNamesSet != null && !clientNamesSet.isEmpty()){
                clientNames.addAll(clientNamesSet);
                clientNames.sort();
            }
            result.add(clientNames);
        }
        return result;
    }
}