force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>CDCS-70 This object is used to store bank account number and name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account_Permission__c/Financial_Account_Permission__c.object-meta.xml
<CustomObject>
    <description>CDCS-70 Junction object representing that the specific user/contact has the access to a specific type of service on a specific financial account.</description>
    <label>Financial Account Permission</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Financial Account Permission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account_Permission__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CDCS-70 This field links financial account permission to the financial account on which permission is granted.</description>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Account Permissions</relationshipLabel>
    <relationshipName>Financial_Account_Permissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Permissions__c/Permissions__c.object-meta.xml
<CustomObject>
    <description>CDCS-70 This object represents the type of service for which permission is granted. Object has one record per service type. Three types of permissions are planned: payment tracking, viewing account balance and generating statement.</description>
    <label>Permissions</label>
    <nameField>
        <label>Service Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OSB_SRV_FinancialAccPermissionHan_Test.cls
/**
 *
 * Test class for OSB_SRV_BotPaymentTrackingHandler
 *
 * @author Konrad Bruszewski (konrad.bruszewski@standardbank.co.za)
 * @date January 2021
 */
@IsTest
public with sharing class OSB_SRV_FinancialAccPermissionHan_Test {

    @TestSetup
    static void setup() {
        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
        Contact con = (Contact) new BLD_Contact(uow)
                .name('Name', 'Test1')
                .email('test1@email.com')
                .ownerId(UserInfo.getUserId())
                .communityAccessRole(DMN_Contact.OSB_COMMUNITY_ACCESS_ROLE_AP)
                .account(
                        new BLD_Account(uow)
                )
                .getRecord();
        uow.commitWork();
    }

    @IsTest
    public static void testCheckContactPermissionNoPermission(){
        Contact con = [SELECT Id, AccountId FROM Contact LIMIT 1];
        OSB_SRV_FinancialAccPermissionHandler.CheckPermissionsInput input = new OSB_SRV_FinancialAccPermissionHandler.CheckPermissionsInput();
        input.contactId = con.Id;
        input.permissionType = 'Payment Tracking';
        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork(new List<SObjectType>{
                Permissions__c.getSObjectType(),
                Financial_Account__c.getSObjectType(), Financial_Account_Permission__c.getSObjectType()
        });
        BLD_Permissions permissionBld = new BLD_Permissions(uow).name('Payment tracking');
        uow.commitWork();
        List<OSB_SRV_FinancialAccPermissionHandler.CheckPermissionsInput> inputs = new List<OSB_SRV_FinancialAccPermissionHandler.CheckPermissionsInput>{input};
        Test.startTest();
        List<Boolean> result = OSB_SRV_FinancialAccPermissionHandler.checkPermissions(inputs);
        Test.stopTest();
        System.assertEquals(1, result.size());
        System.assertEquals(false, result.get(0));
    }

    @IsTest
    public static void testCheckContactPermissionOnAccountNoPermission(){
        Contact con = [SELECT Id, AccountId FROM Contact LIMIT 1];
        OSB_SRV_FinancialAccPermissionHandler.CheckPermissionsInput input = new OSB_SRV_FinancialAccPermissionHandler.CheckPermissionsInput();
        input.contactId = con.Id;
        input.permissionType = 'Payment Tracking';
        input.accountNumber = '/23131321374';
        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork(new List<SObjectType>{
                Permissions__c.getSObjectType(),
                Financial_Account__c.getSObjectType(), Financial_Account_Permission__c.getSObjectType()
        });
        BLD_Permissions permissionBld = new BLD_Permissions(uow).name('Payment tracking');
        BLD_FinancialAccount financialAccountBld = new BLD_FinancialAccount(uow)
                .clientId(con.AccountId)
                .name('John')
                .externalId('/23131321374');
        uow.commitWork();
        List<OSB_SRV_FinancialAccPermissionHandler.CheckPermissionsInput> inputs = new List<OSB_SRV_FinancialAccPermissionHandler.CheckPermissionsInput>{input};
        Test.startTest();
        List<Boolean> result = OSB_SRV_FinancialAccPermissionHandler.checkPermissions(inputs);
        Test.stopTest();
        System.assertEquals(1, result.size());
        System.assertEquals(false, result.get(0));
    }
}