force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>CDCS-70 This object is used to store bank account number and name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>CDCS-70 This field links financial account to Client object.</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>CDCS-70 This field holds the bank account number.</description>
    <label>Account Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Used to store data about errors or significant events.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>Related stream/functional area.</description>
    <label>Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Context_User__c.field-meta.xml
<CustomField>
    <fullName>Context_User__c</fullName>
    <description>Id of executing user, when error occurred.</description>
    <label>Context User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Description of a log.</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stack_trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_trace__c</fullName>
    <description>Exception stack trace.</description>
    <label>Stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of log</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <label>Error</label>
            </value>
            <value>
                <fullName>INFO</fullName>
                <label>Info</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OSB_VA_CustomerIdentifier_CTRL.cls
/**
 *
 * Controller class with logic invoked from the OneHub chat bot
 *
 * @author Konrad Bruszewski (konrad.bruszewski@standardbank.co.za)
 * @date March 2021
 */
@SuppressWarnings('PMD.CognitiveComplexity')
public with sharing class OSB_VA_CustomerIdentifier_CTRL {

    private static List<Log__c> logs = new List<Log__c>();
    private static Map<GetCustomerIdentifierInput, Log__c> input2Log = new Map<GetCustomerIdentifierInput, Log__c>();
    private static List<GetCustomerIdentifierOutput> customerIdentifierOutputs = new List<OSB_VA_CustomerIdentifier_CTRL.GetCustomerIdentifierOutput>();

    public enum OCHGetCustomerIdentifierError {
        HTTP_REQUEST_SEND_ERROR, HTTP_RESPONSE_ERROR, NO_ACCOUNT_FOUND_ERROR
    }

    public static final Map<OCHGetCustomerIdentifierError, String> ERROR_2_ERROR_MESSAGE = new Map<OCHGetCustomerIdentifierError, String>{
            OCHGetCustomerIdentifierError.HTTP_REQUEST_SEND_ERROR => System.Label.OSB_VA_BA_TechnicalErrorSingle,
            OCHGetCustomerIdentifierError.HTTP_RESPONSE_ERROR => System.Label.OSB_VA_BA_TechnicalErrorSingle,
            OCHGetCustomerIdentifierError.NO_ACCOUNT_FOUND_ERROR => System.Label.OSB_VA_NoAccountsFound
    };

    /**
     * DTO class with parameters to get the customer identifier from OCH
     */
    public class GetCustomerIdentifierInput {
        @InvocableVariable
        public String clientName;
        @InvocableVariable
        public String contactId;
        @InvocableVariable
        public String accessToken;
    }

    /**
     * DTO class for output with customer identifier fetching result
     */
    public class GetCustomerIdentifierOutput {
        @InvocableVariable
        public String customerIdentifier;
        @InvocableVariable
        public Boolean hasError;
        @InvocableVariable
        public String errorType;
        @InvocableVariable
        public String errorMessage;
        @InvocableVariable
        public String actionType;
        @InvocableVariable
        public String errorLogId;
    }

    /**
     * Invocable method for getting customer identifier from OCH
     *
     * @param inputs List<GetCustomerIdentifierInput>
     *
     * @return List<GetCustomerIdentifierOutput>
     */
    @InvocableMethod(Label='VA get customer identifier')
    public static List<GetCustomerIdentifierOutput> getCustomerIdentifier(List<GetCustomerIdentifierInput> inputs) {
        logs = new List<Log__c>();
        input2Log = new Map<OSB_VA_CustomerIdentifier_CTRL.GetCustomerIdentifierInput, Log__c>();
        customerIdentifierOutputs = new List<OSB_VA_CustomerIdentifier_CTRL.GetCustomerIdentifierOutput>();
        SEL_FinancialAccounts selector = SEL_FinancialAccounts.newInstance();
        Set<String> clientNames = new Set<String>();
        Map<String, String> clientName2AccountNumber = new Map<String, String>();
        for (GetCustomerIdentifierInput input : inputs) {
            clientNames.add(input.clientName);
        }
        List<Financial_Account__c> finAccounts = selector.selectByClientNames(clientNames);
        for (Financial_Account__c finAccount : finAccounts) {
            if (clientName2AccountNumber.get(finAccount.External_Id__c) == null) {
                clientName2AccountNumber.put(finAccount.Client__r.Name, finAccount.External_Id__c);
            }
        }
        for (GetCustomerIdentifierInput input : inputs) {
            GetCustomerIdentifierOutput output = new GetCustomerIdentifierOutput();
            HttpResponse response = queryOCH(output, clientName2AccountNumber.get(input.clientName), input.accessToken, input);
            if (response == null) {
                continue;
            }
            Map<String, Object> responseBody = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            List<Object> responseData = (List<Object>) responseBody.get('data');
            if (responseData == null || responseData.size() == 0) {
                handleOutputError(output, OCHGetCustomerIdentifierError.NO_ACCOUNT_FOUND_ERROR, OSB_SRV_BotPaymentTrackingHandler.CREATE_CHILD_CASE_ACTION);
                continue;
            }
            String customerIdentifier = (String) ((Map<String, Object>) (responseData.get(0))).get('custId');
            if (customerIdentifier == null) {
                handleOutputError(output, OCHGetCustomerIdentifierError.NO_ACCOUNT_FOUND_ERROR, OSB_SRV_BotPaymentTrackingHandler.CREATE_CHILD_CASE_ACTION);
                continue;
            }
            output.customerIdentifier = customerIdentifier;
            customerIdentifierOutputs.add(output);
        }
        handleLogs(inputs);
        return customerIdentifierOutputs;
    }

    private static HttpResponse queryOch(GetCustomerIdentifierOutput output, String accountNumber, String accessToken, GetCustomerIdentifierInput input) {
        HttpResponse response;
        try {
            response = OSB_SRV_BotBalanceViewHandler.queryOCHForAccountDetails(accountNumber, accessToken);
            if (response.getStatusCode() != 200) {
                if (response.getStatusCode() == 404) {
                    handleOutputError(output, OCHGetCustomerIdentifierError.NO_ACCOUNT_FOUND_ERROR, OSB_SRV_BotPaymentTrackingHandler.CLOSE_CASE_NO_BALANCE_FOUND);
                } else {
                    throw new CalloutException('Response from OCH was returned with status code: ' + String.valueOf(response.getStatusCode()));
                }
                return null;
            }
        } catch (Exception ex) {
            Log__c errorLog = new Log__c(Stack_trace__c = ex.getStackTraceString(), Message__c = ex.getMessage(), Area__c = 'OneHub', Type__c = 'Error', Context_User__c = UserInfo.getUserId());
            input2Log.put(input, errorLog);
            logs.add(errorLog);
            handleOutputError(output, OCHGetCustomerIdentifierError.HTTP_REQUEST_SEND_ERROR, OSB_SRV_BotPaymentTrackingHandler.CREATE_CHILD_CASE_ACTION);
            return null;
        }
        return response;
    }

    private static void handleOutputError(GetCustomerIdentifierOutput outputMsg, OCHGetCustomerIdentifierError errorType, String actionType) {
        outputMsg.hasError = true;
        outputMsg.errorType = errorType.name();
        outputMsg.errorMessage = ERROR_2_ERROR_MESSAGE.get(errorType);
        outputMsg.actionType = actionType;
        customerIdentifierOutputs.add(outputMsg);
    }

    private static void handleLogs(List<GetCustomerIdentifierInput> inputs) {
        if (!logs.isEmpty()) {
            insert logs;
            Integer i = 0;
            while (i < inputs.size()) {
                GetCustomerIdentifierInput input = inputs.get(i);
                Log__c log = input2Log.get(input);
                if (log != null) {
                    GetCustomerIdentifierOutput output = customerIdentifierOutputs.get(i);
                    output.errorLogId = log.Id;
                }
                i += 1;
            }
        }
    }
}