force-app/main/default/objects/Application_Document__c/Application_Document__c.object-meta.xml
<CustomObject>
    <description>Digitization: Onboarding - All required and supporting document link information is stored in this object.The actual file is stored on FileNet..</description>
    <label>Application Document</label>
    <nameField>
        <displayFormat>AD-{000000000}</displayFormat>
        <label>Application Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Document__c/fields/Authorised_Person__c.field-meta.xml
<CustomField>
    <fullName>Authorised_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>All documents related to an Authorised Person</description>
    <inlineHelpText>An authorised person is any person who has been designated by written notice from the client or its designated agent to act on behalf of the client</inlineHelpText>
    <label>Authorised Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Application Documents</relationshipLabel>
    <relationshipName>Application_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Document__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <inlineHelpText>Indicates where in the application process the application is.</inlineHelpText>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Unverified</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Document__c/fields/Onboarding_Application__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Onboarding application that this document was submitted with</description>
    <label>Onboarding Application</label>
    <referenceTo>Onboarding_Application__c</referenceTo>
    <relationshipLabel>Application Documents</relationshipLabel>
    <relationshipName>Application_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Company_Industry__c.field-meta.xml
<CustomField>
    <fullName>Company_Industry__c</fullName>
    <description>OneHub: This field is used to store the Company Industry which is used to personalise the users News on their dashboard. (US-4589)</description>
    <label>Company Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Business Services and Consulting</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Manufacturing and Construction</fullName>
            </value>
            <value>
                <fullName>Marketing and Communications</fullName>
            </value>
            <value>
                <fullName>Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Oil and Gas</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Wholesale/Retail Trade</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Role_s_at_Client__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role_s_at_Client__c</fullName>
    <description>The functional role(s) performed by the Client Contact in dealing with Standard Bank. C-00000333</description>
    <inlineHelpText>The functional role(s) performed by the Client Contact in dealing with Standard Bank</inlineHelpText>
    <label>Contact Role(s) at Client</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved Dealer</fullName>
            </value>
            <value>
                <fullName>Authorised Person</fullName>
            </value>
            <value>
                <fullName>CC Survey Contact</fullName>
            </value>
            <value>
                <fullName>CommB Survey Contact</fullName>
            </value>
            <value>
                <fullName>Direct Shareholder</fullName>
            </value>
            <value>
                <fullName>GM Survey Contact</fullName>
            </value>
            <value>
                <fullName>Group KYC Contact</fullName>
            </value>
            <value>
                <fullName>IB Survey Contact</fullName>
            </value>
            <value>
                <fullName>Indirect Shareholder</fullName>
            </value>
            <value>
                <fullName>KYC Contact</fullName>
            </value>
            <value>
                <fullName>Pricing Contact</fullName>
            </value>
            <value>
                <fullName>Primary GM Research Contact</fullName>
            </value>
            <value>
                <fullName>TPS Survey Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Identity_Number__c.field-meta.xml
<CustomField>
    <fullName>Identity_Number__c</fullName>
    <description>Digital Onboarding: This field stores the Authorised Person&apos;s ID number and is used by the KYC Consultants during the KYC Process. This field is only visible to the Custom KYC User Profile and the Onboarding API profile.</description>
    <label>Identity Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OSB_Community_Access_Manager__c.field-meta.xml
<CustomField>
    <fullName>OSB_Community_Access_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OneHub: This field is used to store who the Authorised Person or Designated Person is that sent the user an invite to sign up for the OneHub Community. (US-4589)</description>
    <inlineHelpText>Contact that is responsible for the access for the OneHub community</inlineHelpText>
    <label>Community Access Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Community Access manager</relationshipLabel>
    <relationshipName>Community_access_manager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OSB_Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>OSB_Passport_Number__c</fullName>
    <description>OneHub: This field stores the Community users Passport Number. (US-4589)</description>
    <inlineHelpText>Clients Passport Number</inlineHelpText>
    <label>Passport Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ping_Id__c.field-meta.xml
<CustomField>
    <fullName>Ping_Id__c</fullName>
    <description>OneHub: Ping Integration Identity Number. (US-4589)</description>
    <externalId>true</externalId>
    <inlineHelpText>Used for the Ping Integration</inlineHelpText>
    <label>Ping ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Onboarding_Application__c/Onboarding_Application__c.object-meta.xml
<CustomObject>
    <description>Digitization - Client Onboarding. This object stores the client initiated request to onboard an entity</description>
    <label>Onboarding Application</label>
    <nameField>
        <displayFormat>OA-{000000000}</displayFormat>
        <label>Onboarding Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding_Application__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The (prospectiive) client record that has been submitted through the client experience portal for onboarding</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Onboarding Applications</relationshipLabel>
    <relationshipName>Onboarding_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SEL_Contacts_TEST.cls
/**
 *  Test class for SEL_Contacts.
 *
 * @author		Youssef Ibrahim (yibrahim@deloittece.com)
 * @date		December 2020
*/
@IsTest
private class SEL_Contacts_TEST {

    @IsTest
    static void shouldSelectById() {
        SEL_Contacts.newInstance().selectById(new Set<Id>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Id IN: idSet'));
    }

    @IsTest
    static void shouldSelectAuthorisedPersonByAccountId() {
        SEL_Contacts.newInstance().selectAuthorisedPersonByAccountId(new Set<Id>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Contact_Role_s_at_' +
                'Client__c includes (\'Authorised Person\') and AccountId in :idSet'));
    }

    @IsTest
    static void shouldSelectKYCContactByAccountId() {
        SEL_Contacts.newInstance().selectKYCContactByAccountId(new Set<Id>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Contact_Role_s_at_Client__c' +
                ' includes (\'KYC Contact\',\'GROUP KYC Contact\') and AccountId in :idSet'));
    }

    @IsTest
    static void shouldSelectByUserId() {
        SEL_Contacts.newInstance().selectByUserId(new Set<Id>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Id IN (SELECT ContactId FROM ' +
                'User WHERE Id IN :ids)'));
//        System.assert(result.getSelectedFields().contains('OSB_Community_Access_Manager__r.name'));
    }

    @IsTest
    static void shouldSelectByEmailIdentityPassport() {
        SEL_Contacts.newInstance().selectByEmailIdentityPassport(new Set<String>(),
                new Set<String>(), new Set<String>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Email IN :emails AND (Identity_Number__c IN' +
                ' :idNumbers OR OSB_Passport_Number__c IN :passportNumbers)'));
    }

    @IsTest
    static void shouldSelectByIdentityNumber() {
        SEL_Contacts.newInstance().selectByIdentityNumber(new Set<String>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Identity_Number__c IN: IdentityNumbers'));
    }

    @IsTest
    static void shouldSelectByOneHubManager() {
        SEL_Contacts.newInstance().selectByOneHubManager(new Set<Id>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('OSB_Community_Access_Manager__c in :idSet'));
    }

    @IsTest
    static void shouldSelectByFirstNameLastNameEmail() {
        SEL_Contacts.newInstance().selectByFirstNameLastNameEmail(new Set<String>(), new Set<String>(), new Set<String>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('(FirstName IN: firstNames AND LastName' +
                ' IN: lastNames AND Email IN: emails)'));
    }

    @IsTest
    static void shouldSelectByNameEmailPingId() {
        SEL_Contacts.newInstance().selectByNameEmailPingId(new Set<String>(), new Set<String>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Name IN: names AND Email IN:' +
                ' emails AND Ping_Id__c !=null '));
    }

    @IsTest
    static void shouldSelectByIndustryUserId() {
        SEL_Contacts.newInstance().selectByIndustryUserId(new Set<Id>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Id IN (SELECT ContactId ' +
                'FROM User WHERE Id IN :ids) AND Company_Industry__c !=null'));
    }

    @IsTest
    static void shouldSelectByIdWoSharing() {
        SEL_Contacts.newInstance().selectByIdWoSharing(new Set<Id>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Id IN: idSet'));
    }

    @IsTest
    static void shouldSelectByIdentityNumberWoSharing() {
        SEL_Contacts.newInstance().selectByIdentityNumberWoSharing(new Set<String>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Identity_Number__c IN: IdentityNumbers'));
    }

    @IsTest
    static void shouldSelectByUserIdWoSharing() {
        SEL_Contacts.newInstance().selectByUserIdWoSharing(new Set<Id>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Id IN (SELECT ContactId FROM ' +
                'User WHERE Id IN :ids)'));
    }

    @IsTest
    static void shouldSelectByIndustryUserIdWoSharing() {
        SEL_Contacts.newInstance().selectByIndustryUserIdWoSharing(new Set<Id>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Id IN (SELECT ContactId FROM User WHERE Id ' +
                'IN :ids) AND Company_Industry__c !=null'));
    }

    @IsTest
    static void shouldSelectByNameEmailPingIdWoSharing() {
        SEL_Contacts.newInstance().selectByNameEmailPingIdWoSharing(new Set<String>(), new Set<String>());
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Name IN: names AND Email IN: emails ' +
                'AND Ping_Id__c !=null '));
    }
    @IsTest
    static void shouldSelectByClientId() {
        Test.startTest();
        SEL_Contacts.newInstance().selectByClientId(new Set<Id>());
        Test.stopTest();
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('AccountId IN: clientId'));
    }
    @IsTest
    static void shouldSelectByOnboardAppId() {
        Test.startTest();
        SEL_Contacts.newInstance().selectByOnboardAppId(new Set<Id>());
        Test.stopTest();
        fflib_QueryFactory result = fflib_QueryFactory.lastQueryFactory;
        System.assert(result.getCondition().containsIgnoreCase('Id IN (SELECT Authorised_Person__c FROM Application_Document__c WHERE '+
                'Onboarding_Application__c IN:onboardId and Document_Status__c=:statusPending)'));
    }
}