force-app/main/default/objects/Client_Plan__c/Client_Plan__c.object-meta.xml
<CustomObject>
    <label>Client Plan</label>
    <nameField>
        <label>Client Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Plan__c/fields/Can_be_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Can_be_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can be Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Plan__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <description>Field that stores Client Plan object relationship with Client Object</description>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Plan</relationshipLabel>
    <relationshipName>Client_Plan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Plan__c/fields/Client_Plan_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Plan_Status__c</fullName>
    <label>Client Plan Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Reviewed</fullName>
                <default>true</default>
                <label>To Be Reviewed</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Plan__c/fields/Current_CC_Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Current_CC_Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current CC Line Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Plan1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BLD_ClientPlan.cls
@IsTest
public without sharing class BLD_ClientPlan  extends ABS_ObjectBuilderBase {
	
	public BLD_ClientPlan() { 
		this(getNewUnitOfWork());        
	}

    public BLD_ClientPlan(Client_Plan__c plan){
        this(plan, getNewUnitOfWork()); 
    }

    public BLD_ClientPlan(fflib_SObjectUnitOfWork workUnit) { 
        super(Client_Plan__c.SObjectType, workUnit);
    }

    private BLD_ClientPlan(Client_Plan__c sObj, fflib_SObjectUnitOfWork workUnit) {
        super(sObj,workUnit);
    }

    protected override void setDefaultData(){
       setField(Client_Plan__c.Client_Plan_Status__c, DMN_ClientPlan.SUBMITTED);
    }

    public BLD_ClientPlan currencyIsoCode(String code){
       return (BLD_ClientPlan) setField(Client_Plan__c.CurrencyIsoCode, code);
    }

    public BLD_ClientPlan status(String status){
        return (BLD_ClientPlan) setField(Client_Plan__c.Client_Plan_Status__c, status);
    }

    public BLD_ClientPlan canBeSubmitted(Boolean submitted){
        return (BLD_ClientPlan) setField(Client_Plan__c.Can_be_Submitted__c, submitted);
    }

    public BLD_ClientPlan currentCcLineManager(Id managerUserId){
        return (BLD_ClientPlan) setField(Client_Plan__c.Current_CC_Line_Manager__c, managerUserId);
    }
    
    public BLD_ClientPlan account(ABS_ObjectBuilderBase accountBld){
        return (BLD_ClientPlan) setRelation(Client_Plan__c.Client_Name__c, accountBld); 
    }

    public BLD_ClientPlan approve(){
    	return (BLD_ClientPlan)setField(Client_Plan__c.Client_Plan_Status__c, DMN_ClientPlan.APPROVED)
    	.setField(Client_Plan__c.Can_be_Submitted__c, false)
    	.setField(Client_Plan__c.Approved_By__c, UserInfo.getUserId());
    }
}