force-app/main/default/objects/Child_products__c/Child_products__c.object-meta.xml
<CustomObject>
    <description>Custom object created to cater for child knowledge articles used within the OneHub digital experience (SFP-5118)</description>
    <label>Child Products</label>
    <nameField>
        <label>Child products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Child Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_products__c/fields/Introduction__c.field-meta.xml
<CustomField>
    <fullName>Introduction__c</fullName>
    <description>OneHub: This field is used to store the description and information about the API Product, Solution and Insights</description>
    <inlineHelpText>Description for the Solution, API Product and Insight</inlineHelpText>
    <label>Introduction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Child_products__c/fields/Knowledge_Parent__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the parent product in knowledge (SFP-5118)</description>
    <inlineHelpText>Parent knowledge article to child product</inlineHelpText>
    <label>Knowledge Parent</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Child Products</relationshipLabel>
    <relationshipName>APIs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_products__c/fields/Sign_Up_URL__c.field-meta.xml
<CustomField>
    <fullName>Sign_Up_URL__c</fullName>
    <description>URL used for retrieving the swagger document in OneHub (SFP-5118)</description>
    <inlineHelpText>URL for the swagger document relating to the API ID in APIC</inlineHelpText>
    <label>Sign Up URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Child_products__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the child product</description>
    <inlineHelpText>Title for the product</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Child_products__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>OneHub: This field stores the Product ID from the API Portal to generate the swagger. (SFP-5118)</description>
    <inlineHelpText>URL to generate API Detail page with Swagger</inlineHelpText>
    <label>Product ID</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SEL_ChildProducts.cls
/**
 * Selector class for Child_products__c SObject
 *
 * @author Wayde Fagan (Wayde.fagan@tetrad.co.za)
 * @date March 2021
 */
public inherited sharing class SEL_ChildProducts extends fflib_SObjectSelector {
	/**
     * Creates a new instance of the selector via the application class. This is here to allow unit tests to override
     * and inject a mock instead of this class or to switch out this class for a new version.
     * @return new instance of the class SEL_ChildProducts
     */
    public static SEL_ChildProducts newInstance() {
        return (SEL_ChildProducts) ORG_Application.selector
                .newInstance(Child_products__c.SObjectType);
    }

    /**
     * Returns the SObject type for the selector. This is used to retrieve the sObject name when building the SOQL
     * queries.
     * 
     * @return Child_products__c object type
     */
    public SObjectType getSObjectType() {
        return Child_products__c.SObjectType;
    }
    
    /**
     * Returns the sObject fields in Child_products__c
     * 
     * @return Child_products__c object list
     */
    public List<SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Child_products__c.Id,
            Child_products__c.Name,
            Child_products__c.Knowledge_Parent__c,
            Child_products__c.Introduction__c,
            Child_products__c.Sign_Up_URL__c,
            Child_products__c.URL__c, 
            Child_products__c.Title__c
        };
    }
    
    /**
     * Searches for specified Knowledge ids (Onehub)
     *
     * @param masterKnowledge set of contacts
     *
     * @return list of Child_products__c
     */
    public List<Child_products__c> selectByParentProduct(Set<Id> masterKnowledge) {
        return Database.query(
                newQueryFactory(false, false, true)
                .setCondition('Knowledge_Parent__c IN :masterKnowledge')
                .toSOQL()
        );
    }
    
    /**
     * Calls method selectContactByNameEmailPingId in without sharing context
     * 
     * @param masterKnowledge set of knowledge article ids
     *
     * @return selectByParentProduct without sharing
     */
    public List<Child_products__c> selectByParentProductWoSharing(Set<Id> masterKnowledge) {
        return new WithoutSharing().selectByParentProduct(this, masterKnowledge);
    }
    
    /**
     * Is used for omitting sharing setting, when needed
     */
    private without sharing class WithoutSharing {

        /**
        * Returns list of Child_products__c by id without sharing
        *
        * @param selProducts selProducts selector instance
        * @param masterKnowledge Set<Id> set of ids
        *
        * @return list of selected Child_products__c
        */
        public List<Child_products__c> selectByParentProduct(SEL_ChildProducts selProducts, Set<Id> masterKnowledge ) {
            return selProducts.selectByParentProduct(masterKnowledge);
        }
        
    }
}