force-app/main/default/objects/Calendar_Content__c/Calendar_Content__c.object-meta.xml
<CustomObject>
    <label>Calendar Content</label>
    <nameField>
        <label>Calendar Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_Content__c/fields/Calendar_Type__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Type__c</fullName>
    <label>Calendar Type</label>
    <referenceTo>Calendar_Type__c</referenceTo>
    <relationshipLabel>Calendar Contents</relationshipLabel>
    <relationshipName>Calendar_Contents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Calendar_Content__c/fields/Event_Legend_Field__c.field-meta.xml
<CustomField>
    <fullName>Event_Legend_Field__c</fullName>
    <label>Event Legend Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Content__c/fields/Event_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Object_Name__c</fullName>
    <description>The name of the object used as base for this calendar</description>
    <label>Event Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Content__c/fields/Event_Start_Field__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Field__c</fullName>
    <description>Case 4740 Shared Calendar 08/2012: Indicates which field on the object represents the start date field for events</description>
    <label>Event Start Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Content__c/fields/Event_Title_Field__c.field-meta.xml
<CustomField>
    <fullName>Event_Title_Field__c</fullName>
    <description>Case 4740 Shared Calendar 08/2012: Indicates which field on the object represents the Title field for events</description>
    <label>Event Title Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Content__c/fields/Hierarchy_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Object_Name__c</fullName>
    <label>Hierarchy Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Content__c/fields/Hierarchy_Relation_Field__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Relation_Field__c</fullName>
    <description>This field is used identify the hierarchy field to enable filter records for the client hierarchy / campagin hierarchy</description>
    <label>Hierarchy Relation Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Legend__c/Calendar_Legend__c.object-meta.xml
<CustomObject>
    <label>Calendar Legend</label>
    <nameField>
        <label>Calendar Legend Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Legends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_Legend__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <description>Used to set the background color for calendar legend and items</description>
    <label>Background Color</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Legend__c/fields/Calendar_Content__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Content__c</fullName>
    <label>Calendar Content</label>
    <referenceTo>Calendar_Content__c</referenceTo>
    <relationshipLabel>Calendar Legend Items</relationshipLabel>
    <relationshipName>Calendar_Legend_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Calendar_Type__c/Calendar_Type__c.object-meta.xml
<CustomObject>
    <description>Used to set the object the Shared Calender is Related to</description>
    <label>Calendar Type</label>
    <nameField>
        <label>Calendar Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CalendarLegend_pageTest.cls
/*************************************************************************
    @ Author        : Petr Svestka
    @ Date          : 21/7/2015
    @ Description   : Force.com reviewer - Blocker and Critical issues - 20150608.xlsx
****************************************************************************/

@isTest
public with sharing class CalendarLegend_pageTest {

    @testSetup
    public static void setUp() {
        Calendar_Type__c testCalType = new Calendar_Type__c();
        testCalType.Name = 'Client';
        insert testCalType;

        List<Calendar_Content__c> calCons = new List<Calendar_Content__c>();

        Calendar_Content__c testCalContent1 = new Calendar_Content__c();
        testCalContent1.Name = 'Client Events';
        testCalContent1.Event_Start_Field__c = 'Start';
        testCalContent1.Event_Title_Field__c = 'Subject';
        testCalContent1.Event_Legend_Field__c = 'Meeting_Purpose__c';
        testCalContent1.Event_Object_Name__c = 'Event';
        testCalContent1.Hierarchy_Object_Name__c = 'Account';
        testCalContent1.Hierarchy_Relation_Field__c = 'ParentId';
        testCalContent1.Calendar_Type__c = testCalType.Id;
        calCons.add(testCalContent1);

        insert calCons;

        List<Calendar_Legend__c> calLegs = new List<Calendar_Legend__c>();

        Calendar_Legend__c calLegend1 = new Calendar_Legend__c();
        calLegend1.Name = 'Day To Day Meeting';
        calLegend1.Background_Color__c = 'gray';
        calLegend1.Calendar_Content__c = testCalContent1.Id;
        calLegs.add(calLegend1);

        Calendar_Legend__c calLegend2 = new Calendar_Legend__c();
        calLegend2.Name = 'Core Client Team Meeting';
        calLegend2.Background_Color__c = 'green';
        calLegend2.Calendar_Content__c = testCalContent1.Id;
        calLegs.add(calLegend2);

        insert calLegs;
    }

    public static testMethod void test() {
        CalendarLegend_page cont = new CalendarLegend_page();

        // fetch pick-list values for Event.Meeting_Purpose__c
        Map<String, Schema.sObjectType> mapToken_SObjects = Schema.getGlobalDescribe();
        Map<String, Schema.sObjectField> mapToken_Fields = mapToken_SObjects.get('Event').getDescribe().fields.getMap();
        Schema.DescribeFieldResult F = mapToken_Fields.get('Meeting_Purpose__c').getDescribe();

        List<Schema.PicklistEntry> meetingTypeValues = F.getPicklistValues();

        // expected pairs
        Map<String, String> expectedColors = new Map<String, String>{
            null => '#FF0000'
        };
        for (Schema.PicklistEntry meetingType: meetingTypeValues) {
            if (meetingType.getLabel() != 'Day To Day Meeting' && meetingType.getLabel() != 'Core Client Team Meeting') {
                expectedColors.put(meetingType.getLabel(), '#FF0000');
            }
        }
        expectedColors.put('Day To Day Meeting', 'gray');
        expectedColors.put('Core Client Team Meeting', 'green');

        Test.startTest();

        List<CalendarLegend_page.eventTypeClass> eventTypes = cont.eventType;

        system.assertEquals(expectedColors.keySet().size(), eventTypes.size(), 'Unexpected number of background color items');

        for (CalendarLegend_page.eventTypeClass et: eventTypes) {
            system.assert(expectedColors.containsKey(et.typeOfEvent), 'Unexpected meeting type returned');
            system.assertEquals(expectedColors.get(et.typeOfEvent), et.backgroundColor, 'Unexpected background color returned for ' + et.typeOfEvent);
        }

        Map<String, String> expectedColorsInDb = new Map<String, String>{
            'Day To Day Meeting' => 'gray',
            'Core Client Team Meeting' => 'green'
        };
        for (Schema.PicklistEntry meetingType: meetingTypeValues) { // without null
            if (!expectedColorsInDb.containsKey(meetingType.getLabel())) {
                expectedColorsInDb.put(meetingType.getLabel(), 'Black');
            }
        }

        for (List<Calendar_Legend__c> pairs: [SELECT name
                                                    ,Background_Color__c
                                                FROM Calendar_Legend__c
                                               WHERE name IN :expectedColorsInDb.keySet()]) {
            for (Calendar_Legend__c pair: pairs) {
                system.assertEquals(expectedColorsInDb.get(pair.name), pair.Background_Color__c, 'Unexpected background color found in database for ' + pair.name);
            }
        }

        Test.stopTest();
    }
}