force-app/main/default/objects/AOB_ReferencedData__c/AOB_ReferencedData__c.object-meta.xml
<CustomObject>
    <label>Referenced Data</label>
    <nameField>
        <label>Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenced Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/AOB_ReferencedData__c/fields/AOB_SAPField__c.field-meta.xml
<CustomField>
    <fullName>AOB_SAPField__c</fullName>
    <description>Sap Field Name</description>
    <label>MRI Table</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AOB_CTRL_ACPicklist.cls
/**
 * @description       : This function will 
 * @author            : Chibuye Kunda
 * @group             : 
 * @last modified on  : 10-14-2021
 * @last modified by  : Chibuye Kunda
**/
public with sharing class AOB_CTRL_ACPicklist {
    /**
    * @description This function will search for potential matches
    * @param    String label can be one of these values
    * @return List<AOB_ReferencedData__c> 
    **/
    @AuraEnabled
    public static List<AOB_ReferencedData__c> loadData(String targetValue){
        List<AOB_ReferencedData__c> referenceDataList;

        try{
            referenceDataList = [SELECT Id, Name
                                 FROM AOB_ReferencedData__c
                                 WHERE (AOB_SapField__c=:targetValue)
                                 WITH SECURITY_ENFORCED
                                 ORDER BY Name];
        }
        catch(QueryException exp){
            throw new AuraHandledException(exp.getMessage());
        }
        
        return referenceDataList;
    }
}