force-app/main/default/objects/Product_Distribution__c/Product_Distribution__c.object-meta.xml
<CustomObject>
    <description>Advisory Product Distribution</description>
    <label>Product Distribution</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Product Distribution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Distribution__c/fields/Bank_Role__c.field-meta.xml
<CustomField>
    <fullName>Bank_Role__c</fullName>
    <description>Selection of SB&apos;s role and corresponding titles in the transaction. SGPRT-624</description>
    <inlineHelpText>Selection of SB&apos;s role and corresponding titles in the transaction.</inlineHelpText>
    <label>Bank Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Distribution__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>SB_Product__c</referenceTo>
    <relationshipLabel>Product Distributions</relationshipLabel>
    <relationshipName>Product_Distributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/SB_Product__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Products as Standard Bank have requirements that cannot be met with standard object.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Prod-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SB_Product__c/fields/Bank_Role__c.field-meta.xml
<CustomField>
    <fullName>Bank_Role__c</fullName>
    <description>Selection of SB&apos;s role and corresponding titles in the transaction.</description>
    <inlineHelpText>Selection of SB&apos;s role and corresponding titles in the transaction.</inlineHelpText>
    <label>Bank Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Bookrunner</fullName>
            </value>
            <value>
                <fullName>Co-Lead Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Debt Advisor</fullName>
            </value>
            <value>
                <fullName>Equity Provider</fullName>
            </value>
            <value>
                <fullName>Joint Lead Arranger</fullName>
            </value>
            <value>
                <fullName>JSE Sponsor</fullName>
            </value>
            <value>
                <fullName>Lead Manager</fullName>
            </value>
            <value>
                <fullName>Lender</fullName>
            </value>
            <value>
                <fullName>Main Lead Arranger</fullName>
            </value>
            <value>
                <fullName>Underwriter</fullName>
            </value>
            <value>
                <fullName>Sole Mandated Lead Arranger</fullName>
            </value>
            <value>
                <fullName>Joint Mandated Lead Arranger</fullName>
            </value>
            <value>
                <fullName>Sole Bookrunner</fullName>
            </value>
            <value>
                <fullName>Joint Bookrunner</fullName>
            </value>
            <value>
                <fullName>Sole Debt Underwriter</fullName>
            </value>
            <value>
                <fullName>Joint Debt Underwriter</fullName>
            </value>
            <value>
                <fullName>Facility Agent</fullName>
            </value>
            <value>
                <fullName>Security Agent</fullName>
            </value>
            <value>
                <fullName>Sole Lead Arranger</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Debt Coordinator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DMN_Product_Distribution.cls
/**
 * Domain class for Product Distribution object.
 * <br/>SGPRT-624
 *
 * @author Joanna Milosz (jmilosz@deloittece.com)
 * @date March 2021
 */
public with sharing class DMN_Product_Distribution {
    public static final String BANK_ROLE_TRANSFERRED = 'Transferred';

    /**
    * Method to populate Bank Role field on Product Distribution upon creation.
    * SGPRT-624
    * @param productDistributions list of new Product Distribution records.
    */
    public static void populateBankRole(List<Product_Distribution__c> productDistributions) {
        Set<Id> parentIds = new Set<Id>();
        for (Product_Distribution__c pd : productDistributions){
            parentIds.add(pd.Product__c);
        }

        SEL_Products selProds = SEL_Products.newInstance();
        List<SB_Product__c> parentProductsList = selProds.selectById(parentIds);
        Map<Id, SB_Product__c> parentProducts = new Map<Id, SB_Product__c>(parentProductsList);

        for (Product_Distribution__c pd : productDistributions){
                pd.Bank_Role__c = parentProducts.get(pd.Product__c).Bank_Role__c;
        }
    }
}