force-app/main/default/objects/Business_Assessment__c/Business_Assessment__c.object-meta.xml
<CustomObject>
    <label>Business Assessment</label>
    <nameField>
        <displayFormat>BA{0000000}</displayFormat>
        <label>Business Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Assessment__c/recordTypes/NBAC.recordType-meta.xml
<RecordType>
    <fullName>NBAC</fullName>
    <active>true</active>
    <description>US-2450</description>
    <label>NBAC</label>
</RecordType>

force-app/main/default/objects/Credit_Risk_Appetite__c/Credit_Risk_Appetite__c.object-meta.xml
<CustomObject>
    <description>US:1931 DM - Risk Appetite information</description>
    <label>Credit Risk Appetite</label>
    <nameField>
        <label>Credit Risk Appetite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Risk Appetites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Risk_Appetite__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Risk Appetite measured Country from PMRC process in Credit Risk</description>
    <inlineHelpText>Country where Credit Appetite is being measured</inlineHelpText>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Risk_Appetite__c/fields/Country_Credit_Appetite__c.field-meta.xml
<CustomField>
    <fullName>Country_Credit_Appetite__c</fullName>
    <description>Risk Appetite Status of the Country / Sector / Sub-Sector from the monthly PMRC process</description>
    <inlineHelpText>Status shows current credit appetite for the given Country / Sector / Sub-Sector. 
Add – Add exposure,
Add ST – Add exposure, subject to certain specific criteria defined by PRMC, 
Hold – Keep exposure at current levels,
Reduce – Reduce exposure.</inlineHelpText>
    <label>Country / Sector / Sub-Sector Credit App</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Add ST</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Reduce</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Risk_Appetite__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <description>Risk Appetite Sector from PMRC process</description>
    <inlineHelpText>Industry sector as per Standard Bank Client Sectors where the Risk Status is allocated to</inlineHelpText>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Industrials</fullName>
            </value>
            <value>
                <fullName>Internal / Grouped</fullName>
            </value>
            <value>
                <fullName>Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Oil and Gas</fullName>
            </value>
            <value>
                <fullName>Power and Infrastructure</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Sovereign / Public Sector</fullName>
            </value>
            <value>
                <fullName>Telecoms and Media</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Risk_Appetite__c/fields/Sector_Credit_Appetite__c.field-meta.xml
<CustomField>
    <fullName>Sector_Credit_Appetite__c</fullName>
    <description>Risk Appetite Status of the Sector from the monthly PMRC process</description>
    <inlineHelpText>Status shows current risk appetite for the given Sector.
Add – Add exposure,
Add ST – Add exposure, subject to certain specific criteria defined by PRMC,
Hold – Keep exposure at current levels,
Reduce – Reduce exposure.</inlineHelpText>
    <label>Sector Credit Appetite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Add ST</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Reduce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Risk_Appetite__c/fields/Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sector__c</fullName>
    <description>Risk Appetite Sub-Sector from PMRC process in Credit Risk</description>
    <inlineHelpText>Industry sub-sector as per Standard Bank Client Sub-Sectors where the Credit Appetite is allocated to</inlineHelpText>
    <label>Sub-Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Agriculture Commodity Traders</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Alternative Investment Vehicles</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automobiles</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Brokers and Exchanges</fullName>
            </value>
            <value>
                <fullName>Bulk Commodities</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Central Banks</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Construction Services</fullName>
            </value>
            <value>
                <fullName>Consumer Services</fullName>
            </value>
            <value>
                <fullName>Development Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Diamonds</fullName>
            </value>
            <value>
                <fullName>Diversified Industrials</fullName>
            </value>
            <value>
                <fullName>Diversified Mining</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equipment Manufacturers</fullName>
            </value>
            <value>
                <fullName>Food and Beverage</fullName>
            </value>
            <value>
                <fullName>Forestry</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Government Departments</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hotel and Leisure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestLightningSharing.cls
@IsTest
private class TestLightningSharing {

    private static final String TEST_USER_NAME = 'stdBank@nbac.com';
    private static final String TEST_ADMIN_USER_NAME = 'stdBankAdmin@nbac.com';

    @IsTest
    static void testSOSL() {
        String result = LightningSharing.doSOSL('McLaughlin', 'Lead');
        System.assertNotEquals(null, result);
    }

    @IsTest
    static void testReturning() {
        string uq = LightningSharing.getReturning('User');
        system.assertEquals(uq, 'User(Id, Name, UserType WHERE UserType in (\'Standard\', \'PowerCustomerSuccess\', \'PowerPartner\'))');
        uq = LightningSharing.getReturning('Group');
        system.assertEquals(uq, 'Group(Id, Name, Type)');
        uq = LightningSharing.getReturning('Custom__c');
        system.assertEquals(uq, 'Custom__c(Id, Name)');
        uq = LightningSharing.getReturning('Lead');
        system.assertEquals(uq, 'Lead(Id, Name)');
  }

    @IsTest
    static void testUserTypes() {
        LightningSharing.huh('PowerCustomerSuccess');
        LightningSharing.huh('PowerPartner');
        LightningSharing.huh('CustomerSuccess');
        LightningSharing.huh('CsnOnly');
        LightningSharing.huh('CSPLitePortal');
        System.assertEquals('MadeUpStuff', LightningSharing.huh('MadeUpStuff'));
  }

    @IsTest
    static void testInnerClass(){
        LightningSharing.sharingHolder sh = new LightningSharing.sharingHolder();
        sh.UserOrGroupName = 'test';
        sh.SubType = 'test';
        sh.UserOrGroupType = 'test';
        sh.UserOrGroupID = 'test';
        sh.AccessLevel = 'test';
        sh.RowCause = 'test';

        system.assertEquals(sh.UserOrGroupName, 'test');
        system.assertEquals(sh.SubType, 'test');
        system.assertEquals(sh.UserOrGroupType, 'test');
        system.assertEquals(sh.UserOrGroupID, 'test');
        system.assertEquals(sh.AccessLevel, 'test');
        system.assertEquals(sh.RowCause, 'test');
  }

    @IsTest
    static void testGetSharings() {
        try {
            list<lead> l = [select id from lead];
            LightningSharing.getSharings(l[0].id);
            list<Opportunity> o = [select id from Opportunity];
            LightningSharing.getSharings(o[0].id);
            list<Business_Assessment__c> ptos = [select id from Business_Assessment__c];
            list<Credit_Risk_Appetite__c> rotos = [select id from Credit_Risk_Appetite__c];
            LightningSharing.getSharings(ptos[0].id);
            LightningSharing.getSharings(rotos[0].id);
        }
        catch (Exception ex) {
            System.assert(false, ex.getMessage());
        }
  }

    @IsTest
    static void testCanIEditPermsAdmin() {
        list<lead> l = [select id from lead];
        LightningSharing.canIEditPerms(l[0].id);

        list<Business_Assessment__c> ptos = [select id from Business_Assessment__c];
        list<Credit_Risk_Appetite__c> rotos = [select id from Credit_Risk_Appetite__c];

        boolean perm = LightningSharing.canIEditPerms(ptos[0].id);
        system.assertEquals(perm, true);
        perm = LightningSharing.canIEditPerms(rotos[0].id);
        system.assertEquals(perm, true);
    }

    @IsTest
    static void testCanIEditPermsAdminNonOwner() {
        list<Business_Assessment__c> ptos = [select id from Business_Assessment__c];
        list<Credit_Risk_Appetite__c> rotos = [select id from Credit_Risk_Appetite__c];
        user u = getAdminUser();
        boolean perm1;
        boolean perm2;

        system.runAs(u){
          perm1 =LightningSharing.canIEditPerms(ptos[0].id);
          perm2 =LightningSharing.canIEditPerms(rotos[0].id);
        }

        system.assertEquals(perm1, true);
        system.assertEquals(perm2, true);
  }

    @IsTest
    static void testDelete() {
        try {
            list<Business_Assessment__c> ptos = [select Id from Business_Assessment__c];
            user u = getUsers()[0];
            LightningSharing.upsertPerm(u.id, ptos[0].id, 'Edit');
            LightningSharing.deletePerm(u.id, ptos[0].id);
        }
        catch (Exception ex) {
            System.assert(false, ex.getMessage());
        }
  }

    @IsTest
    static void testUpsertPerm() {
        list<Opportunity> o = [select id from Opportunity];
        list<lead> l = [select id from Lead];
        list<Business_Assessment__c> ptos = [select id from Business_Assessment__c];
        list<Credit_Risk_Appetite__c> rotos = [select id from Credit_Risk_Appetite__c];
        user u = getUsers()[0];
        try {
            LightningSharing.upsertPerm(u.id, ptos[0].id, 'Edit');
            LightningSharing.upsertPerm(u.id, ptos[0].id, 'Read');
            LightningSharing.upsertPerm(u.id, ptos[0].id, 'Edit');
            LightningSharing.getSharings(ptos[0].id);
            LightningSharing.deletePerm(u.id, ptos[0].id);
            LightningSharing.upsertPerm(u.id, rotos[0].id, 'Edit');
            LightningSharing.getSharings(rotos[0].id);
            LightningSharing.deletePerm(u.id, rotos[0].id);
        }
        catch (Exception ex) {
            System.assert(false, ex.getMessage());
        }

  	try {
  		LightningSharing.upsertPerm(u.id, o[0].id, 'Edit');
  		LightningSharing.deletePerm(u.id, o[0].id);
  	} catch (exception e){
  		//ok, sharing may not be on
  		system.debug(e);
  	}

  	try {
  		LightningSharing.upsertPerm(u.id, o[0].id, 'Read');
  		LightningSharing.deletePerm(u.id, o[0].id);
  	} catch (exception e){
  		system.debug(e);
  		//ok, sharing may not be on
  	}

  	try {
  		LightningSharing.upsertPerm(u.id, l[0].id, 'Edit');
  		LightningSharing.deletePerm(u.id, l[0].id);
  	} catch (exception e){
  		//ok, sharing may not be on
  		system.debug(e);
  	}

  	try {
  		LightningSharing.upsertPerm(u.id, l[0].id, 'Read');
  		LightningSharing.deletePerm(u.id, l[0].id);
  	} catch (exception e){
  		system.debug(e);
  		//ok, sharing may not be on
  	}
  }

    @IsTest
    static void testStringStuff(){
        try {
            LightningSharing.getLookupField('Account');
            LightningSharing.getAccessLevelField('Account');
            LightningSharing.getSharingTableName('Account');
            LightningSharing.getLookupField('Custom__c');
            LightningSharing.getAccessLevelField('Custom__c');
            LightningSharing.getSharingTableName('Custom__c');
        }
        catch (Exception ex) {
            System.assert(false, ex.getMessage());
        }
  }

    @IsTest
    static void testBuildQuery(){
        list<lead> l = [select id from lead];
        String query = LightningSharing.buildQuery(l[0].id);
        System.assertNotEquals(null, query);
  }

    @IsTest
    static void testCanIEditPermsNonAdmin() {
        List<Business_Assessment__c> ptos = [select id from Business_Assessment__c];
        List<Credit_Risk_Appetite__c> rotos = [select id from Credit_Risk_Appetite__c];
        List<user> users = getUsers();
        LightningSharing.upsertPerm(users[0].id, ptos[0].id, 'Edit');
        LightningSharing.upsertPerm(users[0].id, rotos[0].id, 'Edit');
        System.RunAs(users[0]){
            System.assertEquals(LightningSharing.canIEditPerms(ptos[0].id), false);
            System.assertEquals(LightningSharing.canIEditPerms(rotos[0].id), false);
        }
    }

    @IsTest
    static void testGroupStuff() {
        List<group> groups = [select id from group where Name = 'the knights who say nee'];
        List<lead> l = [select id from lead];
        List<Business_Assessment__c> ptos = [select id from Business_Assessment__c];
        List<Credit_Risk_Appetite__c> rotos = [select id from Credit_Risk_Appetite__c];
        List<user> users = getUsers();
        List<GroupMember> gms = new list<GroupMember>();
        gms.add(new GroupMember(GroupId=groups[0].id, UserOrGroupId=users[0].id));
        gms.add(new GroupMember(GroupId=groups[0].id, UserOrGroupId=users[1].id));
        insert gms;

        Test.startTest();
            try {
                System.RunAs(getAdminUser()) {
                    LightningSharing.upsertPerm(groups[0].id, ptos[0].id, 'Read');
                    LightningSharing.getSharings(l[0].id);
                    LightningSharing.getSharings(ptos[0].id);
                    LightningSharing.getSharings(rotos[0].id);
                }
            }
            catch (Exception ex) {
                System.assert(false, ex.getMessage());
            }
        Test.stopTest();
    }

  @testSetup static void makeData(){

    fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
    System.runAs(new User(Id = UserInfo.getUserId())){
            
            new BLD_USER(uow).userName(TEST_ADMIN_USER_NAME).useSysAdmin().syncContact();
            new BLD_USER(uow).userName(TEST_USER_NAME+'1').useCib().syncContact();
            new BLD_USER(uow).userName(TEST_USER_NAME+'2').useCib().syncContact();
    
            uow.commitWork();
    } 
    Test.startTest();
    Test.stopTest(); 
    	//make some object for testing, like a lead
    	lead l = new lead();
    	l.Lastname = 'McLaughlin';
    	l.company = 'Salesforce';
    	l.email = 'm.shane.mclaughlin@gmail.com';
    	insert l;

    	account a = new account();
    	a.Name = 'Ink, inc.';
    	insert a;

    	contact c = new contact();
    	c.accountId = a.id;
    	c.FirstName = 'Sarah';
    	c.LastName = 'McLaughlin';
    	c.Email = 'sarah@gmail.com';
    	insert c;

    	Opportunity o = new Opportunity();
    	o.accountId = a.id;
    	o.closeDate = system.today();
    	o.Name = 'biggest deal ever';

    	o.StageName = [select MasterLabel from OpportunityStage where IsClosed = false][0].MasterLabel;
    	insert o;

      BLD_BusinessAssessment baBld = new BLD_BusinessAssessment(uow).client(a.Id);

      BLD_CreditRiskAppetite riskApetiteBld = (BLD_CreditRiskAppetite) new BLD_CreditRiskAppetite(uow)
                            .setField(Credit_Risk_Appetite__c.Country__c, DMN_Account.CTRY_OF_RISK)
                            .setField(Credit_Risk_Appetite__c.Sector__c, DMN_Account.SEC_CUSTOMER)
                            .setField(Credit_Risk_Appetite__c.Sub_Sector__c, DMN_Account.SUB_SEC_AGRICULTURE)
                            .setField(Credit_Risk_Appetite__c.Sector_Credit_Appetite__c, DMN_RiskAppettite.RISK_HOLD)
                            .setField(Credit_Risk_Appetite__c.Country_Credit_Appetite__c, DMN_RiskAppettite.RISK_HOLD);
      uow.commitWork();

      group g = new group();
      g.Name = 'the knights who say nee';
      g.Type = 'Regular';

      insert g;



  }

  private static User[] getUsers(){ 
        return  [  SELECT Username  
                        FROM User
                        WHERE UserName in: (new String[]{TEST_USER_NAME+'1', TEST_USER_NAME+'2'})];
  }

  private static User getAdminUser(){ 
        return  [  SELECT Username  
                        FROM User
                        WHERE UserName =:TEST_ADMIN_USER_NAME LIMIT 1];
  }


  /*public static user createAdmin(){
  	Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];

		// create User
		User u = new User();

		u.FirstName = 'A';
		u.LastName = 'S';
		u.Email = 'test@testLightningSharing2017.com';
		u.Username = 'astest@testLightningSharing2017.com';
		u.Alias = 'astest';
		u.ProfileId = p.Id;
		u.TimeZoneSidKey    = 'America/Denver';
		u.LocaleSidKey      = 'en_US';
		u.EmailEncodingKey  = 'UTF-8';
		u.LanguageLocaleKey = 'en_US';

		insert u;
		system.debug('u contains ' + u);
		return u;
	}

	public static list<user> createUsers(integer numberOfUsers){
		list<user> users = new list<user>();

		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];


		for (integer i=0; i<numberOfUsers; i++){
			string x = string.valueOf(i);
			User u = new User(Alias = 't'+x, Email='standarduser'+x+'@testLightningSharing2017.msm',
				EmailEncodingKey='UTF-8', LastName='Testing' + x, LanguageLocaleKey='en_US',
				LocaleSidKey='en_US', ProfileId = p.Id,
				TimeZoneSidKey='America/Los_Angeles', UserName='standarduser'+x+'@testLightningSharing2017.msm');
			users.add(u);
		}

		insert users;
		return users;
	}*/

}