force-app/main/default/objects/Business_Assessment__c/Business_Assessment__c.object-meta.xml
<CustomObject>
    <label>Business Assessment</label>
    <nameField>
        <displayFormat>BA{0000000}</displayFormat>
        <label>Business Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Assessment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The name of the group parent client who the business assessment is applicable for</description>
    <inlineHelpText>Group Parent Client that the business assessment is applicable for</inlineHelpText>
    <label>Group Parent Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Assessments</relationshipLabel>
    <relationshipName>Business_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Approval_Milestone_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Milestone_Date__c</fullName>
    <label>Approval Milestone Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Guarantor_Name__c.field-meta.xml
<CustomField>
    <fullName>Guarantor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the Client providing the guarantee for the credit</description>
    <inlineHelpText>Name of the Client providing the guarantee for the credit</inlineHelpText>
    <label>Guarantor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Guarantees</relationshipLabel>
    <relationshipName>Guarantees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/MNPI__c.field-meta.xml
<CustomField>
    <fullName>MNPI__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether there is an MNPI opportunity included on the NBAC</description>
    <inlineHelpText>Indicates whether there is an MNPI opportunity included on the NBAC</inlineHelpText>
    <label>MNPI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BLD_BusinessAssessment.cls
@IsTest
public class BLD_BusinessAssessment extends ABS_ObjectBuilderBase {
	public BLD_BusinessAssessment() {
		this(getNewUnitOfWork());
	}

	public BLD_BusinessAssessment(fflib_SObjectUnitOfWork workUnit) {
		super(Business_Assessment__c.SObjectType, workUnit);
	}

	private BLD_BusinessAssessment(Business_Assessment__c sObj, fflib_SObjectUnitOfWork workUnit) {
		super(sObj, workUnit);
	}	

	protected override void setDefaultData() {
		//setField(Account.Name, DEF_NAME);
	}

	public BLD_BusinessAssessment client(Id accId) {
		setField(Business_Assessment__c.Account__c , accId);
		return this;
	}

	public BLD_BusinessAssessment client(BLD_Account clientBld) {
		setRelation(Business_Assessment__c.Account__c, clientBld);
		return this; 
	}

	public BLD_BusinessAssessment client(){
		setRelation(Business_Assessment__c.Account__c, new BLD_Account(workUnit));
		return this;
	}

	public BLD_BusinessAssessment guarantorName(BLD_Account guarantorNameBld) {
		setRelation(Business_Assessment__c.Guarantor_Name__c, guarantorNameBld);
		return this;
	}

	public BLD_BusinessAssessment approvalMilestoneDate(Date dte) {
		setField(Business_Assessment__c.Approval_Milestone_Date__c , dte);
		return this;
	}

	public BLD_BusinessAssessment mnpi(Boolean mnpi) {
		setField(Business_Assessment__c.MNPI__c , mnpi);
		return this;
	}
}