force-app/main/default/objects/AOB_Application__c/AOB_Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AOB_Application__c/fields/AOB_Status__c.field-meta.xml
<CustomField>
    <fullName>AOB_Status__c</fullName>
    <description>Contains current status of the Application record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AOB_CTRL_SaveForLater_TEST.cls
@isTest
    public class AOB_CTRL_SaveForLater_TEST {
    
    /**
     * @description Test setup method to insert all Test data
     */
     @TestSetup
     public static void testSetUp(){
         AOB_DAL_TestFactory.createCommunityUser();    
    }

    /**
       * @description gets the current application record Test
       *
       */
    @isTest
    public static void getApplicationNameTest() {

        User communityUser = [SELECT Id,contactId FROM USER WHERE Email like '%@test.org' LIMIT 1];

        AOB_Application__c newApplication = AOB_DAL_TestFactory.createApplication(communityUser);

        Test.startTest();
        AOB_Application__c app = AOB_CTRL_SaveForLater.getApplicationName(newApplication.Id);
        Test.stopTest();
        System.assertNotEquals(null, app.Name);
    }
    
    /**
       * @description gets the current application record Test
       *
       */
    @isTest
    public static void updateApplicationToInProgressStatusTest() {
        
       User communityUser = [SELECT Id,contactId FROM USER WHERE Email like '%@test.org' LIMIT 1];
 
       AOB_Application__c newApplication = AOB_DAL_TestFactory.createApplication(communityUser);

       Test.startTest();
       AOB_CTRL_SaveForLater.updateApplicationToInProgressStatus(newApplication.Id);
       Test.stopTest();
       
       AOB_Application__c appAfter = [
          SELECT Id, AOB_Status__c
          FROM AOB_Application__c
          WHERE Id = :newApplication.Id
      ];
      System.assertEquals('In Progress', appAfter.AOB_Status__c);
    
   }
}