force-app/main/default/objects/AOB_Application__c/AOB_Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AOB_Application__c/fields/AOB_Client__c.field-meta.xml
<CustomField>
    <fullName>AOB_Client__c</fullName>
    <inlineHelpText>Parent Account</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AOB_ApplicationLineItem__c/AOB_ApplicationLineItem__c.object-meta.xml
<CustomObject>
    <label>Application line item</label>
    <nameField>
        <label>Application line item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application line items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AOB_ApplicationLineItem__c/fields/AOB_Application__c.field-meta.xml
<CustomField>
    <fullName>AOB_Application__c</fullName>
    <label>Application</label>
    <referenceTo>AOB_Application__c</referenceTo>
    <relationshipLabel>Application line items</relationshipLabel>
    <relationshipName>Application_line_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AOB_ApplicationLineItem__c/fields/AOB_Product__c.field-meta.xml
<CustomField>
    <fullName>AOB_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Application line items</relationshipLabel>
    <relationshipName>Application_line_items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AOB_ProductAOContent__c/AOB_ProductAOContent__c.object-meta.xml
<CustomObject>
    <label>Product AO Content</label>
    <nameField>
        <label>Product AO Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product AO Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AOB_ProductAOContent__c/fields/AOB_description__c.field-meta.xml
<CustomField>
    <fullName>AOB_description__c</fullName>
    <description>description of the content ( what to display for customer)</description>
    <label>description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/AOB_ProductAOContent__c/fields/AOB_HelpText__c.field-meta.xml
<CustomField>
    <fullName>AOB_HelpText__c</fullName>
    <description>help text if applicable</description>
    <label>Help Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AOB_ProductAOContent__c/fields/AOB_Product__c.field-meta.xml
<CustomField>
    <fullName>AOB_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent product(show this content is customer selected this product)</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product AO Content</relationshipLabel>
    <relationshipName>Product_AO_Content</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AOB_ProductAOContent__c/fields/AOB_Sequence__c.field-meta.xml
<CustomField>
    <fullName>AOB_Sequence__c</fullName>
    <description>order of the content</description>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>User Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>User_Division__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Bank Sector</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Br71C Regional Sales</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Business Acquisition</fullName>
            </value>
            <value>
                <fullName>Business Banking Channel</fullName>
            </value>
            <value>
                <fullName>Business Banking Channel Head Office</fullName>
            </value>
            <value>
                <fullName>Business Banking Head Office</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Buy-Side</fullName>
            </value>
            <value>
                <fullName>Cape Head</fullName>
            </value>
            <value>
                <fullName>Capital Markets</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>CDG</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>China/Africa</fullName>
            </value>
            <value>
                <fullName>CIB</fullName>
            </value>
            <value>
                <fullName>Client Access</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
            <value>
                <fullName>Client Onboarding</fullName>
            </value>
            <value>
                <fullName>Client Service</fullName>
            </value>
            <value>
                <fullName>Client Services Operation</fullName>
            </value>
            <value>
                <fullName>Client Solutions</fullName>
            </value>
            <value>
                <fullName>Coastal Region</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Channel</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Channel Head Office</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Head Office</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_CIB_Global_Area__c.field-meta.xml
<CustomField>
    <fullName>User_CIB_Global_Area__c</fullName>
    <label>User CIB Global Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Africa Regions</fullName>
            </value>
            <value>
                <fullName>CIBI</fullName>
            </value>
            <value>
                <fullName>CIBROA</fullName>
            </value>
            <value>
                <fullName>CIBSA</fullName>
            </value>
            <value>
                <fullName>CIB Global</fullName>
            </value>
            <value>
                <fullName>BCC</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>PBB SA</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_Division__c.field-meta.xml
<CustomField>
    <fullName>User_Division__c</fullName>
    <label>User Division</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>User_CIB_Global_Area__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Banking</fullName>
            </value>
            <value>
                <fullName>Business Enablers</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
            <value>
                <fullName>Client Services</fullName>
            </value>
            <value>
                <fullName>Client Solutions</fullName>
            </value>
            <value>
                <fullName>Commercial Banking</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>Entrepreneur</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>Global Markets</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Small Enterprise</fullName>
            </value>
            <value>
                <fullName>Transactional Products and Services</fullName>
            </value>
            <value>
                <fullName>Vehicle and Asset Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AOB_DAL_TestFactory.cls
/**
* Used to create Data, mostly for unit tests
* 
* <p></p> 
* 
* @author Salesforce
* 
* @date Oct 17th 2021
*/
public with sharing class AOB_DAL_TestFactory {
    
    /**
* This method is use to create a community user
* @param profileName The profile that should be linked to the new user
* @param profileName The permissionsetnames that should be assigned to the new user
* @return A user that Is/not inserted
*/
    public static User createCommunityUser( ){
        UserRole userrole = [Select Id, DeveloperName From UserRole where DeveloperName='Business_Banking' Limit 1];
        
        User adminUser = [Select Id, UserRoleId From User Where id=:UserInfo.getUserId() Limit 1];
        
        if(String.isBlank(adminUser.UserRoleId)){
            adminUser.UserRoleId = userRole.Id;
            update adminUser;
        }
        User user;
        System.runAs(adminUser){
            String EXTERNAL_USER_PROFILE = 'AOB_Authenticated Customer Community';
            //get Profile
            Profile profile = [SELECT id 
                               FROM Profile 
                               WHERE name=:EXTERNAL_USER_PROFILE];
            
            //Insert User        
            String uniqueName = getUniqueName();
            
            string accountRT=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesBusiness').getRecordTypeId();
            Account account = new Account(Name='TestACC', RecordTypeId=accountRT);
            insert account;
            
            Contact contact = new Contact(LastName='test',
                                          Email = uniqueName + '@test.org',
                                          firstName='testFirstName',
                                          AccountId = account.Id
                                         ); 
            insert contact;
            user = new User(lastName = 'test',
                            email = uniqueName + '@test.org',
                            Username = uniqueName + '@test.org',
                            ProfileId = profile.Id,
                            EmailEncodingKey = 'ISO-8859-1',
                            Alias = uniqueName.substring(18, 23),
                            TimeZoneSidKey = 'America/Los_Angeles',
                            LocaleSidKey = 'en_US',
                            LanguageLocaleKey = 'en_US',
                            UserPermissionsKnowledgeUser =true,
                            contactId=contact.id,
                            User_Division__c ='Digital',
                            Business_Unit__c  ='Bank Sector',
                            User_CIB_Global_Area__c   ='CIBSA',
                            Country  ='ZA',
                            city  ='city',
                            state='state',
                            postalCode='state',
                            FederationIdentifier='FederationIdentifier'+uniqueName
                           );
            insert user;
        }
        return user;
    }
    
    /**
* Get the unique name to be user for Email, Username of the created user
* @return A unique Name
*/
    public static string getUniqueName(){
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        
        return uniqueName;
    }
    
/**
* This method is used to create a new application (without params)
* @return AOB_Application__c
*/
    public static AOB_Application__c createApplication() {
        User communityUser = [
            SELECT id, contactId
            FROM User
            WHERE id = :UserInfo.getUserId()
        ];
        Account acc = [
            SELECT id
            FROM account
            WHERE
            id IN (
                SELECT accountId
                FROM contact
                WHERE id = :communityUser.contactId
            )
        ];
        AOB_Application__c newApplication = new AOB_Application__c();
        newApplication.AOB_Client__c  = acc.id;
        insert newApplication;
        return newApplication;
    }
    
    /**
* This method is used to create a new application (without params)
* @return AOB_Application__c
*/
    public static AOB_Application__c createApplication(User userId) {
        User communityUser = [
            SELECT id, contactId
            FROM User
            WHERE id = :userId.Id
        ];
        Account acc = [
            SELECT id
            FROM account
            WHERE
            id IN (
                SELECT accountId
                FROM contact
                WHERE id = :communityUser.contactId
            )
        ];
        AOB_Application__c newApplication = new AOB_Application__c();
        newApplication.AOB_Client__c  = acc.id;
        insert newApplication;
        return newApplication;
    }

    
    
    /**
    * This method is used to create a new product
    * @param name: Product name
    * @return Product2
    */
    public static Product2 createProduct(String name, String productCode) {
        Product2 newProduct = new Product2(Name = name);
        newProduct.ProductCode = productCode;
        newProduct.ExternalId = productCode;
        insert newProduct;
        return newProduct;
    }
    
    /**
   * This method is used to create a new AOB_RequiredDocument__c record
   * @param productId: Parent product Id
   * @param description: Record description
   * @param helpText: Current help text
   * @param order: Order of the current record
   * @return AOB_RequiredDocument__c
   */
  public static AOB_ProductAOContent__c createAOContent(
    Id productId,
    String description,
    String helpText,
    Integer order
  ) {
    AOB_ProductAOContent__c requiredDocument = new AOB_ProductAOContent__c(
      AOB_Product__c = productId,
      AOB_Description__c = description,
      AOB_HelpText__c = helpText,
      AOB_Sequence__c = order
    );
    insert requiredDocument;
    return requiredDocument;
  }
    /**
    * This method is use to get the user with profile
    * @param profileName The profile that should be linked to the new user
    * @return A user that Is/not inserted
    */
    public static User createUser (String profileName, Boolean doInsert) {
        User result = new User(
            ProfileId = [
                SELECT  Id
                FROM    Profile
                WHERE   Name = :profileName
                LIMIT 1
            ].Id,
            LastName = 'LastName',
            FirstName='FirstName',
            Email = 'aob@sb.com',
            Username = 'aob@sb.com' + System.currentTimeMillis(),
            CommunityNickname = 'aob' + System.currentTimeMillis(),
            CompanyName = 'aob',
            Title = 'Volunteer',
            Alias = 'aob',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            isActive = true,
            User_Division__c ='Digital',
            Business_Unit__c  ='Bank Sector',
            User_CIB_Global_Area__c   ='CIBSA',
            Country  ='ZA',
            city  ='city',
            state='state',
            postalCode='state'
        );
        
        if (doInsert) {
            insert result; 
        }
        return result;
    }
    
    /**
    * This method is used to create a new product
    * @param name: Product naem
    * @return Product2
    */
    public static Product2 createProduct(String name){
        Product2 newProduct = new Product2(Name = name);
        insert newProduct;
        return newProduct;
    }
    /**
    * This method is used to create a new AOB_RequiredDocument__c record
    * @param productId: Parent product Id
    * @param description: Record description
    * @param helpText: Current help text
    * @param order: Order of the current record
    * @return AOB_RequiredDocument__c
    */
    public static AOB_ProductAOContent__c createAOProductContent(Id productId, String description, String helpText, Integer order){
        AOB_ProductAOContent__c aoContent = new AOB_ProductAOContent__c( AOB_Product__c = productId,
                                                                        AOB_Description__c = description,
                                                                        AOB_HelpText__c = helpText,
                                                                        AOB_sequence__c = order
                                                                       );
        insert aoContent;
        return aoContent;
    }
    
    /**
    * This method is used to create a new application line item
    * @param productId: Parent product Id
    * @param applicationId: Parent application Id
    * @return AOB_ApplicationLineItem__c
    */
    public static AOB_ApplicationLineItem__c createApplicationLineItem(Id productId, Id applicationId){
        AOB_ApplicationLineItem__c newApplicationLineItem = new AOB_ApplicationLineItem__c(AOB_Product__c = productId, AOB_Application__c = applicationId);
        insert newApplicationLineItem;
        return newApplicationLineItem;
    }
    
    /**
    * @desc     genericObjectCreation: Created a record of the provided Object with the provided field values  
    * @param    ObjectName: The object name ( Api name)
    * @param    values: Mapping with key the field api name and the value the field value
    * @return   True if the Record is created and Error otherwise
    */
    public static sObject genericObjectCreation(string objectName, Map<string,object> values){
        Map<String, Schema.SObjectType> m_objects = Schema.getGlobalDescribe();
        sObject n = m_objects.get(objectName).newSObject();
        for(string fieldName:values.keyset()){
            n.put(fieldName,values.get(fieldName));
        }
        return n;
    }
    
}