force-app/main/default/objects/Approval_Configuration__mdt/Approval_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>​Approval Configuration</label>
    <pluralLabel>​Approval Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Approval_Configuration__mdt/fields/Send_Reminder_After__c.field-meta.xml
<CustomField>
    <fullName>Send_Reminder_After__c</fullName>
    <label>Send Reminder After</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/Client_Data_Change__c.object-meta.xml
<CustomObject>
    <description>A new object to keep a track of the Client Information being changed on the Client record. EN-0676</description>
    <label>Client Data Change</label>
    <nameField>
        <label>Client Data Change Record Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Data Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Data_Change__c/fields/Current_Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Current_Client_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the value of the current client coordinator of the client. EN-0676</description>
    <label>Current Client Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Coordinator_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/Keep_Current_CC__c.field-meta.xml
<CustomField>
    <fullName>Keep_Current_CC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Keep Current CC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/New_Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>New_Client_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New Client Coordinator EN-0676</description>
    <label>New Client Coordinator</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active users and users within the following User Divisions: Corporate Banking, Global Markets, Investment Banking, Transactional Products and Services, General Management, Real Estate can be searched.</errorMessage>
        <filterItems>
            <field>User.User_Division__c</field>
            <operation>equals</operation>
            <value>Client Coverage, General Management, Global Markets, Investment Banking, Real Estate, Transactional Products and Services</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Coordinator_Change_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BCH_ApprovalReminder_Test.cls
/**
 * Created by mjaznicki on 04.06.2018.
 */

@IsTest
class BCH_ApprovalReminder_Test {

    static User testCurrentCC, testNewCC;
    static BLD_ClientTeam clientTeam;
    static Account acc;

    @TestSetup
    static void setup() {
        TEST_DataFactory.generateConfiguration();
        fflib_SObjectUnitOfWork uow;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
            testCurrentCC = (User) new BLD_USER(uow).userName('OLDCC@test.com').useCib().division('Transactional Products and Services').syncContact().getRecord();
            testNewCC = (User) new BLD_USER(uow).userName('NEWCC@test.com').useCib().division('Transactional Products and Services').syncContact().getRecord();
            uow.commitWork();
        }
        System.runAs(testCurrentCC) {
            clientTeam = new BLD_ClientTeam().coordinator(true).role('Analyst').user(testCurrentCC.Id);
            acc = (Account) new BLD_Account().name(BLD_Account.DEF_NAME).clientCoordinator(testCurrentCC).addClientTeam(clientTeam).commitWork().getRecord();
        }

    }

    static void getData() {
        for (User usr : [
                SELECT Username, Division, IsActive
                FROM User
                WHERE UserName = 'OLDCC@test.com'
                OR UserName = 'NEWCC@test.com'
                LIMIT 2
        ]) {
            if (usr.UserName == 'OLDCC@test.com') {
                testCurrentCC = usr;
            }
            if (usr.UserName == 'NEWCC@test.com') {
                testNewCC = usr;
            }
        }
    }


    @IsTest
    static void shouldSendApprovalReminder() {
        getData();
        Client_Data_Change__c cdc;
        System.runAs(testCurrentCC) {
            cdc = new Client_Data_Change__c();
            cdc.Keep_Current_CC__c = true;
            cdc.Current_Client_Coordinator__c = testCurrentCC.Id;
            cdc.New_Client_Coordinator__c = testNewCC.Id;
            upsert cdc;

            UTL_Approval.ApprovalResults appRes = UTL_Approval.runApproval(cdc.Id, 'Update_CC');
            ProcessInstance pi = [
                    SELECT ElapsedTimeInDays, ProcessInstance.TargetObjectId, ProcessInstance.ProcessDefinition.DeveloperName
                    FROM ProcessInstance
                    WHERE Status = 'Pending' AND ProcessInstance.TargetObjectId = :cdc.id
            ];


            if (SRV_Approval.approvalName2Config.containsKey(pi.ProcessDefinition.DeveloperName)) {
                Approval_Configuration__mdt config = SRV_Approval.approvalName2Config.get(pi.ProcessDefinition.DeveloperName);
                Datetime crTime = Datetime.now().addDays(-Integer.valueOf(config.Send_Reminder_After__c)).addHours(-1);
                Test.setCreatedDate(pi.Id, crTime);
            }

        }
        Test.startTest();
        BCH_ApprovalReminder bchApprovalReminder = new BCH_ApprovalReminder();
        Database.executeBatch(bchApprovalReminder);
        Test.stopTest();
        System.assertEquals(1, BCH_ApprovalReminder.results.size());

    }

}