force-app/main/default/objects/Account/fields/Actual_CY_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Actual_CY_Revenue__c</fullName>
    <description>EN-0695-Total Revenue rolled up to Client in ZAR</description>
    <inlineHelpText>The actual rolled up Client Revenue (Year to Date in ZAR)</inlineHelpText>
    <label>Actual CY Revenue (ZAR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/AGM_Status__c.field-meta.xml
<CustomField>
    <fullName>AGM_Status__c</fullName>
    <description>US-3868 Strategic Categorization (AGM) of the clients</description>
    <inlineHelpText>Acquire – Clients we don’t bank with;
Grow – Client with potential growth;
Maintain – Maintain current relationship;
One CIB – Existing global clients;
Blank – Not categorised</inlineHelpText>
    <label>AGM Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acquire</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Maintain</fullName>
            </value>
            <value>
                <fullName>One CIB</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CIB_Target_Client__c.field-meta.xml
<CustomField>
    <fullName>CIB_Target_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <description>These are clients as identified during the budget process. (US-2236)</description>
    <inlineHelpText>These are clients as identified during the budget process</inlineHelpText>
    <label>Individually Budgeted Client (IBC)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <description>Label changed from CIF to CIF Number</description>
    <externalId>true</externalId>
    <label>CIF Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Co_ordinator__c.field-meta.xml
<CustomField>
    <fullName>Client_Co_ordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New CC field created to be used for onboarding purposes (EN-0731)</description>
    <inlineHelpText>The suggested Client Coordinator responsible for the Bank’s relationship with the Client. Must be part of the division selected as the Primary Relationship Holder. This can only be changed by the CRM Helpdesk once approved.</inlineHelpText>
    <label>Proposed Client Coordinator</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only active users and users within the following User Divisions: Corporate Banking, Global Markets, Investment Banking, Transactional Products and Services, General Management, Real Estate can be searched.</errorMessage>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.User_Division__c</field>
            <operation>contains</operation>
            <value>Corporate Banking, Global Markets, Investment Banking, Transactional Products and Services, General Management, Real Estate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sector__c</fullName>
    <description>Field Label Rename from &apos;CIB SA Sector&apos; to &apos;Global Sector&apos;, Nov &apos;10

#EN-226 - The primary sector in which the Client operates. This field is used in CRT and MI reporting</description>
    <inlineHelpText>The primary sector in which the Client operates</inlineHelpText>
    <label>Client Sector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Industrials</fullName>
            </value>
            <value>
                <fullName>Internal / Grouped</fullName>
            </value>
            <value>
                <fullName>Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Oil and Gas</fullName>
            </value>
            <value>
                <fullName>Power and Infrastructure</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Sovereign / Public Sector</fullName>
            </value>
            <value>
                <fullName>Telecoms and Media</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Sector__c</fullName>
    <description>The Client Sub-Sector further defines the sector in which the Client operates. This field is used in CRT and MI reporting. The business rule where a Client Sub-Sector cannot be dependent on more than one Client Sector needs to be adhered to at all times. Do not create or assign a duplicate Client Sub-Sector to more than one Client Sector</description>
    <inlineHelpText>The Client Sub-Sector further defines the sector in which the Client operates</inlineHelpText>
    <label>Client Sub-Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Sector__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Agriculture Commodity Traders</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Alternative Investment Vehicles</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automobiles</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Brokers and Exchanges</fullName>
            </value>
            <value>
                <fullName>Bulk Commodities</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Central Banks</fullName>
            </value>
            <value>
                <fullName>Centralised Power</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Construction Services</fullName>
            </value>
            <value>
                <fullName>Consumer Services</fullName>
            </value>
            <value>
                <fullName>Development Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Diamonds</fullName>
            </value>
            <value>
                <fullName>Diversified Industrials</fullName>
            </value>
            <value>
                <fullName>Diversified Mining</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equipment Manufacturers</fullName>
            </value>
            <value>
                <fullName>Food and Beverage</fullName>
            </value>
            <value>
                <fullName>Forestry</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Government Departments</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Overall_CIB_CSI_Rating_Number__c.field-meta.xml
<CustomField>
    <fullName>Overall_CIB_CSI_Rating_Number__c</fullName>
    <label>Overall CIB CSI Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Role_s_at_Client__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role_s_at_Client__c</fullName>
    <description>The functional role(s) performed by the Client Contact in dealing with Standard Bank. C-00000333</description>
    <inlineHelpText>The functional role(s) performed by the Client Contact in dealing with Standard Bank</inlineHelpText>
    <label>Contact Role(s) at Client</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved Dealer</fullName>
            </value>
            <value>
                <fullName>Authorised Person</fullName>
            </value>
            <value>
                <fullName>CC Survey Contact</fullName>
            </value>
            <value>
                <fullName>CommB Survey Contact</fullName>
            </value>
            <value>
                <fullName>Direct Shareholder</fullName>
            </value>
            <value>
                <fullName>GM Survey Contact</fullName>
            </value>
            <value>
                <fullName>Group KYC Contact</fullName>
            </value>
            <value>
                <fullName>IB Survey Contact</fullName>
            </value>
            <value>
                <fullName>Indirect Shareholder</fullName>
            </value>
            <value>
                <fullName>KYC Contact</fullName>
            </value>
            <value>
                <fullName>Pricing Contact</fullName>
            </value>
            <value>
                <fullName>Primary GM Research Contact</fullName>
            </value>
            <value>
                <fullName>TPS Survey Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_CIB_Global_Area__c.field-meta.xml
<CustomField>
    <fullName>User_CIB_Global_Area__c</fullName>
    <label>User CIB Global Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Africa Regions</fullName>
            </value>
            <value>
                <fullName>CIBI</fullName>
            </value>
            <value>
                <fullName>CIBROA</fullName>
            </value>
            <value>
                <fullName>CIBSA</fullName>
            </value>
            <value>
                <fullName>CIB Global</fullName>
            </value>
            <value>
                <fullName>BCC</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>PBB SA</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountHierarchy_LTN_CTRL.cls
public with sharing class AccountHierarchy_LTN_CTRL {

	private static Map<Id,Set<Id>> id2HierarchyIds;

	@TestVisible
	private static Set<Id> getHierarchyIds(Id sourceId){
		if(id2HierarchyIds == null){
			id2HierarchyIds = new Map<Id,Set<Id>>();
		}

		if(!id2HierarchyIds.containsKey(sourceId)){
			Set<Id> recIds = new Set<Id>();

			for(Account acc : [	SELECT Id, ParentId, Parent.ParentId, Parent.Parent.ParentId,
									Parent.Parent.Parent.ParentId, Parent.Parent.Parent.Parent.ParentId
								FROM Account  
								WHERE Id =: sourceId
									OR ParentId =: sourceId
									OR Parent.ParentId =: sourceId
									OR Parent.Parent.ParentId =: sourceId
									OR Parent.Parent.Parent.ParentId =: sourceId
									OR Parent.Parent.Parent.Parent.ParentId =: sourceId]){
				recIds.add(acc.Id);
				if(acc.ParentId != null){
					recIds.add(acc.ParentId);
				}
				if(acc.Parent.ParentId != null){
					recIds.add(acc.Parent.ParentId);
				}
				if(acc.Parent.Parent.ParentId != null){
					recIds.add(acc.Parent.Parent.ParentId);
				}
				if(acc.Parent.Parent.Parent.ParentId != null){
					recIds.add(acc.Parent.Parent.Parent.ParentId);
				}
				if(acc.Parent.Parent.Parent.Parent.ParentId != null){
					recIds.add(acc.Parent.Parent.Parent.ParentId);
				}
				id2HierarchyIds.put(sourceId, recIds);
			}
		}

		return id2HierarchyIds.get(sourceId);
	}

	@auraEnabled
	public static Contact[] getContacts(Id accountId){

		Set<Id> accIds = getHierarchyIds(accountId);

		return [SELECT Name, Account.Name, Phone, Email, Contact_Role_s_at_Client__c, Owner.Name
				FROM Contact 
				WHERE AccountId IN: accIds
					OR Account.ParentId IN: accIds
					OR Account.Parent.ParentId IN: accIds
					OR Account.Parent.Parent.ParentId IN: accIds
					OR Account.Parent.Parent.Parent.ParentId IN: accIds]; 
	} 


	@auraEnabled
	public static Opportunity[] getOpportunities(Id accountId){

		Set<Id> accIds = getHierarchyIds(accountId);

		return [SELECT Name, Account.Name, Owner.Name, StageName, CloseDate
				FROM Opportunity 
				WHERE AccountId IN: accIds
					OR Account.ParentId IN: accIds
					OR Account.Parent.ParentId IN: accIds
					OR Account.Parent.Parent.ParentId IN: accIds
					OR Account.Parent.Parent.Parent.ParentId IN: accIds];
	}

	@auraEnabled
	public static Account[] getAccounts(Id accountId){ 

		Set<Id> accIds = getHierarchyIds(accountId);

		Account[] accs = [	SELECT Name, AGM_Status__c, CIB_Target_Client__c, CIF__c, Client_Sector__c, Client_Sub_Sector__c,
								Overall_CIB_CSI_Rating_Number__c, Actual_CY_Revenue__c, Owner.Name, OwnerId,
								RecordType.Name, Client_Co_ordinator__c, BillingCountry 
							FROM Account   
							WHERE Id IN: accIds
								OR ParentId IN: accIds
								OR Parent.ParentId IN: accIds
								OR Parent.Parent.ParentId IN: accIds
								OR Parent.Parent.Parent.ParentId IN: accIds
								OR Parent.Parent.Parent.Parent.ParentId IN: accIds];

		for(Account acc : accs){
			if(acc.Actual_CY_Revenue__c == null){
				acc.Actual_CY_Revenue__c = 0.00;
			}
		}

		return accs;
	}  


	/**
	 * Returns a boolean wether the agm column status is visible in the heirarchy
	 * CIB profiles currently (09/21/2020) are only profiles that need to see the AGM status column
	 */
	@auraEnabled 
	public static Boolean agmColumnStatusVisible() {

	Id userId = userinfo.getUserId();

	String userCibGLobalArea = [SELECT User_CIB_Global_Area__c FROM User where Id =: userId].User_CIB_Global_Area__c;

	String role = 'cib';

	// return true if role matches cib
	if (userCibGLobalArea.containsIgnoreCase(role)) {
		return true;
	}

	return false;
	}

	@auraEnabled 
	public static Account getAccount(Id accountId){

		return [SELECT Id, Name
				FROM Account 
				WHERE Id =: accountId];
	}

	@auraEnabled
	public static DTO_SelectOption[] getStageNames(){
		System.debug('Stages ' + DTO_SelectOption.fetchOptions(Opportunity.StageName));
		return DTO_SelectOption.fetchOptions(Opportunity.StageName);
	}

	@auraEnabled
	public static DTO_SelectOption[] getContactRoles(){
		System.debug('ROLES ' + DTO_SelectOption.fetchOptions(Contact.Contact_Role_s_at_Client__c));
		return DTO_SelectOption.fetchOptions(Contact.Contact_Role_s_at_Client__c);
	}
}