force-app/main/default/objects/Account/fields/Anticipated_Level_Volume_of_Activity__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Level_Volume_of_Activity__c</fullName>
    <description>Anticipated Level / Volume of Activity</description>
    <inlineHelpText>The expected level or volume of business to be conducted with Standard Bank</inlineHelpText>
    <label>Anticipated Level / Volume of Activity</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Classification__c.field-meta.xml
<CustomField>
    <fullName>Business_Classification__c</fullName>
    <description>Business Classification</description>
    <inlineHelpText>Additional definition of the type of business that the Client is</inlineHelpText>
    <label>Business Classification</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Type_OnBoard__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Central Bank</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Fund</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Informal Body</fullName>
            </value>
            <value>
                <fullName>Joint Venture</fullName>
            </value>
            <value>
                <fullName>Local Authority</fullName>
            </value>
            <value>
                <fullName>Non-Profit Organisation</fullName>
            </value>
            <value>
                <fullName>Parastatal</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Professional Partnership</fullName>
            </value>
            <value>
                <fullName>Public Authority</fullName>
            </value>
            <value>
                <fullName>Public Sector Body</fullName>
            </value>
            <value>
                <fullName>Section 21 / Non Profit Company</fullName>
            </value>
            <value>
                <fullName>Sole Proprietor</fullName>
            </value>
            <value>
                <fullName>Sovereign Wealth Fund</fullName>
            </value>
            <value>
                <fullName>State Owned Company</fullName>
            </value>
            <value>
                <fullName>Supranational Organisation</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Type_OnBoard__c.field-meta.xml
<CustomField>
    <fullName>Client_Type_OnBoard__c</fullName>
    <description>Client Type / Entity Type</description>
    <inlineHelpText>The type of Client that will be conducting business with Standard Bank</inlineHelpText>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Broker Dealer</fullName>
            </value>
            <value>
                <fullName>Fund</fullName>
            </value>
            <value>
                <fullName>Insurance Company</fullName>
            </value>
            <value>
                <fullName>Investment Advisor</fullName>
            </value>
            <value>
                <fullName>Non-Financial Business</fullName>
            </value>
            <value>
                <fullName>Non-Profit Organisation</fullName>
            </value>
            <value>
                <fullName>Public Sector Body</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Expected_Income__c.field-meta.xml
<CustomField>
    <fullName>Expected_Income__c</fullName>
    <description>Refers to funds or money received from the Client that is not attributable to the regular income that the Client generates.</description>
    <inlineHelpText>Refers to funds or money received from the Client that is not attributable to the regular income that the Client generates.</inlineHelpText>
    <label>Expected Income</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code__c</fullName>
    <description>Industry Class code from CIF (ISIC)</description>
    <inlineHelpText>Defines the isic code.</inlineHelpText>
    <label>Industry Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/KYC_Contact__c.field-meta.xml
<CustomField>
    <fullName>KYC_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-1949 - The existing Contact that the KYC Team can consult to complete on boarding process for this Client. Select an existing Contact or create a New Contact on this Contact with a Contact Role(s) at Client value of KYC Contact or Group KYC Contact.</description>
    <inlineHelpText>The existing Contact that the KYC Team can consult to complete on boarding process for this Client. Select an existing Contact or create a New Contact on this Contact with a Contact Role(s) at Client value of KYC Contact or Group KYC Contact.</inlineHelpText>
    <label>KYC Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 4 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.KYC_Contact__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Group_Parent_CIF_Number__c</field>
            <operation>equals</operation>
            <valueField>Contact.Group_Parent_CIF_Number__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.CIF__c</field>
            <operation>equals</operation>
            <valueField>Contact.Group_Parent_CIF_Number__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Contact Record Type</value>
        </filterItems>
        <infoMessage>Select the KYC Contact for this Client</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (KYC Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nature_of_business_activity__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_business_activity__c</fullName>
    <label>Nature Of Business Activity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SA_Industry_Description__c.field-meta.xml
<CustomField>
    <fullName>SA_Industry_Description__c</fullName>
    <description>Previosuly named SA_Industry_Description. API name still SA_industry_description due to trigger using this field
        US-4394 - This field shows ISIC description that is mapped to relative ISIC Code</description>
    <inlineHelpText>Defines the lowest level of classification as per the client sector.</inlineHelpText>
    <label>CIF ISIC Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_of_Funds__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Funds__c</fullName>
    <description>What is the customer’s source of funds?</description>
    <inlineHelpText>What is the customer’s source of funds?</inlineHelpText>
    <label>Source of Funds</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_of_Wealth__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Wealth__c</fullName>
    <description>What is the customer’s source of wealth?</description>
    <inlineHelpText>How does the Client obtain their wealth?</inlineHelpText>
    <label>Source of Wealth</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accumulated Savings &amp; Investments</fullName>
            </value>
            <value>
                <fullName>Capital injection</fullName>
            </value>
            <value>
                <fullName>Capital investment from parent company</fullName>
            </value>
            <value>
                <fullName>Development Financial Institution</fullName>
            </value>
            <value>
                <fullName>Funding obtained from a Commercial Financial Institution</fullName>
            </value>
            <value>
                <fullName>Gifts</fullName>
            </value>
            <value>
                <fullName>Government backed</fullName>
            </value>
            <value>
                <fullName>Inheritance</fullName>
            </value>
            <value>
                <fullName>Retained income from trading subsidiaries</fullName>
            </value>
            <value>
                <fullName>Sale of assets</fullName>
            </value>
            <value>
                <fullName>Shareholders loans</fullName>
            </value>
            <value>
                <fullName>-	Group Loans and income from Trading as personnel and labour supply company</fullName>
                <isActive>false</isActive>
                <label>-	Group Loans and income from Trading as personnel and labour supply company</label>
            </value>
            <value>
                <fullName>0636889249</fullName>
                <isActive>false</isActive>
                <label>0636889249</label>
            </value>
            <value>
                <fullName>100% of all funds and “wealth” has been raised from Allan Gray Proprietary Limited via a 100% owned subsidiary (BEET) pursuant to share issuances to BEET to in order to fund investments as part of its business</fullName>
                <isActive>false</isActive>
                <label>100% of all funds and “wealth” has been raised from Allan Gray Proprietary Limited via a 100% owned subsidiary (BEET) pursuant to share issuances to BEET to in order to fund investments as part of its business</label>
            </value>
            <value>
                <fullName>1000000</fullName>
                <isActive>false</isActive>
                <label>1000000</label>
            </value>
            <value>
                <fullName>100000000</fullName>
                <isActive>false</isActive>
                <label>100000000</label>
            </value>
            <value>
                <fullName>12</fullName>
                <isActive>false</isActive>
                <label>12</label>
            </value>
            <value>
                <fullName>13000000</fullName>
                <isActive>false</isActive>
                <label>13000000</label>
            </value>
            <value>
                <fullName>131000000</fullName>
                <isActive>false</isActive>
                <label>131000000</label>
            </value>
            <value>
                <fullName>2 000 000 000</fullName>
                <isActive>false</isActive>
                <label>2 000 000 000</label>
            </value>
            <value>
                <fullName>300000000</fullName>
                <isActive>false</isActive>
                <label>300000000</label>
            </value>
            <value>
                <fullName>3275000</fullName>
                <isActive>false</isActive>
                <label>3275000</label>
            </value>
            <value>
                <fullName>32750000</fullName>
                <isActive>false</isActive>
                <label>32750000</label>
            </value>
            <value>
                <fullName>3rd party assets</fullName>
                <isActive>false</isActive>
                <label>3rd party assets</label>
            </value>
            <value>
                <fullName>4000000</fullName>
                <isActive>false</isActive>
                <label>4000000</label>
            </value>
            <value>
                <fullName>Active business</fullName>
                <isActive>false</isActive>
                <label>Active business</label>
            </value>
            <value>
                <fullName>Actuarial Consulting Services</fullName>
                <isActive>false</isActive>
                <label>Actuarial Consulting Services</label>
            </value>
            <value>
                <fullName>Actuarial Consulting Services offered to their clients</fullName>
                <isActive>false</isActive>
                <label>Actuarial Consulting Services offered to their clients</label>
            </value>
            <value>
                <fullName>Administration fee income - ETF&apos;s and Unit Trust portfolios</fullName>
                <isActive>false</isActive>
                <label>Administration fee income - ETF&apos;s and Unit Trust portfolios</label>
            </value>
            <value>
                <fullName>Agric income</fullName>
                <isActive>false</isActive>
                <label>Agric income</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/KYC_Contact__c.field-meta.xml
<CustomField>
    <fullName>KYC_Contact__c</fullName>
    <description>US-1812 :Contacts - (6.1) Client On boarding Use existing KYC Contacts in Group (Look Up)</description>
    <formula>IF (INCLUDES (Contact_Role_s_at_Client__c, &quot;KYC Contact&quot;) || 
INCLUDES (Contact_Role_s_at_Client__c, &quot;Group KYC Contact&quot;), 
True, False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KYC Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GenerateGoldtierSAFormController.cls
/**
 * Created by mjaznicki on 09.07.2018.
 */

public with sharing class GenerateGoldtierSAFormController {

    private static Map<PicklistEntry, List<PicklistEntry>> picklistentry2DependEntries {
        get {
            if (picklistentry2DependEntries == null) {
                picklistentry2DependEntries = UTL_Picklist.getControllingToDependentMap(Account.fields.Client_Type_OnBoard__c, Account.fields.Business_Classification__c);
            }
            return picklistentry2DependEntries;
        }
        set;
    }


    @AuraEnabled
    public static Account getAccount(String accId) {
        return [
                SELECT OwnerId, KYC_Contact__c, Source_of_Wealth__c,Source_of_Funds__c, Anticipated_Level_Volume_of_Activity__c, Nature_of_business_activity__c,
                        RecordType.Name, Expected_Income__c, Industry_Code__c, SA_Industry_Description__c,Client_Type_OnBoard__c,Business_Classification__c
                FROM Account
                WHERE Id = :accId
        ];
    }

    @AuraEnabled
    public static Boolean isAccessGiven() {
        return SRV_ProfileConfiguration.checkIfCurrentUserHasAccess('GenerateGoldtierSAForm');
    }

    @AuraEnabled
    public static List<String> bussinessClassificationValues(String entityTypeValue){
        List<String> picklistValues = new List<String>();
        List<PicklistEntry> bussinessEntries = new List<PicklistEntry>();
        Set<PicklistEntry> pes = picklistentry2DependEntries.keySet();
        for(PicklistEntry pe: pes){
            if(pe.value==entityTypeValue){
                 bussinessEntries = picklistentry2DependEntries.get(pe);
            }
        }
        for(PicklistEntry pee : bussinessEntries){
            picklistValues.add(pee.value);
        }
        return picklistValues;
    }

    @AuraEnabled
    public static List<String> getEntityTypeValues(){
        List<String> entityTypes = new List<String>();
       for (PicklistEntry pe: Account.fields.Client_Type_OnBoard__c.getDescribe().getPicklistValues()){
            entityTypes.add(pe.value);
       }
        return entityTypes;
    }

    @AuraEnabled
    public static List<DTO_SelectOption> getSourceOfWealthValues() {
        return DTO_SelectOption.fetchOptions(Account.Source_of_Wealth__c);
    }

    @AuraEnabled
    public static Contact getKycContact(String Id){
        return [SELECT Name, Phone, Title FROM Contact WHERE Id = :Id];
    }


}