force-app/main/default/objects/Account/fields/CIB_Target_Client__c.field-meta.xml
<CustomField>
    <fullName>CIB_Target_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <description>These are clients as identified during the budget process. (US-2236)</description>
    <inlineHelpText>These are clients as identified during the budget process</inlineHelpText>
    <label>Individually Budgeted Client (IBC)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Parent__c.field-meta.xml
<CustomField>
    <fullName>Group_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Group Parent)</relationshipLabel>
    <relationshipName>GroupParents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CI_Parameters__c/CI_Parameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings controlling behaviour of lightning components specific for CI App (CI_Landing and CI_Client)</description>
    <label>CI Parameters</label>
</CustomObject>

force-app/main/default/objects/Custom_Client_Team__c/Custom_Client_Team__c.object-meta.xml
<CustomObject>
    <label>Client Team</label>
    <nameField>
        <displayFormat>Client-{0000}</displayFormat>
        <label>Client Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Client_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/Global_Client_Revenue__c.object-meta.xml
<CustomObject>
    <description>Case #1263 - Client Overview - Stores Global Client Revenue by reporting country data that is fed into salesforce on a monthly basis by CRT. The data from this object should only be shown on the client overview page and only be visible to the client owner and members on the client service team.</description>
    <label>Global Client Revenue</label>
    <nameField>
        <displayFormat>GCR-{0000000000}</displayFormat>
        <label>Global Client Revenue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Client Revenue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Budget_ZAR_Next_Year__c.field-meta.xml
<CustomField>
    <fullName>Budget_ZAR_Next_Year__c</fullName>
    <description>Used to store the Budget for next year in ZAR</description>
    <label>Budget ZAR Next Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to Client Object</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Global Client Revenue</relationshipLabel>
    <relationshipName>Global_Client_Revenue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Client_Value_ZAR_Current_Month__c.field-meta.xml
<CustomField>
    <fullName>Client_Value_ZAR_Current_Month__c</fullName>
    <description>Revenue for the month</description>
    <inlineHelpText>Revenue for the month</inlineHelpText>
    <label>Client Value ZAR Current Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Snapshot_Date__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Date__c</fullName>
    <description>Enh#119 Client Overview: The date when the snapshot in business objects was taken.

            EN 391 : The label changed due to Client Plan Dashboard requirement. The API name was not changed due to the dependency on other components.</description>
    <inlineHelpText>This is not the date at which snapshot is taken but rather the month end date to which the snapshot applies to (eg 31/03/2014)</inlineHelpText>
    <label>Month End Snapshot Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Trading_Division__c.field-meta.xml
<CustomField>
    <fullName>Trading_Division__c</fullName>
    <description>#EN 391 : Data type was changed from text to picklist for Client Plan Dashboard requirement. (More flexibility in reporting)</description>
    <label>Trading Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>IB</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>TPS</fullName>
            </value>
            <value>
                <fullName>VAF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Actual_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Close_Date__c</fullName>
    <inlineHelpText>Date is system generated upon closing of the opportunity, to amend please contact an administrator.</inlineHelpText>
    <label>Actual Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Year_Revenue_Currency__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Revenue_Currency__c</fullName>
    <formula>Current_Year_Revenue_Num__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>A sum of the estimated Current Year Revenue that is anticipated for this Opportunity, based on all Products added to the Opportunity. This value is reflected in ZAR with your currency displayed in brackets.</inlineHelpText>
    <label>Current Year Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_Division__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Division__c</fullName>
    <description>SHAVEEN12APR2011CASE074 &gt; Used to store the original Opportunity Owner User details once the Opportunity is Closed. EN - 1168: Renamed label name alone but not the API and updated helptext.</description>
    <inlineHelpText>Copy of the corresponding Opportunity Owner&apos;s User object fields in the following scenarios: 
1. Automatically updated and checks for updates when the opportunity is open. 
2. Updated when the opportunity is closed and updates only if Owner changes.</inlineHelpText>
    <label>Opportunity Owner User Division</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <description>Team member object connects either internal staff or contractors to a project assignment.  If you further customize the application, you can prevent &quot;stray time reporting&quot; using apex coding so that team members cannot report time outside of the assigned date range.  This becomes important if your organization reports heavily on project costing or SOP-98 capital/expense.  in addition, Force.com Visualforce or Adobe Flex code can be leveraged to help with the matching of resources to projects/work requests.  Please contact professional services for more information on consulting rates or the Salesforce.com Developer network (www.salesforce.com/developer).</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is a lookup to the user and used to assign internal staff to a project team member.</inlineHelpText>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N80000002lXWPEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CI_QueryBuilder.cls
/**
 * A class to build a query with specific criteria, order and group
 *
 * @author Unknown
 * @date Unknown
 */
public with sharing class CI_QueryBuilder {

    /**
     * Method creates query String with the passed object, fields, and filtering conditions
     *
     * @param fieldsToQuery fields needed in the query
     * @param objectToQuery object for the query
     * @param filteringConditions conditions in WHERE clause
     * @param groupingFields grouping fields for GROUP BY clause
     * @param orderFields order fields for ORDER BY clause
     *
     * @return created query String
    */
    public static String getQuery(String[] fieldsToQuery,
            String objectToQuery, String[] filteringConditions, String[] groupingFields, String[] orderFields){

        String query =  'SELECT ' + String.join(fieldsToQuery, ', ');
        query +=        ' FROM ' + objectToQuery;
        if(filteringConditions != null && !filteringConditions.isEmpty()) {
            query += ' WHERE ' + String.join(filteringConditions, ' AND ');
        }
        if(groupingFields != null && !groupingFields.isEmpty()) {
            query += ' GROUP BY ' + String.join(groupingFields, ', ');
        }
        if(orderFields != null && !orderFields.isEmpty()) {
            query += ' ORDER BY ' + String.join(orderFields, ', ');
        }

        return query;
    }

    /**
     * Method creates query String to count number of clients
     *
     * @param querySettings extra filtering conditions for the query passed from controllers
     * @param teamClientsIds list of client ids
     *
     * @return created query String
    */
    public static String getCountByClientGroupQuery(Map<String,Boolean> querySettings, Set<Id> teamClientsIds) {

        String[] fieldsToQuery = new String[] {
                'RecordType.Name rtName'
                , 'Count(Id) clientsCount'
        };
        String objectToQuery = 'Account';

        String[] filteringConditions = new String[] {
                'Id IN : teamClientsIds'
        };
        if(querySettings != null){
            if(querySettings.get('filteringOnIBC')) {
                filteringConditions.add(' CIB_Target_Client__c = TRUE ');
            }
        }

        String[] groupingFields = new String[] {
                'RecordType.Name'
        };

        String[] orderFields;

        return getQuery(fieldsToQuery, objectToQuery, filteringConditions, groupingFields, orderFields);
    }

    /**
     * Method creates queries for current user's client hierarchy
     *
     * @param querySettings extra filtering conditions for the query passed from controllers
     * @param teamClientsIds list of client ids
     *
     * @return map of query identifier to query presented in child, parent and grandparent queries
    */
    public static Map<String, String> getCurrentUserHighestLevelClientsQuery(Map<String,Boolean> querySettings,
            Set<Id> teamClientsIds) {

        String parentQuery;
        String parentImmediateQuery;
        String childQuery;

        parentQuery = 'SELECT Id ' +
                ' FROM Account ' +
                ' WHERE Id IN :teamClientsIds ' +
                ' AND RecordTypeId = \'' + AccountService.RECORD_TYPE_GROUP_PARENT + '\'';

        parentImmediateQuery = 'SELECT Id ' +
                ' FROM Account ' +
                ' WHERE Id IN :teamClientsIds ' +
                ' AND ParentId NOT IN :clientsForRevenue ' +
                ' AND RecordTypeId = \'' + AccountService.RECORD_TYPE_IMMEDIATE_PARENT + '\'';

        childQuery = 'SELECT Id ' +
                ' FROM Account ' +
                ' WHERE Id IN :teamClientsIds ' +
                ' AND ParentId NOT IN :clientsForRevenue ' +
                ' AND Group_Parent__c NOT IN :clientsForRevenue ' +
                ' AND RecordTypeId = \'' + AccountService.RECORD_TYPE_CHILD + '\'';

        if(querySettings != null){
            if(querySettings.get('filteringOnIBC')){
                parentQuery += ' AND CIB_Target_Client__c = TRUE ';
                parentImmediateQuery += ' AND CIB_Target_Client__c = TRUE ';
                childQuery += ' AND CIB_Target_Client__c = TRUE ';

            }
        }

        Map<String, String> name2query = new Map<String, String>();
        name2query.put('parentQuery', parentQuery);
        name2query.put('parentImmediateQuery', parentImmediateQuery);
        name2query.put('childQuery', childQuery);

        return name2query;
    }

    /**
     * Method creates query String of client pipeline
     *
     * @param querySettings extra filtering conditions for the query passed from controllers
     * @param teamClientsIds list of client ids
     * @param activeClientRTIds list of active client recordtype ids
     *
     * @return created query String
    */
    public static String getClientsForPipelineQuery(Map<String,Boolean> querySettings,
            Set<Id> teamClientsIds, Id[] activeClientRTIds) {

        String[] fieldsToQuery = new String[] {
                'Id'
                , 'Name'
        };
        String objectToQuery = 'Account';

        String[] filteringConditions = new String[] {
                '(Id in :teamClientsIds OR ParentId IN :teamClientsIds OR Parent.ParentId IN :teamClientsIds)',
                'RecordTypeId IN :activeClientRTIds'
        };
        if(querySettings != null){
            if(querySettings.get('filteringOnIBC')) {
                filteringConditions.add('CIB_Target_Client__c = TRUE');
            }
        }

        String[] groupingFields;
        String[] orderFields;
        
        return getQuery(fieldsToQuery, objectToQuery, filteringConditions, groupingFields, orderFields);
    }

    /**
     * Method creates query String of client aggregated pipeline with sum of current year revenues
     *
     * @param querySettings extra filtering conditions for the query passed from controllers
     * @param clientsForPipeline list of client ids for pipeline
     *
     * @return created query String
    */
    public static String getAggregatedPipelinesQuery(Map<String,Boolean> querySettings, Set<Id> clientsForPipeline) {

        CI_Parameters__c divisions = CI_Parameters__c.getValues(DCN_CustomSetting.CI_CY_PIPELINE_DIVISIONS_ENABLE);
        String userDivision = UTL_User.getUserDivision();
        
        String[] fieldsToQuery = new String[] {
                'calendar_month(CloseDate) month'
                , 'SUM(Current_Year_Revenue_Currency__c) revenue'
        };
        String objectToQuery = 'Opportunity';

        String[] filteringConditions = new String[] {
                'AccountId in :clientsForPipeline',
                'StageName = \'' + OpportunityService.STAGE_DEVELOPED + '\'',
                'CloseDate = THIS_YEAR'
        };
        if(querySettings != null && divisions != null) {
            if (querySettings.get('filteringOnDivisions')) {
                if (divisions.Value__c.contains(userDivision)) {
                    filteringConditions.add('Opportunity_Owner_Division__c = \'' + userDivision + '\'') ;
                }
            }
        }

        String[] groupingFields = new String[]{
                'calendar_month(CloseDate)'
        };
        String[] orderFields = new String[]{
                'calendar_month(CloseDate)'
        };

        return getQuery(fieldsToQuery, objectToQuery, filteringConditions, groupingFields, orderFields);
    }

    /**
     * Method creates query String of current year portfolio pipeline
     *
     * @param querySettings extra filtering conditions for the query passed from controllers
     * @param clientsIds set of client ids
     *
     * @return created query String
    */
    public static String getPortfolioCYPipelineActionQuery(Map<String,Boolean> querySettings, Set<Id> clientsIds){

        CI_Parameters__c divisions = CI_Parameters__c.getValues(DCN_CustomSetting.CI_CY_PIPELINE_DIVISIONS_ENABLE);
        String userDivision = UTL_User.getUserDivision();

        String[] fieldsToQuery = new String[] {
                'Name',
                'AccountId',
                'Account.Name',
                'convertCurrency(Current_Year_Revenue_Currency__c)',
                'CloseDate',
                'Probability'
        };
        String objectToQuery = 'Opportunity';

        String[] filteringConditions = new String[] {
                'AccountId IN :clientsIds',
                'StageName = \'' + OpportunityService.STAGE_DEVELOPED + '\'',
                'CloseDate = THIS_YEAR'
        };
        if(querySettings != null && divisions != null) {
            if (querySettings.get('filteringOnDivisions')) {
                if (divisions.Value__c.contains(userDivision)) {
                    filteringConditions.add('Opportunity_Owner_Division__c = \'' + userDivision + '\'') ;
                }
            }
        }

        String[] groupingFields;

        String[] orderFields = new String[]{
                'AccountId '
        };

        return getQuery(fieldsToQuery, objectToQuery, filteringConditions, groupingFields, orderFields);
    }

    /**
     * Method creates query String of client revenue and budget gap
     * @param querySettings extra filtering conditions for the query passed from controllers
     * @param clientIds set of client ids
     * @param lastestSnapshotDate snapshot date to be used as a filter
     *
     * @return created query String
    */
    public static String getRevenueVsBudgetGapQuery(Map<String,Boolean> querySettings,
            Set<Id> clientIds, Date lastestSnapshotDate){

        CI_Parameters__c divisions = CI_Parameters__c.getValues(DCN_CustomSetting.CI_REVENUE_BUDGET_DIVISIONS_ENABLE);
        String tradingDivision = DMN_GlobalClientRevenue.getTradingDivisionBasedOnUserDivision();
        String userDivision = UTL_User.getUserDivision();
        String bookingCountryRTD = UTL_RecordType.getRecordTypeId(DMN_GlobalClientRevenue.OBJ_NAME, DMN_GlobalClientRevenue.RTD_BOOKING_COUNTRY);

        String[] fieldsToQuery = new String[] {
                'SUM(Client_Value_ZAR_Current_Month__c) Client_Value_ZAR_Total',
                'SUM(Budget_ZAR_Next_Year__c) Budget_ZAR_Total'
        };
        String objectToQuery = 'Global_Client_Revenue__c';


        String[] filteringConditions = new String[] {
                'Client__c IN: clientIds'
        };

        if (lastestSnapshotDate != null) {
            filteringConditions.add('CALENDAR_YEAR(Snapshot_Date__c) = ' + lastestSnapshotDate.year());
        }

        if(querySettings != null) {
            if (querySettings.containsKey('filteringOnRecordType') &&
                    querySettings.get('filteringOnRecordType')) {
                filteringConditions.add('RecordTypeId != \'' + bookingCountryRTD + '\'');
            }
            if (divisions != null && querySettings.containsKey('filteringOnDivisions') &&
                    querySettings.get('filteringOnDivisions')) {
                if (divisions.Value__c.contains(userDivision)) {
                    filteringConditions.add('Trading_Division__c = \'' + tradingDivision + '\'');
                }
            }
        }

        String[] groupingFields;

        String[] orderFields;

        return getQuery(fieldsToQuery, objectToQuery, filteringConditions, groupingFields, orderFields);

    }

    /**
     * Method creates query String of client revenue and budget
     * @param querySettings extra filtering conditions for the query passed from controllers
     * @param lastestSnapshotDate snapshot date to be used as a filter
     * @param clientsIds list of client ids
     *
     * @return created query String
    */
    public static String getAggregatedRevenuesQuery(Map<String,Boolean> querySettings,
            Date lastestSnapshotDate, Set<Id> clientsIds){

        String tradingDivision = DMN_GlobalClientRevenue.getTradingDivisionBasedOnUserDivision();
        String userDivision = UTL_User.getUserDivision();
        CI_Parameters__c divisions = CI_Parameters__c.getValues(DCN_CustomSetting.CI_REVENUE_BUDGET_DIVISIONS_ENABLE);

        String[] fieldsToQuery = new String[] {
                'calendar_month(Snapshot_Date__c) month',
                'SUM(Client_Value_ZAR_Current_Month__c) revenue',
                'SUM(Budget_ZAR_Next_Year__c) budget'
        };
        String objectToQuery = 'Global_Client_Revenue__c';

        String[] filteringConditions = new String[] {
                'Client__c IN: clientsIds'
        };

        if (lastestSnapshotDate != null) {
            filteringConditions.add('CALENDAR_YEAR(Snapshot_Date__c) = ' + lastestSnapshotDate.year());
        }

        if(querySettings != null && divisions != null) {
            if (querySettings.get('filteringOnDivisions')) {
                if (divisions.Value__c.contains(userDivision)) {
                    filteringConditions.add('Trading_Division__c = \'' + tradingDivision + '\'');
                }
            }
        }

        String[] groupingFields = new String[]{
                'calendar_month(Snapshot_Date__c)'
        };

        String[] orderFields = new String[]{
                'calendar_month(Snapshot_Date__c)'
        };

        return getQuery(fieldsToQuery, objectToQuery, filteringConditions, groupingFields, orderFields);
    }

    /**
     * Method creates query String of client related to current user's team
     * @param querySettings extra filtering conditions for the query passed from controllers
     * @param activeClientRTIds list of active client recordtype ids
     *
     * @return created query String
    */
    public static String getMyTeamClientsQuery(Map<String,Boolean> querySettings, Id[] activeClientRTIds){


        String[] fieldsToQuery = new String[] {
                'Id'
        };
        String objectToQuery = 'Account';

        String[] filteringConditions = new String[] {
                'Id IN( SELECT Account__c FROM Custom_Client_Team__c WHERE Team_Member__c = \'' +  UserInfo.getUserId() + '\' )',
                'RecordTypeId IN :activeClientRTIds'
        };
        if(querySettings != null){
            if(querySettings.get('filteringOnIBC')) {
                filteringConditions.add('CIB_Target_Client__c = TRUE');
            }
        }

        String[] groupingFields;

        String[] orderFields;

        return getQuery(fieldsToQuery, objectToQuery, filteringConditions, groupingFields, orderFields);
    }

    /**
     * Method creates query String of client revenue
     * @param querySettings extra filtering conditions for the query passed from controllers
     * @param lastestRevSnapshotDate snapshot date to be used as a filter
     * @param clientsForRevenue list of client ids
     *
     * @return created query String
    */
    public static String getAggregatedWonRevenuesQuery(Map<String,Boolean> querySettings,
            Date lastestRevSnapshotDate, Set<Id> clientsForRevenue){

        CI_Parameters__c divisions = CI_Parameters__c.getValues(DCN_CustomSetting.CI_CY_PIPELINE_DIVISIONS_ENABLE);

        String userDivision = UTL_User.getUserDivision();

        String[] fieldsToQuery = new String[] {
                'calendar_month(Actual_Close_Date__c) month',
                'SUM(Current_Year_Revenue_Currency__c) revenue'
        };
        String objectToQuery = 'Opportunity';

        String[] filteringConditions = new String[] {
                'AccountId IN :clientsForRevenue ',
                'StageName = \'' + OpportunityService.STAGE_CLOSED_WON + '\''
        };

        if (lastestRevSnapshotDate != null) {
            filteringConditions.add('CALENDAR_YEAR(Actual_Close_Date__c) = ' + lastestRevSnapshotDate.year());
        }

        if(querySettings != null && divisions != null) {
            if (querySettings.get('filteringOnDivisions')) {
                if (divisions.Value__c.contains(userDivision)) {
                    filteringConditions.add('Opportunity_Owner_Division__c = \'' + userDivision + '\'') ;
                }
            }
        }

        String[] groupingFields = new String[]{
                'calendar_month(Actual_Close_Date__c)'
        };
        String[] orderFields = new String[]{
                'calendar_month(Actual_Close_Date__c)'
        };

        return getQuery(fieldsToQuery, objectToQuery, filteringConditions, groupingFields, orderFields);
    }

}