force-app/main/default/objects/Account/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <description>Label changed from CIF to CIF Number</description>
    <externalId>true</externalId>
    <label>CIF Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CIF_Client_Type__c.field-meta.xml
<CustomField>
    <fullName>CIF_Client_Type__c</fullName>
    <description>This Field has been created to reflect the &quot;R&quot; or &quot;W&quot; value from the CIF feed into Salesforce. R = Retail (clients owned by Personal Business Banking and W = Wholesale (clients owned by CIB Coverage) Case #252</description>
    <inlineHelpText>R = Retail (PBB) and W = Wholesale (CIB)</inlineHelpText>
    <label>CIF Client Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Coordinator_Division__c.field-meta.xml
<CustomField>
    <fullName>Client_Coordinator_Division__c</fullName>
    <description>This field will capture the Client Coordinator&apos;s user divsion value, EN-0731</description>
    <formula>TEXT(Owner.User_Division__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Coordinator Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sector__c</fullName>
    <description>Field Label Rename from &apos;CIB SA Sector&apos; to &apos;Global Sector&apos;, Nov &apos;10

#EN-226 - The primary sector in which the Client operates. This field is used in CRT and MI reporting</description>
    <inlineHelpText>The primary sector in which the Client operates</inlineHelpText>
    <label>Client Sector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Industrials</fullName>
            </value>
            <value>
                <fullName>Internal / Grouped</fullName>
            </value>
            <value>
                <fullName>Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Oil and Gas</fullName>
            </value>
            <value>
                <fullName>Power and Infrastructure</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Sovereign / Public Sector</fullName>
            </value>
            <value>
                <fullName>Telecoms and Media</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Sector__c</fullName>
    <description>The Client Sub-Sector further defines the sector in which the Client operates. This field is used in CRT and MI reporting. The business rule where a Client Sub-Sector cannot be dependent on more than one Client Sector needs to be adhered to at all times. Do not create or assign a duplicate Client Sub-Sector to more than one Client Sector</description>
    <inlineHelpText>The Client Sub-Sector further defines the sector in which the Client operates</inlineHelpText>
    <label>Client Sub-Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Sector__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Agriculture Commodity Traders</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Alternative Investment Vehicles</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automobiles</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Brokers and Exchanges</fullName>
            </value>
            <value>
                <fullName>Bulk Commodities</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Central Banks</fullName>
            </value>
            <value>
                <fullName>Centralised Power</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Construction Services</fullName>
            </value>
            <value>
                <fullName>Consumer Services</fullName>
            </value>
            <value>
                <fullName>Development Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Diamonds</fullName>
            </value>
            <value>
                <fullName>Diversified Industrials</fullName>
            </value>
            <value>
                <fullName>Diversified Mining</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equipment Manufacturers</fullName>
            </value>
            <value>
                <fullName>Food and Beverage</fullName>
            </value>
            <value>
                <fullName>Forestry</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Government Departments</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code__c</fullName>
    <description>Industry Class code from CIF (ISIC)</description>
    <inlineHelpText>Defines the isic code.</inlineHelpText>
    <label>Industry Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Relationship_Holder__c.field-meta.xml
<CustomField>
    <fullName>Primary_Relationship_Holder__c</fullName>
    <description>The field determines whether the client is a CIB or a CB client (EN-908).</description>
    <inlineHelpText>The field determines whether the client is a CIB or a PBB client (Commercial, Business, Small Enterprises or Personal)</inlineHelpText>
    <label>Primary Relationship Holder</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal Banking</fullName>
            </value>
            <value>
                <fullName>Business Banking</fullName>
            </value>
            <value>
                <fullName>Commercial Banking</fullName>
            </value>
            <value>
                <fullName>Corporate and Investment Banking</fullName>
            </value>
            <value>
                <fullName>Other PBB Divisions</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BCH_PopulateClientsSector.cls
global class BCH_PopulateClientsSector implements Database.Batchable<sObject>, Database.Stateful {

    private final String[] notifyEmails;
    global Integer successfulRecs, allRecs;

    global BCH_PopulateClientsSector(String[] emails) {
        this.notifyEmails = emails;
        this.successfulRecs = 0;
        this.allRecs = 0;
    }

    global Iterable<sObject> start(Database.BatchableContext BC) {
        return [
                SELECT Client_Coordinator_Division__c
                        , CIF__c
                        , Industry_Code__c
                        , Client_Sector__c
                        , Client_Sub_Sector__c
                        , Primary_Relationship_Holder__c
                        , CIF_Client_Type__c
                FROM Account
                WHERE Client_Coordinator_Division__c = :DMN_Account.CC_DIVISION_COMMB
                    AND CIF__c != NULL
                    AND Industry_Code__c != NULL
                    AND Primary_Relationship_Holder__c = :DMN_Account.PRIMARY_REL_HOLDER_COMMB
                    AND CIF_Client_Type__c = :DMN_Account.CLIENT_TYPE_R
        ];
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {

        Account[] accs = (Account[]) scope;

        DMN_Account.populateFieldsBasingOnIndustryCode(accs, null);

        Database.SaveResult[] srs = Database.update(accs, false);
        for (Database.SaveResult sr : srs) {
            allRecs++;
            if (sr.isSuccess()) {
                successfulRecs++;
            }
        }

    }

    global void finish(Database.BatchableContext BC) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(notifyEmails);
        email.setSubject('BCH_PopulateClientsSector completed');
        email.setPlainTextBody('Schedulded BCH_PopulateClientsSector succesfully processed ' + successfulRecs + ' out of ' + allRecs + ' records.');
        Messaging.sendEmail(new Messaging.Email[]{email});
    }

}