force-app/main/default/objects/Account/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <description>Label changed from CIF to CIF Number</description>
    <externalId>true</externalId>
    <label>CIF Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sector__c</fullName>
    <description>Field Label Rename from &apos;CIB SA Sector&apos; to &apos;Global Sector&apos;, Nov &apos;10

#EN-226 - The primary sector in which the Client operates. This field is used in CRT and MI reporting</description>
    <inlineHelpText>The primary sector in which the Client operates</inlineHelpText>
    <label>Client Sector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Industrials</fullName>
            </value>
            <value>
                <fullName>Internal / Grouped</fullName>
            </value>
            <value>
                <fullName>Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Oil and Gas</fullName>
            </value>
            <value>
                <fullName>Power and Infrastructure</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Sovereign / Public Sector</fullName>
            </value>
            <value>
                <fullName>Telecoms and Media</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hierarchy_Fields__c/Hierarchy_Fields__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Hierarchy Fields</label>
</CustomObject>

force-app/main/default/objects/Hierarchy_Fields__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PickListMultiSelect_Test.cls
/******************************************************************************************************************************
* Name        - PickListMultiSelect_Test
* Description - Test Class for PickListMultiSelect Controller
* Modification Log :
* ---------------------------------------------------------------------------
* Developer                   Date                   Description
* ---------------------------------------------------------------------------
* Abhishek                  17/03/1026                 Created
*******************************************************************************************************************************/

@isTest
public class PickListMultiSelect_Test{
    public static testmethod void testMultiselectPicklist_withfieldsSelected(){
         List<Hierarchy_Fields__c> hrlst = new List<Hierarchy_Fields__c>();
         Hierarchy_Fields__c hf1 = new Hierarchy_Fields__c(Name = 'Account::CIF__c', Field_Label__c = 'CIF Number', Object_Name__c = 'Account', Sort_Order__c = 1);
         Hierarchy_Fields__c hf2 = new Hierarchy_Fields__c(Name = 'Account::Client_Sector__c', Field_Label__c = 'Client Sector', Object_Name__c = 'Account', Sort_Order__c = 2);
         hrlst.add(hf1);
         hrlst.add(hf2);
         insert hrlst;
         PickListMultiSelect controller = new PickListMultiSelect();
         controller.describeObject();
         controller.getAvblFields();
         controller.getAvblobjects();
         controller.getFieldsInSelectList();
         List<String> parameters = new List<String>();
         parameters.add('Test Parameter');
         controller.setFieldsSelected(parameters);
         controller.getFieldsSelected();
         controller.addFields();
         controller.getAvblFields();
         controller.getFieldsInSelectList();
         controller.setremoveList(parameters);
         controller.getremoveList();
         controller.removeFields();
         controller.getAvblFields();
         controller.SaveHierarchyColumns();
         System.assertEquals(controller.ObjectSelected, 'Account');
         System.assertEquals(controller.showOrderSort, True);
         System.assertEquals(controller.Selected.size() , 2);
         controller.back();
   }
   public static testmethod void testMultiselectPicklist_withnoneSelected(){
         PickListMultiSelect controller = new PickListMultiSelect();
         controller.describeObject();
         controller.getAvblFields();
         controller.getAvblobjects();
         controller.getFieldsInSelectList();
         List<String> parameters = new List<String>();
         parameters.add('Test Parameter');
         controller.setFieldsSelected(parameters);
         controller.getFieldsSelected();
         controller.addFields();
         controller.getAvblFields();
         controller.getFieldsInSelectList();
         controller.setremoveList(parameters);
         controller.getremoveList();
         controller.removeFields();
         controller.getAvblFields();
         controller.SaveHierarchyColumns();
         System.Debug(controller.showOrderSort);
         System.assertEquals(controller.ObjectSelected, 'Account');
         System.assertEquals(controller.Selected.size() , 0);
         controller.back();
   }
}