force-app/main/default/objects/Account/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <description>Label changed from CIF to CIF Number</description>
    <externalId>true</externalId>
    <label>CIF Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sector__c</fullName>
    <description>Field Label Rename from &apos;CIB SA Sector&apos; to &apos;Global Sector&apos;, Nov &apos;10

#EN-226 - The primary sector in which the Client operates. This field is used in CRT and MI reporting</description>
    <inlineHelpText>The primary sector in which the Client operates</inlineHelpText>
    <label>Client Sector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Industrials</fullName>
            </value>
            <value>
                <fullName>Internal / Grouped</fullName>
            </value>
            <value>
                <fullName>Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Oil and Gas</fullName>
            </value>
            <value>
                <fullName>Power and Infrastructure</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Sovereign / Public Sector</fullName>
            </value>
            <value>
                <fullName>Telecoms and Media</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CRT_Parent_Child__c.field-meta.xml
<CustomField>
    <fullName>CRT_Parent_Child__c</fullName>
    <label>CRT Parent Child</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>IP</fullName>
            </value>
            <value>
                <fullName>TP</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CST_Allowed_Combinations__c/CST_Allowed_Combinations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CST - dependency between role and user global area</description>
    <label>CST Allowed Combinations</label>
</CustomObject>

force-app/main/default/objects/CST_Allowed_Combinations__c/fields/Opportunity_Team_Roles__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Team_Roles__c</fullName>
    <description>These roles have to be use with given User global area. The name of roles are separated by comma.</description>
    <label>Opportunity Team Roles</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CST_Allowed_Combinations__c/fields/Unique_Team_Roles__c.field-meta.xml
<CustomField>
    <fullName>Unique_Team_Roles__c</fullName>
    <label>Unique Team Roles</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CST_Allowed_Combinations__c/fields/User_Global_Area__c.field-meta.xml
<CustomField>
    <fullName>User_Global_Area__c</fullName>
    <description>Name of Commercial Banking user global area. Users with this global area must be in specific roles.</description>
    <label>User Global Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Short_Summary__c.field-meta.xml
<CustomField>
    <fullName>Short_Summary__c</fullName>
    <description>Devesh : 03sept 2010 - this is a Mandattory field for the user to key in a short description about the opportunity</description>
    <inlineHelpText>The Short Summary is mandatory and is used for Manco / Exco Opportunity reporting  (100 characters or less)</inlineHelpText>
    <label>Short Summary</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityTeamMember/fields/User_CIB_Global_Area__c.field-meta.xml
<CustomField>
    <fullName>User_CIB_Global_Area__c</fullName>
    <description>EN-101</description>
    <formula>TEXT(User.User_CIB_Global_Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User CIB Global Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityTeamMember/fields/User_Division__c.field-meta.xml
<CustomField>
    <fullName>User_Division__c</fullName>
    <description>EN-101</description>
    <formula>TEXT(User.User_Division__c )</formula>
    <label>User Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>User Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>User_Division__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Bank Sector</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Br71C Regional Sales</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Business Acquisition</fullName>
            </value>
            <value>
                <fullName>Business Banking Channel</fullName>
            </value>
            <value>
                <fullName>Business Banking Channel Head Office</fullName>
            </value>
            <value>
                <fullName>Business Banking Head Office</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Buy-Side</fullName>
            </value>
            <value>
                <fullName>Cape Head</fullName>
            </value>
            <value>
                <fullName>Capital Markets</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>CDG</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>China/Africa</fullName>
            </value>
            <value>
                <fullName>CIB</fullName>
            </value>
            <value>
                <fullName>Client Access</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
            <value>
                <fullName>Client Onboarding</fullName>
            </value>
            <value>
                <fullName>Client Service</fullName>
            </value>
            <value>
                <fullName>Client Services Operation</fullName>
            </value>
            <value>
                <fullName>Client Solutions</fullName>
            </value>
            <value>
                <fullName>Coastal Region</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Channel</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Channel Head Office</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Head Office</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/RecieveBirthdayReminderTasks__c.field-meta.xml
<CustomField>
    <fullName>RecieveBirthdayReminderTasks__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is set to indicate if a user wants to receive a birthday reminder for those contacts that they have an interest in as recorded on the SA Contact Team Member object.

            (CRM Birthday Reminder Case# 207 C Reinecke 2010/09)</description>
    <inlineHelpText>Indicate if you would like to receive birthday reminders for contacts that you are the owner or client owner of or that you are on the client contact team.</inlineHelpText>
    <label>Birthday Reminders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Sync_with_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sync_with_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>SHAVEEN06DEC2010 CASE599 &gt; Create a new contact for this USER, else find the BANK CONTACT based on SAM ACCOUNT name and link its BANK CONTACT&apos;s ID to this USER.</description>
    <label>Sync with Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/User_CIB_Global_Area__c.field-meta.xml
<CustomField>
    <fullName>User_CIB_Global_Area__c</fullName>
    <label>User CIB Global Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Africa Regions</fullName>
            </value>
            <value>
                <fullName>CIBI</fullName>
            </value>
            <value>
                <fullName>CIBROA</fullName>
            </value>
            <value>
                <fullName>CIBSA</fullName>
            </value>
            <value>
                <fullName>CIB Global</fullName>
            </value>
            <value>
                <fullName>BCC</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>PBB SA</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_Division__c.field-meta.xml
<CustomField>
    <fullName>User_Division__c</fullName>
    <label>User Division</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>User_CIB_Global_Area__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Banking</fullName>
            </value>
            <value>
                <fullName>Business Enablers</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
            <value>
                <fullName>Client Services</fullName>
            </value>
            <value>
                <fullName>Client Solutions</fullName>
            </value>
            <value>
                <fullName>Commercial Banking</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>Entrepreneur</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>Global Markets</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Small Enterprise</fullName>
            </value>
            <value>
                <fullName>Transactional Products and Services</fullName>
            </value>
            <value>
                <fullName>Vehicle and Asset Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityTeamMemberHelper_Test.cls
/*****************************************************************************************************\
    @ Author        : Petr Roubal
    @ Date          :  January 2016
    @description   : Test class for OpportunityTeamMemberHelper and OpportunityTeamMemberTrigger
 ******************************************************************************************************/

@IsTest(seeAllData=false)
private class OpportunityTeamMemberHelper_Test {

    private static Map<String, Schema.RecordTypeInfo> mapAccountRecordTypes = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
    private final static Id UGP_REC_TYPE_ID  = mapAccountRecordTypes.get('Ultimate Group Parent').getRecordTypeId();
    @TestSetup
    private static void prepareData() {
            CST_Allowed_Combinations__c cstAllowedCombinations = new CST_Allowed_Combinations__c(
                Name = 'OTM CommB',
                Opportunity_Team_Roles__c = 'BCC Portfolio Manager\nBCC Product Specialist\nBCC Service Manager\nBCC Relationship Manager\nBCC Business Development Manager\nOriginator - Primary\nBCC CSU Agent\nBCC CSU Manager',
                Unique_Team_Roles__c = DMN_ClientTeam.ROLE_COMMB_RELATION_MANGER,
                User_Global_Area__c = DMN_User.CIB_GA_COMMB
            );
        	insert cstAllowedCombinations;
    }
    static testMethod void testTriggerFuncionality() {
        // create user with CommB
        List<User> users = new List<User>();
        User userCC = createUser(DCN_Profile.CUSTOM_STD_MOBILE, 'user_test0041_cc@testorg.com');
        userCC.User_CIB_Global_Area__c = 'BCC';
        userCC.user_division__c = 'Commercial Banking';
        users.add(userCC);

        userCC = createUser(DCN_Profile.CUSTOM_STD_MOBILE, 'user_test0041_cc@testorg.com');
        userCC.User_CIB_Global_Area__c = 'CIBSA';
        users.add(userCC);

        insert users;

        Account acc;
        Opportunity opp;
        system.runas(users[0]){
            acc = CreateAccount();
            insert acc;

            opp = new Opportunity();
            opp.AccountId= acc.Id;
            opp.Name= 'Opportunity_'+ acc.Name;
            opp.CloseDate=System.today();
            opp.StageName='2 - Develop';
            opp.Short_Summary__c = 'test opportunity';
            opp.CurrencyIsoCode = 'ZAR';

            insert opp;
        }
        OpportunityTeamMember otm = [Select Id, TeamMemberRole, UserId from OpportunityTeamMember where OpportunityId = :opp.Id ];
		otm.TeammemberRole = DMN_ClientTeam.ROLE_COMMB_RELATION_MANGER;
        update otm;
        system.assertEquals(users[0].id,otm.UserId);
        system.assertEquals(otm.TeammemberRole, DMN_ClientTeam.ROLE_COMMB_RELATION_MANGER);

        system.runas(users[1]){
            acc = CreateAccount();
            acc.Name = '2nd Test Client';
            acc.CIF__c = '4321';
            insert acc;

            opp = new Opportunity();
            opp.AccountId= acc.Id;
            opp.Name= 'Opportunity_'+ acc.Name;
            opp.CloseDate=System.today();
            opp.StageName='2 - Develop';
            opp.Short_Summary__c = 'test opportunity';
            opp.CurrencyIsoCode = 'ZAR';

            insert opp;
        }

        otm = [Select Id, TeamMemberRole, UserId from OpportunityTeamMember where OpportunityId = :opp.Id ];
		otm.TeammemberRole = DMN_ClientTeam.ROLE_BUSINESS;
        update otm;
        system.assertEquals(users[1].id,otm.UserId);
        system.assertEquals(otm.TeammemberRole, DMN_ClientTeam.ROLE_BUSINESS);

    }

    private static user createUser(string profile, string username) {
        username = Math.random()+ username;
        user newUser;
        try {
            Profile userProfile = [select Name from Profile where Name = : profile];
            newUser = new User(alias = String.valueOf(Math.random()).substring(0,7),
                    email = 'one@testorg.com',
                    emailencodingkey = 'UTF-8',
                    lastname = profile + ' User',
                    languagelocalekey = 'en_US',
                    city = 'Smallville',
                    User_Division__c = 'Client Coverage',
                    Business_Unit__c = 'Client Coverage',
                    User_CIB_Global_Area__c = 'BCC',
                    country = 'South Africa',
                    State = 'Test State',
                    RecieveBirthdayReminderTasks__c = true,
                    Sync_with_Contact__c = false,
                    localesidkey = 'en_US',
                    profileid = userProfile.Id,
                    timezonesidkey = 'Africa/Johannesburg',
                    username = username,
                    ManagerId = [Select Id from User Where Name = 'Salesforce Administration'].Id);
        } Catch(Exception e) {
            system.assertEquals('List has no rows for assignment to SObject', e.getMessage());
        }
        return newUser;
    }

    private static Account createAccount() {
        Account acc = new Account();
        acc.RecordTypeId = UGP_REC_TYPE_ID;
        acc.CRT_Parent_Child__c = 'TP';
        acc.Name = 'Test Client';
        acc.BillingStreet = 'Test street';
        acc.Client_Sector__c = 'Unknown Sector';
        acc.Client_Sub_Sector__c = 'Unknown Sub-Sector';
        acc.Client_Segment__c = 'AB';
        acc.Country_Risk__c = 'India';
        acc.Correspondence_Addr_Line1__c = 'Test Street Line 1';
        acc.Correspondence_City__c = 'City';
        acc.Correspondence_Postal_Code__c = '123456';
        acc.Correspondence_Country__c = 'India';
        acc.BillingCountry = 'South Africa';
        acc.BillingCity = 'Durban';

        acc.CIF__c = '1234';

        return acc;
    }



}