force-app/main/default/objects/Account/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <description>Label changed from CIF to CIF Number</description>
    <externalId>true</externalId>
    <label>CIF Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Sector__c</fullName>
    <description>The Client Sub-Sector further defines the sector in which the Client operates. This field is used in CRT and MI reporting. The business rule where a Client Sub-Sector cannot be dependent on more than one Client Sector needs to be adhered to at all times. Do not create or assign a duplicate Client Sub-Sector to more than one Client Sector</description>
    <inlineHelpText>The Client Sub-Sector further defines the sector in which the Client operates</inlineHelpText>
    <label>Client Sub-Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Sector__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Agriculture Commodity Traders</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Alternative Investment Vehicles</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automobiles</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Brokers and Exchanges</fullName>
            </value>
            <value>
                <fullName>Bulk Commodities</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Central Banks</fullName>
            </value>
            <value>
                <fullName>Centralised Power</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Construction Services</fullName>
            </value>
            <value>
                <fullName>Consumer Services</fullName>
            </value>
            <value>
                <fullName>Development Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Diamonds</fullName>
            </value>
            <value>
                <fullName>Diversified Industrials</fullName>
            </value>
            <value>
                <fullName>Diversified Mining</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equipment Manufacturers</fullName>
            </value>
            <value>
                <fullName>Food and Beverage</fullName>
            </value>
            <value>
                <fullName>Forestry</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Government Departments</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/Global_Client_Revenue__c.object-meta.xml
<CustomObject>
    <description>Case #1263 - Client Overview - Stores Global Client Revenue by reporting country data that is fed into salesforce on a monthly basis by CRT. The data from this object should only be shown on the client overview page and only be visible to the client owner and members on the client service team.</description>
    <label>Global Client Revenue</label>
    <nameField>
        <displayFormat>GCR-{0000000000}</displayFormat>
        <label>Global Client Revenue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Client Revenue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to Client Object</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Global Client Revenue</relationshipLabel>
    <relationshipName>Global_Client_Revenue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Client_CIF_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_CIF_Number__c</fullName>
    <label>Client CIF Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Client_Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Sector__c</fullName>
    <description>Client&apos;s Sub-Sector</description>
    <inlineHelpText>Client&apos;s Sub-Sector</inlineHelpText>
    <label>Client Sub-Sector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/recordTypes/Booking_Country_Current_Previous_year.recordType-meta.xml
<RecordType>
    <fullName>Booking_Country_Current_Previous_year</fullName>
    <active>true</active>
    <description>This record type captures the booking country revenue information for previous and current year (US-4059).</description>
    <label>Booking Country Current &amp; Previous year</label>
</RecordType>

force-app/main/default/objects/Global_Client_Revenue__c/recordTypes/Current_Previous_Year.recordType-meta.xml
<RecordType>
    <fullName>Current_Previous_Year</fullName>
    <active>true</active>
    <description>This record type captures the information of Revenue for previous and current year</description>
    <label>Current &amp; Previous Year</label>
</RecordType>

force-app/main/default/objects/Global_Client_Revenue__c/recordTypes/Historical_Revenue.recordType-meta.xml
<RecordType>
    <fullName>Historical_Revenue</fullName>
    <active>true</active>
    <description>This record type captures the monthly revenue information</description>
    <label>Historical Revenue</label>
</RecordType>

force-app/main/default/classes/DMN_GlobalClientRevenue.cls
/**
 * Domain layer class for GlobalClientRevenue SObject
 *
 * @author Unknown
 * @date Unknown
 */
public inherited sharing class DMN_GlobalClientRevenue {

	public static final String
			OBJ_NAME='Global_Client_Revenue__c',
			RTD_BOOKING_COUNTRY = 'Booking_Country_Current_Previous_year',
			RTD_CURRENT_PREVIOUS_YEAR = 'Current_Previous_Year',
			RTD_HISTORICAL_REVENUE = 'Historical_Revenue',
			TRADING_DIVISION_GLOBAL_MARKET = 'GM',
			TRADING_DIVISION_OTHER = 'Other',
			TRADING_DIVISION_INVESTMENT_BANKING = 'IB',
			TRADING_DIVISION_RANSACTIONAL_PRODUCTS_AND_SERVICES = 'TPS',
			TRADING_DIVISION_VEHICLE_AND_ASSET_FINANCE = 'VAF',
			DIVISION_PRODUCT_SUBSETS_CREDIT = 'Credit',
			DIVISION_PRODUCT_SUBSETS_TRADE = 'Trade', 
			DIVISION_PRODUCT_SUBSETS_ADVISORY = 'Advisory',
			DIVISION_PRODUCT_SUBSETS_CAPITAL_MARKETS = 'Capital Markets',
			REPORTING_COUNTRY_SA = 'SA',
			CRT_RECORD_TYPE = 'CRT Global Client Revenue';

	/**
	 * Method updates global client revenue subsectors to related client subsectors
	 *
	 * @param accIds set of client ids
	*/
	public static void updateSubsectors(Set<Id> accIds){

		Global_Client_Revenue__c[] gcrs = new Global_Client_Revenue__c[]{};

		for(Global_Client_Revenue__c gcr : [SELECT Client__r.Client_Sub_Sector__c, Client_Sub_Sector__c
		FROM Global_Client_Revenue__c
		WHERE Client__c IN : accIds]){
			if(gcr.Client_Sub_Sector__c != gcr.Client__r.Client_Sub_Sector__c){
				gcr.Client_Sub_Sector__c = gcr.Client__r.Client_Sub_Sector__c;
				gcrs.add(gcr);
			}
		}
		if(!gcrs.isEmpty()){
			UTL_DmlResult.updateRecords(gcrs, false);
		}
	}

	/**
	 * Method creates a Global Client Revenue share record for specific users
	 *
	 * @param gcrIds set of gcr ids
	 * @param userIds set of user ids
	 * @param sharingReson row cause to share the gcr record
	 * @param accessLvl level of access on the gcr record
	 *
	 * @return list of Global Client Revenue share records
	*/
	public static Global_Client_Revenue__share[] shareGcr(Set<Id> gcrIds,
			Set<Id> userIds, String sharingReson, String accessLvl){

		Global_Client_Revenue__share[] sharingRecords = new Global_Client_Revenue__share[]{};
		for(Id gcrId : gcrIds){
			for(Id usrId : userIds){
				Global_Client_Revenue__share cls = new Global_Client_Revenue__share(ParentId  = gcrId,
						UserOrGroupId = usrId,
						AccessLevel = accessLvl);
				if(String.isNotBlank(sharingReson)){
					cls.RowCause = sharingReson;
				}
				sharingRecords.add(cls);
			}
		}
		return sharingRecords;
	}

	/**
	 * Method fetches trading division based on user division
	 *
	 * @return String representing trading division
	*/
	public static String getTradingDivisionBasedOnUserDivision(){

		String tradingDivision;
		if(UTL_User.getUserDivision() == DMN_User.TPS_DIVISION){
			tradingDivision = TRADING_DIVISION_RANSACTIONAL_PRODUCTS_AND_SERVICES;
		}
		else if(UTL_User.getUserDivision() == DMN_User.IB_DIVISION){
			tradingDivision = TRADING_DIVISION_INVESTMENT_BANKING;
		}
		else if(UTL_User.getUserDivision() == DMN_User.GM_DIVISION){
			tradingDivision = TRADING_DIVISION_GLOBAL_MARKET;
		}
		else if (UTL_User.getUserDivision() == DMN_User.VAF_DIVISION) {
			tradingDivision = TRADING_DIVISION_VEHICLE_AND_ASSET_FINANCE;
		}

		return tradingDivision;
	}

	/**
	 * Method assigning and verifying Client from CIF Number
	 * @param newRecords - List of new Global Client Revenues records created or updated
	*/
	public static void assignClientFromCifNumber(List<Global_Client_Revenue__c> newRecords){
		Set<String> cifNumbers = new Set<String>();
		Map<String,Id> accountMap = new Map<String,Id>();
		Map<String,String> subSectorMap = new Map<String,String>();

		for(Global_Client_Revenue__c gcr : newRecords){
			cifNumbers.add(gcr.Client_CIF_Number__c);
		}

		for(Account accountsToMap : SEL_Accounts.newInstance().selectByCIFNumber(cifNumbers)){
			accountMap.put(accountsToMap.CIF__c,accountsToMap.Id);
			subSectorMap.put(accountsToMap.CIF__c, accountsToMap.Client_Sub_Sector__c);
		}
        
        Id crtRecordTypeId = Schema.SObjectType.Global_Client_Revenue__c.getRecordTypeInfosByName().get(CRT_RECORD_TYPE).getRecordTypeId();

		for(Global_Client_Revenue__c gcr : newRecords){
			gcr.Client__c = accountMap.get(gcr.Client_CIF_Number__c);
			gcr.Client_Sub_Sector__c = subSectorMap.get(gcr.Client_CIF_Number__c);
			if(gcr.RecordTypeId == crtRecordTypeId && gcr.Client_CIF_Number__c != null && gcr.Client__c == null){
				gcr.addError('Invalid CIF Number. Client with this CIF Number does not exist');
			}
		}
	}
}