force-app/main/default/objects/Account/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <description>Label changed from CIF to CIF Number</description>
    <externalId>true</externalId>
    <label>CIF Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/Custom_Client_Team__c.object-meta.xml
<CustomObject>
    <label>Client Team</label>
    <nameField>
        <displayFormat>Client-{0000}</displayFormat>
        <label>Client Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Client_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Access__c.field-meta.xml
<CustomField>
    <fullName>Client_Access__c</fullName>
    <label>Client Access</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full Access</fullName>
            </value>
            <value>
                <fullName>Read/Write</fullName>
                <default>true</default>
                <label>Read/Write</label>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Role__c.field-meta.xml
<CustomField>
    <fullName>Client_Role__c</fullName>
    <label>Team Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Account Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Business Development Manager</fullName>
            </value>
            <value>
                <fullName>BCC CSU Agent</fullName>
            </value>
            <value>
                <fullName>BCC CSU Manager</fullName>
            </value>
            <value>
                <fullName>BCC Ecosystem Manager</fullName>
            </value>
            <value>
                <fullName>BCC Head Trade Sales</fullName>
            </value>
            <value>
                <fullName>BCC Portfolio Manager</fullName>
            </value>
            <value>
                <fullName>BCC Product Specialist</fullName>
            </value>
            <value>
                <fullName>BCC Relationship Manager</fullName>
            </value>
            <value>
                <fullName>BCC Service Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Finance Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Client Analyst</fullName>
            </value>
            <value>
                <fullName>Credit Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Consultant</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Executive Stakeholder</fullName>
            </value>
            <value>
                <fullName>Global Transaction Banker</fullName>
            </value>
            <value>
                <fullName>GM Champion</fullName>
            </value>
            <value>
                <fullName>GM Client Manager</fullName>
            </value>
            <value>
                <fullName>GM Execution Manager</fullName>
            </value>
            <value>
                <fullName>GM Regional Head</fullName>
            </value>
            <value>
                <fullName>IB Champion</fullName>
            </value>
            <value>
                <fullName>Investor Services Manager</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/Global_Client_Revenue__c.object-meta.xml
<CustomObject>
    <description>Case #1263 - Client Overview - Stores Global Client Revenue by reporting country data that is fed into salesforce on a monthly basis by CRT. The data from this object should only be shown on the client overview page and only be visible to the client owner and members on the client service team.</description>
    <label>Global Client Revenue</label>
    <nameField>
        <displayFormat>GCR-{0000000000}</displayFormat>
        <label>Global Client Revenue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Client Revenue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Budget_ZAR_Next_Year__c.field-meta.xml
<CustomField>
    <fullName>Budget_ZAR_Next_Year__c</fullName>
    <description>Used to store the Budget for next year in ZAR</description>
    <label>Budget ZAR Next Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to Client Object</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Global Client Revenue</relationshipLabel>
    <relationshipName>Global_Client_Revenue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Client_CIF_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_CIF_Number__c</fullName>
    <label>Client CIF Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Client_Value_ZAR_Current_Year__c.field-meta.xml
<CustomField>
    <fullName>Client_Value_ZAR_Current_Year__c</fullName>
    <description>Used to store the Current Year ZAR value</description>
    <inlineHelpText>YTD amount for the current year</inlineHelpText>
    <label>Client Value ZAR Current Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <description>Team member object connects either internal staff or contractors to a project assignment.  If you further customize the application, you can prevent &quot;stray time reporting&quot; using apex coding so that team members cannot report time outside of the assigned date range.  This becomes important if your organization reports heavily on project costing or SOP-98 capital/expense.  in addition, Force.com Visualforce or Adobe Flex code can be leveraged to help with the matching of resources to projects/work requests.  Please contact professional services for more information on consulting rates or the Salesforce.com Developer network (www.salesforce.com/developer).</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is a lookup to the user and used to assign internal staff to a project team member.</inlineHelpText>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N80000002lXWPEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CI_ClientListControllerTest.cls
@isTest(SeeAllData=false)
public class CI_ClientListControllerTest{
    private static User user;
    //test method
    private static testMethod void ClientListTest(){

        //Create Manager user
           System.runAs(new User(ID = UserInfo.getUserID())){
               user = (User) new BLD_USER().useSysAdmin().getRecord();
               insert user;
           }
        
         system.runAs(user){
         
            //create account
            RecordType parentRecordType = [select Id from RecordType where Name = 'Ultimate Group Parent' and SobjectType = 'Account' limit 1];
             List<Account> clients = new List<Account>();
            clients.add(new Account(Name ='Google EMEA CICLTest000001', billingCountry='South Africa', CIF__c = 'CICLTest000001', RecordTypeId = parentRecordType.Id));
            clients.add(new Account(Name ='Apple EMEA CICLTest000002', billingCountry='China', CIF__c = 'CICLTest000002', RecordTypeId = parentRecordType.Id));
            insert clients;            
            
            //Create Global Client Revenue record & link client
            RecordType revRT = [select Id from RecordType where Name = 'Current & Previous Year' and SobjectType = 'Global_Client_Revenue__c' limit 1];         
            List<Global_Client_Revenue__c> revenue = new List<Global_Client_Revenue__c>();
            revenue.add(New Global_Client_Revenue__c(Budget_ZAR_Next_Year__c = 1000000, Client_Value_ZAR_Current_Year__c=7000000, RecordTypeId = revRT.id, Client_CIF_Number__c='CIF123', Client__c = clients[0].id));
            revenue.add(New Global_Client_Revenue__c(Budget_ZAR_Next_Year__c = 9000000, Client_Value_ZAR_Current_Year__c=7000000, RecordTypeId = revRT.id, Client_CIF_Number__c='CIF456', Client__c = clients[0].id)); 
            revenue.add(New Global_Client_Revenue__c(Budget_ZAR_Next_Year__c = 1000000, Client_Value_ZAR_Current_Year__c=1000000, RecordTypeId = revRT.id, Client_CIF_Number__c='CIF789', Client__c = clients[1].id));
            revenue.add(New Global_Client_Revenue__c(Budget_ZAR_Next_Year__c = 4000000, Client_Value_ZAR_Current_Year__c=1000000, RecordTypeId = revRT.id, Client_CIF_Number__c='CIF901', Client__c = clients[1].id));
            insert revenue;    
            
            //Link user to client team.
            
            List<Custom_Client_Team__c> addMember = new List<Custom_Client_Team__c>();
            addMember.add(New Custom_Client_Team__c(Account__c = clients[0].id,Team_Member__c = user.id,Client_Role__c = 'Analyst',Client_Access__c = 'Full Access'));
            addMember.add(New Custom_Client_Team__c(Account__c = clients[1].id,Team_Member__c = user.id,Client_Role__c = 'Analyst',Client_Access__c = 'Full Access'));
            insert addMember;
                        
            CI_CardListObjectModel result = (CI_CardListObjectModel)CI_ClientListController.getClientList(null, 'CICLTest000001').Data;

            //Assert that a list of 1 accounts is returned.
            System.assertEquals(1 ,result.cardObjectList.size());  

        }
    }
}