force-app/main/default/objects/Account/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <description>Label changed from CIF to CIF Number</description>
    <externalId>true</externalId>
    <label>CIF Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IgnoreDrawDownValidation__c.field-meta.xml
<CustomField>
    <fullName>IgnoreDrawDownValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Case#141 - Rudolf Niehaus
If this flag gets updated, then validation rules can use this flag to skip validation with the ISCHANGED() function. The reason is that we do not want the validation to run when we update Draw Downs, else the validation will run into an endless loop</description>
    <label>IgnoreDrawDownValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <displayFormat>Oppt-{000000}</displayFormat>
    <inlineHelpText>Unique ID number automatically generated. It used for downstream systems and business processes.</inlineHelpText>
    <label>Opportunity ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Short_Summary__c.field-meta.xml
<CustomField>
    <fullName>Short_Summary__c</fullName>
    <description>Devesh : 03sept 2010 - this is a Mandattory field for the user to key in a short description about the opportunity</description>
    <inlineHelpText>The Short Summary is mandatory and is used for Manco / Exco Opportunity reporting  (100 characters or less)</inlineHelpText>
    <label>Short Summary</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/SB_Product__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Products as Standard Bank have requirements that cannot be met with standard object.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Prod-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SB_Product__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <description>Enter the expected fee amount based on the frequency.</description>
    <inlineHelpText>Enter the expected fee amount based on the frequency.</inlineHelpText>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Grand_Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Grand_Parent_Product__c</fullName>
    <description>Grand Parent Product</description>
    <label>Grand Parent Product (GPP)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Advisory Fees</fullName>
            </value>
            <value>
                <fullName>Agricultural Products</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Bank Sector Services</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Bills of exchange discounted</fullName>
            </value>
            <value>
                <fullName>Bonds</fullName>
            </value>
            <value>
                <fullName>Bulk and Steel</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Commitments</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Core Custody</fullName>
            </value>
            <value>
                <fullName>Cost Overrun Facility</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Credit Finance &amp; Leverage</fullName>
            </value>
            <value>
                <fullName>Credit Linked Notes &amp; Depo</fullName>
            </value>
            <value>
                <fullName>Cross Border Finance</fullName>
            </value>
            <value>
                <fullName>Custody Services</fullName>
            </value>
            <value>
                <fullName>Customer foreign currency accounts (CFC)</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Debtor Finance</fullName>
            </value>
            <value>
                <fullName>Debt Structuring</fullName>
            </value>
            <value>
                <fullName>Deposits</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Drafts issues</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Insurer__c.field-meta.xml
<CustomField>
    <fullName>Insurer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SFP-5354 Name of insurer SBG are collaborating with.</description>
    <inlineHelpText>Select the name of the insurance company that will underwrite the risk.</inlineHelpText>
    <label>Insurer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products (Insurer)</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <description>Parent Product</description>
    <label>Parent Product (PP)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Grand_Parent_Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Electronic Payment</fullName>
            </value>
            <value>
                <fullName>Electronic Collections</fullName>
            </value>
            <value>
                <fullName>Deposits</fullName>
            </value>
            <value>
                <fullName>Letters of Credit</fullName>
            </value>
            <value>
                <fullName>Guarantees</fullName>
            </value>
            <value>
                <fullName>Invoice Financing</fullName>
            </value>
            <value>
                <fullName>LC Discounting</fullName>
            </value>
            <value>
                <fullName>Open Account Finance</fullName>
            </value>
            <value>
                <fullName>Account Verification Service (AVS)</fullName>
            </value>
            <value>
                <fullName>Agricultural Products</fullName>
            </value>
            <value>
                <fullName>Airway Releases</fullName>
            </value>
            <value>
                <fullName>Asset-Backed Commercial Paper (ABCP)</fullName>
            </value>
            <value>
                <fullName>Asset-Backed Securitisation (ABS)</fullName>
            </value>
            <value>
                <fullName>Asset Finance</fullName>
            </value>
            <value>
                <fullName>Associate Income</fullName>
            </value>
            <value>
                <fullName>ATG</fullName>
            </value>
            <value>
                <fullName>ATG - Host to Host</fullName>
            </value>
            <value>
                <fullName>ATG - Online</fullName>
            </value>
            <value>
                <fullName>Autosafe</fullName>
            </value>
            <value>
                <fullName>Autosafe - With Cash Upload</fullName>
            </value>
            <value>
                <fullName>Autosafe - Without Value Hosting / Cash Upload</fullName>
            </value>
            <value>
                <fullName>Autosafe - With Value Hosting</fullName>
            </value>
            <value>
                <fullName>Back-to-Back Guarantee</fullName>
            </value>
            <value>
                <fullName>Back-to-Back  LC</fullName>
            </value>
            <value>
                <fullName>Bank Notes</fullName>
            </value>
            <value>
                <fullName>Base Metals Futures</fullName>
            </value>
            <value>
                <fullName>Base Metals Options</fullName>
            </value>
            <value>
                <fullName>Beyond Payments</fullName>
            </value>
            <value>
                <fullName>Bills For Collection</fullName>
            </value>
            <value>
                <fullName>Bills of Exchange Negotiated (Clean BE&apos;s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Product_Owner__c.field-meta.xml
<CustomField>
    <fullName>Product_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Only to be present on Lending and Commitment Record type</description>
    <inlineHelpText>The product person responsible for pricing and/or execution of this product</inlineHelpText>
    <label>Product Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Risk_Weighted_Value__c.field-meta.xml
<CustomField>
    <fullName>Risk_Weighted_Value__c</fullName>
    <description>Enter the probability of receiving this fee</description>
    <inlineHelpText>Enter the probability of receiving this fee</inlineHelpText>
    <label>Risk Weighted Value (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Total_Fees__c.field-meta.xml
<CustomField>
    <fullName>Total_Fees__c</fullName>
    <inlineHelpText>The Estimated Total Fees that is anticipated for this product on this opportunity.</inlineHelpText>
    <label>Total Fees</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SEL_Opportunities.cls
/**
* @description Selector layer class for Opportunity SObject
*
* @author Kyle Cockroft (kyle@bsky.co.za)
* @date 06-08-2019
*****************************************************************************************
 *   @ Last Modified By  :   Maham Hassan
 *   @ Last Modified On  :   05/04/2022
 *   @ Last Modified Reason  : Get list of Opportunities based on Ids and Account Id.
 *
 *****************************************************************************************
*/
public with sharing class SEL_Opportunities extends fflib_SObjectSelector {

    private Boolean assertCrud = true;
    private Boolean enforceFls = true;
    private Boolean includeSelectorFields = true;

    /**
     * @description Creates a new instance of the selector via the application class.
     *
     * @return
     */
    public static SEL_Opportunities newInstance(){
        return (SEL_Opportunities) ORG_Application.selector.newInstance(Opportunity.SObjectType);
    }

    /**
     * @description Returns the list of Opportunity fields
     *
     * @return List of fields
     */
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            	Opportunity.Id,
                Opportunity.Name,
                Opportunity.StageName,
                Opportunity.Amount,
                Opportunity.Probability,
                Opportunity.CloseDate,
                Opportunity.IgnoreDrawDownValidation__c,
                Opportunity.Short_Summary__c,
                Opportunity.Opportunity_ID__c,
                Opportunity.CurrencyIsoCode
			};
    }

    /**
     * @description Returns the SObject type
     *
     * @return Sobject type
     */
    public Schema.SObjectType getSObjectType(){
        return Opportunity.sObjectType;
    }

    /**
     * @description Set assertCrud field's value. Field can be used when creating instance of fflib_QueryFactory to assert running user's
     *              CRUD on object.
     *
     * @param assertCrud
      *
     * @return
     */
    public SEL_Opportunities withCrudAssert(Boolean assertCrud) {
        this.assertCrud = assertCrud;
        return this;
    }

    /**
     * @description Set enforceFls field's value. Field can be used when creating instance of fflib_QueryFactory to enforce running user's
     *              FLS on object.
     *
     * @param enforceFls
     *
     * @return
     */
    public SEL_Opportunities withFlsEnforced(Boolean enforceFls) {
        this.enforceFls = enforceFls;
        return this;
    }

    /**
     * @description Set includeSelectorFields field's value. Field can be used when creating instance of fflib_QueryFactory to include SObject's fields returned
     *              by getSObjectFieldList method.
     *
     * @param includeSelectorFields
     *
     * @return
     */
    public SEL_Opportunities includeSelectorFields(Boolean includeSelectorFields){
        this.includeSelectorFields = includeSelectorFields;
        return this;
    }

    /**
     * @description Selects opportunities by Ids
     *
     * @param idSet
     *
     * @return List of opportunities
     */
    public List<Opportunity> selectById(Set<ID> idSet) {
		return (List<Opportunity>) selectSObjectsById(idSet);
    }

    /**
     * @description Selects opportunities by Ids and grandparent product type
     *
     * @param opportunityIds
     * @param grandParentProductType
     *
     * @return List of opportunities
     */
    public List<Opportunity> selectByOppIdAndGrandParentProductType(Set<ID> opportunityIds, String grandParentProductType){         
        fflib_QueryFactory oQF = newQueryFactory().setCondition('Id IN :opportunityIds');
		fflib_QueryFactory oliQF = oQF.subSelectQuery('Products__r')
            .selectField('Id')
            .selectField('Grand_Parent_Product__c')
            .selectField('Parent_Product__c')
            .selectField('Risk_Weighted_Value__c')
            .selectField('Fee_Amount__c')
            .selectField('Total_Fees__c')
            .selectField('RecordTypeId')
            .setCondition('Grand_Parent_Product__c = :grandParentProductType');
        return Database.query(oQF.toSOQL());
    }

    /**
     * @description Selects opportunities by CIF number, User Id and start date
     *
     * @param cif
     * @param userId
     * @param startDate
     *
     * @return List of opportunities
     */
    public List<Opportunity> selectByCIFNumberWithStartDate(Set<String> cif, String userId, Date startDate) {
        cif.remove(null);
        String condition = 'OwnerId=:userId AND CreatedDate>=:startDate AND StageName!=\''+DMN_Opportunity.ST_CLOSED_CANCEL+'\' AND Account.CIF__c in:cif';
        return (List<Opportunity>) Database.query(newQueryFactory()
                .setCondition(condition)
                .selectField('Account.CIF__c')
                .selectField('Account.Name')
                .selectField('Owner.Name')
                .toSOQL());
    }


    /**
     * @description Select opportunities with team members
     *
     * @param ids - set of opportunity Ids
     *
     * @return List of opportunities
     */
    public List<Opportunity> selectByIdWithActiveTeamMembers(Set<Id> ids){
        fflib_QueryFactory oppQF = newQueryFactory().setCondition('Id IN :ids');
        fflib_QueryFactory oppTeamQF = oppQF.subSelectQuery('OpportunityTeamMembers')
                .setCondition('IsActive__c = \'True\'')
                .selectField('UserId');
        return (List<Opportunity>) Database.query(oppQF.toSOQL());
    }

    /**
     * @description Select record by Ids without enforcing CRUD and FLS
     *
     * @param ids
     *
     * @return
     */
    public List<Opportunity> selectByIdsWithoutCrudAndFlsEnforcement(Set<Id> ids){
        return Database.query(newQueryFactory(false, false, true).setCondition('Id IN :ids').toSOQL());
    }

    /**
     * @description Select record by Ids without enforcing CRUD and FLS
     *
     * @param ids 
     *
     * @return
     */
    public List<Opportunity> selectByIdsWithoutSharing(Set<Id> ids){
        String query = newQueryFactory(assertCrud, enforceFls, includeSelectorFields).setCondition('Id IN :ids').toSOQL();
        return new WithoutSharing().selectByIdsWithoutSharing(ids, query);
    }

    /**
     * @description Select record by Ids without enforcing CRUD and FLS
     *
     * @param accountIds Set of Account Ids
     *
     * @return List of Opportunities
     */
    public List<Opportunity> selectByAccountIds(Set<Id> accountIds){
        return (List<Opportunity>) Database.query(newQueryFactory(false, false, true).setCondition('AccountId In :accountIds').toSOQL());
        
    }


    /**
     * @description Select record by Ids 
     *
     * @param ids Set of Ids of Opportunities
     *
     * @return List of Opportunities
     */
    public List<Opportunity> selectByIds(Set<Id> ids){
        return (List<Opportunity>) Database.query(newQueryFactory(false, false, true).setCondition('Id IN :ids').toSOQL());
        
    }


    /**
    * @description Sub class to query data without sharing
    * 
    */
    private without sharing class WithoutSharing{
        /**
        * @description select opportunities by WhatId and RecordTypeId
        * @param ids
        * @param query
        * @return List<Opportunity> - with query results
        */
        private List<Opportunity> selectByIdsWithoutSharing(Set<Id> ids, String query){
            return (List<Opportunity>) Database.query(query);
        }
    }
}