force-app/main/default/objects/Account/fields/Client_Managed_By__c.field-meta.xml
<CustomField>
    <fullName>Client_Managed_By__c</fullName>
    <description>Business division responsible for the main relationship management in Standard Bank. This field is used by MI to segment the Client. This field will be updated after the Client Base reviews have been done as a data component.</description>
    <inlineHelpText>Business division responsible for the main relationship management in Standard Bank</inlineHelpText>
    <label>Client Managed By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Enablers</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>Global Markets</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Transactional Products and Services</fullName>
            </value>
            <value>
                <fullName>Unmanaged</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERABatchUpdateRequired__c.field-meta.xml
<CustomField>
    <fullName>ERABatchUpdateRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Helps identify if ERA associated with Event Reports of the client need to be updated w.r.t to EN 661</description>
    <label>ERABatchUpdateRequired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/Custom_Client_Team__c.object-meta.xml
<CustomObject>
    <label>Client Team</label>
    <nameField>
        <displayFormat>Client-{0000}</displayFormat>
        <label>Client Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Client_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Case_Access__c.field-meta.xml
<CustomField>
    <fullName>Case_Access__c</fullName>
    <label>Case Access</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
                <default>true</default>
                <label>Read Only</label>
            </value>
            <value>
                <fullName>Read/Write</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Access__c.field-meta.xml
<CustomField>
    <fullName>Client_Access__c</fullName>
    <label>Client Access</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full Access</fullName>
            </value>
            <value>
                <fullName>Read/Write</fullName>
                <default>true</default>
                <label>Read/Write</label>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Client_Coordinator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to specify the Client Coordinator in the Service Team</description>
    <inlineHelpText>Is this Client Team Member the Client Coordinator?</inlineHelpText>
    <label>CC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Managed_By__c.field-meta.xml
<CustomField>
    <fullName>Client_Managed_By__c</fullName>
    <formula>TEXT(Account__r.Client_Managed_By__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Managed By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Role__c.field-meta.xml
<CustomField>
    <fullName>Client_Role__c</fullName>
    <label>Team Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Account Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Business Development Manager</fullName>
            </value>
            <value>
                <fullName>BCC CSU Agent</fullName>
            </value>
            <value>
                <fullName>BCC CSU Manager</fullName>
            </value>
            <value>
                <fullName>BCC Ecosystem Manager</fullName>
            </value>
            <value>
                <fullName>BCC Head Trade Sales</fullName>
            </value>
            <value>
                <fullName>BCC Portfolio Manager</fullName>
            </value>
            <value>
                <fullName>BCC Product Specialist</fullName>
            </value>
            <value>
                <fullName>BCC Relationship Manager</fullName>
            </value>
            <value>
                <fullName>BCC Service Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Finance Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Client Analyst</fullName>
            </value>
            <value>
                <fullName>Credit Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Consultant</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Executive Stakeholder</fullName>
            </value>
            <value>
                <fullName>Global Transaction Banker</fullName>
            </value>
            <value>
                <fullName>GM Champion</fullName>
            </value>
            <value>
                <fullName>GM Client Manager</fullName>
            </value>
            <value>
                <fullName>GM Execution Manager</fullName>
            </value>
            <value>
                <fullName>GM Regional Head</fullName>
            </value>
            <value>
                <fullName>IB Champion</fullName>
            </value>
            <value>
                <fullName>Investor Services Manager</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Contact_Access__c.field-meta.xml
<CustomField>
    <fullName>Contact_Access__c</fullName>
    <label>Contact Access</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Read/Write</fullName>
                <default>true</default>
                <label>Read/Write</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Opportunity_Access__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Access__c</fullName>
    <label>Opportunity Access</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
                <default>true</default>
                <label>Private</label>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Read/Write</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/SourceFlag__c.field-meta.xml
<CustomField>
    <fullName>SourceFlag__c</fullName>
    <defaultValue>11</defaultValue>
    <description>Flag to determine the Origin and intention of the operation
10 - Standard Save Button
11 - API Mode
12 - Replace Operation</description>
    <label>SourceFlag</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/TeamRoleSortValue__c.field-meta.xml
<CustomField>
    <fullName>TeamRoleSortValue__c</fullName>
    <description>CST Phase (3)  - Core team role ranking values .</description>
    <label>Sort</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/User_Division__c.field-meta.xml
<CustomField>
    <fullName>User_Division__c</fullName>
    <formula>TEXT(Team_Member__r.User_Division__c)</formula>
    <label>User Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <description>Team member object connects either internal staff or contractors to a project assignment.  If you further customize the application, you can prevent &quot;stray time reporting&quot; using apex coding so that team members cannot report time outside of the assigned date range.  This becomes important if your organization reports heavily on project costing or SOP-98 capital/expense.  in addition, Force.com Visualforce or Adobe Flex code can be leveraged to help with the matching of resources to projects/work requests.  Please contact professional services for more information on consulting rates or the Salesforce.com Developer network (www.salesforce.com/developer).</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is a lookup to the user and used to assign internal staff to a project team member.</inlineHelpText>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N80000002lXWPEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/User_Division__c.field-meta.xml
<CustomField>
    <fullName>User_Division__c</fullName>
    <label>User Division</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>User_CIB_Global_Area__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Banking</fullName>
            </value>
            <value>
                <fullName>Business Enablers</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
            <value>
                <fullName>Client Services</fullName>
            </value>
            <value>
                <fullName>Client Solutions</fullName>
            </value>
            <value>
                <fullName>Commercial Banking</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>Entrepreneur</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>Global Markets</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Small Enterprise</fullName>
            </value>
            <value>
                <fullName>Transactional Products and Services</fullName>
            </value>
            <value>
                <fullName>Vehicle and Asset Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TC_updateAccountClientTeam.cls
@IsTest
public class TC_updateAccountClientTeam {


    public static User sysAdmin, testUser_1, testUser_2;
    public static Account acc;
    public static final String
            SYS_ADMIN_NAME          = 'testAdmin.StdBank_Ltn_Ecosystem_Test@test.com',
            TEST_USER_NAME_1        = 'test.StdBank_Ltn_Ecosystem_Test@test.com',
            TEST_USER_NAME_2        = '2test.StdBank_Ltn_Ecosystem_Test@test.com',
            ACC_NAME                = 'TestAccName',
            DEF_ACC_NAME_IMM        = 'Def Name for Immm',
            DEF_ACC_NAME_CHILD      = 'Def Name for Child',
            GROUP_NUMBER            = '1234';

    private static void getData() {
        for (User usr : [
                SELECT Username, Id, User_Division__c
                FROM User
                WHERE Username = :TEST_USER_NAME_1
                OR Username = :TEST_USER_NAME_2
                OR Username = :SYS_ADMIN_NAME
                LIMIT 3
        ]) {
            if (usr.UserName == TEST_USER_NAME_1) {
                testUser_1 = usr;
            }
            if (usr.UserName == TEST_USER_NAME_2) {
                testUser_2 = usr;
            }
            if (usr.UserName == SYS_ADMIN_NAME) {
                sysAdmin = usr;
            }
        }
        acc = [SELECT Id, Client_Managed_By__c FROM Account WHERE Name = :ACC_NAME];
    }

    @TestSetup
    static void testSetup() {
        TEST_DataFactory.generateConfiguration();
        fflib_SObjectUnitOfWork uow;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
            sysAdmin = (User) new BLD_USER(uow).useSysAdmin().userName(SYS_ADMIN_NAME).syncContact().getRecord();
            testUser_1 = (User) new BLD_USER(uow).userName(TEST_USER_NAME_1).division('Transactional Products and Services').useCib().syncContact().getRecord();
            testUser_2 = (User) new BLD_USER(uow).userName(TEST_USER_NAME_2).useCib().division('Client Coverage').syncContact().getRecord();
            uow.commitWork();
        }
        System.runAs(testUser_1) {
            acc = (Account) new BLD_Account().name(ACC_NAME).useCib().useGroupParent().groupNumber(GROUP_NUMBER).commitWork().getRecord();
        }
    }

    @IsTest
    static void shouldPopulateAccess() {
        getData();
        Custom_Client_Team__c customClientTeam = new Custom_Client_Team__c();
        System.runAs(sysAdmin) {
            customClientTeam.Client_Role__c = 'Credit Risk';
            customClientTeam.Account__c = acc.Id;
            customClientTeam.Team_Member__c = testUser_1.Id;
            customClientTeam.Client_Coordinator__c = true;
            Test.startTest();
            insert customClientTeam;
            Test.stopTest();
        }

        Custom_Client_Team__c cct = [SELECT Client_Access__c, Case_Access__c, Opportunity_Access__c, Contact_Access__c FROM Custom_Client_Team__c WHERE Id = :customClientTeam.Id];
        System.assertEquals('Read Only', cct.Case_Access__c);
        System.assertEquals('Read Only', cct.Opportunity_Access__c);
        System.assertEquals('Read/Write', cct.Contact_Access__c);
    }

    @IsTest
    static void shouldPopulateCCToAccount() {
        getData();
        System.runAs(sysAdmin) {
            Account acccouuntBeforeUpdate = [SELECT OwnerId FROM Account WHERE Id = :acc.Id];
            System.assertEquals(testUser_1.Id, acccouuntBeforeUpdate.OwnerId);
            Test.startTest();
            ABS_ObjectBuilderBase teamBld = new BLD_ClientTeam().account(acc.Id).role('Credit Risk').user(testUser_2.Id).coordinator(true).commitWork();
            Test.stopTest();
            Account accountAfterUpdate = [SELECT OwnerId FROM Account WHERE Id = :acc.Id];
            System.assertEquals(testUser_2.Id, accountAfterUpdate.OwnerId);
        }
    }

    @IsTest
    static void shouldSetTeamRoleSortValue() {
        getData();
        Custom_Client_Team__c customClientTeam = new Custom_Client_Team__c();
        customClientTeam.Client_Role__c = 'Credit Risk';
        customClientTeam.Account__c = acc.Id;
        customClientTeam.Team_Member__c = testUser_1.Id;

        System.runAs(testUser_1) {
            Test.startTest();
            insert customClientTeam;
            Test.stopTest();
        }

        Custom_Client_Team__c cct = [SELECT TeamRoleSortValue__c FROM Custom_Client_Team__c WHERE Id = :customClientTeam.Id];
        System.assertEquals('07', cct.TeamRoleSortValue__c);
    }


    @IsTest
    static void shouldPreventFromAddingNotUniqueUsersAsTeamMembers() {
        getData();
        Custom_Client_Team__c customClientTeam = new Custom_Client_Team__c();
        Custom_Client_Team__c customClientTeam2 = new Custom_Client_Team__c();
        String error;
        customClientTeam.Client_Role__c = 'Credit Risk';
        customClientTeam.Account__c = acc.Id;
        customClientTeam.Team_Member__c = testUser_1.Id;
        List<Custom_Client_Team__c> clist = new List<Custom_Client_Team__c>();
        customClientTeam2.Client_Role__c = 'Analyst';
        customClientTeam2.Account__c = acc.Id;
        customClientTeam2.Team_Member__c = testUser_1.Id;
        clist.add(customClientTeam);
        clist.add(customClientTeam2);
        System.runAs(testUser_1) {
            Test.startTest();
            try {
                insert clist;
            } catch (DmlException ex) {
                error = ex.getMessage();
            }
            Test.stopTest();
        }
        System.assertEquals(true, error.contains('already exists in the Client Team'));

    }

    @IsTest
    static void shouldPreventFromAddingNotUniqueRoles() {
        getData();
        Custom_Client_Team__c customClientTeam = new Custom_Client_Team__c();
        Custom_Client_Team__c customClientTeam2 = new Custom_Client_Team__c();
        String error;
        customClientTeam.Client_Role__c = 'Credit Risk';
        customClientTeam.Account__c = acc.Id;
        customClientTeam.Team_Member__c = testUser_1.Id;
        List<Custom_Client_Team__c> clist = new List<Custom_Client_Team__c>();
        customClientTeam2.Client_Role__c = 'Credit Risk';
        customClientTeam2.Account__c = acc.Id;
        customClientTeam2.Team_Member__c = testUser_2.Id;
        customClientTeam2.SourceFlag__c = DMN_ClientTeam.SOURCE_FLAG_STANDARD_MODE;
        customClientTeam2.Client_Coordinator__c = true;
        clist.add(customClientTeam);
        clist.add(customClientTeam2);
        System.runAs(sysAdmin) {
            Test.startTest();
            try {
                insert clist;
            } catch (DmlException ex) {
                error = ex.getMessage();
            }
            Test.stopTest();
        }
        System.assertEquals(true, error.contains('Same Team Role exist for Client Team Member. Please select a different Team Role.'));
    }

    @IsTest
    static void shouldRemoveOldUniqueRoleUser() {
        getData();
        ABS_ObjectBuilderBase teamBld = new BLD_ClientTeam().account(acc.Id).role('Credit Risk').user(testUser_1.Id).coordinator(true).commitWork();
        System.runAs(sysAdmin) {
            Test.startTest();
            ABS_ObjectBuilderBase teamBld2 = new BLD_ClientTeam().account(acc.Id).role('Credit Risk').user(testUser_2.Id).coordinator(true).sourceFlag(DMN_ClientTeam.SOURCE_FLAG_REPLACE_MODE).commitWork();
            Test.stopTest();
        }
        System.assertEquals(1, [SELECT COUNT() FROM Custom_Client_Team__c WHERE Account__c = :acc.Id]);
    }

    @IsTest
    static void shouldRemoveOldCC() {
        getData();
        Custom_Client_Team__c customClientTeam = new Custom_Client_Team__c();
        Custom_Client_Team__c customClientTeam2 = new Custom_Client_Team__c();
        customClientTeam.Client_Role__c = 'Credit Risk';
        customClientTeam.Account__c = acc.Id;
        customClientTeam.Team_Member__c = testUser_1.Id;
        customClientTeam.Client_Coordinator__c = true;
        insert customClientTeam;
        customClientTeam2.Client_Role__c = 'Analyst';
        customClientTeam2.Account__c = acc.Id;
        customClientTeam2.Team_Member__c = testUser_2.Id;
        customClientTeam2.Client_Coordinator__c = true;
        System.runAs(sysAdmin) {
            Test.startTest();
            insert customClientTeam2;
            Test.stopTest();
            System.assertEquals(1, [SELECT COUNT() FROM Custom_Client_Team__c WHERE Account__c = :acc.Id]);

        }
    }

    @IsTest
    static void shouldCreateNewMember() {
        getData();
        System.assertEquals(0, [SELECT COUNT() FROM AccountTeamMember WHERE UserId = :testUser_1.Id]);
        System.runAs(sysAdmin) {
            Test.startTest();
            ABS_ObjectBuilderBase teamBld = new BLD_ClientTeam().account(acc.Id).role('Credit Risk').user(testUser_1.Id).coordinator(true).commitWork();
            Test.stopTest();
        }
        System.assertEquals(1, [SELECT COUNT() FROM AccountTeamMember WHERE UserId = :testUser_1.Id]);
    }

    @IsTest
    static void shouldPopulateManegedByDivisions() {
        getData();
        Custom_Client_Team__c customClientTeam = new Custom_Client_Team__c();
        customClientTeam.Client_Role__c = 'Credit Risk';
        customClientTeam.Account__c = acc.Id;
        customClientTeam.Team_Member__c = testUser_2.Id;
        customClientTeam.Client_Coordinator__c = true;
        System.assertEquals('Unmanaged', [SELECT Client_Managed_By__c FROM Account WHERE Id = :acc.Id LIMIT 1][0].Client_Managed_By__c);
        System.runAs(sysAdmin) {
            Test.startTest();
            insert customClientTeam;
            System.assertEquals(testUser_2.User_Division__c, [SELECT Client_Managed_By__c FROM Account WHERE Id = :acc.Id LIMIT 1][0].Client_Managed_By__c);
            delete customClientTeam;
            System.assertEquals('Unmanaged', [SELECT Client_Managed_By__c FROM Account WHERE Id = :acc.Id LIMIT 1][0].Client_Managed_By__c);
            Test.stopTest();

        }


    }

    @IsTest
    static void shouldUpdateTeam() {
        getData();
        Custom_Client_Team__c customClientTeam = new Custom_Client_Team__c();
        customClientTeam.Client_Role__c = 'Credit Risk';
        customClientTeam.Account__c = acc.Id;
        customClientTeam.Team_Member__c = testUser_2.Id;

        System.assertEquals('Unmanaged', [SELECT Client_Managed_By__c FROM Account WHERE Id = :acc.Id LIMIT 1][0].Client_Managed_By__c);
        System.runAs(sysAdmin) {
            insert customClientTeam;
            Custom_Client_Team__c cct = [SELECT Client_Access__c, Case_Access__c, Opportunity_Access__c, Contact_Access__c FROM Custom_Client_Team__c WHERE Id = :customClientTeam.Id];
            System.assertEquals('Private', cct.Opportunity_Access__c);
//            Test.startTest();
            customClientTeam.Client_Coordinator__c = true;
            update customClientTeam;
//            Test.stopTest();
            System.debug('AAAAA + ' + customClientTeam.Id);
            Custom_Client_Team__c cct2 = [SELECT Client_Access__c, Case_Access__c, Opportunity_Access__c, Contact_Access__c FROM Custom_Client_Team__c WHERE Id = :customClientTeam.Id];
            System.assertEquals('Read Only', cct2.Opportunity_Access__c);
        }
    }

    @IsTest
    static void shouldCreateClientChildShare() {
        getData();
        Account immAccount = (Account) new BLD_Account().name(DEF_ACC_NAME_IMM).useCib().useImmediateParent(acc.Id).groupNumber(GROUP_NUMBER + 10).commitWork().getRecord();
        Account childAccount = (Account) new BLD_Account().name(DEF_ACC_NAME_CHILD).useCib().useChild(immAccount.Id, acc.Id).groupNumber(GROUP_NUMBER + 20).commitWork().getRecord();
        System.assertEquals(1, [SELECT COUNT() FROM AccountShare WHERE UserOrGroupId = :testUser_2.Id]);
        System.assertEquals(0, [SELECT COUNT() FROM AccountShare WHERE AccountId = :childAccount.Id AND UserOrGroupId = :testUser_2.Id]);
        System.runAs(sysAdmin) {
            Test.startTest();
            ABS_ObjectBuilderBase teamBld = new BLD_ClientTeam().account(acc.Id).role('Credit Risk').user(testUser_2.Id).coordinator(true).commitWork();
            Test.stopTest();
        }
        System.assertEquals(testUser_2.Id, [SELECT OwnerId FROM Account WHERE Id = :acc.Id].OwnerId);
        System.assertEquals(1, [SELECT COUNT() FROM AccountShare WHERE AccountId = :immAccount.Id AND UserOrGroupId = :testUser_2.Id]);
        System.assertEquals(1, [SELECT COUNT() FROM AccountShare WHERE AccountId = :childAccount.Id AND UserOrGroupId = :testUser_2.Id]);
    }

    @IsTest
    static void shouldDeleteClientChildShare() {
        getData();
        Custom_Client_Team__c customClientTeam = new Custom_Client_Team__c();
        customClientTeam.Client_Role__c = 'Credit Risk';
        customClientTeam.Account__c = acc.Id;
        customClientTeam.Team_Member__c = testUser_2.Id;
        customClientTeam.Client_Coordinator__c = true;
        Account immAccount = (Account) new BLD_Account().name(DEF_ACC_NAME_IMM).useCib().useImmediateParent(acc.Id).groupNumber(GROUP_NUMBER + 10).commitWork().getRecord();
        Account childAccount = (Account) new BLD_Account().name(DEF_ACC_NAME_CHILD).useCib().useChild(immAccount.Id, acc.Id).groupNumber(GROUP_NUMBER + 20).commitWork().getRecord();
        System.runAs(sysAdmin) {

            insert customClientTeam;
            Test.startTest();
            delete customClientTeam;
            Test.stopTest();
        }
        System.assertEquals(0, [SELECT COUNT() FROM AccountShare WHERE AccountId = :immAccount.Id AND UserOrGroupId = :testUser_2.Id]);
        System.assertEquals(0, [SELECT COUNT() FROM AccountShare WHERE AccountId = :childAccount.Id AND UserOrGroupId = :testUser_2.Id]);
    }

    @IsTest
    static void shouldDeleteAccountTeamMembers() {
        getData();
        Custom_Client_Team__c customClientTeam = new Custom_Client_Team__c();
        customClientTeam.Client_Role__c = 'Credit Risk';
        customClientTeam.Account__c = acc.Id;
        customClientTeam.Team_Member__c = testUser_2.Id;
        customClientTeam.Client_Coordinator__c = true;
        System.runAs(sysAdmin) {
            insert customClientTeam;
        }
        System.assertEquals(1, [SELECT COUNT() FROM AccountTeamMember WHERE UserId = :testUser_2.Id]);
        System.runAs(sysAdmin) {
            delete customClientTeam;
        }
        System.assertEquals(0, [SELECT COUNT() FROM AccountTeamMember WHERE UserId = :testUser_2.Id]);
    }

    @IsTest
    static void shouldUpdateClientAfterDelete() {
        getData();
        Custom_Client_Team__c customClientTeam = new Custom_Client_Team__c();
        customClientTeam.Client_Role__c = 'Credit Risk';
        customClientTeam.Account__c = acc.Id;
        customClientTeam.Team_Member__c = testUser_2.Id;
        customClientTeam.Client_Coordinator__c = true;
        System.runAs(sysAdmin) {
            insert customClientTeam;
        }
        Account beforeDelete = [SELECT ERABatchUpdateRequired__c, OwnerId FROM Account WHERE Id = :acc.Id];
        System.assertEquals(false, beforeDelete.ERABatchUpdateRequired__c);
        System.assertEquals(testUser_2.Id, beforeDelete.OwnerId);
        System.runAs(sysAdmin) {
            delete customClientTeam;
        }
        Account afterDelete = [SELECT ERABatchUpdateRequired__c, OwnerId FROM Account WHERE Id = :acc.Id];
        System.assertEquals(true, afterDelete.ERABatchUpdateRequired__c);
        System.assertEquals(UTL_CustomSetting.getSfAdminUserId(), afterDelete.OwnerId);
    }

}