force-app/main/default/objects/Account/fields/Client_Co_ordinator__c.field-meta.xml
<CustomField>
    <fullName>Client_Co_ordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New CC field created to be used for onboarding purposes (EN-0731)</description>
    <inlineHelpText>The suggested Client Coordinator responsible for the Bank’s relationship with the Client. Must be part of the division selected as the Primary Relationship Holder. This can only be changed by the CRM Helpdesk once approved.</inlineHelpText>
    <label>Proposed Client Coordinator</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only active users and users within the following User Divisions: Corporate Banking, Global Markets, Investment Banking, Transactional Products and Services, General Management, Real Estate can be searched.</errorMessage>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.User_Division__c</field>
            <operation>contains</operation>
            <value>Corporate Banking, Global Markets, Investment Banking, Transactional Products and Services, General Management, Real Estate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EmailAddress__c/EmailAddress__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to manage all the email addresses used in apex classes</description>
    <label>Email Address</label>
</CustomObject>

force-app/main/default/objects/EmailAddress__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Used for storing the email id values which will be used in apex classes</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/SRV_Email.cls
/***
    @ Func Area         : Email Sending
    @ Author            : Artur Kępczynski 
    @ Date              : 08.2017  
    @ Specification     : Main class to manage sending emails.
***/
public without sharing class SRV_Email {
	
	public static void sendRejectionCifClient(Set<Id> accountsIds){
		Id templateId = UTL_EmailTemplate.getTemplateId(DCN_EmailTemplate.CIF_CLIENT_REJECTION);
		List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
		Set<String> emailAddresses = new Set<String>{
				EmailAddress__c.getValues(DCN_CustomSetting.CDG_MAILBOX).Email__c,
				EmailAddress__c.getValues(DCN_CustomSetting.CRM_MAILBOX).Email__c};  

		for(Id accountId : accountsIds){
			emails.add(UTL_Email.createEmails(templateId, accountId, emailAddresses));
		}

		Messaging.sendEmail(emails);
	}

	public static void sendOnboardingSubsectorChange(Account[] accounts){
		Id templateId = UTL_EmailTemplate.getTemplateId(DCN_EmailTemplate.ONBOARDING_SECTOR_CHANGE);
        Messaging.SingleEmailMessage[] emails = new Messaging.SingleEmailMessage[]{};
		List<Id> ccIds = new List<Id>();
		for(Account acc: accounts) {
			ccIds.add(acc.Client_Co_ordinator__c);
		}
		UTL_User.getCachedUsers(ccIds);
        for(Account acc : accounts){
        	emails.add(UTL_Email.createEmails(templateId, acc.Id, UTL_User.getCachedUser(acc.Client_Co_ordinator__c).Contact_Sync_ID__c));
        }
        Messaging.sendEmail(emails);
	}
}