force-app/main/default/objects/Account/fields/Client_Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Sector__c</fullName>
    <description>The Client Sub-Sector further defines the sector in which the Client operates. This field is used in CRT and MI reporting. The business rule where a Client Sub-Sector cannot be dependent on more than one Client Sector needs to be adhered to at all times. Do not create or assign a duplicate Client Sub-Sector to more than one Client Sector</description>
    <inlineHelpText>The Client Sub-Sector further defines the sector in which the Client operates</inlineHelpText>
    <label>Client Sub-Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Sector__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Agriculture Commodity Traders</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Alternative Investment Vehicles</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automobiles</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Brokers and Exchanges</fullName>
            </value>
            <value>
                <fullName>Bulk Commodities</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Central Banks</fullName>
            </value>
            <value>
                <fullName>Centralised Power</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Construction Services</fullName>
            </value>
            <value>
                <fullName>Consumer Services</fullName>
            </value>
            <value>
                <fullName>Development Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Diamonds</fullName>
            </value>
            <value>
                <fullName>Diversified Industrials</fullName>
            </value>
            <value>
                <fullName>Diversified Mining</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equipment Manufacturers</fullName>
            </value>
            <value>
                <fullName>Food and Beverage</fullName>
            </value>
            <value>
                <fullName>Forestry</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Government Departments</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Internal_Credit_Rating__c.field-meta.xml
<CustomField>
    <fullName>Internal_Credit_Rating__c</fullName>
    <inlineHelpText>Standard Bank Internal Risk Rating for the client from Credit Risk</inlineHelpText>
    <label>Client Risk Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>D1</fullName>
            </value>
            <value>
                <fullName>D2</fullName>
            </value>
            <value>
                <fullName>D3</fullName>
            </value>
            <value>
                <fullName>SB01</fullName>
            </value>
            <value>
                <fullName>SB02</fullName>
            </value>
            <value>
                <fullName>SB03</fullName>
            </value>
            <value>
                <fullName>SB04</fullName>
            </value>
            <value>
                <fullName>SB05</fullName>
            </value>
            <value>
                <fullName>SB06</fullName>
            </value>
            <value>
                <fullName>SB07</fullName>
            </value>
            <value>
                <fullName>SB08</fullName>
            </value>
            <value>
                <fullName>SB09</fullName>
            </value>
            <value>
                <fullName>SB10</fullName>
            </value>
            <value>
                <fullName>SB11</fullName>
            </value>
            <value>
                <fullName>SB12</fullName>
            </value>
            <value>
                <fullName>SB13</fullName>
            </value>
            <value>
                <fullName>SB14</fullName>
            </value>
            <value>
                <fullName>SB15</fullName>
            </value>
            <value>
                <fullName>SB16</fullName>
            </value>
            <value>
                <fullName>SB17</fullName>
            </value>
            <value>
                <fullName>SB18</fullName>
            </value>
            <value>
                <fullName>SB19</fullName>
            </value>
            <value>
                <fullName>SB20</fullName>
            </value>
            <value>
                <fullName>SB21</fullName>
            </value>
            <value>
                <fullName>SB22</fullName>
            </value>
            <value>
                <fullName>SB23</fullName>
            </value>
            <value>
                <fullName>SB24</fullName>
            </value>
            <value>
                <fullName>SB25</fullName>
            </value>
            <value>
                <fullName>Not Available in CRS</fullName>
                <default>true</default>
                <label>Not Available in CRS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Line__c/Credit_Line__c.object-meta.xml
<CustomObject>
    <description>Credit Lines will be added to the Client page and displayed on the Client Plan.</description>
    <label>Credit Line</label>
    <nameField>
        <displayFormat>CL-{000}</displayFormat>
        <label>Credit Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Line__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Lines</relationshipLabel>
    <relationshipName>Credit_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Line__c/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <description>Total Credit Limit of the Facilty on this Client - provide the details as recorded in Adaptive</description>
    <inlineHelpText>Total Credit Limit of the Facilty on this Client - provide the details as recorded in Adaptive</inlineHelpText>
    <label>Credit Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Line__c/fields/Limit_Tenor__c.field-meta.xml
<CustomField>
    <fullName>Limit_Tenor__c</fullName>
    <description>The tenor associated with the limit step number (e.g.0D). A single limit can have more than one Tenor</description>
    <inlineHelpText>The tenor associated with the limit step number (e.g.0D)</inlineHelpText>
    <label>Limit Tenor</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Related Product on which we hold this Facility - provide the details as recorded in Adaptive</description>
    <inlineHelpText>Related Product on which we hold this Facility - provide the details as recorded in Adaptive</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>American Depository Receipt</fullName>
            </value>
            <value>
                <fullName>Bond Position</fullName>
            </value>
            <value>
                <fullName>Cape</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debtor Finance</fullName>
            </value>
            <value>
                <fullName>Deposits Held</fullName>
            </value>
            <value>
                <fullName>Equity Position</fullName>
            </value>
            <value>
                <fullName>Financial Guarantee - Given</fullName>
            </value>
            <value>
                <fullName>Fleet Management Card</fullName>
            </value>
            <value>
                <fullName>Foreign Notes</fullName>
            </value>
            <value>
                <fullName>Forfaiting</fullName>
            </value>
            <value>
                <fullName>General Short Term Banking Facilities</fullName>
            </value>
            <value>
                <fullName>Guarantee - Inward</fullName>
            </value>
            <value>
                <fullName>LC</fullName>
            </value>
            <value>
                <fullName>Metal Lease</fullName>
            </value>
            <value>
                <fullName>Money Market</fullName>
            </value>
            <value>
                <fullName>Net Trading Positions</fullName>
            </value>
            <value>
                <fullName>Non-Disclosed Finance</fullName>
            </value>
            <value>
                <fullName>Payment Settlement</fullName>
            </value>
            <value>
                <fullName>Performance Guarantee - Given</fullName>
            </value>
            <value>
                <fullName>Residential Mortgage</fullName>
            </value>
            <value>
                <fullName>Risk Participation Agreement</fullName>
            </value>
            <value>
                <fullName>Risk Transfers</fullName>
            </value>
            <value>
                <fullName>Securities Financing</fullName>
            </value>
            <value>
                <fullName>Structured Loans</fullName>
            </value>
            <value>
                <fullName>TPFA Property Guarantee-Given</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>Vehicle And Asset Finance</fullName>
            </value>
            <value>
                <fullName>Working Capital Facilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Line__c/fields/Total_utilisation__c.field-meta.xml
<CustomField>
    <fullName>Total_utilisation__c</fullName>
    <description>Total utilisation of the Facility on this Client - provide the details as recorded in Adaptive</description>
    <inlineHelpText>Total utilisation of the Facility on this Client - provide the details as recorded in Adaptive</inlineHelpText>
    <label>Total Utilisation</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Probability_of_default__c/Probability_of_default__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This a list of the Probability of default values with the corresponding Risk Grade which is used to determine the PD of a client</description>
    <label>Probability of default</label>
</CustomObject>

force-app/main/default/objects/Probability_of_default__c/fields/Fitted_PD__c.field-meta.xml
<CustomField>
    <fullName>Fitted_PD__c</fullName>
    <label>Fitted PD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CI_CreditController.cls
public without sharing class CI_CreditController {
    @AuraEnabled
    public static CI_ResponseDto getInternalCreditRating(String clientId) {   

        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardMapModel cmm = new CI_CardMapModel();

        // Check to make sure all fields are accessible to this user
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Account.fields.getMap(), new String[] {'Internal_Credit_Rating__c'})){ 
                return new CI_ResponseDto(false, 'You do not have the required permissions to view this data.');    
        }            
        Account acc = [SELECT Id, Name, Internal_Credit_Rating__c FROM Account where Id =: clientId];
                    
        String text = acc.Internal_Credit_Rating__c!=null?acc.Internal_Credit_Rating__c:'None';
        cmm.cardDataMap.put('Description', 'Ratings');
        cmm.cardDataMap.put('Rating', text);
                            
        cmm.Description = 'Ratings';                                      
        return new CI_ResponseDto(cmm);        
    }
    
    @AuraEnabled
    public static CI_ResponseDto getCreditUtilisation(String clientId) {   

        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardMapModel ctm = new CI_CardMapModel();

        // Check to make sure all fields are accessible to this user
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Credit_Line__c.fields.getMap(), new String[] {'Credit_Limit__c', 'Total_utilisation__c', 'Product__c', 'Name', 'CurrencyIsoCode'})){ 
                return new CI_ResponseDto(false, 'Permission error'); 
        }            
        
        List<Credit_Line__c> creditLines = [SELECT Id, Credit_Limit__c, Total_utilisation__c, Product__c, CurrencyIsoCode, Name from Credit_Line__c where Client_Name__r.Id =: clientId];

        Integer facilitiesCount = creditLines.size();
        Integer inExcessCount = 0;
        Decimal creditTotal = 0;
        Decimal utilisationTotal = 0;
        Decimal percentCreditUsed = 0;
        Decimal percentCreditAvail = 0;

        CI_SharedUtilities.CurrencyConverter currConverter =  new CI_SharedUtilities.CurrencyConverter();

        for (Integer i = 0; i < facilitiesCount; i++) {
            creditTotal += currConverter.convert(Double.valueOf(creditLines[i].Credit_Limit__c), String.valueOf(creditLines[i].CurrencyIsoCode), 'ZAR');
            utilisationTotal += currConverter.convert(Double.valueOf(creditLines[i].Total_utilisation__c), String.valueOf(creditLines[i].CurrencyIsoCode), 'ZAR');

            if (creditLines[i].Total_utilisation__c > creditLines[i].Credit_Limit__c)
                inExcessCount++;
        }

        if(facilitiesCount > 0){
            
            if(creditTotal > 0)//creditTotal can be zero because Credit_Limit__c can be zero for some reason
                percentCreditUsed = (utilisationTotal / creditTotal) * 100;
            
            percentCreditAvail = 100 - percentCreditUsed;
            if (percentCreditAvail < 0)//Gone into excess, make percentCreditAvail = 0
                percentCreditAvail = 0;
        }
        else
        {
            //No credit facilities, fill bar with grey emptyness
            percentCreditAvail = 100;
        }

        CI_CardMapModel cmm = new CI_CardMapModel();
        cmm.cardDataMap.put('facilitiesCount', String.valueOf(facilitiesCount));
        cmm.cardDataMap.put('inExcessCount', String.valueOf(inExcessCount));
        cmm.cardDataMap.put('creditTotal', String.valueOf(creditTotal));
        cmm.cardDataMap.put('utilisationTotal', String.valueOf(utilisationTotal));
        cmm.cardDataMap.put('percentCreditUsed', String.valueOf(percentCreditUsed));
        cmm.cardDataMap.put('percentCreditAvail', String.valueOf(percentCreditAvail));
        
        return new CI_ResponseDto(cmm);        
    }

    @AuraEnabled
    public static CI_ResponseDto getCreditLines(String clientId) {
        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardMapModel ctm = new CI_CardMapModel();

        // Check to make sure all fields are accessible to this user
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Credit_Line__c.fields.getMap(), new String[] {'Credit_Limit__c', 'Total_utilisation__c', 'Limit_Tenor__c', 'Product__c', 'Name', 'CurrencyIsoCode'})){ 
                return new CI_ResponseDto(false, 'Permission error'); 
        }            
        
        List<Credit_Line__c> creditLines = [SELECT Id, Limit_Tenor__c, Credit_Limit__c, Total_utilisation__c, Product__c, CurrencyIsoCode, Name from Credit_Line__c where Client_Name__r.Id =: clientId order by Product__c, Credit_Limit__c];

        CI_SharedUtilities.CurrencyConverter currConverter =  new CI_SharedUtilities.CurrencyConverter();
        for(Credit_Line__c creditLine : creditLines) {
            creditLine.Credit_Limit__c = currConverter.convert(Double.valueOf(creditLine.Credit_Limit__c), String.valueOf(creditLine.CurrencyIsoCode), 'ZAR');
            creditLine.Total_utilisation__c = currConverter.convert(Double.valueOf(creditLine.Total_utilisation__c), String.valueOf(creditLine.CurrencyIsoCode), 'ZAR');
        }

        return new CI_ResponseDto(creditLines);
    } 

    @AuraEnabled
    public static CI_ResponseDto getCreditRiskRating(String clientId) {  

        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardMapModel cmm = new CI_CardMapModel();

        // Check to make sure all fields are accessible to this user
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Account.fields.getMap(), new String[] {'Internal_Credit_Rating__c'})){ 
                return new CI_ResponseDto(false, 'You do not have the required permissions to view this data.');    
        }               
        Account acc = [SELECT Id, Name, Internal_Credit_Rating__c FROM Account where Id =: clientId];
                    
        String text = acc.Internal_Credit_Rating__c!=null?acc.Internal_Credit_Rating__c:'None';

        //These are 2 values where there is no PD rating present
        if(text == 'None' || text == 'Not Available in CRS')
            cmm.cardDataMap.put('Rating', 'None');
        else
        {
            List<Probability_of_default__c> rating = [SELECT Fitted_PD__c FROM Probability_of_default__c where Name =: text];
            if(rating.size()==0){
                cmm.cardDataMap.put('Rating', 'None');
            }else{
                cmm.cardDataMap.put('Rating', rating[0].Fitted_PD__c);
            }
        }

        cmm.Description = 'Credit Risk Rating';                                   
        return new CI_ResponseDto(cmm);        
    }

    @AuraEnabled
    public static CI_ResponseDto getRiskAppetite(String clientId) {
        
        List<Account> account = [SELECT Client_Sub_Sector__c, Country_Risk__c
                                FROM Account
                                WHERE Id =: clientId];

        account[0].Country_Risk__c = account[0].Country_Risk__c != null ? account[0].Country_Risk__c : 'Unknown';

        Boolean found = false;
        for (AggregateResult countries : [SELECT Country__c FROM Credit_Risk_Appetite__c GROUP BY Country__c])  
            if(account[0].Country_Risk__c == countries.get('Country__c'))
                found = true;

        if(!found)
            account[0].Country_Risk__c = 'Unknown';

        List<Credit_Risk_Appetite__c> riskAppetite = [SELECT Country_Credit_Appetite__c 
                                                        FROM Credit_Risk_Appetite__c
                                                        WHERE Country__c =: account[0].Country_Risk__c
                                                        AND Sub_Sector__c =: account[0].Client_Sub_Sector__c];

        CI_CardMapModel cmm = new CI_CardMapModel();
        
        if(riskAppetite.size() == 0)
            return new CI_ResponseDto(cmm);

        cmm.cardDataMap.put('Credit_Risk_Appetite__c', String.valueOf(riskAppetite[0].Country_Credit_Appetite__c));

        return new CI_ResponseDto(cmm);
    }       
}