force-app/main/default/objects/Account/fields/Client_Current_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Client_Current_Relationship__c</fullName>
    <description>Case#1263 - Rudolf Niehaus
Current interactions, Recent successes, Issues we are facing and plans to address, Credit Exposure per product</description>
    <inlineHelpText>A summary of current product activity, recent successes, issues we are facing and plans to address with the Client (2100 characters or less)</inlineHelpText>
    <label>Client Current Relationship</label>
    <length>2111</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sector__c</fullName>
    <description>Field Label Rename from &apos;CIB SA Sector&apos; to &apos;Global Sector&apos;, Nov &apos;10

#EN-226 - The primary sector in which the Client operates. This field is used in CRT and MI reporting</description>
    <inlineHelpText>The primary sector in which the Client operates</inlineHelpText>
    <label>Client Sector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Industrials</fullName>
            </value>
            <value>
                <fullName>Internal / Grouped</fullName>
            </value>
            <value>
                <fullName>Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Oil and Gas</fullName>
            </value>
            <value>
                <fullName>Power and Infrastructure</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Sovereign / Public Sector</fullName>
            </value>
            <value>
                <fullName>Telecoms and Media</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Client_Strategy__c</fullName>
    <description>case#1263 - Rudolf Niehaus
Overall objective, Where/how decision making is done, Opportunities we need to be looking for, Brief plan on how to deliver strategy
EN#240
This field was renamed due to the Client Plan phase 1 project. Label and API name have not been aligned because it would require updating code logic.</description>
    <inlineHelpText>Standard Bank&apos;s / Stanbic&apos;s Bank strategy to support the Client&apos;s long term strategy and short term objectives (1500 characters or less)</inlineHelpText>
    <label>Our Strategy For This Client</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Sector__c</fullName>
    <description>The Client Sub-Sector further defines the sector in which the Client operates. This field is used in CRT and MI reporting. The business rule where a Client Sub-Sector cannot be dependent on more than one Client Sector needs to be adhered to at all times. Do not create or assign a duplicate Client Sub-Sector to more than one Client Sector</description>
    <inlineHelpText>The Client Sub-Sector further defines the sector in which the Client operates</inlineHelpText>
    <label>Client Sub-Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Sector__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Agriculture Commodity Traders</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Alternative Investment Vehicles</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automobiles</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Brokers and Exchanges</fullName>
            </value>
            <value>
                <fullName>Bulk Commodities</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Central Banks</fullName>
            </value>
            <value>
                <fullName>Centralised Power</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Construction Services</fullName>
            </value>
            <value>
                <fullName>Consumer Services</fullName>
            </value>
            <value>
                <fullName>Development Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Diamonds</fullName>
            </value>
            <value>
                <fullName>Diversified Industrials</fullName>
            </value>
            <value>
                <fullName>Diversified Mining</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equipment Manufacturers</fullName>
            </value>
            <value>
                <fullName>Food and Beverage</fullName>
            </value>
            <value>
                <fullName>Forestry</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Government Departments</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Long_Term_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Long_Term_Strategy__c</fullName>
    <description>Describes the client&apos;s LT strategy (growth strategy, diversification)</description>
    <inlineHelpText>Long term strategy of the Client (1500 Characters or less)</inlineHelpText>
    <label>Long Term Strategy</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nature_of_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Relationship__c</fullName>
    <description>Type of relationship for global account</description>
    <inlineHelpText>A high level description of Standard Bank&apos;s relationship with the Client</inlineHelpText>
    <label>Nature of Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Growing</fullName>
            </value>
            <value>
                <fullName>Established</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Trusted Advisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Overall_CIB_CSI_Rating_Number__c.field-meta.xml
<CustomField>
    <fullName>Overall_CIB_CSI_Rating_Number__c</fullName>
    <label>Overall CIB CSI Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Short_Term_Objectives__c.field-meta.xml
<CustomField>
    <fullName>Short_Term_Objectives__c</fullName>
    <description>Describes the client&apos;s ST strategy and objectives</description>
    <inlineHelpText>Short term objectives of the Client to achieve their long term strategy (1500 Characters or less)</inlineHelpText>
    <label>Short Term Objectives</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Survey_Year__c.field-meta.xml
<CustomField>
    <fullName>Survey_Year__c</fullName>
    <description>This is used to record the year of survey , created as per EN-0865.</description>
    <label>Survey Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Satisfaction_Index__c/Client_Satisfaction_Index__c.object-meta.xml
<CustomObject>
    <description>Created this object as part of EN-0690, this object is child of Client object.</description>
    <label>Client Satisfaction Index</label>
    <nameField>
        <displayFormat>CSI-{000}</displayFormat>
        <label>Client Satisfaction Index Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Satisfaction Index</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Satisfaction_Index__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <description>This field is used to establish connection between Client and CSI object, created as per EN-0690</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Satisfaction Index</relationshipLabel>
    <relationshipName>Client_Satisfaction_Index</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Satisfaction_Index__c/fields/CSI_GM_Comment__c.field-meta.xml
<CustomField>
    <fullName>CSI_GM_Comment__c</fullName>
    <description>CSI GM Comment (EN-692).</description>
    <inlineHelpText>Why have you given Global Markets this rating?</inlineHelpText>
    <label>CSI GM Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Client_Satisfaction_Index__c/fields/CSI_IB_Comment__c.field-meta.xml
<CustomField>
    <fullName>CSI_IB_Comment__c</fullName>
    <description>CSI IB Comment (EN-692).</description>
    <inlineHelpText>Why have you given Investment Banking this rating?</inlineHelpText>
    <label>CSI IB Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Client_Satisfaction_Index__c/fields/CSI_Survey_Contact__c.field-meta.xml
<CustomField>
    <fullName>CSI_Survey_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CSI Survey Contact (EN-692).</description>
    <label>CSI Survey Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>Please enter an active Client Contact. Bank Contacts (Employees) or inactive contacts cannot be captured.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Contact Record Type</value>
        </filterItems>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Bank Contact Record Type</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Satisfaction Index</relationshipLabel>
    <relationshipName>Client_Satisfaction_Index</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Satisfaction_Index__c/fields/CSI_TPS_Comment__c.field-meta.xml
<CustomField>
    <fullName>CSI_TPS_Comment__c</fullName>
    <description>CSI TPS Comment (EN-692).</description>
    <inlineHelpText>Why have you given Transactional Banking this rating?</inlineHelpText>
    <label>CSI TPS Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Client_Satisfaction_Index__c/fields/GM_CSI_Rating_Number__c.field-meta.xml
<CustomField>
    <fullName>GM_CSI_Rating_Number__c</fullName>
    <label>GM CSI Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Satisfaction_Index__c/fields/IB_CSI_Rating_Number__c.field-meta.xml
<CustomField>
    <fullName>IB_CSI_Rating_Number__c</fullName>
    <label>IB CSI Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Satisfaction_Index__c/fields/Overall_CIB_CSI_Rating_Number__c.field-meta.xml
<CustomField>
    <fullName>Overall_CIB_CSI_Rating_Number__c</fullName>
    <label>Overall CIB CSI Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Satisfaction_Index__c/fields/Survey_Year__c.field-meta.xml
<CustomField>
    <fullName>Survey_Year__c</fullName>
    <description>This is used to record the year of survey , created as per EN-0690</description>
    <label>Survey Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Satisfaction_Index__c/fields/TPS_CSI_Rating_Number__c.field-meta.xml
<CustomField>
    <fullName>TPS_CSI_Rating_Number__c</fullName>
    <label>TPS CSI Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CI_ClientOverviewController.cls
public with sharing class CI_ClientOverviewController {

    @AuraEnabled
    public static CI_ResponseDto getBankStrategy(String clientId) {

        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Account.fields.getMap(), new String[] {'Client_Strategy__c'})){ 
            return new CI_ResponseDto(false, 'You do not have the required permissions to view this data');
        }
        
        Account acc = [SELECT Id, Name, Client_Strategy__c FROM Account where Id =: clientId];

        CI_CardMapModel cmm = new CI_CardMapModel();
        cmm.cardDataMap.put('Text', acc.Client_Strategy__c);
        cmm.cardDataMap.put('Description', 'Bank Strategy');                                  

        return new CI_ResponseDto(cmm);
    }

    @AuraEnabled
    public static CI_ResponseDto getClientStrategy(String clientId) {

        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardTextModel ctm = new CI_CardTextModel();

        // Check to make sure all fields are accessible to this user
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Account.fields.getMap(), new String[] {'Short_Term_Objectives__c','Long_Term_Strategy__c'})){ 
                return new CI_ResponseDto(false, 'You do not have the required permissions to view this data'); 
        }
        Account acc = [SELECT Id, Name, Short_Term_Objectives__c,Long_Term_Strategy__c FROM Account where Id =: clientId];
        
        CI_CardMapModel cmm = new CI_CardMapModel();
        cmm.cardDataMap.put('ShortTermGoal', acc.Short_Term_Objectives__c);
        cmm.cardDataMap.put('LongTermGoal', acc.Long_Term_Strategy__c);        
        cmm.cardDataMap.put('Description', 'Client Strategy');                                   

        return new CI_ResponseDto(cmm);
    }
    
 
    @AuraEnabled
    public static CI_ResponseDto getCSIRating(String clientId) {

        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardMapModel cmm = new CI_CardMapModel();

        // Check to make sure all fields are accessible to this user
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Account.fields.getMap(), new String[] { 'Overall_CIB_CSI_Rating_Number__c' })){
                return new CI_ResponseDto(false, 'You do not have the required permissions to view this data');  
        }
        
        Account acc = [SELECT Id, Name, Overall_CIB_CSI_Rating_Number__c FROM Account where Id =: clientId];

        String text = acc.Overall_CIB_CSI_Rating_Number__c!=null?String.valueOf(acc.Overall_CIB_CSI_Rating_Number__c):null;
        cmm.cardDataMap.put('Rating', text);

        List<Client_Satisfaction_Index__c> DivisionsCSI = [SELECT CSI_Survey_Contact__r.name ,Survey_Year__c ,TPS_CSI_Rating_Number__c ,CSI_TPS_Comment__c,GM_CSI_Rating_Number__c, CSI_GM_Comment__c, IB_CSI_Rating_Number__c, CSI_IB_Comment__c from Client_Satisfaction_Index__c where Client__c =: clientId Order by Survey_Year__c desc limit 1];
                 
        if(DivisionsCSI.size()>0) {
            String TPSRating = DivisionsCSI[0].TPS_CSI_Rating_Number__c!=null?String.valueOf(DivisionsCSI[0].TPS_CSI_Rating_Number__c):null;
            String GMRating = DivisionsCSI[0].GM_CSI_Rating_Number__c!=null?String.valueOf(DivisionsCSI[0].GM_CSI_Rating_Number__c):null;
            String IBRating = DivisionsCSI[0].IB_CSI_Rating_Number__c!=null?String.valueOf(DivisionsCSI[0].IB_CSI_Rating_Number__c):null;

            String TPSComment = DivisionsCSI[0].CSI_TPS_Comment__c!=null?DivisionsCSI[0].CSI_TPS_Comment__c:null;
            String GMComment = DivisionsCSI[0].CSI_GM_Comment__c!=null?String.valueOf(DivisionsCSI[0].CSI_GM_Comment__c):null;
            String IBComment = DivisionsCSI[0].CSI_IB_Comment__c!=null?String.valueOf(DivisionsCSI[0].CSI_IB_Comment__c):null;

            cmm.cardDataMap.put('TPSRating', TPSRating);
            cmm.cardDataMap.put('GMRating', GMRating);
            cmm.cardDataMap.put('IBRating', IBRating); 
                        
            cmm.cardDataMap.put('TPSDescription', sharedUtils.CSIDescription(TPSRating));
            cmm.cardDataMap.put('GMDescription', sharedUtils.CSIDescription(GMRating));
            cmm.cardDataMap.put('IBDescription', sharedUtils.CSIDescription(IBRating));  

            cmm.cardDataMap.put('TPSComment', TPSComment);
            cmm.cardDataMap.put('GMComment', GMComment);
            cmm.cardDataMap.put('IBComment', IBComment);     

            cmm.cardDataMap.put('Year', DivisionsCSI[0].Survey_Year__c);

            cmm.cardDataMap.put('SurveyContact', DivisionsCSI[0].CSI_Survey_Contact__r.name);                                                                
        }
     
        cmm.cardDataMap.put('Description', sharedUtils.CSIDescription(text));
                
        cmm.Description = 'CSI Rating';                                    
        return new CI_ResponseDto(cmm);        
    }   

    @AuraEnabled
    public static CI_ResponseDto getRelationshipStatus(String clientId) {   

        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardMapModel cmm = new CI_CardMapModel();

        // Check to make sure all fields are accessible to this user
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Account.fields.getMap(), new String[] {'Nature_of_Relationship__c','Client_Current_Relationship__c'})){ 
            return new CI_ResponseDto(false, 'You do not have the required permissions to view this data');
        }
        
        Account acc = [SELECT Id, Name, Nature_of_Relationship__c,Client_Current_Relationship__c FROM Account where Id =: clientId];
                    
        String text = acc.Nature_of_Relationship__c!=null?acc.Nature_of_Relationship__c:'None';
        String description = acc.Client_Current_Relationship__c!=null?acc.Client_Current_Relationship__c:'None';
        
        cmm.cardDataMap.put('Status', text);
        cmm.cardDataMap.put('Description', description);
                 
        cmm.Description = 'Relationship Status'; 

        return new CI_ResponseDto(cmm);   
    }     

    @AuraEnabled
    public static CI_ResponseDto getSectorAndSubSubsector(String clientId) {   

        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardMapModel cmm = new CI_CardMapModel();

        // Check to make sure all fields are accessible to this user
        if(!sharedUtils.canAccessFields(Schema.SObjectType.Account.fields.getMap(), new String[] {'Client_Sector__c','Client_Sub_Sector__c'})){ 
            return new CI_ResponseDto(false, 'You do not have the required permissions to view this data');
        }
        
        Account acc = [SELECT Id, Client_Sector__c, Client_Sub_Sector__c FROM Account where Id =: clientId];
                    
        cmm.cardDataMap.put('Sector', acc.Client_Sector__c);
        cmm.cardDataMap.put('Subsector', acc.Client_Sub_Sector__c);
                 
        cmm.Description = 'Sector'; 

        return new CI_ResponseDto(cmm);   
    }        
}