force-app/main/default/objects/Account/fields/Client_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sector__c</fullName>
    <description>Field Label Rename from &apos;CIB SA Sector&apos; to &apos;Global Sector&apos;, Nov &apos;10

#EN-226 - The primary sector in which the Client operates. This field is used in CRT and MI reporting</description>
    <inlineHelpText>The primary sector in which the Client operates</inlineHelpText>
    <label>Client Sector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Industrials</fullName>
            </value>
            <value>
                <fullName>Internal / Grouped</fullName>
            </value>
            <value>
                <fullName>Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Oil and Gas</fullName>
            </value>
            <value>
                <fullName>Power and Infrastructure</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Sovereign / Public Sector</fullName>
            </value>
            <value>
                <fullName>Telecoms and Media</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Sector__c</fullName>
    <description>The Client Sub-Sector further defines the sector in which the Client operates. This field is used in CRT and MI reporting. The business rule where a Client Sub-Sector cannot be dependent on more than one Client Sector needs to be adhered to at all times. Do not create or assign a duplicate Client Sub-Sector to more than one Client Sector</description>
    <inlineHelpText>The Client Sub-Sector further defines the sector in which the Client operates</inlineHelpText>
    <label>Client Sub-Sector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Sector__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Agriculture Commodity Traders</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Alternative Investment Vehicles</fullName>
            </value>
            <value>
                <fullName>Asset Managers</fullName>
            </value>
            <value>
                <fullName>Automobiles</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Brokers and Exchanges</fullName>
            </value>
            <value>
                <fullName>Bulk Commodities</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Central Banks</fullName>
            </value>
            <value>
                <fullName>Centralised Power</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Construction Services</fullName>
            </value>
            <value>
                <fullName>Consumer Services</fullName>
            </value>
            <value>
                <fullName>Development Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Diamonds</fullName>
            </value>
            <value>
                <fullName>Diversified Industrials</fullName>
            </value>
            <value>
                <fullName>Diversified Mining</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equipment Manufacturers</fullName>
            </value>
            <value>
                <fullName>Food and Beverage</fullName>
            </value>
            <value>
                <fullName>Forestry</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Government Departments</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code__c</fullName>
    <description>Industry Class code from CIF (ISIC)</description>
    <inlineHelpText>Defines the isic code.</inlineHelpText>
    <label>Industry Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SA_Industry_Description__c.field-meta.xml
<CustomField>
    <fullName>SA_Industry_Description__c</fullName>
    <description>Previosuly named SA_Industry_Description. API name still SA_industry_description due to trigger using this field
        US-4394 - This field shows ISIC description that is mapped to relative ISIC Code</description>
    <inlineHelpText>Defines the lowest level of classification as per the client sector.</inlineHelpText>
    <label>CIF ISIC Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ISIC_Mapping_Client_Sector__c/ISIC_Mapping_Client_Sector__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom Setting will hold the mapping of ISIC codes with Client Sector and Sub Sector values.</description>
    <label>ISIC Mapping with Client Sector</label>
</CustomObject>

force-app/main/default/objects/ISIC_Mapping_Client_Sector__c/fields/CIF_ISIC_Description__c.field-meta.xml
<CustomField>
    <fullName>CIF_ISIC_Description__c</fullName>
    <description>This field is set when the industry code is passed into the the account object from CIF</description>
    <inlineHelpText>The ISIC Sub-Sector classification as defined with Client On-boarding</inlineHelpText>
    <label>CIF ISIC Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ISIC_Mapping_Client_Sector__c/fields/Client_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sector__c</fullName>
    <description>This will contain the client sector value for corresponding ISIC Code.</description>
    <inlineHelpText>Client Sector value for corresponding ISIC code.</inlineHelpText>
    <label>Client Sector</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ISIC_Mapping_Client_Sector__c/fields/Client_Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Sector__c</fullName>
    <description>This will contain the Client Sub Sector value for corresponding ISIC code.</description>
    <inlineHelpText>Client Sub Sector value for corresponding ISIC code.</inlineHelpText>
    <label>Client Sub-Sector</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SA_StdBank_AutoUpdClIndustry_Test_Proper.cls
/* @Class Name   : SA_StdBank_AutoUpdClIndustry_Test_Proper
 * @Description  : Test class for AccountTriggerHandler_trgr.cls (method updateIndustryDescription)
 * @Created By   : Jana Cechova
 * @Created On   : 21 Mar 2016 
 * @Modification Log:  
 * --------------------------------------------------------------------------------------------------
 * @Developer                Date                   Description
 * --------------------------------------------------------------------------------------------------
 * ---------------------------------------------------------------------------------------------------
*/
@isTest
private class SA_StdBank_AutoUpdClIndustry_Test_Proper {

    /*
    * After update Industry Code on Account we are expecting that after fire trigger for update Industry Description, field SA_Industry_Description__c will be populated based on SA_Industry_Mapping__c for each existin Account.
    * For example:
    * We have 20 Account and 20 SA_Industry_Mapping__c (each SA_Industry_Mapping__c contains SA_1Digit_ISIC_Desc__c) if:
    *   a) Industry Code will be updated with value '' we are expecting that SA_Industry_Description__c will be populaed with 'Missing CIF ISIC code'.
    *   b) Industry Code will be updated with value '!@#$%^&*' we are expecting that SA_Industry_Description__c will be populaed with 'Missing ISIC mapping'.
    *   c) Industry Code will be updated with value '1' we are expecting that SA_Industry_Description__c will be populaed with value which is in SA_1Digit_ISIC_Desc__c on position 1.
    *   d) Industry Code will be updated with value null  we are expecting that SA_Industry_Description__c will be populaed with 'Missing CIF ISIC code'.
    *   e) Industry Code will be updated with value 'test'  we are expecting that SA_Industry_Description__c will be populaed with 'Missing ISIC mapping'.
    *   f) Industry Code will be updated with value '23'  we are expecting that SA_Industry_Description__c will be populaed with 'Missing ISIC mapping'.
    *   g) Industry Code will be updated with value '23test'  we are expecting that SA_Industry_Description__c will be populaed with 'Missing ISIC mapping'.
    *   h) Industry Code will be updated with value '2' we are expecting that SA_Industry_Description__c will be populaed with value which is in SA_1Digit_ISIC_Desc__c on position 2.
    */
    static testMethod void AutoUpdateClientIndustryDescription_Test() {
        List<ISIC_Mapping_Client_Sector__c> isicCodes = new List<ISIC_Mapping_Client_Sector__c>();
        ISIC_Mapping_Client_Sector__c isic = new ISIC_Mapping_Client_Sector__c(Name = '1', Client_Sub_Sector__c = 'Agriculture', Client_Sector__c = 'Consumer', CIF_ISIC_Description__c = 'Agriculture, Hunting And Forestry');
        ISIC_Mapping_Client_Sector__c isic2 = new ISIC_Mapping_Client_Sector__c(Name = '2', Client_Sub_Sector__c = 'Agriculture', Client_Sector__c = 'Consumer', CIF_ISIC_Description__c = 'Fishing');
        isicCodes.add(isic);
        isicCodes.add(isic2);
        insert isicCodes;

        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
        List<Account> olstAccount = new List<Account>();
        for (Integer i = 0; i < 8; i++) {
            olstAccount.add(
                (Account) new BLD_Account(uow).useChild().getRecord()
            );
        }
        uow.commitWork();
        
        list<Account>  accountsToAssert = [Select id, Industry_Code__c, SA_Industry_Description__c from Account where id IN: olstAccount order by id];

        // Check Accounts after insert
        for(Account acct: accountsToAssert){
            system.assertEquals(null, acct.Industry_Code__c,'Industry Code is not null uncorrectly.');
            system.assertNotEquals(null, acct.SA_Industry_Description__c, 'SA Industry Description is null uncorrectly.');
        }
        
        // Update values in Industry Code
        // a)
        olstAccount[0].Industry_Code__c = '';
        // b)
        olstAccount[1].Industry_Code__c = '!@#$%^&*';
        // c)
        olstAccount[2].Industry_Code__c = '1';
        // d)
        olstAccount[3].Industry_Code__c = null;
        // e)
        olstAccount[4].Industry_Code__c = 'test';
        // f)
        olstAccount[5].Industry_Code__c = '23';
        // g)
        olstAccount[6].Industry_Code__c = '23test';
        // h)
        olstAccount[7].Industry_Code__c = '2';
        
        //system.debug(GOVERNOR_LIMITS); 
        system.debug(LoggingLevel.ERROR, 'SOQL query usage before startTest() AutoUpdateClientIndustryDescription_Test() unit test: ' + Limits.getQueries());
        system.debug(LoggingLevel.ERROR, 'DML rows query before startTest() AutoUpdateClientIndustryDescription_Test() unit test: ' + Limits.getDMLRows());
        system.Test.startTest();
        
        // Update Accounts
        update olstAccount; 
        
        list<Account>  accountsToAsserts = [Select id, Industry_Code__c, SA_Industry_Description__c from Account where id IN: olstAccount order by id];
        system.debug(logginglevel.error, 'After' + accountsToAsserts);
        
        //system.debug(GOVERNOR_LIMITS);
        system.debug(LoggingLevel.ERROR, 'SOQL query usage before stopTest() AutoUpdateClientIndustryDescription_Test() unit test: ' + Limits.getQueries());
        system.debug(LoggingLevel.ERROR, 'DML rows query before stopTest() AutoUpdateClientIndustryDescription_Test() unit test: ' + Limits.getDMLRows());
        system.Test.stopTest();
        
        // Check Account after update
        list<Account> accountsToAssert2 = [Select id, Industry_Code__c, SA_Industry_Description__c from Account where id IN: olstAccount];
        system.assertEquals('Missing CIF ISIC code', accountsToAssert2[0].SA_Industry_Description__c, 'SA Industry Description was populated uncorrectly.');
        system.assertEquals('Missing ISIC mapping', accountsToAssert2[1].SA_Industry_Description__c, 'SA Industry Description was populated uncorrectly.');
        system.assertEquals('Agriculture, Hunting And Forestry', accountsToAssert2[2].SA_Industry_Description__c, 'SA Industry Description was populated uncorrectly.');
        system.assertEquals('Missing CIF ISIC code', accountsToAssert2[3].SA_Industry_Description__c, 'SA Industry Description was populated uncorrectly.');
        system.assertEquals('Missing ISIC mapping', accountsToAssert2[4].SA_Industry_Description__c, 'SA Industry Description was populated uncorrectly.');
        system.assertEquals('Missing ISIC mapping', accountsToAssert2[5].SA_Industry_Description__c, 'SA Industry Description was populated uncorrectly.');
        system.assertEquals('Missing ISIC mapping', accountsToAssert2[6].SA_Industry_Description__c, 'SA Industry Description was populated uncorrectly.');
        system.assertEquals('Fishing', accountsToAssert2[7].SA_Industry_Description__c, 'SA Industry Description was populated uncorrectly.');
        
     }
}