force-app/main/default/objects/Account/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>When a new event is created for the client, storing the event subject in to this field.</description>
    <label>Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Event_URL__c.field-meta.xml
<CustomField>
    <fullName>Event_URL__c</fullName>
    <description>When a new event is created for the client, storing the event ID in to this field.This filed is using to trigger a Account work flow whenever task ID is changed .</description>
    <label>Event URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Event Report Object to store the Event Information and associate Attendees and Send Email to them.</description>
    <label>Event Report</label>
    <nameField>
        <label>Event Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/EventId__c.field-meta.xml
<CustomField>
    <fullName>EventId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Stores Event Id</description>
    <externalId>true</externalId>
    <label>EventId</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Report_Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Report_Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact / Lead Lookup for the Report</description>
    <inlineHelpText>Contact at the Client with whom the meeting ‘will be / was’ held. You are required to provide the main Client Contact when the Meeting Audience is External, and there is no Related to Opportunity, Case or Campaign</inlineHelpText>
    <label>Client Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3 AND 4)</booleanFilter>
        <errorMessage>Please enter an active Client Contact for External Meetings only. Bank Contacts (Employees) or inactive contacts cannot be captured.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Contact Record Type</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Inactive Client Contact Record Type</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Reports (Client Contact)</relationshipLabel>
    <relationshipName>Event_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>When a new event is created for the Contact ,storing the event subject in to this field.</description>
    <label>Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Event_URL__c.field-meta.xml
<CustomField>
    <fullName>Event_URL__c</fullName>
    <description>When a new event is created for the Contact ,storing the event ID in to this field. 
This filed is using to trigger a Contact work flow whenever event ID is changed .</description>
    <label>Event URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DMN_Event_TEST.cls
@isTest
private class DMN_Event_TEST {

	public static final Integer UPPER_LIMIT 	= 200;
	public static final String SAMPLE_SUBJECT	= 'Some Subject';

	private static ABS_ObjectBuilderBase accBld;
	private static ABS_ObjectBuilderBase eveBld;
	private static ABS_ObjectBuilderBase conBld;
	private static User usr;
	
	private static testmethod void eventCreationTest() {

		usr = (User)new BLD_USER().useCommB().syncContact().commitWork().getRecord();
  
		System.runAs(usr){
			Test.startTest();
				accBld = new BLD_Account().useCommB().useGroupParent().commitWork(); 
		
				eveBld = new BLD_Event()
								.internalMeeting().meetingPurpose(DMN_Event.CORE_TEAM_MEETING)
								.startDate(System.now()).stopDate(System.now().addHours(1))
								.linkToParent(accBld.getRecordId()).commitWork();
			Test.stopTest();
		} 

		Event eve = (Event)eveBld.refreshFromDB(new Set<String>{'WhatId', 'WhoId'}).getRecord();

		Event[] events = [	SELECT Id, WhatId, WhoId, Related_Event_Report__c
							FROM Event 
							WHERE Id =: eve.Id];

		Call_Report__c[] eveMeetings = [SELECT Id, EventId__c 
										FROM Call_Report__c
										WHERE EventId__c =: eve.Id];

		System.assertEquals(accBld.getRecordId(), eve.WhatId); 
		System.assertEquals(null, eve.WhoId);
		System.assertEquals(1, eveMeetings.size());
		System.assertEquals(1, events.size()); 
		System.assertEquals(events[0].Id, eveMeetings[0].EventId__c);
		System.assertEquals(eveMeetings[0].Id, events[0].Related_Event_Report__c); 
	}

	private static testmethod void deleteEvents_Test() {
		usr = (User)new BLD_USER().useCommB().syncContact().commitWork().getRecord();

		System.runAs(usr){
			accBld = new BLD_Account().useCommB().useGroupParent().commitWork(); 
		
			eveBld = new BLD_Event()
								.internalMeeting().meetingPurpose(DMN_Event.CORE_TEAM_MEETING)
								.startDate(System.now()).stopDate(System.now().addHours(1))
								.linkToParent(accBld.getRecordId()).commitWork();
		}

		Call_Report__c[] eveMeetings = [SELECT Id, EventId__c
										FROM Call_Report__c
										WHERE EventId__c =: eveBld.getRecordId()];
		System.assertEquals(1, eveMeetings.size());
		Database.DeleteResult[] results;

		System.runAs(usr){
			Test.startTest();
				results = DMN_Event.deleteEvents(eveMeetings); 
			Test.stopTest();
		}

		Event[] events = [	SELECT Id  
                           	FROM Event 
                          	WHERE Id =: eveBld.getRecordId()];

       	System.assertEquals(0, events.size());
       	System.assertEquals(1, results.size());
       	System.assertEquals(true, results[0].isSuccess());
	}
	
	private static testmethod void deleteEvents_Test_Multiple() {
		usr = (User)new BLD_USER().useCommB().syncContact().commitWork().getRecord();

		Event[] sourceEvents = new Event[]{};

		System.runAs(usr){
			
			accBld = new BLD_Account().useCommB().useGroupParent().commitWork(); 
			
			for(Integer i = 0; i < UPPER_LIMIT; i++){
				sourceEvents.add((Event)new BLD_Event()
								.internalMeeting().meetingPurpose(DMN_Event.CORE_TEAM_MEETING)
								.startDate(System.now()).stopDate(System.now().addHours(1))
								.linkToParent(accBld.getRecordId()).getRecord());
			}
            
            insert sourceEvents;
		}

		sourceEvents = [SELECT Id, WhatId, WhoId
						FROM Event 
						WHERE Id IN: sourceEvents];

		Set<String> eventIds = new Set<String>();
		for(Event sourceEve : sourceEvents){
			eventIds.add(sourceEve.Id);
		}

		Call_Report__c[] eveMeetings = [SELECT Id, EventId__c 
										FROM Call_Report__c
										WHERE EventId__c IN: eventIds];
		System.assertEquals(UPPER_LIMIT, eveMeetings.size());
		Database.DeleteResult[] results;

		System.runAs(usr){
			Test.startTest();
				results = DMN_Event.deleteEvents(eveMeetings); 
			Test.stopTest();
		} 

		Event[] events = [	SELECT Id  
                           	FROM Event 
                          	WHERE Id IN: eventIds];

       	System.assertEquals(0, events.size());
       	System.assertEquals(UPPER_LIMIT, results.size());
       	for(Database.DeleteResult res : results){
       		System.assertEquals(true, res.isSuccess());
       	}
	}
	
	private static testmethod void syncRelatedObjects_Test_Acc_NoDml() {
		usr = (User)new BLD_USER().useCommB().syncContact().commitWork().getRecord();

		System.runAs(usr){
			
			accBld = new BLD_Account().useCommB().useGroupParent().commitWork(); 
			eveBld = new BLD_Event()
								.internalMeeting().meetingPurpose(DMN_Event.CORE_TEAM_MEETING)
								.startDate(System.now()).stopDate(System.now().addHours(1))
								.unrestricted().linkToParent(accBld.getRecordId()).commitWork();
		}

		Account acc = (Account)accBld.refreshFromDB(new set<String>{'Event_Name__c', 'Event_URL__c'}).getRecord();
		Event eve = (Event)eveBld.getRecord();
		System.assertNotEquals(SAMPLE_SUBJECT, acc.Event_Name__c );
		System.assertEquals(String.valueOf(eve.id).subString(0,15), acc.Event_URL__c );

		System.runAs(usr){  
			Test.startTest();
				eve.Subject = SAMPLE_SUBJECT;
				DMN_Event.syncRelatedObjects(new Event[]{eve});
			Test.stopTest();  
		}

		acc = (Account)accBld.refreshFromDB(new set<String>{'Event_Name__c', 'Event_URL__c'}).getRecord();

		System.assertEquals(SAMPLE_SUBJECT, acc.Event_Name__c );
		System.assertEquals(String.valueOf(eve.id).subString(0,15), acc.Event_URL__c );
	}  
	
	private static testmethod void syncRelatedObjects_Test_Acc_Dml() {
		usr = (User)new BLD_USER().useCommB().syncContact().commitWork().getRecord();

		System.runAs(usr){
			
			accBld = new BLD_Account().useCommB().useGroupParent().commitWork(); 
			eveBld = new BLD_Event()
								.internalMeeting().meetingPurpose(DMN_Event.CORE_TEAM_MEETING)
								.startDate(System.now()).stopDate(System.now().addHours(1))
								.unrestricted().linkToParent(accBld.getRecordId());
		}

		Account acc = (Account)accBld.refreshFromDB(new set<String>{'Event_Name__c', 'Event_URL__c'}).getRecord();
		Event eve = (Event)eveBld.getRecord();


		System.assertNotEquals(SAMPLE_SUBJECT, acc.Event_Name__c );
		System.assertEquals(null, acc.Event_URL__c );

		System.runAs(usr){
			Test.startTest();
				eve.Subject = SAMPLE_SUBJECT;
				insert eve;
			Test.stopTest();
		}

		acc = (Account)accBld.refreshFromDB(new set<String>{'Event_Name__c', 'Event_URL__c'}).getRecord();

		System.assertEquals(SAMPLE_SUBJECT, acc.Event_Name__c );
		System.assertEquals(String.valueOf(eve.id).subString(0,15), acc.Event_URL__c );
	}
    
    private static testmethod void populateRelatedTo_NoDml() {
       	usr = (User)new BLD_USER().useCommB().syncContact().commitWork().getRecord();

		System.runAs(usr){
			
			accBld = new BLD_Account().useCommB().useGroupParent().commitWork(); 
			eveBld = new BLD_Event()
								.internalMeeting().meetingPurpose(DMN_Event.CORE_TEAM_MEETING)
								.startDate(System.now()).stopDate(System.now().addHours(1))
								.linkToParent(accBld.getRecordId()).commitWork();
            conBld = new BLD_Contact().useClientContact().accountId(accBld.getRecordId()).commitWork();
		}
        
        Event eve = (Event)eveBld.refreshFromDB(new Set<String>{'WhatId', 'WhoId'}).getRecord();
        Account acc = (Account)accBld.getRecord();
        Contact con = (Contact)conBld.getRecord();
        System.assertEquals(eve.WhoId, null);
        System.assertEquals(eve.WhatId, acc.Id);
        
        System.runAs(usr){
			Test.startTest();
            	eve.Report_Client_Contact__c = con.Id;
        		eve.WhatId = null;
            	DMN_Event.populateRelatedTo(new Event[]{eve}); 
			Test.stopTest();
		}
        
        System.assertEquals(eve.WhoId, con.Id);
        System.assertEquals(eve.WhatId, acc.Id); 
    }

    private static testmethod void populateRelatedTo_Dml() {
        usr = (User)new BLD_USER().useCommB().syncContact().commitWork().getRecord();

		System.runAs(usr){
			accBld = new BLD_Account().useCommB().useGroupParent().commitWork(); 
            conBld = new BLD_Contact().useClientContact().accountId(accBld.getRecordId()).commitWork();
			eveBld = new BLD_Event()
								.externalMeeting().meetingPurpose(DMN_Event.CLIENT_MEETING)
								.startDate(System.now()).stopDate(System.now().addHours(1))
								.setField(Event.Report_Client_Contact__c, conBld.getRecordId()); 
		}
        
        Event eve = (Event)eveBld.refreshFromDB(new Set<String>{'WhatId', 'WhoId'}).getRecord();
        Account acc = (Account)accBld.getRecord();
        Contact con = (Contact)conBld.getRecord();
        
        System.runAs(usr){ 
			Test.startTest();
            	eve.whatId = null;
            	insert eve; 
			Test.stopTest();
		}

        eve = (Event)eveBld.refreshFromDB(new Set<String>{'WhatId', 'WhoId', 'Report_Client_Contact__c'}).getRecord(); 
        System.assertEquals(con.Id, eve.Report_Client_Contact__c);
        System.assertEquals(con.Id, eve.WhoId);
        System.assertEquals(acc.Id, eve.WhatId); 
    }
    
}