force-app/main/default/objects/Account/fields/Group_Parent_CIF_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Parent_CIF_Number__c</fullName>
    <description>This Fields sets the Top Parent CIF Number if a hierarchy exists for Reporting</description>
    <formula>If(ISPICKVAL(CRT_Parent_Child__c, &quot;TP&quot;), CIF__c  ,If(Not(Group_Parent__c = &quot;&quot;) , Group_Parent__r.CIF__c ,&quot;&quot;))</formula>
    <inlineHelpText>CIF number of the Group Parent. If the Client does not have a “Parent” it will be the Group Parent.</inlineHelpText>
    <label>Group Parent CIF Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>GUID used for Gateway API integration. This is the unique value that for security reasons is used instead of BPID to retrieve data for the client, US-4557</description>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Group_Parent_CIF_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Parent_CIF_Number__c</fullName>
    <description>This is helper field to hold Group CIF value from Account (US - 1729).</description>
    <label>Group Parent CIF Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PBB_External_ID__c.field-meta.xml
<CustomField>
    <fullName>PBB_External_ID__c</fullName>
    <description>A Salesforce Identifier for PBB clients, US-4334</description>
    <externalId>true</externalId>
    <label>PBB External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Individual/fields/Guid__c.field-meta.xml
<CustomField>
    <fullName>Guid__c</fullName>
    <description>Related customer GUID, US-4334</description>
    <externalId>true</externalId>
    <label>Guid</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PBB_SRV_RefreshRelatedParties.cls
public with sharing class PBB_SRV_RefreshRelatedParties {
	private static final PBB_SRV_GatewayAPI_RelatedParties.IService RELATED_PARTIES_SERVICE = PBB_SRV_GatewayAPI_RelatedParties.newInstance();
	private static final SRV_Logger LOGGER = (SRV_Logger) SRV_Logger.newInstance();

	@AuraEnabled
	public static void upsertRelatedParties(Id clientId) {
		Account[] records = SEL_Accounts.newInstance().selectGuidById(new Set<Id> { clientId });
		PBB_SRV_GatewayAPI_RelatedParties.Response resp = RELATED_PARTIES_SERVICE.getRelatedParties(clientId);
		if (
		    resp == null || resp.relationshipInformation == null
		    || resp.relationshipInformation.relationship == null
		    || resp.relationshipInformation.relationship.isEmpty()
		) { return; }
		Map<String, Individual> individuals = new Map<String, Individual> ();
		Map<String, Contact> contacts = new Map<String, Contact> ();
		for (PBB_SRV_GatewayAPI_RelatedParties.Relationship singleParty : resp.relationshipInformation.relationship) {
			if (singleParty.RelatedCustomerClassification != PBB_SRV_GatewayAPI_RelatedParties.RelatedCustomerClassification.INDIVIDUAL) { continue; }
			Individual individualRecord;
			if (!contacts.containsKey(singleParty.relatedCustomerGuid)) {
				individualRecord = new Individual(
				                                  Guid__c = singleParty.relatedCustomerGuid,
				                                  FirstName = singleParty.firstName,
				                                  LastName = singleParty.lastName
				);
				individuals.put(singleParty.relatedCustomerGuid, individualRecord);
			}
			String contactExtId = String.format('{0}-{1}', new List<String> { records[0].GUID__c, singleParty.relatedCustomerGuid });
			Contact contactRecord;
			if (!contacts.containsKey(contactExtId)) {
				contactRecord = new Contact(
				                            PBB_External_ID__c = contactExtId,
				                            FirstName = singleParty.firstName,
				                            LastName = singleParty.lastName,
				                            AccountId = clientId,
				                            Group_Parent_CIF_Number__c = records[0].GUID__c,
				                            Individual = new Individual(
				                                                        Guid__c = singleParty.relatedCustomerGuid
				)
				);
				contacts.put(contactExtId, contactRecord);
			} else {
				contactRecord = contacts.get(contactExtId);
			}
			contactRecord.Email = singleParty.email;
			contactRecord.Phone = singleParty.telephone;
			contactRecord.MobilePhone = singleParty.mobile;
			if (String.isBlank(contactRecord.Title)) {
				contactRecord.Title = UTL_String.capitalizeWords(singleParty.relationshipType);
			} else if (!contactRecord.Title.containsIgnoreCase(singleParty.relationshipType)) {
				contactRecord.Title += ', ' + UTL_String.capitalizeWords(singleParty.relationshipType);
			}
		}

		LOGGER.log(Database.upsert(individuals.values(), Individual.Guid__c, false), PBB_SRV_RefreshRelatedParties.class.getName(), DMN_Log.AREA_PBB_GATEWAY);
		LOGGER.log(Database.upsert(contacts.values(), Contact.PBB_External_ID__c, false), PBB_SRV_RefreshRelatedParties.class.getName(), DMN_Log.AREA_PBB_GATEWAY);
	}
}