force-app/main/default/objects/Account/fields/Group_KYC_Review_In_Progress__c.field-meta.xml
<CustomField>
    <fullName>Group_KYC_Review_In_Progress__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EN:1043 This field will check if client is in the process of a KYC Review.This will be used to report on Clients in KYC</description>
    <inlineHelpText>This is an indication if any of the clients within the Group (based on client hierarchy) are under KYC review</inlineHelpText>
    <label>Group KYC Review In Progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Parent__c.field-meta.xml
<CustomField>
    <fullName>Group_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Group Parent)</relationshipLabel>
    <relationshipName>GroupParents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/KYC_Status__c.field-meta.xml
<CustomField>
    <fullName>KYC_Status__c</fullName>
    <label>KYC Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Freeze Level 2</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Unfreeze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_Status__c/KYC_Status__c.object-meta.xml
<CustomObject>
    <description>KYC Status Object Updated in 2015 (EN-0670) as part of the Data Project and KYC Workstream Updates</description>
    <label>KYC Status</label>
    <nameField>
        <displayFormat>KYC-{000000}</displayFormat>
        <label>KYC Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYC Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KYC_Status__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KYC Statuses</relationshipLabel>
    <relationshipName>KYC_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KYC_Status__c/fields/Closure_Suspended_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closure_Suspended_Reason__c</fullName>
    <description>Closure / Suspended Reason</description>
    <inlineHelpText>Closure / Suspended Reason</inlineHelpText>
    <label>Closure/Suspended Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Documents Provided</fullName>
            </value>
            <value>
                <fullName>Record created in error</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
            <value>
                <fullName>Duplicate record</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive/Dormant</fullName>
            </value>
            <value>
                <fullName>Parent Closed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>De-Registered</fullName>
            </value>
            <value>
                <fullName>Closed on Take-on</fullName>
            </value>
            <value>
                <fullName>Relationship moved to retail</fullName>
            </value>
            <value>
                <fullName>Liquidated</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Merger &amp; Acquisition</fullName>
            </value>
            <value>
                <fullName>Amend Owner Form</fullName>
            </value>
            <value>
                <fullName>Sanctioned Entity</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>KYC Outstanding</fullName>
            </value>
            <value>
                <fullName>Propagated</fullName>
            </value>
            <value>
                <fullName>Awaiting Closure</fullName>
            </value>
            <value>
                <fullName>Dispensation Expired</fullName>
            </value>
            <value>
                <fullName>BS&amp;R</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_Status__c/fields/Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>Entity_Code__c</fullName>
    <label>Entity Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARG</fullName>
            </value>
            <value>
                <fullName>BSI</fullName>
            </value>
            <value>
                <fullName>LIB</fullName>
            </value>
            <value>
                <fullName>SALL</fullName>
            </value>
            <value>
                <fullName>SBA</fullName>
            </value>
            <value>
                <fullName>SBAO</fullName>
            </value>
            <value>
                <fullName>SBAU</fullName>
            </value>
            <value>
                <fullName>SBBW</fullName>
            </value>
            <value>
                <fullName>SBCD</fullName>
            </value>
            <value>
                <fullName>SBCI</fullName>
            </value>
            <value>
                <fullName>SBGH</fullName>
            </value>
            <value>
                <fullName>SBGS</fullName>
            </value>
            <value>
                <fullName>SBKE</fullName>
            </value>
            <value>
                <fullName>SBLS</fullName>
            </value>
            <value>
                <fullName>SBMU</fullName>
            </value>
            <value>
                <fullName>SBMW</fullName>
            </value>
            <value>
                <fullName>SBMZ</fullName>
            </value>
            <value>
                <fullName>SBN</fullName>
            </value>
            <value>
                <fullName>SBNA</fullName>
            </value>
            <value>
                <fullName>SBSA</fullName>
                <default>true</default>
                <label>SBSA</label>
            </value>
            <value>
                <fullName>SBSZ</fullName>
            </value>
            <value>
                <fullName>SBT</fullName>
            </value>
            <value>
                <fullName>SBTZ</fullName>
            </value>
            <value>
                <fullName>SBU</fullName>
            </value>
            <value>
                <fullName>SBUG</fullName>
            </value>
            <value>
                <fullName>SBZM</fullName>
            </value>
            <value>
                <fullName>SBZW</fullName>
            </value>
            <value>
                <fullName>SFL</fullName>
            </value>
            <value>
                <fullName>SMBA</fullName>
            </value>
            <value>
                <fullName>SSAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_Status__c/fields/KYC_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>KYC_Review_Status__c</fullName>
    <description>KYC Review Status</description>
    <inlineHelpText>KYC Review Status</inlineHelpText>
    <label>KYC Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Awaiting Compliance/Legal Guidance</fullName>
            </value>
            <value>
                <fullName>Client Risk Committee Approval Outstanding</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Compliant</fullName>
            </value>
            <value>
                <fullName>Deferred Entities</fullName>
            </value>
            <value>
                <fullName>Entities Still to Contact</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>KYC Processing Documents</fullName>
            </value>
            <value>
                <fullName>KYC Reviewer Approval Outstanding</fullName>
            </value>
            <value>
                <fullName>Migrated Entity to Contact</fullName>
            </value>
            <value>
                <fullName>Migrated to PBB</fullName>
            </value>
            <value>
                <fullName>Migration in Progress</fullName>
            </value>
            <value>
                <fullName>Potential Closure</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_Status__c/fields/KYC_Status__c.field-meta.xml
<CustomField>
    <fullName>KYC_Status__c</fullName>
    <formula>CASE( Status__c ,&quot;Y&quot;,&quot;Complete&quot;,&quot;N&quot;,&quot;Not Complete&quot;,&quot;S&quot;,&quot;Suspended&quot;,&quot;E&quot;,&quot;Exited&quot;,&quot;R&quot;,&quot;Requested&quot;,&quot;N/A&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KYC Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KYC_Status__c/fields/Review_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Review_Completed_Date__c</fullName>
    <description>Date of review completion</description>
    <inlineHelpText>Date of review completion</inlineHelpText>
    <label>Review Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/KYCStatusTriggerUtilityTest.cls
/* @Class Name   : KYCStatusTriggerUtilityTest
 * @Description  : Test class for KYCStatusTriggerUtility
 * @Created By   : Manoj Gupta
 * @Created On   : 17 Feb 2016
 * @Modification Log:  
 * --------------------------------------------------------------------------------------------------
 * @Developer                Date                   Description
 * --------------------------------------------------------------------------------------------------

 
 * ---------------------------------------------------------------------------------------------------
*/

@IsTest(SeeAllData=false)
private class KYCStatusTriggerUtilityTest {

    @TestSetup
    static void setupData() {
        TEST_DataFactory.insertSettings(new List<Object> {
            TEST_DataFactory.getOpenKycReviewStatuses()
        });
    }

    /**********************************************************
     @vishnu(26-03-2015) : EN-694 : Test method to test tasks notification to escalated to business users
    **********************************************************/
    @IsTest
    static void testUpdateOfGroupKYCReviewStatus() {

        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();

        List<Account> lstTestAccount = new List<Account> {
            (Account) new BLD_Account(uow).useGroupParent().CIF('11223344').getRecord(),
            (Account) new BLD_Account(uow).useImmediateParent().getRecord(),
            (Account) new BLD_Account(uow).getRecord()
        };

        uow.commitWork();

        lstTestAccount[1].Group_Parent__c = lstTestAccount[0].Id;
        lstTestAccount[2].Group_Parent__c = lstTestAccount[0].Id;

        update lstTestAccount ;

        // create standard user
        User user01 = (User) new BLD_USER().useKyc().title('Senior').getRecord();
        System.runAs(new User(Id = UserInfo.getUserId())) {
            insert user01;
        }

        List<KYC_Status__c> lstKYCToInsert = new List<KYC_Status__c>();

        KYC_Status__c kyc = new KYC_Status__c();
        kyc.Client__c = lstTestAccount[0].Id ;
        kyc.Entity_Code__c = 'SBSA';
        kyc.KYC_Review_Status__c = 'In progress';
        lstKYCToInsert.add(kyc);

        KYC_Status__c kyc2 = new KYC_Status__c();
        kyc2.Client__c = lstTestAccount[1].Id ;
        kyc2.Entity_Code__c = 'SBSA';
        kyc2.KYC_Review_Status__c = 'KYC Processing Documents';
        lstKYCToInsert.add(kyc2);

        KYC_Status__c kyc3 = new KYC_Status__c();
        kyc3.Client__c = lstTestAccount[0].Id ;
        kyc3.Entity_Code__c = 'ARG';
        kyc3.KYC_Review_Status__c = 'KYC Processing Documents';
        lstKYCToInsert.add(kyc3);

        KYC_Status__c kyc4 = new KYC_Status__c();
        kyc4.Client__c = lstTestAccount[2].Id ;
        kyc4.Entity_Code__c = 'SBSA';
        kyc4.KYC_Review_Status__c = 'Entities Still to Contact';
        lstKYCToInsert.add(kyc4);

        insert lstKYCToInsert;

        System.runAs(user01) {
            Test.startTest();
            kyc.KYC_Review_Status__c = 'Closed';
            kyc.Closure_Suspended_Reason__c = 'Exited';
            kyc.Review_Completed_Date__c = Date.today();

            kyc2.KYC_Review_Status__c = 'Suspended';
            kyc2.Closure_Suspended_Reason__c = 'Pending';
            kyc2.Review_Completed_Date__c = Date.today();

            kyc3.KYC_Review_Status__c = 'Closed';
            kyc3.Closure_Suspended_Reason__c = 'Exited';
            kyc3.Review_Completed_Date__c = Date.today();

            kyc4.KYC_Review_Status__c = 'In Progress';
            kyc4.Closure_Suspended_Reason__c = 'Pending';
            kyc4.Review_Completed_Date__c = Date.today();
            update lstKYCToInsert;
            Test.stopTest();

            Account acc0 = [SELECT Id,Group_KYC_Review_In_Progress__c FROM Account WHERE Id = :lstTestAccount[0].Id];

            System.assertEquals(false, acc0.Group_KYC_Review_In_Progress__c);

            Account acc1 = [SELECT Id,Group_KYC_Review_In_Progress__c FROM Account WHERE Id = :lstTestAccount[1].Id];

            System.assertEquals(true, acc1.Group_KYC_Review_In_Progress__c);

        }

    }


}