force-app/main/default/objects/Account/fields/KYC_Status__c.field-meta.xml
<CustomField>
    <fullName>KYC_Status__c</fullName>
    <label>KYC Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Freeze Level 2</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Unfreeze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <description>Registration number of company</description>
    <inlineHelpText>Registration number of company</inlineHelpText>
    <label>Registration Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>CIF Allocated</fullName>
            </value>
            <value>
                <fullName>Need Approval Again</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Potential</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Rejected by GoldTier</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Submitted for Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_Status__c/KYC_Status__c.object-meta.xml
<CustomObject>
    <description>KYC Status Object Updated in 2015 (EN-0670) as part of the Data Project and KYC Workstream Updates</description>
    <label>KYC Status</label>
    <nameField>
        <displayFormat>KYC-{000000}</displayFormat>
        <label>KYC Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYC Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KYC_Status__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KYC Statuses</relationshipLabel>
    <relationshipName>KYC_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KYC_Status__c/fields/Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>Entity_Code__c</fullName>
    <label>Entity Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARG</fullName>
            </value>
            <value>
                <fullName>BSI</fullName>
            </value>
            <value>
                <fullName>LIB</fullName>
            </value>
            <value>
                <fullName>SALL</fullName>
            </value>
            <value>
                <fullName>SBA</fullName>
            </value>
            <value>
                <fullName>SBAO</fullName>
            </value>
            <value>
                <fullName>SBAU</fullName>
            </value>
            <value>
                <fullName>SBBW</fullName>
            </value>
            <value>
                <fullName>SBCD</fullName>
            </value>
            <value>
                <fullName>SBCI</fullName>
            </value>
            <value>
                <fullName>SBGH</fullName>
            </value>
            <value>
                <fullName>SBGS</fullName>
            </value>
            <value>
                <fullName>SBKE</fullName>
            </value>
            <value>
                <fullName>SBLS</fullName>
            </value>
            <value>
                <fullName>SBMU</fullName>
            </value>
            <value>
                <fullName>SBMW</fullName>
            </value>
            <value>
                <fullName>SBMZ</fullName>
            </value>
            <value>
                <fullName>SBN</fullName>
            </value>
            <value>
                <fullName>SBNA</fullName>
            </value>
            <value>
                <fullName>SBSA</fullName>
                <default>true</default>
                <label>SBSA</label>
            </value>
            <value>
                <fullName>SBSZ</fullName>
            </value>
            <value>
                <fullName>SBT</fullName>
            </value>
            <value>
                <fullName>SBTZ</fullName>
            </value>
            <value>
                <fullName>SBU</fullName>
            </value>
            <value>
                <fullName>SBUG</fullName>
            </value>
            <value>
                <fullName>SBZM</fullName>
            </value>
            <value>
                <fullName>SBZW</fullName>
            </value>
            <value>
                <fullName>SFL</fullName>
            </value>
            <value>
                <fullName>SMBA</fullName>
            </value>
            <value>
                <fullName>SSAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_Status__c/fields/KYC_Status__c.field-meta.xml
<CustomField>
    <fullName>KYC_Status__c</fullName>
    <formula>CASE( Status__c ,&quot;Y&quot;,&quot;Complete&quot;,&quot;N&quot;,&quot;Not Complete&quot;,&quot;S&quot;,&quot;Suspended&quot;,&quot;E&quot;,&quot;Exited&quot;,&quot;R&quot;,&quot;Requested&quot;,&quot;N/A&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KYC Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KYC_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>R</fullName>
                <default>true</default>
                <label>R</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AOB_LegalEntityHierarchy_Test.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
*
* Test Class for AOB_LegalEntityHierarchyResource class
*
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Caro Reinecke
* @version        1.0
* @created        2018-02-20
* @systemLayer    Test ( Choose from: Invocation | Service | Utility | Selector | Domain | Test )
* @description TestClass for AOB_LegalHierarchyResource
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/

@IsTest
private class AOB_LegalEntityHierarchy_Test {

    private static final Integer HTTP_RESPONSE_CODE_OK = 200;
    private static final Integer HTTP_RESPONSE_CODE_ERROR = 500;

    private static final String
            USER_NAME           = 'henimmarrifi-1815@yopmail.com',
            DEF_ACC_NAME        = 'Def Name for Acc',
            GROUP_NUMBER        = '123456';

    private static User aobUser {
        get {
            if (aobUser == null) {
                aobUser = [SELECT Id FROM User WHERE UserName = :USER_NAME];
            }
            return aobUser;
        }
    }

    @TestSetup
    static void setup() {
        new BLD_USER(USER_NAME)
                .useAPIUser()
                .commitWork();
        System.runAs(aobUser) {

            fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();

            BLD_Account parentAccount = new BLD_Account(uow).CIF('530437495').name('parent0').useGroupParent();
            BLD_Account secondParentAccount = new BLD_Account(uow).CIF('100061211').name('parent1').useGroupParent();

            parentAccount
                    .setField(Account.BillingCountry,'South Africa')
                    .setField(Account.Registration_Number__c,'2020/2020/2020');
            secondParentAccount
                    .setField(Account.BillingCountry,'South Africa')
                    .setField(Account.Registration_Number__c,'2121/2121/2121');
            new BLD_KYC_Status(uow)
                    .setField(KYC_Status__c.Entity_Code__c,'SBSA')
                    .setField(KYC_Status__c.Status__c,'y')
                    .setRelation(KYC_Status__c.Client__c,parentAccount);

            new BLD_KYC_Status(uow)
                    .setField(KYC_Status__c.Entity_Code__c,'SBSA')
                    .setField(KYC_Status__c.Status__c,'N')
                    .setRelation(KYC_Status__c.Client__c,secondParentAccount);

            uow.commitWork();

            uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
            BLD_Account immediateChildAccount = new BLD_Account(uow).CIF('1000666621').name('i01').useImmediateParent(parentAccount);
            BLD_Account immediateChildAccount1 = new BLD_Account(uow).CIF('1000666623').name('ip1').useImmediateParent(parentAccount);
            BLD_Account immediateChildAccount2 = new BLD_Account(uow).CIF('1000666624').name('ip2').useImmediateParent(secondParentAccount);
            BLD_Account immediateChildAccount3 = new BLD_Account(uow).CIF('1000666625').name('ip3').useImmediateParent(secondParentAccount);

            immediateChildAccount
                    .setField(Account.BillingCountry,'South Africa')
                    .setField(Account.Registration_Number__c,'2022/2022/2022');
            immediateChildAccount1
                    .setField(Account.BillingCountry,'South Africa')
                    .setField(Account.Registration_Number__c,'2023/2023/2023');
            immediateChildAccount2
                    .setField(Account.BillingCountry,'South Africa')
                    .setField(Account.Registration_Number__c,'2024/2024/2024');
            immediateChildAccount3
                    .setField(Account.BillingCountry,'South Africa')
                    .setField(Account.Registration_Number__c,'2025/2025/2025');
            uow.commitWork();

            uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
            BLD_Account childAccount = new BLD_Account(uow).CIF('1000666620').name('child0').useChild(immediateChildAccount, parentAccount);
            BLD_Account invalidAccount = new BLD_Account(uow).name(DEF_ACC_NAME).useCommB().useGroupParent().groupNumber(GROUP_NUMBER).cibTarget(true);
            childAccount
                    .setField(Account.BillingCountry,'South Africa')
                    .setField(Account.Registration_Number__c,'2120/2120/2120');

            new BLD_KYC_Status(uow)
                    .setField(KYC_Status__c.Entity_Code__c,'SBSA')
                    .setField(KYC_Status__c.Status__c,'y')
                    .setRelation(KYC_Status__c.Client__c,childAccount);

            uow.commitWork();

        }
    }

    @IsTest
    static void testPostMethodPositive() {
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri ='/services/apexrest/LegalEntities';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('["1000666620","100061211"]');
        RestContext.request = request;
        RestContext.response = response;
        Test.startTest();
        AOB_LegalEntityHierarchyResource.doPost();
        Test.stopTest();
        System.assertEquals(HTTP_RESPONSE_CODE_OK, RestContext.response.statusCode);
    }

    @IsTest
    static void testPostMethodNegative() {
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri ='/services/apexrest/LegalEntities';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('[]');
        RestContext.request = request;
        RestContext.response = response;
        Test.startTest();
        AOB_LegalEntityHierarchyResource.doPost();
        Test.stopTest();
        System.assertEquals(HTTP_RESPONSE_CODE_OK, RestContext.response.statusCode);
    }

    @IsTest
    static void testPostMethodNoCIF() {
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri ='/services/apexrest/LegalEntities';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('');
        RestContext.request = request;
        RestContext.response = response;
        Test.startTest();
        AOB_LegalEntityHierarchyResource.doPost();
        Test.stopTest();
        System.assertEquals(HTTP_RESPONSE_CODE_OK, RestContext.response.statusCode);
    }

    @IsTest
    static void testPosttMethodAccountServiceException() {
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri ='/services/apexrest/LegalEntities';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('["INVALID1"]');
        RestContext.request = request;
        RestContext.response = response;
        Test.startTest();
        AOB_LegalEntityHierarchyResource.doPost();
        Test.stopTest();
        System.assertEquals(HTTP_RESPONSE_CODE_OK, RestContext.response.statusCode);
    }
}