force-app/main/default/objects/Account/fields/Overall_CIB_CSI_Rating_Number__c.field-meta.xml
<CustomField>
    <fullName>Overall_CIB_CSI_Rating_Number__c</fullName>
    <label>Overall CIB CSI Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/Custom_Client_Team__c.object-meta.xml
<CustomObject>
    <label>Client Team</label>
    <nameField>
        <displayFormat>Client-{0000}</displayFormat>
        <label>Client Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Client_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <description>Team member object connects either internal staff or contractors to a project assignment.  If you further customize the application, you can prevent &quot;stray time reporting&quot; using apex coding so that team members cannot report time outside of the assigned date range.  This becomes important if your organization reports heavily on project costing or SOP-98 capital/expense.  in addition, Force.com Visualforce or Adobe Flex code can be leveraged to help with the matching of resources to projects/work requests.  Please contact professional services for more information on consulting rates or the Salesforce.com Developer network (www.salesforce.com/developer).</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is a lookup to the user and used to assign internal staff to a project team member.</inlineHelpText>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N80000002lXWPEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CI_ClientListController.cls
public without sharing class CI_ClientListController {
    @AuraEnabled
    public static CI_ResponseDto getClientList(String recordType, String searchTerm){
        CI_SharedUtilities sharedUtils = new CI_SharedUtilities();
        CI_CardListObjectModel clients = new CI_CardListObjectModel();

        //get the list
        clients.Description ='Client List';

        String userID = '\'' + UserInfo.getUserId() + '\'';
        String recordTypeFilter = '';
        String clientNameFilter = '';
        
        if(recordType != null)
            recordTypeFilter = ' AND RecordType.Name = \'' + recordType + '\'';   
        
        if(searchTerm != null && searchTerm != '')
        {
            if(searchTerm.Length() == 1)
                clientNameFilter = searchTerm + '%';
            else
                clientNameFilter = '%' + searchTerm + '%';
            
            clientNameFilter = ' AND Name LIKE \'' + clientNameFilter + '\'';
        }

        String queryString = 'SELECT Name, Id, billingCountry, Overall_CIB_CSI_Rating_Number__c, LastModifiedDate, RecordType.Name FROM Account WHERE Id in (SELECT Account__c FROM Custom_Client_Team__c where Team_Member__c = ' + userID + ')' +
                                                  recordTypeFilter + 
                                                  clientNameFilter +
                                                  ' ORDER BY LastModifiedDate DESC NULLS LAST';

        System.debug('Search   ' + queryString);
        
        List<Account> clientList = Database.query(queryString);

        Map<String, String> clientMap;

        for(Account acc: clientList)
        {
            clientMap = new Map<String, String>();
            Boolean revenueFound = false;

            clientMap.put('Id', acc.Id);
            clientMap.put('Name', acc.Name);
            clientMap.put('BillingCountry', acc.billingCountry);
            clientMap.put('LastModifiedDate', String.valueOf(acc.LastModifiedDate));
            clientMap.put('CSIRating', acc.Overall_CIB_CSI_Rating_Number__c != null ? String.valueOf(acc.Overall_CIB_CSI_Rating_Number__c) : null);
            clientMap.put('ClientHierarchyPosition', acc.RecordType.Name);


            if(!revenueFound)
                clientMap.put('GlobalClientRevenue', '0');

            clients.cardObjectList.add(clientMap);
        }                          
        
        clients.cardObject = searchTerm;
        //return the list
        return new CI_ResponseDto(clients);
    }

    @AuraEnabled
    public static void getClientForViewLastViewed(String clientId){

        List<Account> clientList = [SELECT Id
                                    FROM Account 
                                    WHERE Id =: clientId 
                                    FOR VIEW];
    }
}