force-app/main/default/objects/Account/fields/Primary_Relationship_Holder__c.field-meta.xml
<CustomField>
    <fullName>Primary_Relationship_Holder__c</fullName>
    <description>The field determines whether the client is a CIB or a CB client (EN-908).</description>
    <inlineHelpText>The field determines whether the client is a CIB or a PBB client (Commercial, Business, Small Enterprises or Personal)</inlineHelpText>
    <label>Primary Relationship Holder</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal Banking</fullName>
            </value>
            <value>
                <fullName>Business Banking</fullName>
            </value>
            <value>
                <fullName>Commercial Banking</fullName>
            </value>
            <value>
                <fullName>Corporate and Investment Banking</fullName>
            </value>
            <value>
                <fullName>Other PBB Divisions</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Event Report Object to store the Event Information and associate Attendees and Send Email to them.</description>
    <label>Event Report</label>
    <nameField>
        <label>Event Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Meeting_Audience__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Audience__c</fullName>
    <description>The nature of the meeting and its participants. E.g. Internal would represent a client team meeting about this Client, not with the Client</description>
    <inlineHelpText>The nature of the meeting and its participants. E.g. Internal would represent a client team meeting about this Client, not with the Client</inlineHelpText>
    <label>Meeting Audience</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Meeting_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Purpose__c</fullName>
    <description>The specific type of meeting that was held internally or externally. E.g. An Internal meeting can be further defined as a core client team meeting or a day to day meeting</description>
    <inlineHelpText>The specific type of meeting that was held internally or externally. E.g. An Internal meeting can be further defined as a core client team meeting or a day to day meeting</inlineHelpText>
    <label>Meeting Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Meeting_Audience__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Client Discussion/Insights</fullName>
            </value>
            <value>
                <fullName>Client Execution</fullName>
            </value>
            <value>
                <fullName>Client Pitch</fullName>
            </value>
            <value>
                <fullName>Client Road Show</fullName>
            </value>
            <value>
                <fullName>Client Service</fullName>
            </value>
            <value>
                <fullName>Client Training</fullName>
            </value>
            <value>
                <fullName>Market Research Update</fullName>
            </value>
            <value>
                <fullName>Core Client Team Meeting</fullName>
            </value>
            <value>
                <fullName>Day To Day Meeting</fullName>
            </value>
            <value>
                <fullName>NBAC Meeting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Relate_to_Client__c.field-meta.xml
<CustomField>
    <fullName>Relate_to_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link related client to event report</description>
    <inlineHelpText>The Client that was ‘discussed at / included in’ the meeting. You are required to provide a Related to Client when the Meeting Audience is Internal, and there is no Related to Opportunity, Case or Campaign</inlineHelpText>
    <label>Related to Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Reports (Relate to Client)</relationshipLabel>
    <relationshipName>Event_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EventReport_Navigate_Lightning_TEST.cls
/**
 * Test class for EventReport_Navigate_Lightning
 *
 * @author		Youssef Ibrahim (yibrahim@deloittece.com)
 * @date		December 2020
*/
@IsTest
public class EventReport_Navigate_Lightning_TEST {

    public static final String TEST_CIB_USERNAME = 'test.cibUser@test.com';
    public static final String DEF_ACC_NAME = 'Def Name for Acc';

    private static User cibUser;
    private static Account acc;

    @TestSetup
    private static void setupData() {
        TEST_DataFactory.insertSettings(new List<Object> {
                TEST_DataFactory.getEnvironmentVariable()
        });
        fflib_SObjectUnitOfWork uow;
        System.runAs(new User(Id = UserInfo.getUserId())){
            uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
            cibUser = (User)new BLD_USER(uow)
                    .userName(TEST_CIB_USERNAME)
                    .useCib()
                    .syncContact()
                    .getRecord();

            uow.commitWork();
        }
        System.runAs(cibUser){
            acc = (Account) new BLD_Account(uow)
                    .name(DEF_ACC_NAME)
                    .useCib()
                    .getRecord();
            uow.commitWork();
        }
    }

    private static void getData(){
        cibUser = [
                SELECT Id
                FROM User
                WHERE UserName = :TEST_CIB_USERNAME
        ];

        acc = [
                SELECT
                        Name,
                        Primary_Relationship_Holder__c
                FROM Account
                WHERE Name = :DEF_ACC_NAME
        ];
    }

    @IsTest
    static void shouldSaveSuccessfullyTrueCoreCheck() {
        getData();
        ApexPages.StandardController stdController;
        EventReport_Navigate_Lightning cont = new EventReport_Navigate_Lightning(stdController);
        cont.eventReportRecord.Subject__c = cont.eventReportValues;
        cont.eventReportRecord.Meeting_Audience__c = DMN_CallReport.INTERNAL;
        cont.eventReportRecord.Meeting_Purpose__c = DMN_CallReport.CORE_TEAM_MEETING;
        cont.eventReportRecord.Relate_to_Client__c = acc.Id;

        System.runAs(cibUser) {
            Test.startTest();
            PageReference result = cont.Save();
            Test.stopTest();

            System.assertNotEquals(null, result);
            System.assertEquals(cont.eventReportRecord.Id, result.getParameters().get('reportid'));
            System.assertEquals(cont.eventReportValues, cont.eventReportRecord.Name);
            System.assertEquals(encodeDateTime(cont.startDate), cont.eventReportRecord.Start__c);
            System.assertEquals(encodeDateTime(cont.endDate), cont.eventReportRecord.End__c);

            List<Call_Report__c> insertedEvent = [
                    SELECT
                            Name, Start__c, End__c
                    FROM Call_Report__c
                    WHERE Subject__c = :cont.eventReportValues
            ];
            System.assertEquals(1, insertedEvent.size());
            System.assertEquals(cont.eventReportValues+'-'+DEF_ACC_NAME, insertedEvent[0].Name);
            System.assertEquals(encodeDateTime(cont.startDate), insertedEvent[0].Start__c);
            System.assertEquals(encodeDateTime(cont.endDate), insertedEvent[0].End__c);
        }
    }

    @IsTest
    static void shouldSaveSuccessfullyFalseCoreCheck() {
        getData();
        ApexPages.StandardController stdController;
        EventReport_Navigate_Lightning cont = new EventReport_Navigate_Lightning(stdController);
        cont.eventReportRecord.Subject__c = cont.eventReportValues;

        System.runAs(cibUser) {
            Test.startTest();
            PageReference result = cont.Save();
            Test.stopTest();

            System.assertNotEquals(null, result);
            System.assertEquals('/'+cont.eventReportRecord.Id, result.getUrl());
        }
    }

    @IsTest
    static void shouldSaveFailDMLException() {
        getData();
        ApexPages.StandardController stdController;
        EventReport_Navigate_Lightning cont = new EventReport_Navigate_Lightning(stdController);
        System.runAs(cibUser) {
            Test.startTest();
            PageReference result = cont.Save();
            Test.stopTest();

            List<Call_Report__c> insertedEvent = [
                    SELECT
                            Id
                    FROM Call_Report__c
                    WHERE Subject__c = :cont.eventReportValues
            ];
            System.assertEquals(null, result);
            System.assertEquals(0, insertedEvent.size());
        }
    }

    @IsTest
    static void shouldSaveAndNewSuccessfully() {
        getData();
        ApexPages.StandardController stdController;
        EventReport_Navigate_Lightning cont = new EventReport_Navigate_Lightning(stdController);
        cont.eventReportRecord.Subject__c = cont.eventReportValues;
        cont.eventReportRecord.Meeting_Audience__c = DMN_CallReport.INTERNAL;
        cont.eventReportRecord.Meeting_Purpose__c = DMN_CallReport.CORE_TEAM_MEETING;
        cont.eventReportRecord.Relate_to_Client__c = acc.Id;

            Test.startTest();
            PageReference result = cont.SaveAndNew();
            Test.stopTest();

            System.assertNotEquals(null, result);
            System.assertEquals('/apex/EventReport_New_Navigate', result.getUrl());

            List<Call_Report__c> insertedEvent = [
                    SELECT
                            Name, Start__c, End__c
                    FROM Call_Report__c
                    WHERE Subject__c = :cont.eventReportValues
            ];
            System.assertEquals(1, insertedEvent.size());
            System.assertEquals(cont.eventReportValues+'-'+DEF_ACC_NAME, insertedEvent[0].Name);
            System.assertEquals(encodeDateTime(cont.startDate), insertedEvent[0].Start__c);
            System.assertEquals(encodeDateTime(cont.endDate), insertedEvent[0].End__c);
    }

    @IsTest
    static void shouldSaveAndNewFailDMLException() {
        getData();
        ApexPages.StandardController stdController;
        EventReport_Navigate_Lightning cont = new EventReport_Navigate_Lightning(stdController);
            Test.startTest();
            PageReference result = cont.SaveAndNew();
            Test.stopTest();

            List<Call_Report__c> insertedEvent = [
                    SELECT
                            Id
                    FROM Call_Report__c
                    WHERE Subject__c = :cont.eventReportValues
            ];
            System.assertEquals(null, result);
            System.assertEquals(0, insertedEvent.size());
    }

    @IsTest
    static void shouldCancelRequest() {
        getData();
        ApexPages.StandardController stdController;
        EventReport_Navigate_Lightning cont = new EventReport_Navigate_Lightning(stdController);
            Test.startTest();
            PageReference result = cont.cancelRequest();
            Test.stopTest();

            System.assertNotEquals(null, result);
            System.assertEquals('/a0K/o', result.getUrl());
            System.assert(result.getRedirect());
    }

    private static Datetime encodeDateTime(String value) {
        DateTime dt = null;

        String datePart = value.split(' ')[0];
        String timePart = value.split(' ')[1];

        List<String> dateSplit = datePart.split('/');
        Integer year = Integer.valueOf(dateSplit[2]);
        Integer month = Integer.valueOf(dateSplit[1]);
        Integer day = Integer.valueOf(dateSplit[0]);

        List<String> times = timePart.split(':');
        Integer hours = Integer.valueOf(times[0]);
        Integer minutes = Integer.valueOf(times[1]);

        dt = DateTime.newInstance(year, month, day, hours, minutes, 0);
        
        return dt;
    }
}