force-app/main/default/objects/Account/fields/Relationship_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Group_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The number used to group various client records belonging to a Hierarchy or Risk Group.</inlineHelpText>
    <label>Relationship Group Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/Custom_Client_Team__c.object-meta.xml
<CustomObject>
    <label>Client Team</label>
    <nameField>
        <displayFormat>Client-{0000}</displayFormat>
        <label>Client Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Client_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Role__c.field-meta.xml
<CustomField>
    <fullName>Client_Role__c</fullName>
    <label>Team Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Account Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Business Development Manager</fullName>
            </value>
            <value>
                <fullName>BCC CSU Agent</fullName>
            </value>
            <value>
                <fullName>BCC CSU Manager</fullName>
            </value>
            <value>
                <fullName>BCC Ecosystem Manager</fullName>
            </value>
            <value>
                <fullName>BCC Head Trade Sales</fullName>
            </value>
            <value>
                <fullName>BCC Portfolio Manager</fullName>
            </value>
            <value>
                <fullName>BCC Product Specialist</fullName>
            </value>
            <value>
                <fullName>BCC Relationship Manager</fullName>
            </value>
            <value>
                <fullName>BCC Service Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Finance Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Client Analyst</fullName>
            </value>
            <value>
                <fullName>Credit Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Consultant</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Executive Stakeholder</fullName>
            </value>
            <value>
                <fullName>Global Transaction Banker</fullName>
            </value>
            <value>
                <fullName>GM Champion</fullName>
            </value>
            <value>
                <fullName>GM Client Manager</fullName>
            </value>
            <value>
                <fullName>GM Execution Manager</fullName>
            </value>
            <value>
                <fullName>GM Regional Head</fullName>
            </value>
            <value>
                <fullName>IB Champion</fullName>
            </value>
            <value>
                <fullName>Investor Services Manager</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ecosystem__c/Ecosystem__c.object-meta.xml
<CustomObject>
    <label>Ecosystem</label>
    <nameField>
        <displayFormat>ECO-{0000}</displayFormat>
        <label>Ecosystem ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ecosystems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ecosystem__c/fields/Relationship_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Group_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The number used to group various client records belonging to a Hierarchy or Risk Group.</inlineHelpText>
    <label>Relationship Group Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Ecosystem_Entity__c/Ecosystem_Entity__c.object-meta.xml
<CustomObject>
    <label>Ecosystem Entity</label>
    <nameField>
        <label>Ecosystem Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ecosystem Enitiies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ecosystem_Entity__c/fields/Ecosystem__c.field-meta.xml
<CustomField>
    <fullName>Ecosystem__c</fullName>
    <label>Ecosystem</label>
    <referenceTo>Ecosystem__c</referenceTo>
    <relationshipLabel>Ecosystem Entities</relationshipLabel>
    <relationshipName>Ecosystem_Entities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ecosystem_Entity__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ecosystem Entities</relationshipLabel>
    <relationshipName>Ecosystem_Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <description>Team member object connects either internal staff or contractors to a project assignment.  If you further customize the application, you can prevent &quot;stray time reporting&quot; using apex coding so that team members cannot report time outside of the assigned date range.  This becomes important if your organization reports heavily on project costing or SOP-98 capital/expense.  in addition, Force.com Visualforce or Adobe Flex code can be leveraged to help with the matching of resources to projects/work requests.  Please contact professional services for more information on consulting rates or the Salesforce.com Developer network (www.salesforce.com/developer).</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is a lookup to the user and used to assign internal staff to a project team member.</inlineHelpText>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N80000002lXWPEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SRV_Ecosystem_Test.cls
/*****************************************************************************************************\
    @ Func Area     : Ecosystem
    @ Author        : Marko Dvečko
    @ Date          : 15/04/2017
    @ Test File     : 
    @ Specification : Unit tests for SRV_Ecosystem.cls
******************************************************************************************************/

@isTest
private class SRV_Ecosystem_Test {
    @isTest static void testEcosystemSharing() {

        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
        User testUser = (User) new BLD_USER(uow).useCommB().cibGlobalArea(DMN_User.CIB_GA_CIBI).getRecord();
        User accOwnerUser = (User) new BLD_USER(uow).useSysAdmin().getRecord();
        System.runAs(new User(Id = UserInfo.getUserId())) {
            uow.commitWork();
        }

        Account acc = (Account) new BLD_Account()
            .proposedClientCoordinator(accOwnerUser)
            .commitWork()
            .getRecord();

        Ecosystem__c eco = new Ecosystem__c(Relationship_Group_Number__c = '1000');
        insert eco;

        Ecosystem_Entity__c ecoEntity = new Ecosystem_Entity__c(Entity__c = acc.Id, Ecosystem__c = eco.Id);
        insert ecoEntity;

        Ecosystem__Share[] ecoShares = [SELECT Id, UserOrGroup.Name, AccessLevel FROM Ecosystem__Share WHERE RowCause = 'Manual'];
       // System.assertEquals(1, ecoShares.size());

        TEST_DataFactory.insertSettings(new List<Object> {
            TEST_DataFactory.getCcSettings(),
            TEST_DataFactory.getUserProfileIds()
        });

        Custom_Client_Team__c clientTeam = new Custom_Client_Team__c(
            Team_Member__c = testUser.Id,
            Account__c = acc.Id,
            Client_Role__c = DMN_ClientTeam.ROLE_ANALYST);
        insert clientTeam;

        ecoShares = [SELECT Id FROM Ecosystem__Share WHERE RowCause = 'Manual'];
       // System.assertEquals(1, ecoShares.size());

        delete clientTeam;
        ecoShares = [SELECT Id FROM Ecosystem__Share WHERE RowCause = 'Manual'];
        //System.assertEquals(1, ecoShares.size());

        delete acc;
        ecoShares = [SELECT Id FROM Ecosystem__Share WHERE RowCause = 'Manual'];
    }
}