force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>CIF Allocated</fullName>
            </value>
            <value>
                <fullName>Need Approval Again</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Potential</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Rejected by GoldTier</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Submitted for Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CMN_Account_Contact_Relationship_Detail__c/CMN_Account_Contact_Relationship_Detail__c.object-meta.xml
<CustomObject>
    <label>CMN Account Contact Relationship Detail</label>
    <nameField>
        <displayFormat>ACR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CMN Account Contact Relationship Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CMN_Account_Contact_Relationship_Detail__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CMN Account Contact Relationship Details</relationshipLabel>
    <relationshipName>CMN_Account_Contact_Relationship_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CMN_Account_Contact_Relationship_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CMN Account Contact Relationship Details</relationshipLabel>
    <relationshipName>CMN_Account_Contact_Relationship_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CMN_Account_Contact_Relationship_Detail__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACCOUNTING OFFICER</fullName>
            </value>
            <value>
                <fullName>ADMINISTRATOR</fullName>
            </value>
            <value>
                <fullName>AGENT</fullName>
            </value>
            <value>
                <fullName>AUDITOR GENERAL</fullName>
            </value>
            <value>
                <fullName>BENEFICIAL OWNER</fullName>
                <label>Beneficial Owner</label>
            </value>
            <value>
                <fullName>BENEFICIARY</fullName>
            </value>
            <value>
                <fullName>BOARD MEMBER</fullName>
            </value>
            <value>
                <fullName>BUSINESS CONTROLLER</fullName>
            </value>
            <value>
                <fullName>BUSINESS REPRESENTATIVE</fullName>
            </value>
            <value>
                <fullName>BUSINESS RESCUE PRACTITIONER</fullName>
            </value>
            <value>
                <fullName>Business User</fullName>
            </value>
            <value>
                <fullName>CHAIRMAN</fullName>
            </value>
            <value>
                <fullName>CHAIRPERSON</fullName>
            </value>
            <value>
                <fullName>CHAIRPERSON OF THE COUNCIL</fullName>
            </value>
            <value>
                <fullName>CHANCELLOR</fullName>
            </value>
            <value>
                <fullName>CHIEF EXECUTIVE OFFICER</fullName>
            </value>
            <value>
                <fullName>CHIEF FINANCIAL OFFICER</fullName>
            </value>
            <value>
                <fullName>CHIEF OPERATIONS</fullName>
            </value>
            <value>
                <fullName>COMPANY DIRECTOR</fullName>
            </value>
            <value>
                <fullName>COMPANY SECRETARY</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
                <isActive>false</isActive>
                <label>Contact</label>
            </value>
            <value>
                <fullName>CONTACT PERSON</fullName>
            </value>
            <value>
                <fullName>CONTROLLING ENTITY</fullName>
            </value>
            <value>
                <fullName>CO-PARTICIPANT</fullName>
            </value>
            <value>
                <fullName>CorpRep</fullName>
                <isActive>false</isActive>
                <label>CorpRep</label>
            </value>
            <value>
                <fullName>COUNCILLOR</fullName>
            </value>
            <value>
                <fullName>CURATOR</fullName>
            </value>
            <value>
                <fullName>DEBT COUNSELLOR</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>DEPUTY CHAIRPERSON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SEL_CMN_AccountContactRelationshipDetail.cls
/**
 * @description Selector class for CMN_Account_Contact_Relationship_Detail__c SObject
 * @author Maham Hassan
 * @since 05-04-2022 
 */
public with sharing class SEL_CMN_AccountContactRelationshipDetail extends fflib_SObjectSelector {
    
    /**
     * @description Creates a new instance of the selector via the application class. This is here to allow unit tests to override
	 * and inject a mock instead of this class or to switch out this class for a new version.
     *
     * @return SEL_CMN_AccountContactRelationshipDetail
     */
    public static SEL_CMN_AccountContactRelationshipDetail newInstance() {
        return (SEL_CMN_AccountContactRelationshipDetail) ORG_Application.selector.newInstance(CMN_Account_Contact_Relationship_Detail__c.SObjectType);
    }

    /**
     * @description Returns the SObject type for the selector. This is used to retrieve the sObject name when building the SOQL
     * queries.
     *
     * @return SObjectType
     */
    public SObjectType getSObjectType() {
        return CMN_Account_Contact_Relationship_Detail__c.SObjectType;
    }

    /**
     * @description Returns list of User fields
     *
     * @return list of SObjectField
     */
    public List<SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            CMN_Account_Contact_Relationship_Detail__c.Contact__c,
            CMN_Account_Contact_Relationship_Detail__c.Client__c,
            CMN_Account_Contact_Relationship_Detail__c.Role__c,
            CMN_Account_Contact_Relationship_Detail__c.Status__c,
            CMN_Account_Contact_Relationship_Detail__c.Valid_From__c,
            CMN_Account_Contact_Relationship_Detail__c.Valid_To__c
        };
    }

    /**
     * @description Selects Accounts Contact by Ids
     *
     * @param conAccIds list of Contact Account's Ids 
     *
     * @return list of CMN_Account_Contact_Relationship_Detail__c
     */
    public List<CMN_Account_Contact_Relationship_Detail__c> selectByIds(Set<Id> conAccIds) {
        return Database.query(
                newQueryFactory(false, false, true)
                        .selectField('Contact__r.Name')
                        .setCondition('Id in :conAccIds')
                        .toSOQL()
        );
    }

    /**
     * @description Selects custom Accounts Contact Relationship linked to the accountIds
     *
     * @param accountIds Set of Account Ids 
     *
     * @return list of CMN_Account_Contact_Relationship_Detail__c
     */
    public List<CMN_Account_Contact_Relationship_Detail__c> selectByAccountIds(Set<Id> accountIds) {
        return Database.query(
                newQueryFactory(false, false, true)
                    .selectField('Contact__r.Name')
                    .setCondition('Client__c In :accountIds')
                    .toSOQL()
        );
    }
    /**
     * @description Selects active custom Accounts Contact Relationship linked to the accountIds
     *
     * @param accountIds Set of Account Ids 
     *
     * @return list of CMN_Account_Contact_Relationship_Detail__c
     */
    public List<CMN_Account_Contact_Relationship_Detail__c> selectActiveByAccountIds(Set<Id> accountIds) {
        String statusActive = DMN_CMN_AccountContactRelationshipDetail.ACTIVE_STATUS;
        return Database.query(
                newQueryFactory(false, false, true)
                    .selectField('Contact__r.Name')
                    .setCondition('Client__c In :accountIds AND Status__c=:statusActive')
                    .toSOQL()
        );
    }
    
}