force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>CIF Allocated</fullName>
            </value>
            <value>
                <fullName>Need Approval Again</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Potential</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Rejected by GoldTier</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Submitted for Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/Client_Data_Change__c.object-meta.xml
<CustomObject>
    <description>A new object to keep a track of the Client Information being changed on the Client record. EN-0676</description>
    <label>Client Data Change</label>
    <nameField>
        <label>Client Data Change Record Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Data Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Data_Change__c/fields/Current_Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Current_Client_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the value of the current client coordinator of the client. EN-0676</description>
    <label>Current Client Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Coordinator_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/New_Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>New_Client_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New Client Coordinator EN-0676</description>
    <label>New Client Coordinator</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active users and users within the following User Divisions: Corporate Banking, Global Markets, Investment Banking, Transactional Products and Services, General Management, Real Estate can be searched.</errorMessage>
        <filterItems>
            <field>User.User_Division__c</field>
            <operation>equals</operation>
            <value>Client Coverage, General Management, Global Markets, Investment Banking, Real Estate, Transactional Products and Services</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Coordinator_Change_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/New_Client_Coordinator_Role__c.field-meta.xml
<CustomField>
    <fullName>New_Client_Coordinator_Role__c</fullName>
    <description>Only the core team roles should be available for assigning it to the new client coordinator. EN-0676</description>
    <label>New Client Coordinator Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Client Analyst</fullName>
            </value>
            <value>
                <fullName>Credit Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Consultant</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>GM Champion</fullName>
            </value>
            <value>
                <fullName>GM Client Manager</fullName>
            </value>
            <value>
                <fullName>GM Execution Manager</fullName>
            </value>
            <value>
                <fullName>IB Champion</fullName>
            </value>
            <value>
                <fullName>Investor Services Manager</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal Lead</fullName>
            </value>
            <value>
                <fullName>Manager Client Coverage</fullName>
            </value>
            <value>
                <fullName>Portfolio Specialist</fullName>
            </value>
            <value>
                <fullName>Product Specialist</fullName>
            </value>
            <value>
                <fullName>Sales/Cell Head</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sector/Client Coverage Head</fullName>
            </value>
            <value>
                <fullName>Service Advisor</fullName>
            </value>
            <value>
                <fullName>Service Advisory Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Structurer</fullName>
            </value>
            <value>
                <fullName>TPS Champion</fullName>
            </value>
            <value>
                <fullName>Trade Finance Manager</fullName>
            </value>
            <value>
                <fullName>Trader</fullName>
            </value>
            <value>
                <fullName>Trade Service Advisory Manager</fullName>
            </value>
            <value>
                <fullName>Transaction Solutions Associate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status keeps the track of the record for different approval steps. EN-0676</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved – Awaiting Execution</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Data Update Completed</fullName>
            </value>
            <value>
                <fullName>Data Update Not Completed</fullName>
            </value>
            <value>
                <fullName>Approval Step Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StdBank_Cls_ClientDataChange_Test.cls
@isTest(SeeAllData = False)
private class StdBank_Cls_ClientDataChange_Test {

    @isTest
    static void testPage() {
        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();

        User userAdmin = (User) new BLD_USER(uow).useSysAdmin().division(DMN_User.GM_DIVISION).getRecord();
        User userStandard = (User) new BLD_USER(uow).useCib().division(DMN_User.GM_DIVISION).getRecord();
        System.runAs(new User(Id = UserInfo.getUserId())){
            uow.commitWork();
        }

        List<Account> accounts = new List<Account> {(Account) new BLD_Account().useChild().getRecord()};
        insert accounts;

        Client_Data_Change__c clientDataChange = new Client_Data_Change__c();

        clientDataChange.Current_Client_Coordinator__c = userAdmin.Id;
        clientDataChange.New_Client_Coordinator__c = userStandard.Id;
        clientDataChange.New_Client_Coordinator_Role__c = 'Analyst';
        clientDataChange.Status__c = 'New';

        System.runAs(new User(Id = UserInfo.getUserId())){
            insert clientDataChange;
        }

        PageReference pgRef = Page.StdBank_Cls_ClientDataChange;

        Test.setCurrentPage(pgRef);

        ApexPages.currentPage().getParameters().put('ClientId', accounts[0].id);
        ApexPages.currentPage().getParameters().put('ClientOwner', accounts[0].id);

        Test.startTest();

        System.runAs(userAdmin) {
            try {
                ApexPages.StandardController standardController = new ApexPages.StandardController(clientDataChange);
                StdBank_Cls_ClientDataChange  controllerInstance = new StdBank_Cls_ClientDataChange(standardController);
                controllerInstance.cancelRequest();
            }
            catch (Exception ex) {
                System.assert(false, ex.getMessage());
            }
        }
        Test.stopTest();
    }

    @isTest
    static void testAccessClassic() {
        Client_Data_Change__c clientDataChange = new Client_Data_Change__c();
        // No reason to insert as we need instance and insert is causing validation to trigger
        //insert clientDataChange;

        PageReference pgRef = Page.StdBank_Cls_ClientDataChange;

        Test.setCurrentPage(pgRef);

        Test.startTest();

        ApexPages.StandardController standardController = new ApexPages.StandardController(clientDataChange);
        StdBank_Cls_ClientDataChange  controller = new StdBank_Cls_ClientDataChange(standardController);

        System.assertEquals(false, controller.getIsLightning());
        System.assertEquals(true, controller.getIsClassic());

        Test.stopTest();
    }

    @isTest
    static void testAccessLightning() {
        Client_Data_Change__c clientDataChange = new Client_Data_Change__c();
        // No reason to insert as we need instance and insert is causing validation to trigger
        //insert clientDataChange;

        PageReference pgRef = Page.StdBank_Cls_ClientDataChange;

        Test.setCurrentPage(pgRef);

        ApexPages.currentPage().getParameters().put('isdtp', 'p1');

        Test.startTest();

        ApexPages.StandardController standardController = new ApexPages.StandardController(clientDataChange);
        StdBank_Cls_ClientDataChange  controller = new StdBank_Cls_ClientDataChange(standardController);

        System.assertEquals(true, controller.getIsLightning());
        System.assertEquals(false, controller.getIsClassic());

        Test.stopTest();
    }
}