force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>CIF Allocated</fullName>
            </value>
            <value>
                <fullName>Need Approval Again</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Potential</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Rejected by GoldTier</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Submitted for Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CMN_Account_Contact_Relationship_Detail__c/CMN_Account_Contact_Relationship_Detail__c.object-meta.xml
<CustomObject>
    <label>CMN Account Contact Relationship Detail</label>
    <nameField>
        <displayFormat>ACR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CMN Account Contact Relationship Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CMN_Account_Contact_Relationship_Detail__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CMN Account Contact Relationship Details</relationshipLabel>
    <relationshipName>CMN_Account_Contact_Relationship_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CMN_Account_Contact_Relationship_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CMN Account Contact Relationship Details</relationshipLabel>
    <relationshipName>CMN_Account_Contact_Relationship_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CMN_Account_Contact_Relationship_Detail__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACCOUNTING OFFICER</fullName>
            </value>
            <value>
                <fullName>ADMINISTRATOR</fullName>
            </value>
            <value>
                <fullName>AGENT</fullName>
            </value>
            <value>
                <fullName>AUDITOR GENERAL</fullName>
            </value>
            <value>
                <fullName>BENEFICIAL OWNER</fullName>
                <label>Beneficial Owner</label>
            </value>
            <value>
                <fullName>BENEFICIARY</fullName>
            </value>
            <value>
                <fullName>BOARD MEMBER</fullName>
            </value>
            <value>
                <fullName>BUSINESS CONTROLLER</fullName>
            </value>
            <value>
                <fullName>BUSINESS REPRESENTATIVE</fullName>
            </value>
            <value>
                <fullName>BUSINESS RESCUE PRACTITIONER</fullName>
            </value>
            <value>
                <fullName>Business User</fullName>
            </value>
            <value>
                <fullName>CHAIRMAN</fullName>
            </value>
            <value>
                <fullName>CHAIRPERSON</fullName>
            </value>
            <value>
                <fullName>CHAIRPERSON OF THE COUNCIL</fullName>
            </value>
            <value>
                <fullName>CHANCELLOR</fullName>
            </value>
            <value>
                <fullName>CHIEF EXECUTIVE OFFICER</fullName>
            </value>
            <value>
                <fullName>CHIEF FINANCIAL OFFICER</fullName>
            </value>
            <value>
                <fullName>CHIEF OPERATIONS</fullName>
            </value>
            <value>
                <fullName>COMPANY DIRECTOR</fullName>
            </value>
            <value>
                <fullName>COMPANY SECRETARY</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
                <isActive>false</isActive>
                <label>Contact</label>
            </value>
            <value>
                <fullName>CONTACT PERSON</fullName>
            </value>
            <value>
                <fullName>CONTROLLING ENTITY</fullName>
            </value>
            <value>
                <fullName>CO-PARTICIPANT</fullName>
            </value>
            <value>
                <fullName>CorpRep</fullName>
                <isActive>false</isActive>
                <label>CorpRep</label>
            </value>
            <value>
                <fullName>COUNCILLOR</fullName>
            </value>
            <value>
                <fullName>CURATOR</fullName>
            </value>
            <value>
                <fullName>DEBT COUNSELLOR</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>DEPUTY CHAIRPERSON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RemoveMultiSelectValues.cls
/**
 * @description Class for removal of expired roles on the AccountContactRelation object
 * @author		Sipho Mbulawa
 * @date		March 2022
 */
global class RemoveMultiSelectValues implements Database.Batchable<sObject>{
    private static final String ERROR_MSG = 'An error has ocured,please contact system administrator.';
    public class RemoveMultiSelectValuesException extends Exception{}
    public String queryString;
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        Date currentDate = Date.today();
        String activeStatus = DMN_CMN_AccountContactRelationshipDetail.ACTIVE_STATUS;
        this.queryString = 'SELECT Id,Status__c,Client__c,Contact__c,Role__c FROM CMN_Account_Contact_Relationship_Detail__c WHERE Valid_To__c<:currentDate AND Status__c=:activeStatus';
        return Database.getQueryLocator(this.queryString);
    }
    
    global void execute(Database.BatchableContext BC, List<CMN_Account_Contact_Relationship_Detail__c> cmnAccountContactRelation){
        
        for(CMN_Account_Contact_Relationship_Detail__c acr:cmnAccountContactRelation){
            acr.Status__c = DMN_CMN_AccountContactRelationshipDetail.EXPIRED_STATUS;
        }
        update cmnAccountContactRelation;
        
    }
    
    global void finish(Database.BatchableContext BC){}
   /**
    * @description This is to remove a pick list value from the Account Contact Relationship role field
    * 
    */    
    @InvocableMethod(label='Remove MultiSelect Value' description='This is to remove a pick list value from the Account Contact Relationship role field')
    public static void callRemoveMultiSelectValuesBatch(){

        RemoveMultiSelectValues bt = new RemoveMultiSelectValues();
        Database.executeBatch (bt,5000);
    }
}