force-app/main/default/objects/PP_PartnerApplication__c/PP_PartnerApplication__c.object-meta.xml
<CustomObject>
    <description>SFP-11649 -  Represents an Application of a Partner.</description>
    <label>Partner Application</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PP_PartnerApplication__c/fields/PP_ApplicationStatus__c.field-meta.xml
<CustomField>
    <fullName>PP_ApplicationStatus__c</fullName>
    <description>SFP-11649 - Represents the partners application status.</description>
    <inlineHelpText>Represents the partners onboarding application status.</inlineHelpText>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PP_PartnerApplication__c/fields/PP_Capabilities__c.field-meta.xml
<CustomField>
    <fullName>PP_Capabilities__c</fullName>
    <description>SFP-11649 - Represents what business or technology capabilities a partner has.</description>
    <inlineHelpText>Represents what business or technology capabilities a partner has.</inlineHelpText>
    <label>Capabilities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>APIs</fullName>
            </value>
            <value>
                <fullName>Architecture</fullName>
            </value>
            <value>
                <fullName>Artificial Intelligence</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Big Data</fullName>
            </value>
            <value>
                <fullName>BlockChain</fullName>
            </value>
            <value>
                <fullName>Business Intelligence</fullName>
            </value>
            <value>
                <fullName>Cloud as a Service (CaaS)</fullName>
            </value>
            <value>
                <fullName>Cloud Computing</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Cybersecurity</fullName>
            </value>
            <value>
                <fullName>Data Analytics</fullName>
            </value>
            <value>
                <fullName>Data Modelling</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
            <value>
                <fullName>Digital Marketing</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
            <value>
                <fullName>Financial Modelling</fullName>
            </value>
            <value>
                <fullName>FOREX</fullName>
            </value>
            <value>
                <fullName>Gaming</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Information Security</fullName>
            </value>
            <value>
                <fullName>Infrastructure-as-a-Service (IaaS)</fullName>
            </value>
            <value>
                <fullName>Internet of Things</fullName>
            </value>
            <value>
                <fullName>KYC</fullName>
            </value>
            <value>
                <fullName>Leadership</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Management Consulting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PP_PartnerApplication__c/fields/PP_EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>PP_EmailAddress__c</fullName>
    <description>SFP-11649 - Email address provided during registration process.</description>
    <inlineHelpText>Email address provided during registration process.</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PP_PartnerApplication__c/fields/PP_FirstName__c.field-meta.xml
<CustomField>
    <fullName>PP_FirstName__c</fullName>
    <description>SFP-11649 - First name provided during registration process.</description>
    <inlineHelpText>First name provided during registration process.</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PP_PartnerApplication__c/fields/PP_Industry__c.field-meta.xml
<CustomField>
    <fullName>PP_Industry__c</fullName>
    <description>SFP-11649 -Industry that the partner operates in.</description>
    <inlineHelpText>Industry that the partner operates in.</inlineHelpText>
    <label>Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PP_PartnerApplication__c/fields/PP_LastName__c.field-meta.xml
<CustomField>
    <fullName>PP_LastName__c</fullName>
    <description>SFP-11649- Last name provided during registration process.</description>
    <inlineHelpText>Last name provided during registration process.</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PP_PartnerApplication__c/fields/PP_LinkedInProfile__c.field-meta.xml
<CustomField>
    <fullName>PP_LinkedInProfile__c</fullName>
    <description>SFP-11649 - LinkedIn profile URL for the partner.</description>
    <inlineHelpText>LinkedIn profile URL for the partner.</inlineHelpText>
    <label>LinkedIn Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PP_PartnerApplication__c/fields/PP_OperatingCountry__c.field-meta.xml
<CustomField>
    <fullName>PP_OperatingCountry__c</fullName>
    <description>SFP-11649 - Countries that the partner operates in.</description>
    <inlineHelpText>Countries that the partner operates in.</inlineHelpText>
    <label>Operating Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PP_PartnerApplication__c/fields/PP_PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PP_PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SFP-11649 - The contact that represents the partners main contact person at the time of registration. This contact is also enabled as community user.</description>
    <inlineHelpText>The contact that represents the partners main contact person at the time of registration. This contact is also enabled as community user.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Partner Applications</relationshipLabel>
    <relationshipName>PartnerApplications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PP_PartnerApplication__c/fields/PP_Website__c.field-meta.xml
<CustomField>
    <fullName>PP_Website__c</fullName>
    <description>SFP-11649 - Website URL provided during registration.</description>
    <inlineHelpText>Website URL provided during registration.</inlineHelpText>
    <label>Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SEL_PartnerApplication.cls
/**
* Selector class for PP_PartnerApplication__c SObject
* User Story : SFP-4874
*
* @author Syed Ovais Ali (syed.ali@standardbank.co.za)
* @date July 2021
*/
public inherited sharing class SEL_PartnerApplication extends fflib_SObjectSelector {
    /**
     * Creates a new instance of the selector via the application class. This is here to allow unit tests to override
	 * and inject a mock instead of this class or to switch out this class for a new version.
     * @return SEL_PartnerApplication class instance
     */ 
	public static SEL_PartnerApplication newInstance() {
        return (SEL_PartnerApplication) ORG_Application.selector.newInstance(PP_PartnerApplication__c.SObjectType);
    }
    
     /**
     * Returns the SObject fields on this sObject
     * @return PP_PartnerApplication__c fields list
     */
	public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                PP_PartnerApplication__c.Id,
                PP_PartnerApplication__c.Name,
                PP_PartnerApplication__c.PP_FirstName__c,
                PP_PartnerApplication__c.PP_LastName__c,
                PP_PartnerApplication__c.PP_Industry__c,
                PP_PartnerApplication__c.PP_OperatingCountry__c,
                PP_PartnerApplication__c.OwnerId   
        };
    }
    
    
    /**
     * Returns the SObject type for the selector. This is used to retrieve the sObject name when building the SOQL
     * queries.
     * @return PP_PartnerApplication__c object type
     */
    public Schema.SObjectType getSObjectType() {
        return PP_PartnerApplication__c.SObjectType;
    }
    
     /**
     * Select PP_PartnerApplication__c filtered by Primary Contact ID
     * @param idSet set of Ids of Contact
     *
     * @return list of PP_PartnerApplication__c
     */
    public List<PP_PartnerApplication__c> selectByPrimaryContactId(Set<Id> idSet) {
        return (List<PP_PartnerApplication__c>) Database.query(
                newQueryFactory()
            	.selectField('PP_Website__c')
				.selectField('PP_LinkedInProfile__c')
				.selectField('PP_Capabilities__c')
                .setCondition('PP_PrimaryContact__c IN: idSet')
                .toSOQL()
        );
    }
    
        
    /**
    * Select PP_PartnerApplication__c filtered by IDs
    * @param idSet set of Ids of PP_PartnerApplication__c
    *
    * @return list of PP_PartnerApplication__c
    */
    
    public List<PP_PartnerApplication__c> selectById(Set<Id> idSet) {
        return (List<PP_PartnerApplication__c>) Database.query(
                newQueryFactory()
            	.selectField('PP_EmailAddress__c')
				.selectField('PP_PrimaryContact__c')
				.selectField('PP_ApplicationStatus__c')
                .setCondition('Id IN: idSet')
                .toSOQL()
        );
    }
    
   
}