force-app/main/default/objects/Financial_Account_Permission__c/Financial_Account_Permission__c.object-meta.xml
<CustomObject>
    <description>CDCS-70 Junction object representing that the specific user/contact has the access to a specific type of service on a specific financial account.</description>
    <label>Financial Account Permission</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Financial Account Permission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account_Permission__c/fields/Permission__c.field-meta.xml
<CustomField>
    <fullName>Permission__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Permissions__c</referenceTo>
    <relationshipLabel>Financial Account Permissions</relationshipLabel>
    <relationshipName>Financial_Account_Permissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Permissions__c/Permissions__c.object-meta.xml
<CustomObject>
    <description>CDCS-70 This object represents the type of service for which permission is granted. Object has one record per service type. Three types of permissions are planned: payment tracking, viewing account balance and generating statement.</description>
    <label>Permissions</label>
    <nameField>
        <label>Service Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BLD_Permissions.cls
/**
 * Builder class for Permissions__c SObject
 *
 * @author      Konrad Bruszewski (konrad.bruszewski@standardbank.co.za)
 * @date        January 2020
 */
@IsTest
public with sharing class BLD_Permissions extends ABS_ObjectBuilderBase {

    public BLD_Permissions(){
        this(getNewUnitOfWork());
    }

    public BLD_Permissions(fflib_SObjectUnitOfWork workUnit) {
        super(Permissions__c.sObjectType, workUnit);
    }

    public BLD_Permissions(Permissions__c sObj, fflib_SObjectUnitOfWork workUnit) {
        super(sObj, workUnit);
    }

    public BLD_Permissions addFinancialAccountPermission(BLD_FinancialAccountPermission financialAccountPermissionBld) {
        return(BLD_Permissions) addChild(Financial_Account_Permission__c.Permission__c, financialAccountPermissionBld);
    }

    public BLD_Permissions name(String name){
        return (BLD_Permissions) setField(Permissions__c.Name, name);
    }
}