force-app/main/default/objects/CMN_WebserviceSetting__mdt/CMN_WebserviceSetting__mdt.object-meta.xml
<CustomObject>
    <description>Use this to register various web service handlers and their settings such as endpoint, named credentials etc.</description>
    <label>Webservice Setting</label>
    <pluralLabel>Webservice Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/AOB_DefaultChannel__c.field-meta.xml
<CustomField>
    <fullName>AOB_DefaultChannel__c</fullName>
    <defaultValue>&quot;SF_SBG&quot;</defaultValue>
    <label>DefaultChannel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/CMN_AddStackTraceToExceptions__c.field-meta.xml
<CustomField>
    <fullName>CMN_AddStackTraceToExceptions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, then when an error is encountered, the system will add the stack track to the errors lists on Queue Item and in responses.</description>
    <label>Add Stack Trace to Exceptions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/CMN_ApiKey__c.field-meta.xml
<CustomField>
    <fullName>CMN_ApiKey__c</fullName>
    <description>Can be used to define additional information required when doing API all</description>
    <label>ApiKey</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/CMN_BackoffPeriod__c.field-meta.xml
<CustomField>
    <fullName>CMN_BackoffPeriod__c</fullName>
    <label>Backoff Period (sec)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/CMN_Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>CMN_Client_Secret__c</fullName>
    <description>OAuth Client Secret</description>
    <label>Client Secret</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/CMN_ClientID__c.field-meta.xml
<CustomField>
    <fullName>CMN_ClientID__c</fullName>
    <description>OAuth Client ID</description>
    <label>ClientID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/CMN_CompanyID__c.field-meta.xml
<CustomField>
    <fullName>CMN_CompanyID__c</fullName>
    <label>CompanyID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/CMN_MaxRetriesNo__c.field-meta.xml
<CustomField>
    <fullName>CMN_MaxRetriesNo__c</fullName>
    <label>Max Retries No.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/CMN_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>CMN_NamedCredential__c</fullName>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/CMN_Password__c.field-meta.xml
<CustomField>
    <fullName>CMN_Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/CMN_Path__c.field-meta.xml
<CustomField>
    <fullName>CMN_Path__c</fullName>
    <description>Relative path for a service call; prefixed by the URL provided either by a Named Credential or the Endpoint URL field</description>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CMN_WebserviceSetting__mdt/fields/CMN_Username__c.field-meta.xml
<CustomField>
    <fullName>CMN_Username__c</fullName>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CMN_DAL_WebserviceSetting.cls
/**
 * @description Provides Query methods related to CMN_WebserviceSetting__mdt Custom Metadata object
 *
 * @author Accenture
 *
 * @date 2019
 */
public inherited sharing class CMN_DAL_WebserviceSetting
{
	private static final String TEST_SETTING = 'CMN_API_RestOutboundExample';

	/**
	 * @description This method is use to get the list of metadata
	 *
	 * @param serviceName The web service for which we want to retrieve metadata
	 *
	 * @return relevant service settings
	 */
	public static CMN_WebserviceSetting__mdt getMetadata(String serviceName)
	{
		List<CMN_WebserviceSetting__mdt> settings;

		if(String.isNotBlank(serviceName))
		{
			settings =
			[
					SELECT
							CMN_AddStackTraceToExceptions__c,
							CMN_ApiKey__c,
							CMN_BackoffPeriod__c,
							CMN_Client_Secret__c,
							CMN_ClientID__c,
                			AOB_DefaultChannel__c, 
							CMN_CompanyID__c,
							CMN_MaxRetriesNo__c,
							CMN_NamedCredential__c,
							CMN_Password__c,
							CMN_Path__c,
							CMN_Username__c
					FROM
							CMN_WebserviceSetting__mdt
					WHERE DeveloperName = :serviceName
			];
		}

		CMN_WebserviceSetting__mdt setting = settings.isEmpty() ? null : settings[0];

		setting = setting == null && Test.isRunningTest() ? getMetadata(TEST_SETTING) : setting;

		return setting;
	}
}