force-app/main/default/objects/Client_Data_Change__c/Client_Data_Change__c.object-meta.xml
<CustomObject>
    <description>A new object to keep a track of the Client Information being changed on the Client record. EN-0676</description>
    <label>Client Data Change</label>
    <nameField>
        <label>Client Data Change Record Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Data Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Data_Change__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be a master for all the records which are getting created. EN-0676</description>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Data Changes</relationshipLabel>
    <relationshipName>Client_Coordinator_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/Current_CCBM__c.field-meta.xml
<CustomField>
    <fullName>Current_CCBM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current CCBM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Data_Changes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/Current_Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Current_Client_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the value of the current client coordinator of the client. EN-0676</description>
    <label>Current Client Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Coordinator_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/Current_Client_Coordinator_Role__c.field-meta.xml
<CustomField>
    <fullName>Current_Client_Coordinator_Role__c</fullName>
    <description>The roles are same as that on the client team roles. EN-0676</description>
    <label>Current Client Coordinator Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Client Analyst</fullName>
            </value>
            <value>
                <fullName>Credit Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Consultant</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>GM Champion</fullName>
            </value>
            <value>
                <fullName>GM Client Manager</fullName>
            </value>
            <value>
                <fullName>GM Execution Manager</fullName>
            </value>
            <value>
                <fullName>IB Champion</fullName>
            </value>
            <value>
                <fullName>In Country RM</fullName>
            </value>
            <value>
                <fullName>Investor Services Manager</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal Lead</fullName>
            </value>
            <value>
                <fullName>Manager Client Coverage</fullName>
            </value>
            <value>
                <fullName>Portfolio Specialist</fullName>
            </value>
            <value>
                <fullName>Product Specialist</fullName>
            </value>
            <value>
                <fullName>Sales/Cell Head</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sector/Client Coverage Head</fullName>
            </value>
            <value>
                <fullName>Service Advisor</fullName>
            </value>
            <value>
                <fullName>Service Advisory Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Structurer</fullName>
            </value>
            <value>
                <fullName>TPS Champion</fullName>
            </value>
            <value>
                <fullName>Trade Finance Manager</fullName>
            </value>
            <value>
                <fullName>Trader</fullName>
            </value>
            <value>
                <fullName>Trade Service Advisory Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/Keep_Current_CC__c.field-meta.xml
<CustomField>
    <fullName>Keep_Current_CC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Keep Current CC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/New_Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>New_Client_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New Client Coordinator EN-0676</description>
    <label>New Client Coordinator</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active users and users within the following User Divisions: Corporate Banking, Global Markets, Investment Banking, Transactional Products and Services, General Management, Real Estate can be searched.</errorMessage>
        <filterItems>
            <field>User.User_Division__c</field>
            <operation>equals</operation>
            <value>Client Coverage, General Management, Global Markets, Investment Banking, Real Estate, Transactional Products and Services</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Coordinator_Change_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/Custom_Client_Team__c.object-meta.xml
<CustomObject>
    <label>Client Team</label>
    <nameField>
        <displayFormat>Client-{0000}</displayFormat>
        <label>Client Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Client_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Client_Coordinator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to specify the Client Coordinator in the Service Team</description>
    <inlineHelpText>Is this Client Team Member the Client Coordinator?</inlineHelpText>
    <label>CC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Coordinator_BM__c.field-meta.xml
<CustomField>
    <fullName>Client_Coordinator_BM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enh#096 - Indicates the client coordinator business manager.</description>
    <label>CC BM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Role__c.field-meta.xml
<CustomField>
    <fullName>Client_Role__c</fullName>
    <label>Team Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Account Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Business Development Manager</fullName>
            </value>
            <value>
                <fullName>BCC CSU Agent</fullName>
            </value>
            <value>
                <fullName>BCC CSU Manager</fullName>
            </value>
            <value>
                <fullName>BCC Ecosystem Manager</fullName>
            </value>
            <value>
                <fullName>BCC Head Trade Sales</fullName>
            </value>
            <value>
                <fullName>BCC Portfolio Manager</fullName>
            </value>
            <value>
                <fullName>BCC Product Specialist</fullName>
            </value>
            <value>
                <fullName>BCC Relationship Manager</fullName>
            </value>
            <value>
                <fullName>BCC Service Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Finance Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Client Analyst</fullName>
            </value>
            <value>
                <fullName>Credit Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Consultant</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Executive Stakeholder</fullName>
            </value>
            <value>
                <fullName>Global Transaction Banker</fullName>
            </value>
            <value>
                <fullName>GM Champion</fullName>
            </value>
            <value>
                <fullName>GM Client Manager</fullName>
            </value>
            <value>
                <fullName>GM Execution Manager</fullName>
            </value>
            <value>
                <fullName>GM Regional Head</fullName>
            </value>
            <value>
                <fullName>IB Champion</fullName>
            </value>
            <value>
                <fullName>Investor Services Manager</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/TeamRoleSortValue__c.field-meta.xml
<CustomField>
    <fullName>TeamRoleSortValue__c</fullName>
    <description>CST Phase (3)  - Core team role ranking values .</description>
    <label>Sort</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <description>Team member object connects either internal staff or contractors to a project assignment.  If you further customize the application, you can prevent &quot;stray time reporting&quot; using apex coding so that team members cannot report time outside of the assigned date range.  This becomes important if your organization reports heavily on project costing or SOP-98 capital/expense.  in addition, Force.com Visualforce or Adobe Flex code can be leveraged to help with the matching of resources to projects/work requests.  Please contact professional services for more information on consulting rates or the Salesforce.com Developer network (www.salesforce.com/developer).</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is a lookup to the user and used to assign internal staff to a project team member.</inlineHelpText>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N80000002lXWPEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClientDataChangeCreationController.cls
/**
 * Created by akepczynski on 12.04.2018.
 */

public without sharing class ClientDataChangeCreationController {
    
    private static String
        INPUT           = 'INPUT',
        HEADER          = 'The CC for this entity will be changed from {0} to {1} with {2} role.<br/>',
        CURRENT_ROLE    = '&nbspNote that {1} will replace {3} in the client team.<br/>',
        APPROVERS       = '&nbsp&nbsp- Approval request will be sent to ' + INPUT +  '.<br/>',
        FOOTER          = '&nbsp&nbsp- If you would like to keep the current CC in the client team, please select Keep.<br/>'
                        + '&nbsp&nbsp- If you want to remove the current CC from the client team, please select Remove.';
    
    @AuraEnabled
    public static Map<String, object> getData(Id recordId){
        Map<String, object> field2Values;
        if(recordId.getSobjectType() == Client_Data_Change__c.SObjectType){
            Client_Data_Change__c cdc = [SELECT Id FROM Client_Data_Change__c WHERE Id =: recordId ];
            field2Values = cdc.getPopulatedFieldsAsMap();
        }
        
        if(recordId.getSobjectType() == Account.SObjectType){
            Client_Data_Change__c cdc = new Client_Data_Change__c(Client_Name__c = recordId);
            cdc.Client_Name__c = recordId;
            
            Custom_Client_Team__c[] ccts = [SELECT Team_Member__c, Team_Member__r.Id, Client_Role__c, Team_Member__r.Name,
                Account__r.Id, Account__r.Name, Account__c, Client_Coordinator__c, Client_Coordinator_BM__c 
                                            FROM Custom_Client_Team__c
                                            WHERE Account__c =: recordId
                                                AND (Client_Coordinator__c = true
                                                        OR Client_Coordinator_BM__c = true)
                                            ORDER BY TeamRoleSortValue__c ASC ];
            
            if(ccts.isEmpty()){
                Account acc = [SELECT OwnerId, Owner.Name, Name FROM Account WHERE Id =: recordId];

                cdc.Current_Client_Coordinator__c = acc.OwnerId;
                cdc.Current_Client_Coordinator_Role__c = '';
                cdc.Client_Name__c = acc.Id;
            
                field2Values = getRecordMap(cdc);
                field2Values.put('Current_Client_Coordinator__r', getRecordMap(acc.Owner));
                field2Values.put('Client_Name__r', getRecordMap(acc));
                return field2Values;
            }
            
            for(Custom_Client_Team__c cct :ccts){
                if(cct.Client_Coordinator__c){
            cdc.Current_Client_Coordinator__c = cct.Team_Member__c;
            cdc.Current_Client_Coordinator_Role__c = cct.Client_Role__c;
            cdc.Client_Name__c = cct.Account__c;
    
            field2Values = getRecordMap(cdc);
            field2Values.put('Current_Client_Coordinator__r', getRecordMap(cct.Team_Member__r));
            field2Values.put('Client_Name__r', getRecordMap(cct.Account__r));
        }
                if(cct.Client_Coordinator_BM__c){
                    cdc.Current_CCBM__c = cct.Team_Member__c;
                    field2Values.put('Current_CCBM__r', getRecordMap(cct.Team_Member__r));
                    field2Values.put('Current_CCBM__c', cct.Team_Member__c);
                }
            }
        }
        return field2Values;
    }
    
    private static Map<String, Object> getRecordMap(SObject record){
        Map<String, Object> field2Data = record.getPopulatedFieldsAsMap().clone();
        field2Data.put('sobjectType', record.getSObjectType().getDescribe().getName());
        return field2Data;
    }
    
    
    @AuraEnabled
    public static UTL_Approval.ApprovalResults runApproval(Id recordId, Boolean isKeep ){
        if(isKeep != null){
            update new Client_Data_Change__c(Id = recordId, Keep_Current_CC__c = isKeep);
        }
        return UTL_Approval.runApproval(recordId, 'Update_CC');
    }
    
    @AuraEnabled
    public static String getMessage(Client_Data_Change__c cdc ){
    
        Set<String> multipleMemberPerRole = CSTManyperRegionTeamRoles__c.getAll().keySet();
        String newCCName = cdc.New_Client_Coordinator__r.Name != null ?
                                                                cdc.New_Client_Coordinator__r.Name
                                                                : UTL_User.getCachedUser(cdc.New_Client_Coordinator__c).Name;
        
        Custom_Client_Team__c[] members = [ SELECT Client_Role__c, Team_Member__r.Name
                                            FROM Custom_Client_Team__c
                                            WHERE Account__c =: cdc.Client_Name__c
                                                AND Client_Role__c =: cdc.New_Client_Coordinator_Role__c
                                                AND (( Core__c = true AND Client_Coordinator__c = false)
                                                    OR Client_Role__c NOT IN : multipleMemberPerRole )];
        
        String[] values = new String[]{cdc.Current_Client_Coordinator__r.Name, newCCName,
            cdc.New_Client_Coordinator_Role__c};
        String approvercode = '';
        
        if(UserInfo.getUserId() != cdc.Current_Client_Coordinator__c
            && cdc.Current_Client_Coordinator__c != UTL_User.getSfAdministrationUser().Id
            && UserInfo.getUserId() != cdc.Current_CCBM__c){
            approvercode = '{0}';
        }
        if(UserInfo.getUserId() != cdc.New_Client_Coordinator__c
            && cdc.New_Client_Coordinator__c !=  cdc.Current_Client_Coordinator__c){
            approvercode += String.isBlank(approvercode) ? '{1}' : ' and {1}';
        }
        Boolean isShowKeepAndRemove =  showKeepAndRemove(cdc);

        String message = String.format(HEADER, values);
        if(members.size() == 1){
            values.add(members[0].Team_Member__r.Name);
            if(isShowKeepAndRemove){
                message += String.format(CURRENT_ROLE, values);
            }

            if(members[0].Team_Member__c != UserInfo.getUserId()
                && members[0].Team_Member__c != cdc.Current_Client_Coordinator__c
                && members[0].Team_Member__c != cdc.New_Client_Coordinator__c) {
                approvercode = approvercode.contains('{0}') && approvercode.contains('{1}') ? '{3}, ' + approvercode : approvercode + ' and {3}';
            }
        }

        APPROVERS = APPROVERS.replace(INPUT, approvercode);
        if(cdc.Current_Client_Coordinator__c != UTL_User.getSfAdministrationUser().Id
            || cdc.New_Client_Coordinator__c != UserInfo.getUserId()){
        message += String.format(APPROVERS, values);
        }
        if(isShowKeepAndRemove){
            message += String.format(FOOTER, values);
        }
        return message;
    }
    
    @AuraEnabled
    public static Boolean showKeepAndRemove(Client_Data_Change__c cdc){
        Set<String> multipleMemberPerRole = CSTManyperRegionTeamRoles__c.getAll().keySet();
        
        Custom_Client_Team__c[] teammembers = [ SELECt Core__c, Client_Role__c, Client_Coordinator__c
                                                FROM Custom_Client_Team__c
                                                WHERE Account__c =: cdc.Client_Name__c
                                                AND Client_Coordinator__c = true
                                                AND (( Core__c = true AND Client_Coordinator__c = false)
                                                    OR Client_Role__c NOT IN : multipleMemberPerRole)
                                                AND Client_Role__c =: cdc.New_Client_Coordinator_Role__c];
        return teammembers.isEmpty() && String.isNotBlank(cdc.Current_Client_Coordinator_Role__c) ;
    }
    
    @AuraEnabled
    public static UTL_Approval.ApprovalResults runApproval(Boolean isKeep, Client_Data_Change__c cdc){
        UTL_Approval.ApprovalResults appRes;
        Savepoint sp =  Database.setSavepoint();
        Boolean isSuccess = true;
        try{
            if(isKeep != null){
                cdc.Keep_Current_CC__c = isKeep;
            }
            upsert cdc;
            
            if(cdc.Current_Client_Coordinator__c == UTL_User.getSfAdministrationUser().Id
                && cdc.New_Client_Coordinator__c == UserInfo.getUserId()){
                cdc.Status__c = DMN_ClientDataChange.APPROVED;
                update cdc;
                appRes = new UTL_Approval.ApprovalResults(false, '', cdc.Id);
            }
            else{
            appRes = UTL_Approval.runApproval(cdc.Id, 'Update_CC');
            isSuccess = appRes.isSuccess;
        }
        }
        catch(DmlException ex ){
            appRes = new  UTL_Approval.ApprovalResults(true, ex.getDmlMessage(0));
            isSuccess = false;
        }
        catch (Exception ex){
            appRes = new  UTL_Approval.ApprovalResults(true, ex.getMessage());
            isSuccess = false;
        }
        
        if(!isSuccess){
            Database.rollback(sp);
        }
        return appRes;
    }
}