force-app/main/default/objects/Client_Data_Change__c/Client_Data_Change__c.object-meta.xml
<CustomObject>
    <description>A new object to keep a track of the Client Information being changed on the Client record. EN-0676</description>
    <label>Client Data Change</label>
    <nameField>
        <label>Client Data Change Record Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Data Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Data_Change__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be a master for all the records which are getting created. EN-0676</description>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Data Changes</relationshipLabel>
    <relationshipName>Client_Coordinator_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/Current_CCBM__c.field-meta.xml
<CustomField>
    <fullName>Current_CCBM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current CCBM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Data_Changes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/Current_Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Current_Client_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the value of the current client coordinator of the client. EN-0676</description>
    <label>Current Client Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Coordinator_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/Current_Client_Coordinator_New_Role__c.field-meta.xml
<CustomField>
    <fullName>Current_Client_Coordinator_New_Role__c</fullName>
    <label>Current Client Coordinator New Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Client Analyst</fullName>
            </value>
            <value>
                <fullName>Credit Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
                <isActive>false</isActive>
                <label>Dealer</label>
            </value>
            <value>
                <fullName>Dedicated Service Consultant</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>GM Champion</fullName>
            </value>
            <value>
                <fullName>GM Client Manager</fullName>
            </value>
            <value>
                <fullName>GM Execution Manager</fullName>
            </value>
            <value>
                <fullName>GM Regional Head</fullName>
            </value>
            <value>
                <fullName>IB Champion</fullName>
            </value>
            <value>
                <fullName>Investor Services Manager</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal Lead</fullName>
            </value>
            <value>
                <fullName>Manager Client Coverage</fullName>
            </value>
            <value>
                <fullName>Portfolio Specialist</fullName>
            </value>
            <value>
                <fullName>Product Specialist</fullName>
            </value>
            <value>
                <fullName>Sales/Cell Head</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sector/Client Coverage Head</fullName>
            </value>
            <value>
                <fullName>Service Advisor</fullName>
            </value>
            <value>
                <fullName>Service Advisory Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Structurer</fullName>
            </value>
            <value>
                <fullName>TPS Champion</fullName>
            </value>
            <value>
                <fullName>Trade Finance Manager</fullName>
            </value>
            <value>
                <fullName>Trader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/Current_Client_Coordinator_Role__c.field-meta.xml
<CustomField>
    <fullName>Current_Client_Coordinator_Role__c</fullName>
    <description>The roles are same as that on the client team roles. EN-0676</description>
    <label>Current Client Coordinator Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Client Analyst</fullName>
            </value>
            <value>
                <fullName>Credit Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Consultant</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>GM Champion</fullName>
            </value>
            <value>
                <fullName>GM Client Manager</fullName>
            </value>
            <value>
                <fullName>GM Execution Manager</fullName>
            </value>
            <value>
                <fullName>IB Champion</fullName>
            </value>
            <value>
                <fullName>In Country RM</fullName>
            </value>
            <value>
                <fullName>Investor Services Manager</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal Lead</fullName>
            </value>
            <value>
                <fullName>Manager Client Coverage</fullName>
            </value>
            <value>
                <fullName>Portfolio Specialist</fullName>
            </value>
            <value>
                <fullName>Product Specialist</fullName>
            </value>
            <value>
                <fullName>Sales/Cell Head</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sector/Client Coverage Head</fullName>
            </value>
            <value>
                <fullName>Service Advisor</fullName>
            </value>
            <value>
                <fullName>Service Advisory Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Structurer</fullName>
            </value>
            <value>
                <fullName>TPS Champion</fullName>
            </value>
            <value>
                <fullName>Trade Finance Manager</fullName>
            </value>
            <value>
                <fullName>Trader</fullName>
            </value>
            <value>
                <fullName>Trade Service Advisory Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/Keep_Current_CC__c.field-meta.xml
<CustomField>
    <fullName>Keep_Current_CC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Keep Current CC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/New_Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>New_Client_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New Client Coordinator EN-0676</description>
    <label>New Client Coordinator</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active users and users within the following User Divisions: Corporate Banking, Global Markets, Investment Banking, Transactional Products and Services, General Management, Real Estate can be searched.</errorMessage>
        <filterItems>
            <field>User.User_Division__c</field>
            <operation>equals</operation>
            <value>Client Coverage, General Management, Global Markets, Investment Banking, Real Estate, Transactional Products and Services</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Coordinator_Change_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Data_Change__c/fields/New_Client_Coordinator_Role__c.field-meta.xml
<CustomField>
    <fullName>New_Client_Coordinator_Role__c</fullName>
    <description>Only the core team roles should be available for assigning it to the new client coordinator. EN-0676</description>
    <label>New Client Coordinator Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Client Analyst</fullName>
            </value>
            <value>
                <fullName>Credit Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Consultant</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>GM Champion</fullName>
            </value>
            <value>
                <fullName>GM Client Manager</fullName>
            </value>
            <value>
                <fullName>GM Execution Manager</fullName>
            </value>
            <value>
                <fullName>IB Champion</fullName>
            </value>
            <value>
                <fullName>Investor Services Manager</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal Lead</fullName>
            </value>
            <value>
                <fullName>Manager Client Coverage</fullName>
            </value>
            <value>
                <fullName>Portfolio Specialist</fullName>
            </value>
            <value>
                <fullName>Product Specialist</fullName>
            </value>
            <value>
                <fullName>Sales/Cell Head</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sector/Client Coverage Head</fullName>
            </value>
            <value>
                <fullName>Service Advisor</fullName>
            </value>
            <value>
                <fullName>Service Advisory Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Structurer</fullName>
            </value>
            <value>
                <fullName>TPS Champion</fullName>
            </value>
            <value>
                <fullName>Trade Finance Manager</fullName>
            </value>
            <value>
                <fullName>Trader</fullName>
            </value>
            <value>
                <fullName>Trade Service Advisory Manager</fullName>
            </value>
            <value>
                <fullName>Transaction Solutions Associate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BLD_ClientDataChange.cls
/**
 * Builder class for Client_Data_Change__c SObject
 *
 * @author Youssef Ibrahim (yibrahim@deloittece.com)
 * @date April 2020
 */
@IsTest
public without sharing class BLD_ClientDataChange extends ABS_ObjectBuilderBase {

    public BLD_ClientDataChange(fflib_SObjectUnitOfWork uow) {
        super(Client_Data_Change__c.SObjectType, uow);
    }

    public BLD_ClientDataChange client(BLD_Account clientBld) {
        return(BLD_ClientDataChange) setRelation(Client_Data_Change__c.Client_Name__c, clientBld);
    }

    public BLD_ClientDataChange currentClientCoordinator(Id userId) {
        return (BLD_ClientDataChange) setField(Client_Data_Change__c.Current_Client_Coordinator__c, userId);
    }

    public BLD_ClientDataChange currentCcbm(Id userId) {
        return (BLD_ClientDataChange) setField(Client_Data_Change__c.Current_CCBM__c, userId);
    }

    public BLD_ClientDataChange newClientCoordinatorRole(String role) {
        return (BLD_ClientDataChange) setField(Client_Data_Change__c.New_Client_Coordinator_Role__c, role);
    }

    public BLD_ClientDataChange currentClientCoordinatorRole(String role) {
        return (BLD_ClientDataChange) setField(Client_Data_Change__c.Current_Client_Coordinator_Role__c, role);
    }

    public BLD_ClientDataChange currentClientCoordinatorNewRole(String role) {
        return (BLD_ClientDataChange) setField(Client_Data_Change__c.Current_Client_Coordinator_New_Role__c, role);
    }

    public BLD_ClientDataChange newClientCoordinator(Id userId) {
        return (BLD_ClientDataChange) setField(Client_Data_Change__c.New_Client_Coordinator__c, userId);
    }

    public BLD_ClientDataChange keepCurrentCC(Boolean isKeepCurrentCC) {
        return (BLD_ClientDataChange) setField(Client_Data_Change__c.Keep_Current_CC__c, isKeepCurrentCC);
    }

    public BLD_ClientDataChange name(String name) {
        return (BLD_ClientDataChange) setField(Client_Data_Change__c.Name, name);
    }
}