force-app/main/default/objects/Campaign_Hosts__c/Campaign_Hosts__c.object-meta.xml
<CustomObject>
    <description>Case#1168 - 11/2011 - Rudolf Niehaus
Object that holds the link between host and member.</description>
    <label>Campaign Hosts</label>
    <nameField>
        <label>Campaign Hosts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Hosts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Hosts__c/fields/Campaign_Member_Host__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case#1168 - 11/2011 - Rudolf Niehaus
Look-up to &quot;Campaign member host&quot; object</description>
    <label>Campaign Member Host</label>
    <referenceTo>Campaign_Member_Host__c</referenceTo>
    <relationshipLabel>Campaign Hosts</relationshipLabel>
    <relationshipName>Campaign_Hosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Host__c/Campaign_Member_Host__c.object-meta.xml
<CustomObject>
    <description>Case#1168 - 11/2011 - Rudolf Niehaus
The object forms a link between Campaign, Campaign members and Bank Contacts (Hosts). Objects gets populated, updated and deleted by the CampaignMemebers trigger</description>
    <label>Campaign Member Host</label>
    <nameField>
        <displayFormat>MEMHOST-{0000}</displayFormat>
        <label>Campaign Member Host Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Hosts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TRH_Contact.cls
/**
 * Created by yibrahim on 04.11.2019.
 */

public class TRH_Contact extends ABS_TriggerHandlerBase {
    private Contact[] records {
        get { return (Contact[])Trigger.new; }
    }

    private Contact[] oldRecords {
        get { return (Contact[])Trigger.old; }
    }

    private Map<Id, Contact> id2OldRecords{
        get{
            if(Trigger.old == null){
                return null;
            }
            return new Map<Id, Contact>((Contact[])Trigger.old);
        }
    }

    private Map<Id, Contact> id2NewRecords {
        get {
            if (Trigger.newMap == null) {
                return null;
            }
            return (Map<Id, Contact>) Trigger.newMap;
        }
    }

    public override void handleBeforeInsert() {
        DMN_Contact.setEmailAndMobileFromAccount(records);
        DMN_Contact.populateCIFNumber(records);
        DMN_Contact.emailValidation(records);
		DMN_Contact.insertPBBExternalID(records);

    }

    public override void handleAfterInsert() {
        DMN_Contact.contactUserSyncProcess(records, id2OldRecords, true);
        DMN_Contact.updateRelatedAccounts(records);
        ContactTriggerFuctions.createCCCShare(records);
    }

    public override void handleBeforeUpdate() {
        DMN_Contact.populateCIFNumber(records);
        DMN_Contact.emailValidation(records);
		DMN_Contact.insertPBBExternalID(DMN_Contact.returnContactsWithUpdatedAccount(id2OldRecords, records));
    }

    public override void handleAfterUpdate() {
        DMN_Contact.contactUserSyncProcess(records, id2OldRecords, false);
        DMN_Contact.updateRelatedAccounts(records);
        ContactTriggerFuctions.createCCCShare(records);
        DMN_Contact.syncContactCategoryEventReport(records, id2OldRecords);
        DMN_Contact.updateEventReportCSuiteFlag(records, id2OldRecords);
    }

    private static List<Campaign_Hosts__c> orphanedHosts;
    private static List<Campaign_Member_Host__c> orphanedMemberHosts;
    public override void handleBeforeDelete() {
        orphanedHosts = SEL_CampaignHosts.newInstance().selectByBankContact(id2OldRecords.keySet());
        orphanedMemberHosts = SEL_CampaignMemberHosts.newInstance().selectByMember(id2OldRecords.keySet());
    }

    public override void handleAfterDelete() {
        //Case#6246: Functionality that will merge campaign members in the custom Campiagn_Members_Host__c object when
        //Contacts are merge using standard sf functionality.

        if(oldRecords != null){
            ContactTriggerFuctions clsInstance = new ContactTriggerFuctions(oldRecords);
            //The method will merge campaign members in the custom Campiagn_Members_Host__c
            //object when Contacts are merge using standard sf functionality.
            clsInstance.mergeCampaignMembers();

            DMN_Contact.removeOrphanedHostsAndMemberHosts(orphanedHosts, orphanedMemberHosts);

            //sync junction object with std member object to rectify previous data inconsistencies.
            clsInstance.syncJunctionObject();

            //Case#7064: Merge Event Report Attendees
            //Will determine which Event Report Attendees must be deleted and deletes them
            clsInstance.mergeEventReportAttendees();

            //Will determine which Non-User Client Team must be deleted and deletes them
            clsInstance.mergeNonUserClientTeam();

            //Will determine which Contact Team Members must be deleted and deletes them
            clsInstance.mergeContactTeamMembers();
        }
        DMN_Contact.updateRelatedAccounts(oldRecords);
    }
}