force-app/main/default/objects/Campaign_Hosts__c/Campaign_Hosts__c.object-meta.xml
<CustomObject>
    <description>Case#1168 - 11/2011 - Rudolf Niehaus
Object that holds the link between host and member.</description>
    <label>Campaign Hosts</label>
    <nameField>
        <label>Campaign Hosts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Hosts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Hosts__c/fields/Bank_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bank_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case#1168 - 11/2011 - Rudolf Niehaus
Look-up to Bank Contacts</description>
    <label>Bank Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Hosts</relationshipLabel>
    <relationshipName>Campaign_Hosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Hosts__c/fields/Campaign_Member_Host__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case#1168 - 11/2011 - Rudolf Niehaus
Look-up to &quot;Campaign member host&quot; object</description>
    <label>Campaign Member Host</label>
    <referenceTo>Campaign_Member_Host__c</referenceTo>
    <relationshipLabel>Campaign Hosts</relationshipLabel>
    <relationshipName>Campaign_Hosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Host__c/Campaign_Member_Host__c.object-meta.xml
<CustomObject>
    <description>Case#1168 - 11/2011 - Rudolf Niehaus
The object forms a link between Campaign, Campaign members and Bank Contacts (Hosts). Objects gets populated, updated and deleted by the CampaignMemebers trigger</description>
    <label>Campaign Member Host</label>
    <nameField>
        <displayFormat>MEMHOST-{0000}</displayFormat>
        <label>Campaign Member Host Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Hosts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BLD_CampaignHost.cls
/**
 * Builder class for Campaign_Hosts__c SObject
 *
 * @author Bartosz Sliwinski (bsliwinski@deloittece.com)
 * @date April 2020
 */
@IsTest
public without sharing class BLD_CampaignHost extends ABS_ObjectBuilderBase {

    public BLD_CampaignHost(fflib_SObjectUnitOfWork uow) {
        super(Campaign_Hosts__c.SObjectType, uow);
    }

    public BLD_CampaignHost bankContact(BLD_Contact contactBuilder) {
        return (BLD_CampaignHost) setRelation(Campaign_Hosts__c.Bank_Contact__c, contactBuilder);
    }

    public BLD_CampaignHost memberHost(BLD_CampaignMemberHost memberHostBuilder) {
        return (BLD_CampaignHost) setRelation(Campaign_Hosts__c.Campaign_Member_Host__c, memberHostBuilder);
    }

    public BLD_CampaignHost memberHostId(Id campaignMemberHostId) {
        return (BLD_CampaignHost) setField(Campaign_Hosts__c.Campaign_Member_Host__c, campaignMemberHostId);
    }

}