force-app/main/default/objects/Campaign_Hosts__c/Campaign_Hosts__c.object-meta.xml
<CustomObject>
    <description>Case#1168 - 11/2011 - Rudolf Niehaus
Object that holds the link between host and member.</description>
    <label>Campaign Hosts</label>
    <nameField>
        <label>Campaign Hosts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Hosts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Hosts__c/fields/Bank_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bank_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case#1168 - 11/2011 - Rudolf Niehaus
Look-up to Bank Contacts</description>
    <label>Bank Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Hosts</relationshipLabel>
    <relationshipName>Campaign_Hosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Hosts__c/fields/Campaign_Member_Host__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case#1168 - 11/2011 - Rudolf Niehaus
Look-up to &quot;Campaign member host&quot; object</description>
    <label>Campaign Member Host</label>
    <referenceTo>Campaign_Member_Host__c</referenceTo>
    <relationshipLabel>Campaign Hosts</relationshipLabel>
    <relationshipName>Campaign_Hosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Host__c/Campaign_Member_Host__c.object-meta.xml
<CustomObject>
    <description>Case#1168 - 11/2011 - Rudolf Niehaus
The object forms a link between Campaign, Campaign members and Bank Contacts (Hosts). Objects gets populated, updated and deleted by the CampaignMemebers trigger</description>
    <label>Campaign Member Host</label>
    <nameField>
        <displayFormat>MEMHOST-{0000}</displayFormat>
        <label>Campaign Member Host Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Hosts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/User_Business_Unit_Sync__c.field-meta.xml
<CustomField>
    <fullName>User_Business_Unit_Sync__c</fullName>
    <label>User Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>User_Division_Sync__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Bank Sector</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Br71C Regional Sales</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Business Acquisition</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Buy-Side</fullName>
            </value>
            <value>
                <fullName>Cape Head</fullName>
            </value>
            <value>
                <fullName>Capital Markets</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>CDG</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>China/Africa</fullName>
            </value>
            <value>
                <fullName>CIB</fullName>
            </value>
            <value>
                <fullName>Client Access</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
            <value>
                <fullName>Client Onboarding</fullName>
            </value>
            <value>
                <fullName>Client Service</fullName>
            </value>
            <value>
                <fullName>Client Services Operation</fullName>
            </value>
            <value>
                <fullName>Coastal Region</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Channel</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Channel Head Office</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Head Office</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Conglomerates Commodities &amp; General Commerce</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Corporate Finance</fullName>
            </value>
            <value>
                <fullName>Corporates</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/User_Division_Sync__c.field-meta.xml
<CustomField>
    <fullName>User_Division_Sync__c</fullName>
    <label>User Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Enablers</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
            <value>
                <fullName>Client Services</fullName>
            </value>
            <value>
                <fullName>Commercial Banking</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>Global Markets</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Transactional Products and Services</fullName>
            </value>
            <value>
                <fullName>Vehicle and Asset Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaigHostsWrapper.cls
/*************************************************************************\
    @ Func Area     : Campaign Members and Campaign Hosts 
    @ Author        : Rudolf Niehaus
    @ Date          : 11/2011
    @ Test File     : Test Method in this class : testMe()
    @ Description   : Case#1168
                      Campaign memeber host wrapper class to keep track of check box 
                      selection on members  
    @ Last Modified By  : Rudolf Niehaus
    @ Last Modified On  : 25/05/2012
    @ Modified Reason   : Case#6374 - Fix campaign member host info not showing correctly in excel file  
    
    @ Last Modified By  : Wayne Gray
    @ Last Modified On  : June 2012
    @ Last Modified Reason  :  Move test methods into external class  
                               Case #6521- Change contact to use TestFatcory    
                               API Version moved from 24 to 25
****************************************************************************/

public class CampaigHostsWrapper {
    
    public Boolean checked{ get; set; }
    public List<String> hostsPerMember{ get; set; }
    public Campaign_Member_Host__c memhost { get; set;}
    public Campaign_Hosts__c host { get; set;}
    public String hostNames { get; set;}
    
    public CampaigHostsWrapper(){
       
        memhost = new Campaign_Member_Host__c();
       
        checked = false;
    }
    public CampaigHostsWrapper(Campaign_Member_Host__c c, Set<String> hList, List<Campaign_Hosts__c> hostList){
        
        memhost = c;
        
        hostsPerMember = new List<String>();
        String hostFirstName = '';
        String hostLastName = '';
        String hostDivision = '';
        String hostBusinessUnit = '';
        
        for(Campaign_Hosts__c ch : hostList){
             
             if(ch.Bank_Contact__r.FirstName!=null){
                    hostFirstName = ch.Bank_Contact__r.FirstName;
             }else{
                hostFirstName = '&nbsp;';
             }
             if(ch.Bank_Contact__r.LastName!=null){
                hostLastName = ch.Bank_Contact__r.LastName;
             }else{
                hostLastName = '&nbsp;';
             }
             if(ch.Bank_Contact__r.User_Division_Sync__c!=null){
                hostDivision = ch.Bank_Contact__r.User_Division_Sync__c;
             }else{
                hostDivision = '&nbsp;';
             }
             if(ch.Bank_Contact__r.User_Business_Unit_Sync__c!=null){
                hostBusinessUnit = ch.Bank_Contact__r.User_Business_Unit_Sync__c;
             }else{
                hostBusinessUnit = '&nbsp;';
             }
             
             hostsPerMember.add('<td>' + hostFirstName + '</td><td>' + hostLastName + '</td><td>' + hostDivision + '</td><td>' + hostBusinessUnit + '</td>');
        }
       
       
        hostNames = '';
        
        //Sort host list
       
        List<String> toSort = new List<String>();
        
        toSort.addAll(hList);
        toSort.sort(); 
        
        for(String s : toSort){
            hostNames = hostNames + s + ' , ';
            
        }
        
        hostNames = hostNames.substring(0,hostNames.length()-3);
        
        checked = false;
    }
    public CampaigHostsWrapper(Campaign_Hosts__c h){
        host = h;
        checked = false;
    }
}