force-app/main/default/objects/Custom_Client_Team__c/Custom_Client_Team__c.object-meta.xml
<CustomObject>
    <label>Client Team</label>
    <nameField>
        <displayFormat>Client-{0000}</displayFormat>
        <label>Client Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Client_Coordinator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to specify the Client Coordinator in the Service Team</description>
    <inlineHelpText>Is this Client Team Member the Client Coordinator?</inlineHelpText>
    <label>CC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Coordinator_BM__c.field-meta.xml
<CustomField>
    <fullName>Client_Coordinator_BM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enh#096 - Indicates the client coordinator business manager.</description>
    <label>CC BM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Role__c.field-meta.xml
<CustomField>
    <fullName>Client_Role__c</fullName>
    <label>Team Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Account Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Business Development Manager</fullName>
            </value>
            <value>
                <fullName>BCC CSU Agent</fullName>
            </value>
            <value>
                <fullName>BCC CSU Manager</fullName>
            </value>
            <value>
                <fullName>BCC Ecosystem Manager</fullName>
            </value>
            <value>
                <fullName>BCC Head Trade Sales</fullName>
            </value>
            <value>
                <fullName>BCC Portfolio Manager</fullName>
            </value>
            <value>
                <fullName>BCC Product Specialist</fullName>
            </value>
            <value>
                <fullName>BCC Relationship Manager</fullName>
            </value>
            <value>
                <fullName>BCC Service Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Finance Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Client Analyst</fullName>
            </value>
            <value>
                <fullName>Credit Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Consultant</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Executive Stakeholder</fullName>
            </value>
            <value>
                <fullName>Global Transaction Banker</fullName>
            </value>
            <value>
                <fullName>GM Champion</fullName>
            </value>
            <value>
                <fullName>GM Client Manager</fullName>
            </value>
            <value>
                <fullName>GM Execution Manager</fullName>
            </value>
            <value>
                <fullName>GM Regional Head</fullName>
            </value>
            <value>
                <fullName>IB Champion</fullName>
            </value>
            <value>
                <fullName>Investor Services Manager</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Global_Client_Revenue__c/Global_Client_Revenue__c.object-meta.xml
<CustomObject>
    <description>Case #1263 - Client Overview - Stores Global Client Revenue by reporting country data that is fed into salesforce on a monthly basis by CRT. The data from this object should only be shown on the client overview page and only be visible to the client owner and members on the client service team.</description>
    <label>Global Client Revenue</label>
    <nameField>
        <displayFormat>GCR-{0000000000}</displayFormat>
        <label>Global Client Revenue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Client Revenue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_Client_Revenue__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to Client Object</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Global Client Revenue</relationshipLabel>
    <relationshipName>Global_Client_Revenue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sharing_Settings__c/Sharing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Sharing Settings</label>
</CustomObject>

force-app/main/default/objects/Sharing_Settings__c/fields/Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Access_Level__c</fullName>
    <label>Access Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <description>Team member object connects either internal staff or contractors to a project assignment.  If you further customize the application, you can prevent &quot;stray time reporting&quot; using apex coding so that team members cannot report time outside of the assigned date range.  This becomes important if your organization reports heavily on project costing or SOP-98 capital/expense.  in addition, Force.com Visualforce or Adobe Flex code can be leveraged to help with the matching of resources to projects/work requests.  Please contact professional services for more information on consulting rates or the Salesforce.com Developer network (www.salesforce.com/developer).</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is a lookup to the user and used to assign internal staff to a project team member.</inlineHelpText>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N80000002lXWPEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SHR_GlobalClientRevenue.cls
public class SHR_GlobalClientRevenue extends ABS_Sharing { 

	public static final String DEF_SHARING = 'CCT_Member_Can_Read_GCR__c';

	public SHR_GlobalClientRevenue() { 
		sharingType = Global_Client_Revenue__share.SobjectType;
		defaultSharing = new Sharing_Settings__c(	Access_Level__c 	= 'Read',
													Sharing_Reason__c 	= DEF_SHARING);
	} 

	public override Map<Id, Sobject[]> fetchRecords(Set<Id> parentIds){
		Map<Id, Global_Client_Revenue__c[]> parentId2Gcrs = new Map<Id, Global_Client_Revenue__c[]>();

		for(Global_Client_Revenue__c gcr : [	SELECT OwnerId, Client__r.OwnerId, Client__r.Owner.isActive,
										Client__r.ParentId, Client__r.Parent.ParentId
									FROM Global_Client_Revenue__c
									WHERE Client__c IN : parentIds 
										OR Client__r.ParentId IN : parentIds 
										OR Client__r.Parent.ParentId IN : parentIds
								]){
			Id recordId;
			if(parentIds.contains(gcr.Client__c)){
				recordId = gcr.Client__c; 
			}
			else if (parentIds.contains(gcr.Client__r.ParentId)) {
				recordId = gcr.Client__r.ParentId;
			}
			else if (parentIds.contains(gcr.Client__r.Parent.ParentId)) {
				recordId = gcr.Client__r.Parent.ParentId;
			}

			if(!parentId2Gcrs.containsKey(recordId)){
				parentId2Gcrs.put(recordId, new Global_Client_Revenue__c[]{});
			}
			parentId2Gcrs.get(recordId).add(gcr);
		}
		return parentId2Gcrs;
	}

	protected override SObject[] createShares(User[] users, Sobject[] records, Sobject[] team){
		Custom_Client_Team__c[] teamMembers = (Custom_Client_Team__c[])team;
		Global_Client_Revenue__c[] creditLines = (Global_Client_Revenue__c[])records;

		Global_Client_Revenue__share[] shares = new Global_Client_Revenue__share[]{};
		for(Custom_Client_Team__c cct : teamMembers){
			for(Global_Client_Revenue__c gcr : creditLines){

				if(cct.Team_Member__c == gcr.OwnerId){
					continue;
				}
				
				Sharing_Settings__c ss = getSharingOptions(Custom_Client_Team__c.SobjectType, buildSharingKey(cct));
				shares.addAll(DMN_GlobalClientRevenue.shareGcr(new Set<Id>{gcr.Id}, new Set<Id>{cct.Team_Member__c} ,  
																ss.Sharing_Reason__c , ss.Access_Level__c));
			}
		} 
		return shares;
	} 

	protected override SObject[] deleteShares(User[] users, Sobject[] records, Sobject[] team){
		Sobject[] shares = new Sobject[]{};

		Custom_Client_Team__c[] teamMembers	= (Custom_Client_Team__c[])team;
		Global_Client_Revenue__c[] creditLines 		= (Global_Client_Revenue__c[])records;

		for(Custom_Client_Team__c member : teamMembers){
			for(Global_Client_Revenue__c gcr : creditLines){
				Sobject share = getSharing(member.Team_Member__c ,gcr.Id);
				System.debug('shar' + share);
				if(share != null && gcr.OwnerId != (Id)share.get('UserOrGroupId')){
					shares.add(share);
				}
			}
		} 
		return shares;		
	}

	public static void manageSharing(Global_Client_Revenue__c[] newGcr, Map<Id, Global_Client_Revenue__c> is2OldGcr){

        SRV_AccountSharing shr = new SRV_AccountSharing();

        if(newGcr != null && is2OldGcr == null){
            for(Global_Client_Revenue__c gcr : newGcr){
                shr.share(gcr.Client__c, gcr);
            } 
        }
 
        else if(newGcr == null && is2OldGcr != null){
            for(Global_Client_Revenue__c gcr : is2OldGcr.values()){
                shr.remove(gcr.Client__c, gcr);
            } 
        }

        else {
            for(Global_Client_Revenue__c gcr : newGcr){
                Global_Client_Revenue__c oldCsi = is2OldGcr.get(gcr.Id);
                if(gcr.Client__c != oldCsi.Client__c){
                    shr.change(gcr.Client__c, gcr); 
                }
            }
        }  
        shr.run();  
    }

    private String buildSharingKey(Custom_Client_Team__c member){
    	if(member.Client_Coordinator__c){
    		return '';
    	}
    	else if(member.Client_Coordinator_BM__c){
    		return '';
    	}
    	return member.Client_Role__c;
    }
}