force-app/main/default/objects/CSTManyperRegionTeamRoles__c/CSTManyperRegionTeamRoles__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CST- Phase(3) - Many per region team role List</description>
    <label>CST Many per Region Team Roles</label>
</CustomObject>

force-app/main/default/objects/Custom_Client_Team__c/Custom_Client_Team__c.object-meta.xml
<CustomObject>
    <label>Client Team</label>
    <nameField>
        <displayFormat>Client-{0000}</displayFormat>
        <label>Client Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Client_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/AccountUserId__c.field-meta.xml
<CustomField>
    <fullName>AccountUserId__c</fullName>
    <formula>Account__r.Id+&apos;#&apos;+Team_Member__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AccountUserId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Client_Coordinator__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to specify the Client Coordinator in the Service Team</description>
    <inlineHelpText>Is this Client Team Member the Client Coordinator?</inlineHelpText>
    <label>CC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Coordinator_BM__c.field-meta.xml
<CustomField>
    <fullName>Client_Coordinator_BM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enh#096 - Indicates the client coordinator business manager.</description>
    <label>CC BM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Client_Role__c.field-meta.xml
<CustomField>
    <fullName>Client_Role__c</fullName>
    <label>Team Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Account Analyst</fullName>
            </value>
            <value>
                <fullName>BCC Business Development Manager</fullName>
            </value>
            <value>
                <fullName>BCC CSU Agent</fullName>
            </value>
            <value>
                <fullName>BCC CSU Manager</fullName>
            </value>
            <value>
                <fullName>BCC Ecosystem Manager</fullName>
            </value>
            <value>
                <fullName>BCC Head Trade Sales</fullName>
            </value>
            <value>
                <fullName>BCC Portfolio Manager</fullName>
            </value>
            <value>
                <fullName>BCC Product Specialist</fullName>
            </value>
            <value>
                <fullName>BCC Relationship Manager</fullName>
            </value>
            <value>
                <fullName>BCC Service Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Finance Manager</fullName>
            </value>
            <value>
                <fullName>BCC Trade Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Client Analyst</fullName>
            </value>
            <value>
                <fullName>Credit Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Consultant</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Executive Stakeholder</fullName>
            </value>
            <value>
                <fullName>Global Transaction Banker</fullName>
            </value>
            <value>
                <fullName>GM Champion</fullName>
            </value>
            <value>
                <fullName>GM Client Manager</fullName>
            </value>
            <value>
                <fullName>GM Execution Manager</fullName>
            </value>
            <value>
                <fullName>GM Regional Head</fullName>
            </value>
            <value>
                <fullName>IB Champion</fullName>
            </value>
            <value>
                <fullName>Investor Services Manager</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Client_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Client_Team__c/fields/User_Division__c.field-meta.xml
<CustomField>
    <fullName>User_Division__c</fullName>
    <formula>TEXT(Team_Member__r.User_Division__c)</formula>
    <label>User Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Environment_Variable__c/Environment_Variable__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Environment Variables</label>
</CustomObject>

force-app/main/default/objects/Environment_Variable__c/fields/BatchErrorEmails__c.field-meta.xml
<CustomField>
    <fullName>BatchErrorEmails__c</fullName>
    <description>Variable to store an email address to be used to send the email after Batch execution</description>
    <label>BatchErrorEmails</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <description>Team member object connects either internal staff or contractors to a project assignment.  If you further customize the application, you can prevent &quot;stray time reporting&quot; using apex coding so that team members cannot report time outside of the assigned date range.  This becomes important if your organization reports heavily on project costing or SOP-98 capital/expense.  in addition, Force.com Visualforce or Adobe Flex code can be leveraged to help with the matching of resources to projects/work requests.  Please contact professional services for more information on consulting rates or the Salesforce.com Developer network (www.salesforce.com/developer).</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is a lookup to the user and used to assign internal staff to a project team member.</inlineHelpText>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N80000002lXWPEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SyncCustStdClientTeamForDeleteCCT.cls
/*************************************************************************\
    @ Author        : Abhishek Arya
    @ Date          : Dec, 2010
    @ Test File     : TC_SyncCustStdClientTeamForDeleteCCT.cls
    @ Description   : This Batch class deletes the extra records from the Custom Client Team object 
    @                 keeping it in Synch with the Standard AccountTeamMember object.
    @
    @ Audit Trial   : Repeating block for each change to the code
    @ Last Modified By  :   Anurag Jan
    @ Last Modified On  :   19 May 2011
    @ Last Modified Reason  :   Done the Code review.
    @
    @ Audit Trial   : Repeating block for each change to the code
    @ Last Modified By  :   Y.Balabramham
    @ Last Modified On  :   4/11/2011
    @ Last Modified Reason  : Case - 1845 , Getting the team role rankings and many per region 
                              team roles form custom setting adding into custom object.Modified the 
                              Validation rules based on our requirment.
                              
    @ Last Modified By  :   Jorel Naidoo        
    @ Last Modified On  :   06 November 2012
    @ Last Modified Reason  : Case - 8165 , Added code to allow for sequential execution on batch jobs. 
    
    @ Last Modified By  :   Navin Rai
    @ Last Modified On  :   14/06/2013
    @ Last Modified Reason : EN-101.Changed the code to schedule the Batch class SyncCustClientTeam 
                             Changed the version to 28. 
****************************************************************************/

global class SyncCustStdClientTeamForDeleteCCT implements Schedulable,Database.Batchable<SObject>{
    
    global String query='Select ID From Account order by LastModifiedDate asc';
    
    global Database.QueryLocator start(Database.BatchableContext ctx){
        return Database.getQueryLocator(query);         
      }

    global void execute(SchedulableContext ctx){        
        Database.executeBatch(new SyncCustStdClientTeamForDeleteCCT()); // Start Batch Apex job    
      } 

    global void execute(Database.BatchableContext ctx, List<SObject> records){  
               
        List<Id> AccId=new List<Id>();
        Map<String,AccountTeamMember> accountTeamMembersRecordMap=new Map<String,AccountTeamMember>();
        Map<String,Custom_Client_Team__c> customClientTeamRecordMap=new Map<String,Custom_Client_Team__c>();
        List<String> customClientTeamKeyValue=new List<String>();
        Account acc;
        //List<CSTManyperRegionTeamRoles__c> manyteamrole =[Select Name, ManyPerRegionTeamRoles__c from CSTManyperRegionTeamRoles__c] ;
        for(SObject record : records){                          
           acc = (Account) record;
           AccId.add(acc.Id);
        }
        List<AccountTeamMember> accountTeamMemberRecords=[Select ID,UserId,AccountAccessLevel,TeamMemberRole,AccountId,LastModifiedDate From AccountTeamMember where AccountId in:AccId];
        List<Custom_Client_Team__c> customClientTeamRecords=[Select Id,Team_Member__c,Account__c,AccountUserId__c,Client_Role__c,User_Division__c,Client_Coordinator__c,Client_Coordinator_BM__c from Custom_Client_Team__c where Account__c in:AccId];
        List<Custom_Client_Team__c> customClientTeamRecordsToBeDeleted=new List<Custom_Client_Team__c>();
        
       
            if(customClientTeamRecords.size()>0){
            for(AccountTeamMember atm_obj:accountTeamMemberRecords){
                accountTeamMembersRecordMap.put((String.valueOf(atm_obj.AccountId)).substring(0,15)+'#'+(String.valueOf(atm_obj.UserId)).substring(0,15),atm_obj);
            }
           
            for(Custom_Client_Team__c cct_obj:customClientTeamRecords){
                customClientTeamRecordMap.put((String.valueOf(cct_obj.Account__c)).substring(0,15)+'#'+(String.valueOf(cct_obj.Team_Member__c)).substring(0,15),cct_obj);
                customClientTeamKeyValue.add((String.valueOf(cct_obj.Account__c)).substring(0,15)+'#'+(String.valueOf(cct_obj.Team_Member__c)).substring(0,15));
            }
            
           
                for(String cct_key:customClientTeamKeyValue){
                        if(!accountTeamMembersRecordMap.containsKey(cct_key)){
                          customClientTeamRecordsToBeDeleted.add(customClientTeamRecordMap.get(cct_key));
                        }
                }
                         
                if(customClientTeamRecordsToBeDeleted.size()>0){
                    delete customClientTeamRecordsToBeDeleted;
                }
             
        }

               
    }
    
    global void finish(Database.BatchableContext BC){
        // Get the ID of the AsyncApexJob representing this batch job from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        Environment_Variable__c env = Environment_Variable__c.getInstance();
        
        String onErrorEmail = env.BatchErrorEmails__c;
        String[] toAddresses = new String[] {onErrorEmail};
        //String[] toAddresses = new String[] {'balabramham_yadamakanti@mahindrasatyam.com'};
        mail.setToAddresses(toAddresses);
      
        mail.setSubject('Client Team Batch>> SynchCustStdClientTeamforDeleteCCT ' + a.Status);
        mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems + ' batches with '+ a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
       //JN added to Automactically run the next batch job when this one completes
        //Build the system time of now + 30 seconds to schedule the batch apex.
        Datetime sysTime = System.now();
        sysTime = sysTime.addSeconds(30);
        String chron_exp = '' + sysTime.second() + ' ' + sysTime.minute() + ' ' + sysTime.hour() + ' ' + sysTime.day() + ' ' + sysTime.month() + ' ? ' + sysTime.year();
        system.debug(chron_exp);
        
        //Schedule the next job, and give it the system time so name is unique
        System.schedule('Runs SyncCustClientTeam'+System.Today(),chron_exp,new SyncCustClientTeam ());
        
 
   }
        
}