force-app/main/default/objects/CMN_JobScheduler__c/CMN_JobScheduler__c.object-meta.xml
<CustomObject>
    <description>An object that can be used to manage CronTriggers (Scheduled Jobs) in a managed manager. Only accessible by Administrators.</description>
    <label>Job Scheduler</label>
    <nameField>
        <displayFormat>SCHED-{0000}</displayFormat>
        <label>Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Schedulers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CMN_JobScheduler__c/fields/CMN_CronExpression__c.field-meta.xml
<CustomField>
    <fullName>CMN_CronExpression__c</fullName>
    <description>This is a Salesforce specific Cron (https://en.wikipedia.org/wiki/Cron) expression that will be used to schedule jobs. The supported syntax can be found here (https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm)</description>
    <label>Cron Expression</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CMN_TRG_JobSchedule_Test.cls
/**
* Test class for CMN_TRG_JobSchedule
* 
* <p>DPB-1156</p> 
* 
* @author Salesforce
* 
* @date Nov 10th 2021 
*/
@IsTest
public class CMN_TRG_JobSchedule_Test {

	private static final String NO_EXCEPTION_WAS_THROWN_AS_EXPECTED = 'No exception was thrown as expected';
	private static final String ERROR_WAS_THROWN_AS_EXPECTED = 'Error was thrown as expected';
     /**
    * @description Test setup method to insert a job scheduler
    */
    @IsTest
    public static void insertJobScheduler(){
    	try
		{
			Test.startTest();

			CMN_JobScheduler__c scheduler = CMN_DAL_DataFactory.newJobScheduler(CMN_SCHED_Foobar.class.getName());
			scheduler.CMN_CronExpression__c = CMN_DAL_SObjectDomain.generateRandomName();

			insert scheduler;

			Test.stopTest();

			System.assert(false, NO_EXCEPTION_WAS_THROWN_AS_EXPECTED);
		}
		catch(Exception error)
		{
			System.assert(true, ERROR_WAS_THROWN_AS_EXPECTED);
		}
    }
}