force-app/main/default/objects/CMN_TriggersToDisable__c/CMN_TriggersToDisable__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The class name of the trigger handler that should be disable</description>
    <label>CMN_TriggersToDisable</label>
</CustomObject>

force-app/main/default/objects/CMN_TriggersToDisable__c/fields/CMN_ClassName__c.field-meta.xml
<CustomField>
    <fullName>CMN_ClassName__c</fullName>
    <description>The class name of the trigger handler that should be disabled</description>
    <externalId>true</externalId>
    <label>Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CMN_DAL_TriggersToDisable.cls
/**
 * @description Provides Query methods related for TriggersToDisable Custom Setting
 *
 * @author Accenture
 *
 * @date 2020
 */
public inherited sharing class CMN_DAL_TriggersToDisable
{
	/**
	 * @description Will return base fields to return on a query
	 *
	 * @return A list of Trigger To Enable Custom Setting fields
	 */
	@TestVisible
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				'CMN_ClassName__c',
				'Id',
				'Name'
		};
	}

	/**
	 * @description Will check if a trigger has been disabled
	 *
	 * @param triggerName The name of the trigger to check (must be the class name)
	 *
	 * @return Returns true if a row is NOT found for the given triggerName
	 */
	public static Boolean isTriggerEnabled(String triggerName)
	{
		SObject foundItem = CMN_DAL_SObjectSelector.findByField(CMN_TriggersToDisable__c.SObjectType,
				CMN_TriggersToDisable__c.CMN_ClassName__c, triggerName, getDefaultFields(), false);

		return foundItem == null;
	}
}