force-app/main/default/objects/Gift_Expense_Log__c/Gift_Expense_Log__c.object-meta.xml
<CustomObject>
    <description>Log of Gifts &amp; Expenses (keep)

Gifts are defined as anything of value, such as items, goods, services, favours, access to information, free publicity in whatever form or any other benefit that may accrue to any person, but does not include:
     Official donations made on behalf of Standard Bank / CIB 
     Items, goods, services, information or money in whatever form provided or obtained from third parties in terms of an official contract with Standard Bank / CIB 
     Does not include internal staff incentives.

Entertainment/Event - To provide amusement or enjoyment or to show hospitality. Does not include internal staff incentives.

Case 1051: Gift / Expense Logs : C Reinecke</description>
    <label>Gift / Expense Log</label>
    <nameField>
        <displayFormat>GEL-{00000}</displayFormat>
        <label>Gift / Expense Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift / Expense Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_Expense_Log__c/fields/Approval_Overall_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Overall_Status__c</fullName>
    <description>Approval Reporting Field - Populated via trigger during approval process; Not shown on Page 

Case 1051: Gift / Expense Logs : C Reinecke</description>
    <label>Approval Overall Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift_Expense_Log__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the person responsible for approving the offer for a gift.

Case 1051: Gift / Expense Logs : C Reinecke</description>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gift_Expense_Logs_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift_Expense_Log_Variables__c/Gift_Expense_Log_Variables__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Gift Expense Log Variables</label>
</CustomObject>

force-app/main/default/classes/GiftExpenseLog_Test.cls
/*************************************************************************\
    @ Author        :     Stephen Moore
    @ Date          :     9 Nov 2011
    @ Test File     :     N/A
    @ Description   :     Test Class for Gift Logs

    @ Last Modified By  : Wayne Gray
    @ Last Modified On  : June 2012
    @ Modification Description :  Case #6521- Change contact to use TestFatcory
                                   API Version moved from 23 to 25

    @ Last Modified By  : Nitish Kumar
    @ Last Modified On  : 21  FEB 2013
    @ Modification Description :  EN #31- Use of TestDataUtilityClass
                                  Added best prctices to the test class
                                  API Version moved from 25 to 27
****************************************************************************/
@isTest(SeeAllData=false)
public with sharing class GiftExpenseLog_Test {

    //Static data Member
    public static Gift_Expense_Log_Variables__c oGiftExpenseVariable ;

    static testMethod void GiftLogApproverTestMethod() {

        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
        User user01 = (User) new BLD_USER(uow).useCib().getRecord();
        User user02 = (User) new BLD_USER(uow).useCib().getRecord();
        User user03 = (User) new BLD_USER(uow).useCib().getRecord();
        User user04 = (User) new BLD_USER(uow).useSysAdmin().getRecord();
        System.runAs(new User(Id = UserInfo.getUserId())) {
            uow.commitWork();
        }

        oGiftExpenseVariable = TEST_DataFactory.getGiftExpenseLogVariable();
        insert oGiftExpenseVariable;

        BLD_Account accBld = new BLD_Account(uow).useChild()
            .name(DMN_Account.STANDARD_BANK_EMPLOYEES)
            .proposedClientCoordinator(user04);

        BLD_Contact bankConBld = new BLD_Contact(uow).useBankContact().account(accBld);
        BLD_Contact clientConBld = new BLD_Contact(uow).useClientContact().account(accBld);

        uow.commitWork();

        List<User> usersToUpdate = new List<User>();
        user01.DelegatedApproverId = user02.id;
        usersToUpdate.add(user01);
        user02.DelegatedApproverId = user03.id;
        usersToUpdate.add(user02);
        update usersToUpdate;

        Test.startTest();

        Gift_Expense_Log__c giftExpLogRec = (Gift_Expense_Log__c) new BLD_GiftExpenseLog(uow)
            .bankContact(bankConBld)
            .clientContact(clientConBld)
            .approverId(user01.Id)
            .commitWork()
            .getRecord();

        String objectPrefix = Schema.getGlobalDescribe().get('Gift_Expense_Log__c').getDescribe().getKeyPrefix();
        ApexPages.StandardController sc = new ApexPages.StandardController(giftExpLogRec);

        GiftExpenseNewOverride controller = new GiftExpenseNewOverride(sc);

        String theURL = controller.defaultFields().getUrl();

        System.Assert(theURL.contains(objectPrefix + '/e'));

        giftExpLogRec.Approver__c = user02.id;
        update giftExpLogRec;

        delete oGiftExpenseVariable ;
        String theURL2 = controller.defaultFields().getUrl();

        //Create new Approval Process 1
        Approval.ProcessSubmitRequest submitRequestTest = new Approval.ProcessSubmitRequest();
        //submitRequestTest.setComments('Test');
        submitRequestTest.setObjectId(giftExpLogRec.Id);
        //Simmulate Submit
        Approval.ProcessResult result = Approval.process(submitRequestTest);
        System.assert(result.isSuccess(), 'Result Status:' + result.isSuccess());

        List<Id> newWorkItemIds = result.getNewWorkitemIds();

        Approval.ProcessWorkitemRequest processRequestTest = new Approval.ProcessWorkitemRequest();
        processRequestTest.setComments('Approved Comments');
        processRequestTest.setAction('Approve');
        processRequestTest.setWorkitemId(newWorkItemIds.get(0));

        Approval.ProcessResult result2 = Approval.process(processRequestTest);
        System.assert(result2.isSuccess(), 'Result Status:' + result2.isSuccess());

        Gift_Expense_Log__c testRecord = [SELECT Approval_Overall_Status__c FROM Gift_Expense_Log__c WHERE Id = :giftExpLogRec.Id];
        System.assertEquals('Approved', testRecord.Approval_Overall_Status__c);

        Test.stopTest();

    }
}