force-app/main/default/objects/Onboarding_Application__c/Onboarding_Application__c.object-meta.xml
<CustomObject>
    <description>Digitization - Client Onboarding. This object stores the client initiated request to onboard an entity</description>
    <label>Onboarding Application</label>
    <nameField>
        <displayFormat>OA-{000000000}</displayFormat>
        <label>Onboarding Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding_Application__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The (prospectiive) client record that has been submitted through the client experience portal for onboarding</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Onboarding Applications</relationshipLabel>
    <relationshipName>Onboarding_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding_Application__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>The type of request as determined by the on boarding process in salesforce</description>
    <inlineHelpText>Type of application requested.</inlineHelpText>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Hierarchy</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Request Consent</fullName>
            </value>
            <value>
                <fullName>Hierarchy Change</fullName>
                <isActive>false</isActive>
                <label>Hierarchy Change</label>
            </value>
            <value>
                <fullName>New On-boarding</fullName>
                <isActive>false</isActive>
                <label>New On-boarding</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Onboarding_Application__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <description>The person who requested the on-boarding request</description>
    <inlineHelpText>The person who has submitted the request for approval/review.</inlineHelpText>
    <label>Requested By</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Onboarding_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This is to track the status of Client Consent that will be sent to one or multiple clients(SGPRT-1199 )</description>
    <inlineHelpText>Indicates where in the request process the current request is.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BLD_Onboarding_Application.cls
/**
 *
 * @author Emmanuel Mulea Nocks(BlueSky)
 * @date June 2020
 * @description Builder class
 */
@SuppressWarnings('PMD.ExcessivePublicCount')
@IsTest
public without sharing class BLD_Onboarding_Application extends ABS_ObjectBuilderBase{
    public BLD_Onboarding_Application() {
        this(getNewUnitOfWork());
    }
    
    public BLD_Onboarding_Application(fflib_SObjectUnitOfWork workUnit) {
        super(Onboarding_Application__c.SObjectType, workUnit);
    }
    
    public BLD_Onboarding_Application(Onboarding_Application__c sObj, fflib_SObjectUnitOfWork workUnit) {
        super(sObj, workUnit);
    }
    
    protected override void setdefaultData() {
        setField(Onboarding_Application__c.Status__c,  DMN_OnboardingApplications.STATUS_PENDING);
    }
    
    public BLD_Onboarding_Application requestType(String requestType) {
        return(BLD_Onboarding_Application) setField(Onboarding_Application__c.Request_Type__c, requestType);
    }
    
    public BLD_Onboarding_Application client(BLD_Account clientBld) {
        return(BLD_Onboarding_Application) setRelation(Onboarding_Application__c.Client__c, clientBld);
    }
    
    public BLD_Onboarding_Application requestedBy(String requestedBy) {
        return(BLD_Onboarding_Application) setField(Onboarding_Application__c.Requested_By__c, requestedBy);
    }

    public BLD_Onboarding_Application status(String status) {
        return(BLD_Onboarding_Application) setField(Onboarding_Application__c.Status__c, status);
    }
    
    public BLD_Onboarding_Application useRequestConsentRT(String commBRecTypeConsent) {
        string recordTypeId = UTL_RecordType.getRecordTypeId(DMN_OnboardingApplications.OBJECT_NAME, commBRecTypeConsent);
        return(BLD_Onboarding_Application) setField(Onboarding_Application__c.RecordTypeId, recordTypeId);
    }
    
}