force-app/main/default/objects/Key_Client_Contact__c/Key_Client_Contact__c.object-meta.xml
<CustomObject>
    <description>This object stores the info of important contacts related with a client.</description>
    <label>Key Client Contact</label>
    <nameField>
        <label>Key Client Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Client Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Client_Contact__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related client with the record.</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Key Client Contacts</relationshipLabel>
    <relationshipName>Key_Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Key_Client_Contact__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related contact</description>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Key Client Contacts</relationshipLabel>
    <relationshipName>Key_Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BLD_KeyClientContact.cls
/**
 * Builder class for Key_Client_Contact__c SObject
 *
 * @author Bartosz Sliwinski (bsliwinski@deloittece.com)
 * @date April 2020
 */
@IsTest
public without sharing class BLD_KeyClientContact extends ABS_ObjectBuilderBase {

    public BLD_KeyClientContact(fflib_SObjectUnitOfWork uow) {
        super(Key_Client_Contact__c.SObjectType, uow);
    }

    public BLD_KeyClientContact client(BLD_Account accountBld) {
        return (BLD_KeyClientContact) setRelation(Key_Client_Contact__c.Client__c, accountBld);
    }

    public BLD_KeyClientContact contact(BLD_Contact contactBld) {
        return (BLD_KeyClientContact) setRelation(Key_Client_Contact__c.Contact_Name__c, contactBld);
    }

}