force-app/main/default/objects/SVC_ContactChannelSurvey__c/SVC_ContactChannelSurvey__c.object-meta.xml
<CustomObject>
    <description>SFP-10420 - Survey responses inserted via the integration API user to store the responses for the post call/chat satisfaction survey.</description>
    <label>Contact Channel Survey</label>
    <nameField>
        <displayFormat>CCS-{0000000}</displayFormat>
        <label>Contact Channel Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Channel Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVC_ContactChannelSurvey__c/fields/SVC_ACContactChannel__c.field-meta.xml
<CustomField>
    <fullName>SVC_ACContactChannel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SFP-10420 Lookup to the AC Contact Object which is created by the AC CTI adapter</description>
    <label>AC Contact Channel</label>
    <referenceTo>amazonconnect__AC_ContactChannels__c</referenceTo>
    <relationshipLabel>Contact Channel Surveys</relationshipLabel>
    <relationshipName>SVC_ContactChannelSurveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVC_ContactChannelSurvey__c/fields/SVC_AchievedPurpose__c.field-meta.xml
<CustomField>
    <fullName>SVC_AchievedPurpose__c</fullName>
    <description>SFP-10420 Indicates if the agent managed to achieve everything they intended during their interaction?</description>
    <inlineHelpText>Did you manage to achieve everything you intended during this interaction?</inlineHelpText>
    <label>Achieved Purpose?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVC_ContactChannelSurvey__c/fields/SVC_AgentRating__c.field-meta.xml
<CustomField>
    <fullName>SVC_AgentRating__c</fullName>
    <description>SFP-10420 Indicates the agent&apos;s rating during the interaction with a customer.</description>
    <inlineHelpText>Please rate your experience with the agent who assisted you on this interaction on a scale of 1 to 10?</inlineHelpText>
    <label>Agent Rating</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SVC_ContactChannelSurvey__c/fields/SVC_NetPromoterScoreRating__c.field-meta.xml
<CustomField>
    <fullName>SVC_NetPromoterScoreRating__c</fullName>
    <description>SFP-10420 Indicates how likely the customer is to recommend Standard Bank to their friends and family.</description>
    <inlineHelpText>Please rate how likely you are to recommend Standard Bank to friends and family based on your experience on this interaction on a scale of 0 to 10?</inlineHelpText>
    <label>Net Promoter Score Rating</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SVC_ContactChannelSurvey__c/fields/SVC_SurveyComplete__c.field-meta.xml
<CustomField>
    <fullName>SVC_SurveyComplete__c</fullName>
    <description>SFP-10420 The survey is only indicated as complete when all 3 questions (achieved purpose, net promoter score rating and agent rating) have been answered.</description>
    <formula>AND(
    NOT(ISBLANK(TEXT(SVC_AchievedPurpose__c))),
    NOT(ISBLANK(TEXT(SVC_NetPromoterScoreRating__c))),
    NOT(ISBLANK(TEXT(SVC_AgentRating__c)))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The survey is only indicated as complete when all 3 questions (achieved purpose, net promoter score rating and agent rating) have been answered.</inlineHelpText>
    <label>Survey Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SVC_DAL_ContactChannelSurvey.cls
/**
 * @description Data access layer for the SVC_ContactChannelSurvey__c SObject
 * 
 * @author Accenture
 * @date March 2022
 * 
 **/
public inherited sharing class SVC_DAL_ContactChannelSurvey
{
    public static final String OBJECT_NAME = SVC_ContactChannelSurvey__c.SObjectType.getDescribe().getLocalName();

    /**
     * @description Find the corresponding survey response based on the contact channel id
     * 
     * @param contactChannelId
     * @return SVC_ContactChannelSurvey__c
     * 
     **/
    public static SVC_ContactChannelSurvey__c findSurveyResponseByContactChannelId(String contactChannelId)
    {
        List<SVC_ContactChannelSurvey__c> channelSurveys = [SELECT
            	Id,
            	Name,
            	OwnerId, 
                SVC_AchievedPurpose__c,
                SVC_AgentRating__c,
                SVC_NetPromoterScoreRating__c,
                SVC_SurveyComplete__c
            FROM                
				SVC_ContactChannelSurvey__c
            WHERE
              	SVC_ACContactChannel__c = :contactChannelId
        ];
        return channelSurveys.size() > 0 ? channelSurveys[0] : null;
    }
    
}