force-app/main/default/objects/Opportunity/fields/Actual_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Close_Date__c</fullName>
    <inlineHelpText>Date is system generated upon closing of the opportunity, to amend please contact an administrator.</inlineHelpText>
    <label>Actual Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reason_Won_Lost_Comments__c.field-meta.xml
<CustomField>
    <fullName>Reason_Won_Lost_Comments__c</fullName>
    <inlineHelpText>A brief description of why the Opportunity was won / lost (255 characters or less)</inlineHelpText>
    <label>Reason Won / Lost Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReasonForWinLossPickList__c.field-meta.xml
<CustomField>
    <fullName>ReasonForWinLossPickList__c</fullName>
    <description>Reason for winning / losing the Opportunity</description>
    <inlineHelpText>Reason for winning / losing this Opportunity</inlineHelpText>
    <label>Reason Won / Lost</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bank Strategy not Aligned to Client Strategy</fullName>
            </value>
            <value>
                <fullName>Client Irrelevance / Unfavourable Relationship</fullName>
            </value>
            <value>
                <fullName>Client Relevance / Relationship</fullName>
            </value>
            <value>
                <fullName>Compliance Risk</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Favourable Response Time</fullName>
            </value>
            <value>
                <fullName>Fewer Products Available and Poor Product Fit</fullName>
            </value>
            <value>
                <fullName>Greater Product Mix and Exact Product Fit</fullName>
            </value>
            <value>
                <fullName>Most Competitive Market Pricing</fullName>
            </value>
            <value>
                <fullName>Unfavourable Market Pricing</fullName>
            </value>
            <value>
                <fullName>Unfavourable Response Time</fullName>
            </value>
            <value>
                <fullName>Unfavourable Returns from Pricing Structure</fullName>
            </value>
            <value>
                <fullName>Captured in Error / Duplicate / Expired</fullName>
            </value>
            <value>
                <fullName>Client Strategy Change</fullName>
            </value>
            <value>
                <fullName>Unfavorable Returns from Pricing Structure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunitiesAutoCloseBatch_Test.cls
/**
 * A test class for the OpportunitiesAutoCloseBatch class.
 * <br/>US-4657 - SGPRT-827
 *
 * @author Youssef Ibrahim(yibrahim@deloittece.com)
 * @date November 2019
 */
@IsTest
class OpportunitiesAutoCloseBatch_Test {

    @TestSetup
    static void setup() {                        
        List<Opportunity> openOppsLessThan1MonthOld = new List<Opportunity>();
        List<Opportunity> openOppsMoreThan1MonthOld = new List<Opportunity>();
        
        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();        
        User admUser = (User) new BLD_USER(uow).useSysAdmin().getRecord();
        User busUser = (User) new BLD_USER(uow).useBusinessAdmin().getRecord();        
        System.runAs(new User(Id = UserInfo.getUserId())){
            uow.commitWork();
        }
        uow.commitWork();
        
        system.runAs(busUser){
            for (Integer i = 0; i < 5; i++) {
                Opportunity testOpp = new Opportunity(Name = 'Test-Autoclosed-Opp ' + i, StageName = '1 - Lead', CloseDate = System.today() - 30);
                openOppsLessThan1MonthOld.add(testOpp);
            }
            for (Integer i = 0; i < 5; i++) {
                Opportunity testOpp = new Opportunity(Name = 'Test-Open-Opp ' + i, StageName = '1 - Lead', CloseDate = System.today() - 35);
                openOppsMoreThan1MonthOld.add(testOpp);
            }
            insert openOppsMoreThan1MonthOld;
            insert openOppsLessThan1MonthOld;
        }
    }

    @IsTest
    static void shouldBatchAutoCloseOldOpportunities() {
        Test.startTest();
        OpportunitiesAutoCloseBatch oppAutoCloseBatch = new OpportunitiesAutoCloseBatch();
        Database.executeBatch(oppAutoCloseBatch);
        Test.stopTest();
        List<Opportunity> autoClosedOpps= [SELECT Id, StageName, Reason_Won_Lost_Comments__c, ReasonForWinLossPickList__c, Actual_Close_Date__c
                                            FROM Opportunity
                                            WHERE Name LIKE 'Test-Autoclosed-Opp%'
                                            AND Reason_Won_Lost_Comments__c = 'Auto closed'
                                            AND StageName = 'Cancel'
                                            AND Actual_Close_Date__c = TODAY
                                            AND ReasonForWinLossPickList__c = 'Captured in Error / Duplicate / Expired'];

        List<Opportunity> stillOppenOpps = [SELECT Id, StageName, Reason_Won_Lost_Comments__c, ReasonForWinLossPickList__c, Actual_Close_Date__c
                                            FROM Opportunity
                                            WHERE Name LIKE 'Test-Open-Opp%'
                                            AND StageName = '1 - Lead'];
        System.assertEquals(5, autoClosedOpps.size());
    }
}