force-app/main/default/objects/Opportunity/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <displayFormat>Oppt-{000000}</displayFormat>
    <inlineHelpText>Unique ID number automatically generated. It used for downstream systems and business processes.</inlineHelpText>
    <label>Opportunity ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Product_Fields__c/Product_Fields__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the fields and their Ids for Product Object to be pre populated on product create.</description>
    <label>Product Object Descriptions</label>
</CustomObject>

force-app/main/default/objects/Product_Fields__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <description>Contains the field Id of Account Id field on Product Object.</description>
    <inlineHelpText>Contains the field Id of Account Id field on Product Object.</inlineHelpText>
    <label>Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Fields__c/fields/Grand_Parent_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Grand_Parent_Product_Id__c</fullName>
    <description>Contains the Grand Parent Product field Id in current org..</description>
    <inlineHelpText>Contains the Grand Parent Product field Id in current org.</inlineHelpText>
    <label>Grand Parent Product Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Fields__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <description>Contains the Opportunity Field Id of Product Object.</description>
    <inlineHelpText>Contains the Opportunity Field Id of Product Object.</inlineHelpText>
    <label>Opportunity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Fields__c/fields/Parent_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product_Id__c</fullName>
    <description>Contains the Parent Product field Id.</description>
    <inlineHelpText>Contains the Parent Product field Id of current Org.</inlineHelpText>
    <label>Parent Product Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Fields__c/fields/Product_Division_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Division_Id__c</fullName>
    <description>Contains the Product Division field Id.</description>
    <inlineHelpText>Contains the Product Division field Id of current Org.</inlineHelpText>
    <label>Product Division Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Fields__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <description>Contains the Product field Id of current Org.</description>
    <inlineHelpText>Contains the Product field Id of current Org.</inlineHelpText>
    <label>Product Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/SB_Product__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Products as Standard Bank have requirements that cannot be met with standard object.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Prod-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SB_Product__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Grand_Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Grand_Parent_Product__c</fullName>
    <description>Grand Parent Product</description>
    <label>Grand Parent Product (GPP)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Advisory Fees</fullName>
            </value>
            <value>
                <fullName>Agricultural Products</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Bank Sector Services</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Bills of exchange discounted</fullName>
            </value>
            <value>
                <fullName>Bonds</fullName>
            </value>
            <value>
                <fullName>Bulk and Steel</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Commitments</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Core Custody</fullName>
            </value>
            <value>
                <fullName>Cost Overrun Facility</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Credit Finance &amp; Leverage</fullName>
            </value>
            <value>
                <fullName>Credit Linked Notes &amp; Depo</fullName>
            </value>
            <value>
                <fullName>Cross Border Finance</fullName>
            </value>
            <value>
                <fullName>Custody Services</fullName>
            </value>
            <value>
                <fullName>Customer foreign currency accounts (CFC)</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Debtor Finance</fullName>
            </value>
            <value>
                <fullName>Debt Structuring</fullName>
            </value>
            <value>
                <fullName>Deposits</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Drafts issues</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <description>Parent Product</description>
    <label>Parent Product (PP)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Grand_Parent_Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Electronic Payment</fullName>
            </value>
            <value>
                <fullName>Electronic Collections</fullName>
            </value>
            <value>
                <fullName>Deposits</fullName>
            </value>
            <value>
                <fullName>Letters of Credit</fullName>
            </value>
            <value>
                <fullName>Guarantees</fullName>
            </value>
            <value>
                <fullName>Invoice Financing</fullName>
            </value>
            <value>
                <fullName>LC Discounting</fullName>
            </value>
            <value>
                <fullName>Open Account Finance</fullName>
            </value>
            <value>
                <fullName>Account Verification Service (AVS)</fullName>
            </value>
            <value>
                <fullName>Agricultural Products</fullName>
            </value>
            <value>
                <fullName>Airway Releases</fullName>
            </value>
            <value>
                <fullName>Asset-Backed Commercial Paper (ABCP)</fullName>
            </value>
            <value>
                <fullName>Asset-Backed Securitisation (ABS)</fullName>
            </value>
            <value>
                <fullName>Asset Finance</fullName>
            </value>
            <value>
                <fullName>Associate Income</fullName>
            </value>
            <value>
                <fullName>ATG</fullName>
            </value>
            <value>
                <fullName>ATG - Host to Host</fullName>
            </value>
            <value>
                <fullName>ATG - Online</fullName>
            </value>
            <value>
                <fullName>Autosafe</fullName>
            </value>
            <value>
                <fullName>Autosafe - With Cash Upload</fullName>
            </value>
            <value>
                <fullName>Autosafe - Without Value Hosting / Cash Upload</fullName>
            </value>
            <value>
                <fullName>Autosafe - With Value Hosting</fullName>
            </value>
            <value>
                <fullName>Back-to-Back Guarantee</fullName>
            </value>
            <value>
                <fullName>Back-to-Back  LC</fullName>
            </value>
            <value>
                <fullName>Bank Notes</fullName>
            </value>
            <value>
                <fullName>Base Metals Futures</fullName>
            </value>
            <value>
                <fullName>Base Metals Options</fullName>
            </value>
            <value>
                <fullName>Beyond Payments</fullName>
            </value>
            <value>
                <fullName>Bills For Collection</fullName>
            </value>
            <value>
                <fullName>Bills of Exchange Negotiated (Clean BE&apos;s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Product_Division__c.field-meta.xml
<CustomField>
    <fullName>Product_Division__c</fullName>
    <description>EN-0815:Represents the product house/division that the product belongs to</description>
    <inlineHelpText>Represents the product house/division that the product belongs to.</inlineHelpText>
    <label>Product Division</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Grand_Parent_Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Business and Commercial Banking</fullName>
            </value>
            <value>
                <fullName>Global Markets</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Transactional Products and Services</fullName>
            </value>
            <value>
                <fullName>Vehicle and Asset Finance</fullName>
            </value>
            <value>
                <fullName>Client Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SB_Product__c/fields/Product_Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Revenue_Type__c</fullName>
    <description>SFP-10156: Identification if the product will bring in new revenue or is existing revenue</description>
    <inlineHelpText>Identifies if the product will bring in new revenue or additional revenue on an existing product</inlineHelpText>
    <label>Product Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New to TPS</fullName>
            </value>
            <value>
                <fullName>Retention Money</fullName>
                <default>true</default>
                <label>Retention Money</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SB_Product__c/recordTypes/Advisory.recordType-meta.xml
<RecordType>
    <fullName>Advisory</fullName>
    <active>true</active>
    <label>Advisory</label>
</RecordType>

force-app/main/default/classes/ProductCreationPageSLDS_TEST.cls
/**
 * Test class for ProductCreationPageSLDS.
 *
 * @author Bartosz Sliwinski (bsliwinski@deloittece.com)
 * @date December 2020
 */
@IsTest (IsParallel = true)
private with sharing class ProductCreationPageSLDS_TEST {

    @TestSetup
    static void setupData() {
        TEST_DataFactory.insertSettings(new List<Object> {
            TEST_DataFactory.getProductFieldsSettings()
        });
    }

    @IsTest
    static void shouldPopulateProductsRecordTypeId() {
        PageReference pageRef = Page.ProductCreationPageSLDS;
        Id prodRtId = UTL_RecordType.getRecordTypeId(DMN_SB_Product.OBJ_NAME, DMN_SB_Product.RT_ADVISORY);
        Map<String, String> parameters = pageRef.getParameters();
        parameters.put('RecordType', prodRtId);
        Test.setCurrentPage(pageRef);

        Test.startTest();
        ProductCreationPageSLDS ctrl = new ProductCreationPageSLDS(new ApexPages.StandardController(new BLD_Product().getRecord()));
        Test.stopTest();

        System.assertEquals(prodRtId, ctrl.prod.RecordTypeId);
    }

    @IsTest
    static void shouldInitializeFieldsFromPageParameters() {
        PageReference pageRef = Page.ProductCreationPageSLDS;
        Id prodRtId = UTL_RecordType.getRecordTypeId(DMN_SB_Product.OBJ_NAME, DMN_SB_Product.RT_ADVISORY);
        Map<String, String> parameters = pageRef.getParameters();
        parameters.put('RecordType', prodRtId);

        Product_Fields__c settings = Product_Fields__c.getInstance('productIds');

        parameters.put(settings.Opportunity_Id__c + '_lkid', fflib_IDGenerator.generate(Opportunity.SObjectType));
        parameters.put(settings.Account_Id__c + '_lkid', fflib_IDGenerator.generate(Account.SObjectType));
        parameters.put(settings.Grand_Parent_Product_Id__c, DMN_SB_Product.GPP_CASH_MANAGEMENT);
        parameters.put(settings.Product_Division_Id__c, 'Global Markets');
        parameters.put(settings.Parent_Product_Id__c, 'Advisory');
        parameters.put(settings.Product_Id__c, 'Test prod');
        Test.setCurrentPage(pageRef);

        Test.startTest();
        ProductCreationPageSLDS ctrl = new ProductCreationPageSLDS(new ApexPages.StandardController(new BLD_Product().getRecord()));
        Test.stopTest();

        System.assertNotEquals(null, ctrl.prod.Opportunity__c);
        System.assertNotEquals(null, ctrl.prod.Client__c);
        System.assertNotEquals(null, ctrl.prod.Grand_Parent_Product__c);
        System.assertNotEquals(null, ctrl.prod.Product_Division__c);
        System.assertNotEquals(null, ctrl.prod.Parent_Product__c);
        System.assertNotEquals(null, ctrl.prod.Product_Division__c);
    }

    @IsTest
    static void shouldSuccessfullyInsertProduct() {
        PageReference pageRef = Page.ProductCreationPageSLDS;
        Id prodRtId = UTL_RecordType.getRecordTypeId(DMN_SB_Product.OBJ_NAME, DMN_SB_Product.RT_ADVISORY);
        Map<String, String> parameters = pageRef.getParameters();
        parameters.put('RecordType', prodRtId);

        Product_Fields__c settings = Product_Fields__c.getInstance('productIds');

        parameters.put(settings.Opportunity_Id__c + '_lkid', new BLD_Opportunity().commitWork().getRecordId());

        Test.setCurrentPage(pageRef);

        SB_Product__c prod = (SB_Product__c) new BLD_Product().getRecord();

        ProductCreationPageSLDS ctrl = new ProductCreationPageSLDS(new ApexPages.StandardController(prod));

        Test.startTest();
        PageReference result = ctrl.save();
        Test.stopTest();

        System.assertNotEquals(null, prod.Id);
        System.assertEquals(new ApexPages.StandardController(prod).view().getUrl(), result.getUrl());

    }

    @IsTest
    static void shouldFailWhenInsertingProductBecauseOpportunityMissing() {
        PageReference pageRef = Page.ProductCreationPageSLDS;
        Id prodRtId = UTL_RecordType.getRecordTypeId(DMN_SB_Product.OBJ_NAME, DMN_SB_Product.RT_ADVISORY);
        Map<String, String> parameters = pageRef.getParameters();
        parameters.put('RecordType', prodRtId);

        Test.setCurrentPage(pageRef);

        SB_Product__c prod = (SB_Product__c) new BLD_Product().getRecord();

        ProductCreationPageSLDS ctrl = new ProductCreationPageSLDS(new ApexPages.StandardController(prod));

        Test.startTest();
        PageReference result = ctrl.save();
        Test.stopTest();

        System.assertEquals(null, prod.Id);
        System.assertEquals(null, result);

    }

    @IsTest
    static void shouldCancelAndRedirectToProductSearchPage() {
        PageReference pageRef = Page.ProductCreationPageSLDS;
        Id prodRtId = UTL_RecordType.getRecordTypeId(DMN_SB_Product.OBJ_NAME, DMN_SB_Product.RT_ADVISORY);
        Map<String, String> parameters = pageRef.getParameters();
        parameters.put('RecordType', prodRtId);

        Product_Fields__c settings = Product_Fields__c.getInstance('productIds');

        Id oppId = fflib_IDGenerator.generate(Opportunity.SObjectType);
        parameters.put(settings.Opportunity_Id__c + '_lkid', oppId);

        Test.setCurrentPage(pageRef);

        SB_Product__c prod = (SB_Product__c) new BLD_Product().getRecord();

        ProductCreationPageSLDS ctrl = new ProductCreationPageSLDS(new ApexPages.StandardController(prod));

        Test.startTest();
        PageReference result = ctrl.cancel();
        Test.stopTest();

        System.assertEquals('/apex/ProductSearchPageSLDS?oppId=' + oppId, result.getUrl());

    }

    @IsTest
    static void shouldCoverProperties() {
        PageReference pageRef = Page.ProductCreationPageSLDS;
        Id prodRtId = UTL_RecordType.getRecordTypeId(DMN_SB_Product.OBJ_NAME, DMN_SB_Product.RT_ADVISORY);
        Map<String, String> parameters = pageRef.getParameters();
        parameters.put('RecordType', prodRtId);

        Test.setCurrentPage(pageRef);

        ProductCreationPageSLDS ctrl = new ProductCreationPageSLDS(new ApexPages.StandardController(new BLD_Product().getRecord()));

        Test.startTest();
        System.assertEquals(null, ctrl.opp);
        System.assertEquals(null, ctrl.rt);
        System.assertEquals(null, ctrl.gpp);
        System.assertEquals(null, ctrl.prodobj);
        System.assertEquals(null, ctrl.fieldnames);
        Test.stopTest();

    }
    @IsTest
    static void shouldCovergetInsuranceLeadSource() {
        PageReference pageRef = Page.ProductCreationPageSLDS;
        Id prodRtId = UTL_RecordType.getRecordTypeId(DMN_SB_Product.OBJ_NAME, DMN_SB_Product.RT_INSURANCE);
        Map<String, String> parameters = pageRef.getParameters();
        parameters.put('RecordType', prodRtId);
        
		Product_Fields__c settings = Product_Fields__c.getInstance('productIds');

        Id oppId = fflib_IDGenerator.generate(Opportunity.SObjectType);
        parameters.put(settings.Opportunity_Id__c + '_lkid', oppId);
        
        Test.setCurrentPage(pageRef);
		SB_Product__c prod = (SB_Product__c) new BLD_Product().getRecord();
        ProductCreationPageSLDS ctrl = new ProductCreationPageSLDS(new ApexPages.StandardController(prod));
		
    }
	
    @IsTest
    static void shouldDisplayProductRevenueTypeDefaultValue() {
        PageReference pageRef = Page.ProductCreationPageSLDS;
        Id prodRtId = UTL_RecordType.getRecordTypeId(DMN_SB_Product.OBJ_NAME, DMN_SB_Product.RT_TRANSACTIONAL_2014);
        Map<String, String> parameters = pageRef.getParameters();
        parameters.put('RecordType', prodRtId);
        
		Product_Fields__c settings = Product_Fields__c.getInstance('productIds');

        Id oppId = fflib_IDGenerator.generate(Opportunity.SObjectType);
        parameters.put(settings.Opportunity_Id__c + '_lkid', oppId);
        
        Test.setCurrentPage(pageRef);
		SB_Product__c prod = (SB_Product__c) new BLD_Product().getRecord();
        ProductCreationPageSLDS ctrl = new ProductCreationPageSLDS(new ApexPages.StandardController(prod));
		
        System.assertNotEquals(null, ctrl.prod.Product_Revenue_Type__c);
    }
}