force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Business_Unit__c</fullName>
    <description>SHAVEEN12APR2011CASE074 &gt; Used to store the original Opportunity Owner User details once the Opportunity is Closed. EN - 1168: Renamed label name alone but not the API and updated helptext.</description>
    <inlineHelpText>Copy of the corresponding Opportunity Owner&apos;s User object fields in the following scenarios:
1. Automatically updated and checks for updates when the opportunity is open.
2. Updated when the opportunity is closed and updates only if Owner changes.</inlineHelpText>
    <label>Opportunity Owner User Business Unit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_City__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_City__c</fullName>
    <description>SHAVEEN12APR2011CASE074 &gt; Used to store the original Opportunity Owner User details once the Opportunity is Closed. EN - 1168: Renamed label name alone but not the API and updated helptext.</description>
    <inlineHelpText>Copy of the corresponding Opportunity Owner&apos;s User object fields in the following scenarios: 
1. Automatically updated and checks for updates when the opportunity is open. 
2. Updated when the opportunity is closed and updates only if Owner changes.</inlineHelpText>
    <label>Opportunity Owner User City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_Country__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Country__c</fullName>
    <description>SHAVEEN12APR2011CASE074 &gt; Used to store the original Opportunity Owner User details once the Opportunity is Closed. EN - 1168: Renamed label name alone but not the API and updated helptext.</description>
    <inlineHelpText>Copy of the corresponding Opportunity Owner&apos;s User object fields in the following scenarios: 
1. Automatically updated and checks for updates when the opportunity is open. 
2. Updated when the opportunity is closed and updates only if Owner changes.</inlineHelpText>
    <label>Opportunity Owner User Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_Division__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Division__c</fullName>
    <description>SHAVEEN12APR2011CASE074 &gt; Used to store the original Opportunity Owner User details once the Opportunity is Closed. EN - 1168: Renamed label name alone but not the API and updated helptext.</description>
    <inlineHelpText>Copy of the corresponding Opportunity Owner&apos;s User object fields in the following scenarios: 
1. Automatically updated and checks for updates when the opportunity is open. 
2. Updated when the opportunity is closed and updates only if Owner changes.</inlineHelpText>
    <label>Opportunity Owner User Division</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_Franco__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Franco__c</fullName>
    <description>Used to store the original Opportunity Owner User details once the Opportunity is Closed. EN - 1168: Renamed label name alone but not the API and updated helptext.</description>
    <inlineHelpText>Copy of the corresponding Opportunity Owner&apos;s User object fields in the following scenarios: 
1. Automatically updated and checks for updates when the opportunity is open. 
2. Updated when the opportunity is closed and updates only if Owner changes.</inlineHelpText>
    <label>Opportunity Owner User Franco</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_Global_Area__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Global_Area__c</fullName>
    <description>SHAVEEN12APR2011CASE074 &gt; Used to store the original Opportunity Owner User details once the Opportunity is Closed. EN - 1168: Renamed label name alone but not the API and updated helptext.</description>
    <inlineHelpText>Copy of the corresponding Opportunity Owner&apos;s User object fields in the following scenarios: 
1. Automatically updated and checks for updates when the opportunity is open. 
2. Updated when the opportunity is closed and updates only if Owner changes.</inlineHelpText>
    <label>Opportunity Owner Global Area</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_State_Province__c</fullName>
    <description>SHAVEEN12APR2011CASE074 &gt; Used to store the original Opportunity Owner User details once the Opportunity is Closed. EN - 1168: Renamed label name alone but not the API and updated helptext.</description>
    <inlineHelpText>Copy of the corresponding Opportunity Owner&apos;s User object fields in the following scenarios: 
1. Automatically updated and checks for updates when the opportunity is open. 
2. Updated when the opportunity is closed and updates only if Owner changes.</inlineHelpText>
    <label>Opportunity Owner User State/Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_Team__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Team__c</fullName>
    <description>SHAVEEN12APR2011CASE074 &gt; Used to store the original Opportunity Owner User details once the Opportunity is Closed. EN - 1168: Renamed label name alone but not the API and updated helptext.</description>
    <inlineHelpText>Copy of the corresponding Opportunity Owner&apos;s User object fields in the following scenarios: 
1. Automatically updated and checks for updates when the opportunity is open. 
2. Updated when the opportunity is closed and updates only if Owner changes.</inlineHelpText>
    <label>Opportunity Owner User Team</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>User Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>User_Division__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Bank Sector</fullName>
            </value>
            <value>
                <fullName>Base Metals</fullName>
            </value>
            <value>
                <fullName>Br71C Regional Sales</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Business Acquisition</fullName>
            </value>
            <value>
                <fullName>Business Banking Channel</fullName>
            </value>
            <value>
                <fullName>Business Banking Channel Head Office</fullName>
            </value>
            <value>
                <fullName>Business Banking Head Office</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Buy-Side</fullName>
            </value>
            <value>
                <fullName>Cape Head</fullName>
            </value>
            <value>
                <fullName>Capital Markets</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>CDG</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>China/Africa</fullName>
            </value>
            <value>
                <fullName>CIB</fullName>
            </value>
            <value>
                <fullName>Client Access</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
            <value>
                <fullName>Client Onboarding</fullName>
            </value>
            <value>
                <fullName>Client Service</fullName>
            </value>
            <value>
                <fullName>Client Services Operation</fullName>
            </value>
            <value>
                <fullName>Client Solutions</fullName>
            </value>
            <value>
                <fullName>Coastal Region</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Channel</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Channel Head Office</fullName>
            </value>
            <value>
                <fullName>Commercial Banking Head Office</fullName>
            </value>
            <value>
                <fullName>Commodities</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_CIB_Global_Area__c.field-meta.xml
<CustomField>
    <fullName>User_CIB_Global_Area__c</fullName>
    <label>User CIB Global Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Africa Regions</fullName>
            </value>
            <value>
                <fullName>CIBI</fullName>
            </value>
            <value>
                <fullName>CIBROA</fullName>
            </value>
            <value>
                <fullName>CIBSA</fullName>
            </value>
            <value>
                <fullName>CIB Global</fullName>
            </value>
            <value>
                <fullName>BCC</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>PBB SA</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_City__c.field-meta.xml
<CustomField>
    <fullName>User_City__c</fullName>
    <formula>City</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The User&apos;s City location (80 characters or less)</inlineHelpText>
    <label>User City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/User_Country__c.field-meta.xml
<CustomField>
    <fullName>User_Country__c</fullName>
    <formula>Country</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The User&apos;s Country location (80 characters or less)</inlineHelpText>
    <label>User Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/User_Division__c.field-meta.xml
<CustomField>
    <fullName>User_Division__c</fullName>
    <label>User Division</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>User_CIB_Global_Area__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Banking</fullName>
            </value>
            <value>
                <fullName>Business Enablers</fullName>
            </value>
            <value>
                <fullName>Client Coverage</fullName>
            </value>
            <value>
                <fullName>Client Services</fullName>
            </value>
            <value>
                <fullName>Client Solutions</fullName>
            </value>
            <value>
                <fullName>Commercial Banking</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>Entrepreneur</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>Global Markets</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Small Enterprise</fullName>
            </value>
            <value>
                <fullName>Transactional Products and Services</fullName>
            </value>
            <value>
                <fullName>Vehicle and Asset Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_Franco__c.field-meta.xml
<CustomField>
    <fullName>User_Franco__c</fullName>
    <description>this field is to set the Franco the user belongs to</description>
    <label>User Franco</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Developed Markets</fullName>
            </value>
            <value>
                <fullName>DRC</fullName>
            </value>
            <value>
                <fullName>East Africa</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>Nigeria</fullName>
            </value>
            <value>
                <fullName>South and Central Africa</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>West Africa</fullName>
            </value>
            <value>
                <fullName>Uganda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_State_Province__c.field-meta.xml
<CustomField>
    <fullName>User_State_Province__c</fullName>
    <formula>State</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The User&apos;s State / Province location (80 characters or less)</inlineHelpText>
    <label>User State/Province</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/UserEmail__c.field-meta.xml
<CustomField>
    <fullName>UserEmail__c</fullName>
    <description>Used to load contacts manually</description>
    <externalId>true</externalId>
    <inlineHelpText>The User&apos;s Email Address (80 characters or less)</inlineHelpText>
    <label>User Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OptyClosedOwnerDetailUpdate.cls
/*************************************************************************\    
    @ Author        :     Shaveen Bageloo    
    @ Date          :     13 Apr 2011    
    @ Test File     :     OptyClosedOwnerDetailUpdate_Test    
    @ Description   :     CASE074                          
                            This trigger will copy the Opportunity Owner's                          
                            details from the USER object.                          
                            This code must fire when the Stage is either                          
                            "6 - Closed Lost" or "5 - Closed Won" and only                           
                            execute once per record.
    @ Last Modified By  :   Shaveen Bageloo
    @ Last Modified On  :   09 Jun 2011
    @ Last Modified Reason  :   Functionality change.  The 7 fields must be
                                updated when the Opportunity Owner changes 
                                and the Stage is CLOSED.  It must also fire
                                when the Stage is set to CLOSED.
                                @ Last Modified By  :   Shaveen Bageloo
    @ Last Modified On  :   09 Jun 2015 
    @ Last Modified Reason  :   Functionality change.EN-0619 Field included to update Closed Opportunity Owner Franco
    
    @Last Modified By       :   Abhishek V
    @ Last Modified On      :   07 Mar 2016
    @ Last Modified Reason  :   EN - 1168: Modified code to include scenarios for open opportunities as well.

    @Last Modified By       :   Petr Roubal
    @ Last Modified On      :   15 Mar 2016
    @ Last Modified Reason  :   EN - 1174: RTB - Compliance: Rename of Opportunity Owner User Fields (APIs) and CIB Global Area
                            
****************************************************************************/

public class OptyClosedOwnerDetailUpdate{

    List<Opportunity> optysToBeUpdated = new List<Opportunity>{};
    List<Id> ownerIds = new List<Id>{};
    
    //This method is being called from the TRIGGER class that has records to be CREATED.
    public List<Opportunity> copyOppOwnerDetails(List <Opportunity> optyTriggerNew) {
    
        System.Debug('## >>> copyOppOwnerDetails <<< run by ' + UserInfo.getName());
        System.debug('##:getDMLRows/getLimitDMLRows: ' + Limits.getDMLRows() +'/'+ Limits.getLimitDMLRows());        
        System.debug('##### START: CASE740 - Update Opportunity fields with Opportunity Owners User Details : START #####');  
        System.debug('##### CREATE OPPORTUNITY #####');   

        for (Opportunity optyTriggerNewRec : optyTriggerNew) {
              
            System.debug('## Checking: Opportunity Record is (EN - 1168)Open/Closed ##');                    
            if ((optyTriggerNewRec.StageName == '1 - Lead') || (optyTriggerNewRec.StageName == '2 - Develop') ||(optyTriggerNewRec.StageName == '3 - Closed Won')  || (optyTriggerNewRec.StageName == '4 - Closed Lost') || (optyTriggerNewRec.StageName == 'Cancel'))
            {
                System.debug('## TRUE: Opportunity Record is Open/Closed##'); 
                optysToBeUpdated.add(optyTriggerNewRec);
                ownerIds.add(optyTriggerNewRec.OwnerId);   
            } 
        }
            
        return UpdateOptys(optysToBeUpdated);
   }    
   
  //This method is being called from the TRIGGER class that has records to be UPDATED.    
    public List<Opportunity> copyOppOwnerDetails(List <Opportunity> optyTriggerNew, Map<Id, Opportunity> optyTriggerOldMap) {
    
        System.Debug('## >>> copyOppOwnerDetails <<< run by ' + UserInfo.getName());
        System.debug('##:getDMLRows/getLimitDMLRows: ' + Limits.getDMLRows() +'/'+ Limits.getLimitDMLRows());        
        System.debug('##### START: CASE740 - Update Opportunity fields with Opportunity Owners User Details : START #####');  
        System.debug('##### UPDATE OPPORTUNITY #####');                 
        
            for (Opportunity optyTriggerNewRec : optyTriggerNew) {
                         
                if (optyTriggerOldMap.containsKey(optyTriggerNewRec.Id)) {
                
                    System.debug('## Opportunity New Record = Opportunity Old Record ##');
                    
                    //EN - 1168:Opportunity Stage was changed and it is changed from any value to Lead/Develop
                    if((optyTriggerOldMap.get(optyTriggerNewRec.Id).StageName != optyTriggerNewRec.StageName) && (optyTriggerNewRec.StageName == '1 - Lead' || optyTriggerNewRec.StageName == '2 - Develop'))
                    {
                        System.debug('## TRUE: Opportunity Record was CLOSED/OPEN and changed to LEAD/DEVELOP ##'); 
                        optysToBeUpdated.add(optyTriggerNewRec);
                        ownerIds.add(optyTriggerNewRec.OwnerId);
                    } 
                    
                    System.debug('## Checking: Opportunity Record was (EN - 1168)OPEN and changed to CLOSED ##');                    
                    if (((optyTriggerOldMap.get(optyTriggerNewRec.Id).StageName == '1 - Lead') || (optyTriggerOldMap.get(optyTriggerNewRec.Id).StageName == '2 - Develop')) &&
                        ((optyTriggerNewRec.StageName == '3 - Closed Won') || (optyTriggerNewRec.StageName == '4 - Closed Lost') || (optyTriggerNewRec.StageName == 'Cancel')))
                    {
                        System.debug('## TRUE: Opportunity Record was OPEN and changed to CLOSED ##'); 
                        optysToBeUpdated.add(optyTriggerNewRec);
                        ownerIds.add(optyTriggerNewRec.OwnerId);
                        
                    } 
                    
                    System.debug('## Checking: Opportunity Record is (EN - 1168)OPEN/CLOSED and OWNER has changed ##');                    
                    if (optyTriggerOldMap.get(optyTriggerNewRec.Id).OwnerId <> optyTriggerNewRec.OwnerId)
                    {
                        System.debug('## TRUE: Opportunity Record is OPEN/CLOSED and OWNER has changed ##');
                        optysToBeUpdated.add(optyTriggerNewRec);  
                        ownerIds.add(optyTriggerNewRec.OwnerId);                   
                    }
                    
                }
            }       
            
            
        return UpdateOptys(optysToBeUpdated);
   }   
    
   public List<Opportunity> UpdateOptys(List <Opportunity> optysToBeUpdated) {

        System.debug('## Opportunities to be updated : ' + optysToBeUpdated.size());   

        if (optysToBeUpdated.size() > 0) {
           
            System.debug('## Populating Closed Opportunity Owner"s Details... ##');  
            
            List<User> optyOwnersDetails = new List<User>
                                                    ([Select 
                                                      Id,
                                                      Name,
                                                      Business_Unit__c,
                                                      User_CIB_Global_Area__c,
                                                      User_City__c,
                                                      User_Country__c,
                                                      User_Division__c,
                                                      UserEmail__c,
                                                      User_State_Province__c,
                                                      User_Team__c,
                                                      User_Franco__c
                                                      from User
                                                      where Id IN :ownerIds]);    
    
    
            for (Opportunity optyToBeUpdated : optysToBeUpdated) {
            
                for (User optyOwnerDetailsRec : optyOwnersDetails) {
                
                    if (optyToBeUpdated.OwnerId == optyOwnerDetailsRec.Id) {
                        
            
                        System.debug('## Updating Opportunity fields ##'); 
                                                
                        optyToBeUpdated.Opportunity_Owner_Business_Unit__c = optyOwnerDetailsRec.Business_Unit__c;
                        optyToBeUpdated.Opportunity_Owner_Global_Area__c = optyOwnerDetailsRec.User_CIB_Global_Area__c;
                        optyToBeUpdated.Opportunity_Owner_City__c = optyOwnerDetailsRec.User_City__c;
                        optyToBeUpdated.Opportunity_Owner_Country__c = optyOwnerDetailsRec.User_Country__c;
                        optyToBeUpdated.Opportunity_Owner_Division__c = optyOwnerDetailsRec.User_Division__c;
                        optyToBeUpdated.Opportunity_Owner_State_Province__c = optyOwnerDetailsRec.User_State_Province__c;
                        optyToBeUpdated.Opportunity_Owner_Team__c = optyOwnerDetailsRec.User_Team__c;
                        optyToBeUpdated.Opportunity_Owner_Franco__c = optyOwnerDetailsRec.User_Franco__c;
                        
                        System.debug('## Opportunity fields updated ##');  
                            
                    }
                }
            }
                                                    
            System.debug('## Updating done. ##');
        }   
        
        System.debug('##### END: CASE740 - Update Opportunity fields with Opportunity Owners User Details : START #####');          
        return optysToBeUpdated;                   
   }
   
}