force-app/main/default/objects/Opportunity/fields/Reason_Won_Lost_Comments__c.field-meta.xml
<CustomField>
    <fullName>Reason_Won_Lost_Comments__c</fullName>
    <inlineHelpText>A brief description of why the Opportunity was won / lost (255 characters or less)</inlineHelpText>
    <label>Reason Won / Lost Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reason_Won_Lost_Detail__c.field-meta.xml
<CustomField>
    <fullName>Reason_Won_Lost_Detail__c</fullName>
    <description>Related detail for winning / losing the Opportunity</description>
    <inlineHelpText>Related detail for winning / losing this Opportunity</inlineHelpText>
    <label>Reason Won / Lost Detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ReasonForWinLossPickList__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Appetite for Client / Sector</fullName>
            </value>
            <value>
                <fullName>Client / Transaction Risk</fullName>
            </value>
            <value>
                <fullName>Client Governance / Regulatory Restrictions</fullName>
            </value>
            <value>
                <fullName>Client not Aligned with SB Geographic Footprint</fullName>
            </value>
            <value>
                <fullName>Delays in Credit Approval</fullName>
            </value>
            <value>
                <fullName>Delays in Implementation Phase</fullName>
            </value>
            <value>
                <fullName>Efficiencies in Banking Platforms, Systems and Channels</fullName>
            </value>
            <value>
                <fullName>Favourable Client Onboarding (KYC) Turnaround</fullName>
            </value>
            <value>
                <fullName>Individual Excellence and Service</fullName>
            </value>
            <value>
                <fullName>Inefficiencies in Banking Platforms, Systems and Channels</fullName>
            </value>
            <value>
                <fullName>Inefficient Interaction and Service from Key Business Rep</fullName>
            </value>
            <value>
                <fullName>Inefficient Interaction and Service from  Opportunity Team</fullName>
            </value>
            <value>
                <fullName>Insufficient Security</fullName>
            </value>
            <value>
                <fullName>Key Relationship Bank</fullName>
            </value>
            <value>
                <fullName>Not Clients Primary Relationship Bank</fullName>
            </value>
            <value>
                <fullName>Opportunity Team Excellence and Service</fullName>
            </value>
            <value>
                <fullName>Poor Response from Opportunity Team</fullName>
            </value>
            <value>
                <fullName>Prompt Credit Approval Process</fullName>
            </value>
            <value>
                <fullName>SB Geographic Footprint</fullName>
            </value>
            <value>
                <fullName>Seamless Implementation</fullName>
            </value>
            <value>
                <fullName>Swift Response from Opportunity Team</fullName>
            </value>
            <value>
                <fullName>Unfavourable Client Onboarding (KYC) Turnaround</fullName>
            </value>
            <value>
                <fullName>Mandate terminated/expired</fullName>
            </value>
            <value>
                <fullName>Process abandoned</fullName>
            </value>
            <value>
                <fullName>Offer received too low</fullName>
            </value>
            <value>
                <fullName>Client bid too low</fullName>
            </value>
            <value>
                <fullName>Pricing too high</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReasonForWinLossPickList__c.field-meta.xml
<CustomField>
    <fullName>ReasonForWinLossPickList__c</fullName>
    <description>Reason for winning / losing the Opportunity</description>
    <inlineHelpText>Reason for winning / losing this Opportunity</inlineHelpText>
    <label>Reason Won / Lost</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bank Strategy not Aligned to Client Strategy</fullName>
            </value>
            <value>
                <fullName>Client Irrelevance / Unfavourable Relationship</fullName>
            </value>
            <value>
                <fullName>Client Relevance / Relationship</fullName>
            </value>
            <value>
                <fullName>Compliance Risk</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Favourable Response Time</fullName>
            </value>
            <value>
                <fullName>Fewer Products Available and Poor Product Fit</fullName>
            </value>
            <value>
                <fullName>Greater Product Mix and Exact Product Fit</fullName>
            </value>
            <value>
                <fullName>Most Competitive Market Pricing</fullName>
            </value>
            <value>
                <fullName>Unfavourable Market Pricing</fullName>
            </value>
            <value>
                <fullName>Unfavourable Response Time</fullName>
            </value>
            <value>
                <fullName>Unfavourable Returns from Pricing Structure</fullName>
            </value>
            <value>
                <fullName>Captured in Error / Duplicate / Expired</fullName>
            </value>
            <value>
                <fullName>Client Strategy Change</fullName>
            </value>
            <value>
                <fullName>Unfavorable Returns from Pricing Structure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>The day the Opportunity discussions started, only editable in the Lead stage.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_OpportunityProgressTrackerExt.cls
/*****************************************************************************************************************************************************************************************************************
    @ Author        : Shubham Khilauria
    @ Date          : 13 - Feb - 2014
    @ Description   : Test Class for ClientOperatingCountryControllerClass.cls. This class will test the Unit test for Drag and Drop Page
                      which will include creating Existing Business Records, Prospective Business Records and also the scenario when 
                      Client doesn't have any Client Operating COuntries associated to it.

    @Last Modified Date: 4 Dec 2015
    @Last ModifiedBy: Petr Svestka
    @Last Modified Reason: fixed the users' timezone to SAST
    
    @ Last Modified By  : Abhishek V
    @ Last Modified On  : July 5, 2016
    @ Modification Description : Moved test.startTest() to fix 101 SOQL limit. Also, combined individual user records to a list and inserted
******************************************************************************************************************************************************************************************************************/

@isTest(seealldata = false)
private class Test_OpportunityProgressTrackerExt {
    /************************************************************************************************
    Scenario - Test different stages on Opportunity to show different visuals on screen.
    *************************************************************************************************/
    static testMethod void testOpportunityStages() {
        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();

        User admUser = (User) new BLD_USER(uow).useSysAdmin().getRecord();
        User admUser1 = (User) new BLD_USER(uow).useSysAdmin().getRecord();
        User custUser = (User) new BLD_USER(uow).useCib().getRecord();

        System.runAs(new User(Id = UserInfo.getUserId())){
            uow.commitWork();
        }

        BLD_Opportunity oppBld = new BLD_Opportunity(uow)
            .stage(DMN_Opportunity.ST_LEAD)
            .client(
                new BLD_Account(uow).useChild().CIF('0').CIFActiveCode('A')
            );

        uow.commitWork();

        Opportunity oppRec = (Opportunity) oppBld.getRecord();
        
        
        system.runAs(admUser){
            
            ApexPages.StandardController std_Controller = new ApexPages.StandardController(oppRec);
            PageReference testPage  = Page.ProgressTracker;
            Test.setCurrentPage(testPage);
            OpportunityProgressTrackerExt oppStage = new OpportunityProgressTrackerExt(std_controller);
             
            // Set Close date less than today then Expired Opportunity will be Highlighted
            oppRec.CloseDate = System.today()-1;
            oppRec.Start_Date__c = System.today();
            update oppRec;
            oppStage.oppId = oppRec.Id;
            //call Process opportunity
            oppStage.processOpportunity();
             
            //Insert Opp Team Members
            new BLD_OpportunityTeamMember(uow)
                .opportunity(oppBld)
                .userId(custUser.Id)
                .role('Product Specialist')
                .commitWork();
            oppStage.processOpportunity();
            System.assertEquals(oppStage.boolLeadWithMileStoneExpired,true);
            
            test.startTest();
            // Set Close date less than today then Expired Opportunity will be Highlighted
            oppRec.CloseDate = System.today()+4;
            oppRec.Start_Date__c = System.today();
            update oppRec;
            oppStage.oppId = oppRec.Id;
            //call Process opportunity
            oppStage.processOpportunity();
            System.assertEquals(oppStage.boolLeadWithMileStone,true);
            
            //Change Opportunity Stage to Develop without Revenue.
            oppRec.StageName = DMN_Opportunity.ST_DEVELOP;
            update oppRec;
            oppStage.oppId = oppRec.Id;
            //call Process opportunity
            oppStage.processOpportunity();
            System.assertEquals(oppStage.boolOrangeOpp,true);
            
            //Change Opportunity Stage to Develop with Rvenue.
            new BLD_Product()
                .linkToOpp(oppBld)
                .commitWork();
            oppRec.StageName = DMN_Opportunity.ST_DEVELOP;
            oppRec.Amount = 220.00;
            update oppRec;
            oppStage.oppId = oppRec.Id;
            //call Process opportunity
            oppStage.processOpportunity();
            System.assertEquals(oppStage.boolDevelopWithMileStone,true);
            
            //Expire Opportunity in Develop Stage.
            oppRec.CloseDate = System.today()-4;
            oppRec.Start_Date__c = System.today();
            update oppRec;
            oppStage.oppId = oppRec.Id;
            //call Process opportunity
            oppStage.processOpportunity();
            System.assertEquals(oppStage.boolDevelopWithMileStoneExpired,true);
            
            //Change Opportunity Stage to Closed
            oppRec.StageName = DMN_Opportunity.ST_CLOSED_WON;
            oppRec.Reason_Won_Lost_Comments__c = 'Test Comments';
            oppRec.Reason_Won_Lost_Detail__c = 'Test Detail';
            oppRec.ReasonForWinLossPickList__c = 'Win Reason';
            
            update oppRec;
            oppStage.oppId = oppRec.Id;
            //call Process opportunity
            oppStage.processOpportunity();
            System.assertEquals(oppStage.boolClosedStage,true);
            
            oppRec.OwnerId = admUser1.Id;
            update oppRec;
            //call Process opportunity
            oppStage.processOpportunity();
            test.stopTest();
            
        }   
    
       
    }
    
    
}