force-app/main/default/objects/Contact/fields/Birth_Day_Month__c.field-meta.xml
<CustomField>
    <fullName>Birth_Day_Month__c</fullName>
    <description>Please enter the day and the month of the contact&apos;s birthday. Format dd/mm</description>
    <inlineHelpText>Please enter the day and the month of the Contact&apos;s birthday. Format dd/mm (5 characters or less)</inlineHelpText>
    <label>Birth Day/Month</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Birthday_Date_Format__c.field-meta.xml
<CustomField>
    <fullName>Birthday_Date_Format__c</fullName>
    <description>This field converts the birthday day/month field into a proper date field. The year part is irrelevant and is set to 2008 to cater for 29 Feb birthdays. This field is used in the birthday reminder scheduled job to determine which contact team members must be sent a notification task.

(CRM Birthday Reminder Case# 207 C Reinecke 2010/09)</description>
    <formula>IF((ISBLANK(Birth_Day_Month__c)),NULL,DATEVALUE( &quot;2008-&quot; &amp; RIGHT(Birth_Day_Month__c , 2)&amp;&quot;-&quot;&amp;LEFT( Birth_Day_Month__c , 2) ))</formula>
    <label>Birthday Date Format</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the status of the contact at the client. This status is used to improve contact searches .Inactive Contacts are excluded from lookup searches</description>
    <inlineHelpText>Indicates the status of the contact at the client. This status is used to improve contact searches.</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SA_Contact_Team_Member__c/SA_Contact_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Contact Team Member</label>
    <nameField>
        <displayFormat>CTM-{00000}</displayFormat>
        <label>Contact Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SA_Contact_Team_Member__c/fields/SA_Contact__c.field-meta.xml
<CustomField>
    <fullName>SA_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Team Members</relationshipLabel>
    <relationshipName>Contact_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SA_Contact_Team_Member__c/fields/SA_User__c.field-meta.xml
<CustomField>
    <fullName>SA_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contact_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Birth_Day_Month__c.field-meta.xml
<CustomField>
    <fullName>Birth_Day_Month__c</fullName>
    <description>Stores the Users birthday in the format dd/mm

            (CRM Birthday Reminder Case# 207 C Reinecke 2010/09)</description>
    <inlineHelpText>Please enter the day and the month of the User&apos;s birthday. Format dd/mm (5 characters or less)</inlineHelpText>
    <label>Birth Day/Month</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Birthday_Date_Format__c.field-meta.xml
<CustomField>
    <fullName>Birthday_Date_Format__c</fullName>
    <description>This field converts the birthday day/month field into a proper date field. The year part is irrelevant and is set to 2008 to cater for 29 Feb birthdays. This field is used in the birthday reminder scheduled job to determine which users must be sent a happy birthday email.

            (CRM Birthday Reminder Case# 207 C Reinecke 2010/09)</description>
    <formula>IF((ISBLANK(Birth_Day_Month__c)),NULL,DATEVALUE( &quot;2008-&quot; &amp; RIGHT(Birth_Day_Month__c , 2)&amp;&quot;-&quot;&amp;LEFT( Birth_Day_Month__c , 2) ))</formula>
    <label>Birthday Date Format</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/RecieveBirthdayReminderTasks__c.field-meta.xml
<CustomField>
    <fullName>RecieveBirthdayReminderTasks__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is set to indicate if a user wants to receive a birthday reminder for those contacts that they have an interest in as recorded on the SA Contact Team Member object.

            (CRM Birthday Reminder Case# 207 C Reinecke 2010/09)</description>
    <inlineHelpText>Indicate if you would like to receive birthday reminders for contacts that you are the owner or client owner of or that you are on the client contact team.</inlineHelpText>
    <label>Birthday Reminders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/batchContactTeamBirthdayReminders.cls
/*************************************************************************\
    @ Author        : Revashlin Iyman
    @ Date          : 23rd Sept, 2010
    @ Test File     : BirthdayCronJob_Test.cls
    @ Description   : This batch class sends birthday reminders to the bank contacts
    @ Audit Trial   : Repeating block for each change to the code
    @ Last Modified By  :   Nikhita Reddy
    @ Last Modified On  :   14 Jan 2013
    @ Last Modified Reason  :   Indented the code and added comments. Updated the API Version to 27
****************************************************************************/

global class batchContactTeamBirthdayReminders implements Database.Batchable<sObject> {
    public Boolean runTestMethod = false;
    global String query;
    public Integer Month;
    public Integer Day;
    global Set<Id> ContactOwners;
    global Set<Id> ClientOwners;
    private Date today, birthdayToDate;

    private static String ACTIVITY_SUBJECT_BIRTHDAY_REMINDER = 'Birthday Reminder';
    
    global batchContactTeamBirthdayReminders() {
        /*Date theBigDay = Date.today().addDays(7);
        this.Day = theBigDay.day();
        this.Month = theBigDay.month();*/
        this.today = Date.today();
        this.birthdayToDate = Date.today().addDays(7);

        this.ContactOwners = new Set<Id>();
        this.ClientOwners = new Set<Id>();

        this.query = 'SELECT Id, SA_User__c, SA_Contact__c, SA_Contact__r.Name, SA_Contact__r.Birth_Day_Month__c, SA_Contact__r.Account.Name, SA_User__r.Id'+
                        +' FROM SA_Contact_Team_Member__c'+
                        +' WHERE SA_Contact__r.Inactive__c = false'+
                        +' AND SA_User__r.RecieveBirthdayReminderTasks__c = true'+
                        +' AND SA_Contact__r.Birthday_Date_Format__c <= :birthdayToDate'+
                        +' AND SA_Contact__r.Birthday_Date_Format__c >= :today';
                        
    }
    
    // Start method of the batch class
    global Database.QueryLocator start(Database.BatchableContext BC) {
        if (runTestMethod) {
            query = query + ' ORDER BY CreatedDate DESC LIMIT 200';
        }
        return Database.getQueryLocator(query);
    }
    
    // Execute method of the batch class
    global void execute(Database.BatchableContext BC, List<SA_Contact_Team_Member__c> scope) {
        List<Task> taskList = new List<Task>([SELECT WhoId, OwnerId FROM Task
                                              WHERE WhoId IN (SELECT SA_Contact__c
                                                            FROM SA_Contact_Team_Member__c
                                                            WHERE Id IN :scope) AND
                                                    Subject = :ACTIVITY_SUBJECT_BIRTHDAY_REMINDER AND
                                                    ActivityDate >= :Date.today().addDays(-7)
                                                    ]);
        Set<String> activityIdentifiers = new Set<String>();
        for (Task task : taskList) {
            activityIdentifiers.add(''+task.WhoId+task.OwnerId);
        }

        //String whoIdString = String.join(idList, ', ');
        List<Task> reminderTasks = new List<Task>();
        Task theReminderTask;
        
        // Generates a new Task as a birthday reminder
        for (SA_Contact_Team_Member__c reminderRecipient : scope) {
            // Don't create birthday Reminder if it's already Completed or already exists
            if (!activityIdentifiers.contains(''+reminderRecipient.SA_Contact__c+reminderRecipient.SA_User__c)) {
                theReminderTask = new Task();
                String[] dayMonth = reminderRecipient.SA_Contact__r.Birth_Day_Month__c.split('/');
                theReminderTask.ActivityDate = Date.newInstance(Date.today().year(), Integer.valueOf(dayMonth[1]), Integer.valueOf(dayMonth[0]));  //Date.today().addDays(7);
                theReminderTask.OwnerId = reminderRecipient.SA_User__r.Id;
                theReminderTask.Subject = ACTIVITY_SUBJECT_BIRTHDAY_REMINDER; // for: ' + reminderRecipient.SA_Contact__r.Name;
                theReminderTask.WhoId = reminderRecipient.SA_Contact__r.Id;
                theReminderTask.Description = 'This is a system generated task created as a birthday reminder for ' + reminderRecipient.SA_Contact__r.Name + ' from ' + reminderRecipient.SA_Contact__r.Account.Name + '. Please action according to your mandate regarding Contact birthdays.';
                theReminderTask.Type = 'Follow-up';
                theReminderTask.Status = 'Not Started';
                theReminderTask.Priority = 'Low';
                theReminderTask.IsReminderSet = true;
                theReminderTask.Item_to_Action__c = true;
                reminderTasks.add(theReminderTask);
            }
        }
        
        if (reminderTasks.size() > 0) {
            Database.DMLOptions dlo = new Database.DMLOptions();
            dlo.EmailHeader.triggerUserEmail = true;
            Database.insert(reminderTasks, dlo);
        }
    }

    // Finish method of the batch class
    global void finish(Database.BatchableContext BC) {
    }
}