force-app/main/default/objects/Contact/fields/Identity_Number__c.field-meta.xml
<CustomField>
    <fullName>Identity_Number__c</fullName>
    <description>Digital Onboarding: This field stores the Authorised Person&apos;s ID number and is used by the KYC Consultants during the KYC Process. This field is only visible to the Custom KYC User Profile and the Onboarding API profile.</description>
    <label>Identity Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OSB_Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>OSB_Passport_Number__c</fullName>
    <description>OneHub: This field stores the Community users Passport Number. (US-4589)</description>
    <inlineHelpText>Clients Passport Number</inlineHelpText>
    <label>Passport Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OSB_MarketGramPopup_Ctrl.cls
/**
 * Controller class for OSB_MarketGramPopup_Ctrl component
 *
 * @author Wayde Fagan (wayde.fagan@tetrad.co.za)
 * @date April 2020
 *
 **/
public without sharing class OSB_MarketGramPopup_Ctrl {

    /**
     * Creates a case for the contact us request access form
     *
     * @param case fields
     * @param Id number
     * @param passport number
     *
     * @return Case
     **/
    @AuraEnabled
    public static Case saveCase(Case MarketGramCase,String IdentityNum, String PassNum) {
        Id QueueId = UTL_Queue.getQueueId(DMN_Queue.ONEHUB_QUEUE);
        try{
            List <Contact> contact = [Select Id,RecordTypeId,Email,Identity_Number__c from Contact
                                      where Email =: MarketGramCase.SuppliedEmail AND (Identity_Number__c =: IdentityNum OR OSB_Passport_Number__c =: PassNum)  LIMIT 1];
            if(!contact.isEmpty()){ 
                MarketGramCase.ContactId = contact[0].Id;
                if(contact[0].RecordTypeId == UTL_RecordType.getRecordTypeId(DMN_Contact.OBJ_NAME, DMN_Contact.RTD_BANK)){
                	MarketGramCase.RecordTypeId = UTL_RecordType.getRecordTypeId(DMN_Case.OBJ_NAME, DMN_Case.RT_USER_CASE);
                }
                else{
                    MarketGramCase.RecordTypeId = UTL_RecordType.getRecordTypeId(DMN_Case.OBJ_NAME, DMN_Case.RT_CIB_CLIENT_CASE);
                }
            }else{
                MarketGramCase.RecordTypeId = UTL_RecordType.getRecordTypeId(DMN_Case.OBJ_NAME, DMN_Case.RT_CIB_CLIENT_CASE);
            }
            
            MarketGramCase.Priority = DMN_Case.PRIORITY_LOW;
            MarketGramCase.OwnerId = QueueId;
            insert MarketGramCase;
            return MarketGramCase;
        }catch(Exception e){
            System.debug(e.getMessage());
            return null;
        }
    }
}