force-app/main/default/objects/Contact/fields/Onboarding_Tour_Date__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Tour_Date__c</fullName>
    <description>OneHub: Date, when user finished onboarding tour in OneHub Community. (US-4589)</description>
    <inlineHelpText>Indicates the date and time user completed the onboarding tour on the OneHub community.</inlineHelpText>
    <label>Onboarding Tour Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Subscribed_Solutions__c/Subscribed_Solutions__c.object-meta.xml
<CustomObject>
    <description>OneHub: This object is used to manage the Solutions a user has signed up for and create the tile on the dashboard.</description>
    <label>Subscribed Solution</label>
    <nameField>
        <displayFormat>SS{00000}</displayFormat>
        <label>Subscribed Solutions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OSB_Dashboard_CTRL.cls
/**
* Controller class for OSBDashboard aura component
*
* @author Wojciech Kowalczyk (wkowalczyk@deloittece.com)
* @date June 2020
*/
public with sharing class OSB_Dashboard_CTRL {
    /**
* Checks if the user has been logged in for the first time for guided tour
*
* @return contact related to current user
**/
    @AuraEnabled(Cacheable=true)
    public static Contact getOnboardingDetails() {
        try{
            if (UTL_User.isLoggedInUser()) {
                return SEL_Contacts.newInstance().selectByUserId(new Set<Id>{UserInfo.getUserId()})[0];
            }
            return null;
        }
        catch(Exception ex){
            return null;
        }
    }
    
    /**
* Gets a list of solutions that a user is subscribed to
*
* @return List<Knowledge__kav> register applications
**/
    @AuraEnabled(Cacheable=true)
    public static List<Subscribed_Solutions__c> getRegisteredApplication() {
        return SEL_SubscribedSolutions.newInstance().selectByUserId(new Set<Id>{UserInfo.getUserId()});
    }
    
    /**
* Sets the user contact Onboarding_Tour_Date__c to current date time
*
* @param contactId id of contact
*
* @return String
**/
    @AuraEnabled(Cacheable=false)
    public static void setUserContactOnboardingDate(Id contactId) {
        fflib_ISObjectUnitOfWork uow = ORG_Application.unitOfWork.newInstance();
        OSB_SRV_OnboardingHandler.newInstance().setUserContactOnboardingDate(new Set<Id>{contactId}, uow);
        uow.commitWork();
    }
    
    /**
* Checks if user has any registered device
*
* @return Map<String,Map<String,Object>> that contains the device details  */
    @AuraEnabled(Cacheable=true)
    public static Map<String,Map<String,Object>> hasRegisteredDevices(){
        Boolean hasRegisteredDevices;
        Map<String,Map<String,Object>> deviceHeaders2Values = OSB_SRV_NoknokIntegration.newInstance().getDeviceList();
        
        return deviceHeaders2Values; 
    }
    
}