force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Created for PBB - will store transactional data</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Balance__c.field-meta.xml
<CustomField>
    <fullName>Account_Balance__c</fullName>
    <description>&quot;The minimum or maximum amount that the account reached in a particular period
US-4409
US-4456
US-4425&quot;</description>
    <inlineHelpText>This is the minimum or maximum amount that the account reached in a particular period</inlineHelpText>
    <label>Account Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Account_OD_Limit__c.field-meta.xml
<CustomField>
    <fullName>Account_OD_Limit__c</fullName>
    <description>&quot;The limit on the client&apos;s account for the said period
US-4409
US-4456
US-4425&quot;</description>
    <inlineHelpText>This is the  limit on the client&apos;s account for the said period</inlineHelpText>
    <label>Account OD Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Flag_Pos_Trans_Amt__c.field-meta.xml
<CustomField>
    <fullName>Flag_Pos_Trans_Amt__c</fullName>
    <description>Negative/ Positive flag</description>
    <label>Flag Pos Trans Amt</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>Last day of month for the period
&quot;The 12-month period that is being reported on
US-4409
US-4456
US-4425&quot;</description>
    <inlineHelpText>Last day of month for the period
The 12-month period that is being reported on</inlineHelpText>
    <label>Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <description>&quot;Amount that is being credited/debited on the client&apos;s account
NB: Data for creditor and debtor amount is received in the same field/column from Proact
US-4409
US-4456
US-4425&quot;</description>
    <inlineHelpText>This is the amount that is being credited/debited on the client&apos;s account
This is the amount that is flowing in or out of the client&apos;s account</inlineHelpText>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Count__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Count__c</fullName>
    <description>&quot;Number of times that the account has been credited/debited over the last 6 months
NB: Data for creditor and debtor amount is received in the same field/column from Proact
US-4409
US-4456
US-4425&quot;</description>
    <inlineHelpText>This is the number of times that the account has been credited/debited</inlineHelpText>
    <label>Transaction Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field help to differentiate transaction summary and outflows/inflows
US-4456</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Balances/Cash Flow</fullName>
            </value>
            <value>
                <fullName>Inflow/Outflow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BLD_Transaction.cls
public without sharing class BLD_Transaction extends ABS_ObjectBuilderBase {
    public BLD_Transaction() {
        super(Transaction__c.SobjectType);
        init();
    }

    public BLD_Transaction(fflib_SObjectUnitOfWork workUnit) {
        super(Transaction__c.sObjectType, workUnit);
        init();
    }

    public BLD_Transaction(Transaction__c rap) {
        super(rap);
    }

    private void init() {
        setField(Transaction__c.Period__c, System.today());
    }

    public BLD_Transaction accountBalance(Integer value) {
        return (BLD_Transaction) setField(Transaction__c.Account_Balance__c, value);
    }

    public BLD_Transaction flagPosTransAmt(String value) {
        return (BLD_Transaction) setField(Transaction__c.Flag_Pos_Trans_Amt__c, value);
    }

    public BLD_Transaction period(Date value) {
        return (BLD_Transaction) setField(Transaction__c.Period__c, value);
    }

    public BLD_Transaction accountODLimit(Integer value) {
        return (BLD_Transaction) setField(Transaction__c.Account_OD_Limit__c, value);
    }

    public BLD_Transaction transactionAmount(Integer value) {
        return (BLD_Transaction) setField(Transaction__c.Transaction_Amount__c, value);
    }

    public BLD_Transaction transactionCount(Integer value) {
        return (BLD_Transaction) setField(Transaction__c.Transaction_Count__c, value);
    }

    public BLD_Transaction transactionType(String value) {
        return (BLD_Transaction) setField(Transaction__c.Transaction_Type__c, value);
    }
}