force-app/main/default/objects/Account_Application__c/Account_Application__c.object-meta.xml
<CustomObject>
    <description>Digitization: Onboarding - This object stores a client initiated request for a product such a business current account..</description>
    <label>Account Application</label>
    <nameField>
        <displayFormat>AAN-{00000000}</displayFormat>
        <label>Account Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Terms_Accepted__c/Product_Terms_Accepted__c.object-meta.xml
<CustomObject>
    <description>Digitization - Onboarding: This junction object stores the acceptance of each product term</description>
    <label>Product Terms Accepted</label>
    <nameField>
        <displayFormat>PTA-{000000000}</displayFormat>
        <label>Product Terms Accepted Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Terms Accepted</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Terms_Accepted__c/fields/Account_Application__c.field-meta.xml
<CustomField>
    <fullName>Account_Application__c</fullName>
    <label>Account Application</label>
    <referenceTo>Account_Application__c</referenceTo>
    <relationshipLabel>Product Terms Accepted</relationshipLabel>
    <relationshipName>Product_Terms_Accepted</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Terms_Accepted__c/fields/Term_URL__c.field-meta.xml
<CustomField>
    <fullName>Term_URL__c</fullName>
    <label>Term URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SEL_ProductTermsAccepted.cls
/**
 * Selector layer class for Product_Terms_Accepted__c SObject
 *
 * @author Caro Reinecke (caro@khonology.com)
 * @date 2018-01-08
 */
public class SEL_ProductTermsAccepted extends fflib_SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
                Product_Terms_Accepted__c.Name,
                Product_Terms_Accepted__c.Id,
                Product_Terms_Accepted__c.Account_Application__c,
                Product_Terms_Accepted__c.Accepted__c,
                Product_Terms_Accepted__c.Term_Name__c,
                Product_Terms_Accepted__c.Term_Title__c,
                Product_Terms_Accepted__c.Term_URL__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Product_Terms_Accepted__c.sObjectType;
    }

    public List<Product_Terms_Accepted__c> selectById(Set<ID> idSet) {

        return (List<Product_Terms_Accepted__c>) selectSObjectsById(idSet);
    }

    public List<Product_Terms_Accepted__c> selectByAccountApplicationId(Set<Id> idSet) {
        return (List<Product_Terms_Accepted__c>) Database.query(
                newQueryFactory().
                        setCondition('Account_Application__c in :IdSet').
                        toSOQL());
    }
}