force-app/main/default/objects/CI_Gem__c/CI_Gem__c.object-meta.xml
<CustomObject>
    <description>A gem in the context of Client Insights is a valuable nugget or gem of information associated to a particular user</description>
    <label>CI Gem</label>
    <nameField>
        <label>CI Gem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CI Gems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CI_Gem__c/fields/Dismissed__c.field-meta.xml
<CustomField>
    <fullName>Dismissed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the user has dismissed the Gem notification</description>
    <label>Dismissed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CI_Gem__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CI_Gems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CI_GemController.cls
public class CI_GemController {
    @AuraEnabled
    public static CI_ResponseDto getGemsAction(String clientId) {   
        //News article lead notifications
        List<CI_Gem__c> leadGems = CI_GemLeadController.getLeadGems(clientId);

        //Combine all above gems lists into single list
        List<CI_Gem__c> allGems = new List<CI_Gem__c>();
        allGems.addAll(leadGems);
        
        removeDeletedGems(allGems);
        
        return new CI_ResponseDto(allGems);        
    }

    @AuraEnabled
    public static CI_ResponseDto dismissGemAction(String gemId) {   
        CI_Gem__c gemToDismiss = [SELECT Dismissed__c FROM CI_Gem__c WHERE Id = :gemId AND User__c =: UserInfo.getUserId()];
        gemToDismiss.Dismissed__c = true;
        update gemToDismiss;

        return new CI_ResponseDto(gemToDismiss);        
    }

    @AuraEnabled
    public static CI_ResponseDto deleteGemAction(String gemId) {   
        CI_Gem__c gemToDelete = [SELECT Deleted__c FROM CI_Gem__c WHERE Id = :gemId AND User__c =: UserInfo.getUserId()];
        gemToDelete.Deleted__c = true;
        update gemToDelete;

        return new CI_ResponseDto(gemToDelete);        
    }

    public static void removeDeletedGems(List<CI_Gem__c> gems) {
        Integer j = 0;
        while (j < gems.size())
        {
            if(gems.get(j).Deleted__c) {
                gems.remove(j);
            } else {
                j++;
            }
        }
    }
}