force-app/main/default/objects/PBB_Note_Types__c/PBB_Note_Types__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Settings to store possible Note Types for PBB Lifestyle</description>
    <label>PBB Note Types</label>
</CustomObject>

force-app/main/default/objects/PBB_Note_Types__c/fields/Account_Notepad__c.field-meta.xml
<CustomField>
    <fullName>Account_Notepad__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether category belongs to Account Notepad or not, US-4570</description>
    <inlineHelpText>Choose if category belongs to Account Notepad</inlineHelpText>
    <label>Account Notepad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBB_Note_Types__c/fields/Customer_Notepad__c.field-meta.xml
<CustomField>
    <fullName>Customer_Notepad__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether category belongs to Customer Notepad or not, US-4570</description>
    <inlineHelpText>Choose if category belongs to Customer Notepad</inlineHelpText>
    <label>Customer Notepad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBB_Note_Types__c/fields/Note_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Note_Type_Name__c</fullName>
    <description>The type or category of the note, US-4570</description>
    <label>Note Type Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLD_PbbNoteTypes.cls
/**
 * Created by zwalczewska on 08.05.2020.
 */

public without sharing class BLD_PbbNoteTypes extends ABS_ObjectBuilderBase {

    public static final String DEF_NAME = 'testNoteType';

    public BLD_PbbNoteTypes() {
        this(getNewUnitOfWork());
    }

    public BLD_PbbNoteTypes(fflib_SObjectUnitOfWork workUnit) {
        super(PBB_Note_Types__c.sObjectType, workUnit);
        setDefaultData();
    }

    public BLD_PbbNoteTypes(PBB_Note_Types__c sObj, fflib_SObjectUnitOfWork workUnit) {
        super(sObj, workUnit);
    }

    protected override void setDefaultData() {
        setField(PBB_Note_Types__c.Name, DEF_NAME);
    }

    public BLD_PbbNoteTypes name(String value) {
        return(BLD_PbbNoteTypes) setField(PBB_Note_Types__c.Name, value);
    }

    public BLD_PbbNoteTypes noteTypeName(String value) {
        return(BLD_PbbNoteTypes) setField(PBB_Note_Types__c.Note_Type_Name__c, value);
    }

    public BLD_PbbNoteTypes accountNotepad(Boolean value) {
        return(BLD_PbbNoteTypes) setField(PBB_Note_Types__c.Account_Notepad__c, value);
    }

    public BLD_PbbNoteTypes customerNotepad(Boolean value) {
        return(BLD_PbbNoteTypes) setField(PBB_Note_Types__c.Customer_Notepad__c, value);
    }
}