force-app/main/default/objects/Ecosystem__c/Ecosystem__c.object-meta.xml
<CustomObject>
    <label>Ecosystem</label>
    <nameField>
        <displayFormat>ECO-{0000}</displayFormat>
        <label>Ecosystem ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ecosystems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ecosystem_Entity__c/Ecosystem_Entity__c.object-meta.xml
<CustomObject>
    <label>Ecosystem Entity</label>
    <nameField>
        <label>Ecosystem Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ecosystem Enitiies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ecosystem_Entity__c/fields/Ecosystem__c.field-meta.xml
<CustomField>
    <fullName>Ecosystem__c</fullName>
    <label>Ecosystem</label>
    <referenceTo>Ecosystem__c</referenceTo>
    <relationshipLabel>Ecosystem Entities</relationshipLabel>
    <relationshipName>Ecosystem_Entities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ecosystem_Entity__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ecosystem Entities</relationshipLabel>
    <relationshipName>Ecosystem_Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ecosystem_Entity__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <defaultValue>&quot;Shareholder / Director&quot;</defaultValue>
    <label>Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shareholder / Director</fullName>
            </value>
            <value>
                <fullName>Debtor / Client</fullName>
            </value>
            <value>
                <fullName>Subsidiary</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Creditor / Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BLD_EcosystemEntity.cls
@IsTest
public without sharing class BLD_EcosystemEntity extends ABS_ObjectBuilderBase{

    public BLD_EcosystemEntity() {  
        this(getNewUnitOfWork());        
    }

    public BLD_EcosystemEntity(fflib_SObjectUnitOfWork workUnit) { 
        super(Ecosystem_Entity__c.sObjectType, workUnit);
    }

    private BLD_EcosystemEntity(Ecosystem_Entity__c sObj, fflib_SObjectUnitOfWork workUnit) {
        super(sObj,workUnit);
    }

    public BLD_EcosystemEntity ecosystem(String ecosystemId){
    	return (BLD_EcosystemEntity)setField(Ecosystem_Entity__c.Ecosystem__c, ecosystemId); 
    }

    public BLD_EcosystemEntity client(String accountId){
    	return (BLD_EcosystemEntity)setField(Ecosystem_Entity__c.Entity__c, accountId); 
    }

    public BLD_EcosystemEntity entityType(String entityType){
    	return (BLD_EcosystemEntity)setField(Ecosystem_Entity__c.Entity_Type__c, entityType); 
    }

    public BLD_EcosystemEntity ecosystem(BLD_Ecosystem ecosystemBuilder) {
        return(BLD_EcosystemEntity) setRelation(Ecosystem_Entity__c.Ecosystem__c, ecosystemBuilder);
    }

}