force-app/main/default/objects/Ecosystem__c/Ecosystem__c.object-meta.xml
<CustomObject>
    <label>Ecosystem</label>
    <nameField>
        <displayFormat>ECO-{0000}</displayFormat>
        <label>Ecosystem ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ecosystems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ecosystem__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ecosystems</relationshipLabel>
    <relationshipName>Ecosystems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ecosystem__c/fields/Relationship_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Group_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The number used to group various client records belonging to a Hierarchy or Risk Group.</inlineHelpText>
    <label>Relationship Group Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BLD_Ecosystem.cls
/**
*
* @ModifiedBy Emmanuel Mulea Nocks(BlueSky)
* @date April 2021
* @description This is a builder class for Ecosystem custom object
*/
@IsTest
public without sharing class BLD_Ecosystem extends ABS_ObjectBuilderBase{

    public BLD_Ecosystem() {
        this(getNewUnitOfWork());        
    }

    public BLD_Ecosystem(fflib_SObjectUnitOfWork workUnit) { 
        super(Ecosystem__c.sObjectType, workUnit);
    }

    private BLD_Ecosystem(Ecosystem__c sObj, fflib_SObjectUnitOfWork workUnit) {
        super(sObj,workUnit);
    }

    public BLD_Ecosystem groupNumber(String groupNumber){
    	return (BLD_Ecosystem)setField(Ecosystem__c.Relationship_Group_Number__c, groupNumber);
    }
    public BLD_Ecosystem groupName(BLD_Account groupName){
    	return (BLD_Ecosystem)setRelation(Ecosystem__c.Client_Name__c, groupName);
    }
}