force-app/main/default/objects/Assessment_Opportunity__c/Assessment_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Assessment Opportunity</label>
    <nameField>
        <displayFormat>AO{0000000}</displayFormat>
        <label>Assessment Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Opportunity__c/fields/Business_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Business_Assessment__c</fullName>
    <label>Business Assessment</label>
    <referenceTo>Business_Assessment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Assessment_Opportunities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Business Assessments</relationshipLabel>
    <relationshipName>Assessment_Opportunities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Opportunity__c/fields/Total_SB_Gross_Participation__c.field-meta.xml
<CustomField>
    <fullName>Total_SB_Gross_Participation__c</fullName>
    <description>The total amount that SB will be providing the client for the opportunities selected for the business assessment. Change to Notional field SGPRT-1229</description>
    <inlineHelpText>The total amount that SB will be providing the client for the opportunities selected for the business assessment</inlineHelpText>
    <label>Total SB Gross Participation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/Business_Assessment__c.object-meta.xml
<CustomObject>
    <label>Business Assessment</label>
    <nameField>
        <displayFormat>BA{0000000}</displayFormat>
        <label>Business Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_Application_Created__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Application_Created__c</fullName>
    <description>Date that the Digital Credit Paper was created SGPRT-1201</description>
    <inlineHelpText>Date that the Digital Credit Paper was created</inlineHelpText>
    <label>Credit Paper Application Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_Application_Created_By__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Application_Created_By__c</fullName>
    <description>The person that created the Digital Credit Paper SGPRT-1201</description>
    <inlineHelpText>The person that created the Digital Credit Paper</inlineHelpText>
    <label>Credit Paper Application Created By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_Approval__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Approval__c</fullName>
    <description>Date that the Digital Credit Paper was approved SGPRT-1201</description>
    <inlineHelpText>Date that the Digital Credit Paper was approved</inlineHelpText>
    <label>Credit Paper Approval</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Approved_By__c</fullName>
    <description>The person that approved the Digital Credit Paper SGPRT-1201</description>
    <inlineHelpText>The person that approved the Digital Credit Paper</inlineHelpText>
    <label>Credit Paper Approved By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_Decline_By__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Decline_By__c</fullName>
    <description>Credit Paper Declined by SGPRT-1201</description>
    <inlineHelpText>Credit Paper Declined by</inlineHelpText>
    <label>Credit Paper Decline By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_Decline_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Decline_Date__c</fullName>
    <description>Credit Paper Declined Date SGPRT-1201</description>
    <inlineHelpText>Credit Paper Declined Date</inlineHelpText>
    <label>Credit Paper Decline Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_Decline_Reason__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Decline_Reason__c</fullName>
    <description>Credit Paper Declined Reason SGPRT-1201</description>
    <inlineHelpText>Credit Paper Declined Reason</inlineHelpText>
    <label>Credit Paper Decline Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_Declined__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Declined__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Digital Credit Paper Decline SGPRT-1201</description>
    <inlineHelpText>Digital Credit Paper Decline</inlineHelpText>
    <label>Credit Paper Declined</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_ID__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_ID__c</fullName>
    <description>Digital Credit Paper ID SGPRT-1201</description>
    <inlineHelpText>Digital Credit Paper ID</inlineHelpText>
    <label>Credit Paper ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_Sent_for_Approval__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Sent_for_Approval__c</fullName>
    <description>Date that the Digital Credit Paper was sent for approval SGPRT-1201</description>
    <inlineHelpText>Date that the Digital Credit Paper was sent for approval</inlineHelpText>
    <label>Credit Paper Sent for Approval</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_Sent_for_Approval_By__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Sent_for_Approval_By__c</fullName>
    <description>The person that sent the Digital Credit Paper for approval SGPRT-1201</description>
    <inlineHelpText>The person that sent the Digital Credit Paper for approval</inlineHelpText>
    <label>Credit Paper Sent for Approval By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Credit_Paper_URL__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_URL__c</fullName>
    <description>Digital Credit Paper URL SGPRT-1201</description>
    <inlineHelpText>Digital Credit Paper URL</inlineHelpText>
    <label>Credit Paper URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transaction Overview</fullName>
                <default>true</default>
                <label>Transaction Overview</label>
            </value>
            <value>
                <fullName>Stakeholder Contribution</fullName>
            </value>
            <value>
                <fullName>Finalisation</fullName>
            </value>
            <value>
                <fullName>Supported</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/NBAC_Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>NBAC_Meeting_Date__c</fullName>
    <description>The actual date the NBAC form is expected to be presented to the committee</description>
    <inlineHelpText>Date of which the NBAC application will be presented to the Committee</inlineHelpText>
    <label>NBAC Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/fields/Total_SB_Gross_Participation__c.field-meta.xml
<CustomField>
    <fullName>Total_SB_Gross_Participation__c</fullName>
    <description>The total amount that SB will be providing the client for the opportunities selected for the business assessment SGPRT-1229</description>
    <formula>Total_SB_Gross_Participation_of_Opps__c + Economic_Group_Parent_Credit_Limits__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The total amount that SB will be providing the Client for the Opportunities selected for the Business Assessment</inlineHelpText>
    <label>Total SB Gross Participation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_Application_Created__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Application_Created__c</fullName>
    <description>Date that the Digital Credit Paper was created [SFP-6735]</description>
    <inlineHelpText>Date that the Digital Credit Paper was created</inlineHelpText>
    <label>Credit Paper Application Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_Application_Created_By__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Application_Created_By__c</fullName>
    <description>The person that created the Digital Credit Paper [SFP-6735]</description>
    <inlineHelpText>The person that created the Digital Credit Paper</inlineHelpText>
    <label>Credit Paper Application Created By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_Approval__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Approval__c</fullName>
    <description>Date that the Digital Credit Paper was approved [SFP-6735]</description>
    <inlineHelpText>Date that the Digital Credit Paper was approved</inlineHelpText>
    <label>Credit Paper Approval</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Approved_By__c</fullName>
    <description>The person that approved the Digital Credit Paper [SFP-6735]</description>
    <inlineHelpText>The person that approved the Digital Credit Paper</inlineHelpText>
    <label>Credit Paper Approved By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_Decline_By__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Decline_By__c</fullName>
    <description>Credit Paper Declined by [SFP-6735]</description>
    <inlineHelpText>Credit Paper Declined by</inlineHelpText>
    <label>Credit Paper Decline By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_Decline_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Decline_Date__c</fullName>
    <description>Credit Paper Declined Date [SFP-6735]</description>
    <inlineHelpText>Credit Paper Declined Date</inlineHelpText>
    <label>Credit Paper Decline Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_Decline_Reason__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Decline_Reason__c</fullName>
    <description>Credit Paper Declined Reason [SFP-6735]</description>
    <inlineHelpText>Credit Paper Declined Reason</inlineHelpText>
    <label>Credit Paper Decline Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_Declined__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Declined__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Digital Credit Paper Decline [SFP-6735]</description>
    <inlineHelpText>Digital Credit Paper Decline</inlineHelpText>
    <label>Credit Paper Declined</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_ID__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_ID__c</fullName>
    <description>Digital Credit Paper ID [SFP-6735]</description>
    <inlineHelpText>Digital Credit Paper ID</inlineHelpText>
    <label>Credit Paper ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_Sent_for_Approval__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Sent_for_Approval__c</fullName>
    <description>Date that the Digital Credit Paper was sent for approval [SFP-6735]</description>
    <inlineHelpText>Date that the Digital Credit Paper was sent for approval</inlineHelpText>
    <label>Credit Paper Sent for Approval</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_Sent_for_Approval_By__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_Sent_for_Approval_By__c</fullName>
    <description>The person that sent the Digital Credit Paper for approval [SFP-6735]</description>
    <inlineHelpText>The person that sent the Digital Credit Paper for approval</inlineHelpText>
    <label>Credit Paper Sent for Approval By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Paper_URL__c.field-meta.xml
<CustomField>
    <fullName>Credit_Paper_URL__c</fullName>
    <description>Digital Credit Paper URL [SFP-6735]</description>
    <inlineHelpText>Digital Credit Paper URL</inlineHelpText>
    <label>Credit Paper URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>SFP-9031: Milestone field that displays the next Action Plan tasks subject line based on the earliest due date and where the status does not equal Completed or Cancelled</description>
    <label>Milestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_SB_Gross_Participation__c.field-meta.xml
<CustomField>
    <fullName>Total_SB_Gross_Participation__c</fullName>
    <description>The total amount that SB will be providing the client. Change to Notional field SGPRT-1229</description>
    <formula>Total_SB_Gross_Participation_Num__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The total amount that SB will be providing the client (sum of SB participation)</inlineHelpText>
    <label>Total SB Gross Participation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SEL_AssessmentOpportunities.cls
/**
* Assessment Opportunities Selector Layer class.
*
* @author Wayne Solomon
* @date 2020-06-17
*/
public with sharing class SEL_AssessmentOpportunities extends fflib_SObjectSelector {

    private Boolean assertCrud = true;
    private Boolean enforceFls = true;
    private Boolean includeSelectorFields = true;

    /**
     * Creates a new instance of the selector via the application class.
     *
     * @return SEL_AssessmentOpportunities
     */
    public static SEL_AssessmentOpportunities newInstance() {
        return (SEL_AssessmentOpportunities)ORG_Application.selector.newInstance(Assessment_Opportunity__c.SObjectType);
    }

    /**
     * Returns the list of Resourcing fields
     *
     * @return List<Schema.SObjectField>
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Assessment_Opportunity__c.Business_Assessment__c,
                Assessment_Opportunity__c.Id,
                Assessment_Opportunity__c.Opportunity__c,
                Assessment_Opportunity__c.Total_SB_Gross_Participation__c
        };
    }

    /**
     * Returns SObject type
     *
     * @return SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Assessment_Opportunity__c.sObjectType;
    }

    /**
     * Set assertCrud field's value. Field can be used when creating instance of fflib_QueryFactory to assert running user's
     * CRUD on object.
     *
     * @param assertCrud
     *
     * @return
     */
    public SEL_AssessmentOpportunities withCrudAssert(Boolean assertCrud) {
        this.assertCrud = assertCrud;
        return this;
    }

    /**
     * Set enforceFls field's value. Field can be used when creating instance of fflib_QueryFactory to enforce running user's
     * FLS on object.
     *
     * @param enforceFls
     *
     * @return
     */
    public SEL_AssessmentOpportunities withFlsEnforced(Boolean enforceFls) {
        this.enforceFls = enforceFls;
        return this;
    }

    /**
     * Set includeSelectorFields field's value. Field can be used when creating instance of fflib_QueryFactory to include SObject's fields returned
     * by getSObjectFieldList method.
     *
     * @param includeSelectorFields
     *
     * @return
     */
    public SEL_AssessmentOpportunities includeSelectorFields(Boolean includeSelectorFields){
        this.includeSelectorFields = includeSelectorFields;
        return this;
    }

    /**
     * Select records filtered by Opportunity Ids
     *
     * @param opportunityIds
     * @param withSharing
     *
     * @return
     */
    public List<Assessment_Opportunity__c> selectByOpportunityId(Set<Id> opportunityIds, Boolean withSharing) {
        String query = newQueryFactory(assertCrud, enforceFls, includeSelectorFields)
                .setCondition('Opportunity__c IN :opportunityIds')
                .toSOQL();
        if (withSharing == true) {
            return (List<Assessment_Opportunity__c>) Database.query(query);
        }
        return new WithoutSharing().selectByOpportunityId(opportunityIds, query);
    }

    /**
     * Select by opportunity Ids with DCP fields
     *
     * @param opportunityIds
     * @param withSharing
     *
     * @return
     */
    public List<Assessment_Opportunity__c> selectByOpportunityIdWithDcpFields(Set<Id> opportunityIds, Boolean withSharing) {
        String query = newQueryFactory(assertCrud, enforceFls, includeSelectorFields)
                .setCondition('Opportunity__c IN :opportunityIds AND Business_Assessment__r.IsDeleted = false')
                .selectField('Business_Assessment__r.Credit_Paper_Application_Created__c')
                .selectField('Business_Assessment__r.Credit_Paper_Application_Created_By__c')
                .selectField('Business_Assessment__r.Credit_Paper_Sent_for_Approval__c')
                .selectField('Business_Assessment__r.Credit_Paper_Sent_for_Approval_By__c')
                .selectField('Business_Assessment__r.Credit_Paper_Approval__c')
                .selectField('Business_Assessment__r.Credit_Paper_Approved_By__c')
                .selectField('Business_Assessment__r.Credit_Paper_ID__c')
                .selectField('Business_Assessment__r.Credit_Paper_URL__c')
                .selectField('Business_Assessment__r.Credit_Paper_Declined__c')
                .selectField('Business_Assessment__r.Credit_Paper_Decline_Reason__c')
                .selectField('Business_Assessment__r.Credit_Paper_Decline_Date__c')
                .selectField('Business_Assessment__r.Credit_Paper_Decline_By__c')
                .selectField('Business_Assessment__r.Name')
                .selectField('Business_Assessment__r.Milestone__c')
                .selectField('Business_Assessment__r.NBAC_Meeting_Date__c')
                .selectField('Business_Assessment__r.NBAC_Committee__c')
                .selectField('Business_Assessment__r.Approval_Milestone_Date__c')
                .selectField('Business_Assessment__r.LastModifiedDate')
                .toSOQL();
        if (withSharing == true) {
            return (List<Assessment_Opportunity__c>) Database.query(query);
        }
        return new WithoutSharing().selectByOpportunityIdWithDcpFields(opportunityIds, query);
    }

    /**
     * Select records filtered by Business Assessment Ids
     *
     * @param businessAssessmentIds
     * @param withSharing
     *
     * @return
     */
    public List<Assessment_Opportunity__c> selectByBusinessAssessmentId(Set<Id> businessAssessmentIds, Boolean withSharing) {
        String query = newQueryFactory(assertCrud, enforceFls, includeSelectorFields)
                .setCondition('Business_Assessment__c IN :businessAssessmentIds')
                .toSOQL();
        if (withSharing == true) {
            return (List<Assessment_Opportunity__c>) Database.query(query);
        }
        return new WithoutSharing().selectByBusinessAssessmentId(businessAssessmentIds, query);
    }

    /**
     * Select deleted by Business Assessment Ids
     *
     * @param businessAssessmentIds
     * @param withSharing
     *
     * @return
     */
    public List<Assessment_Opportunity__c> selectDeletedByBusinessAssessmentId(Set<Id> businessAssessmentIds, Boolean withSharing) {
        String query = newQueryFactory(assertCrud, enforceFls, includeSelectorFields)
                .setCondition('Business_Assessment__c IN :businessAssessmentIds AND IsDeleted = true')
                .toSOQL() + ' ALL ROWS';
        if (withSharing == true) {
            return (List<Assessment_Opportunity__c>) Database.query(query);
        }
        return new WithoutSharing().selectDeletedByBusinessAssessmentId(businessAssessmentIds, query);
    }

    private without sharing class WithoutSharing {

        private List<Assessment_Opportunity__c> selectByOpportunityId(Set<Id> opportunityIds, String query) {
            return (List<Assessment_Opportunity__c>) Database.query(query);
        }

        private List<Assessment_Opportunity__c> selectByOpportunityIdWithDcpFields(Set<Id> opportunityIds, String query) {
            return (List<Assessment_Opportunity__c>) Database.query(query);
        }

        private List<Assessment_Opportunity__c> selectByBusinessAssessmentId(Set<Id> businessAssessmentIds, String query) {
            return (List<Assessment_Opportunity__c>) Database.query(query);
        }

        private List<Assessment_Opportunity__c> selectDeletedByBusinessAssessmentId(Set<Id> businessAssessmentIds, String query) {
            return (List<Assessment_Opportunity__c>) Database.query(query);
        }
    }
}