force-app/main/default/objects/Assessment_Opportunity__c/Assessment_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Assessment Opportunity</label>
    <nameField>
        <displayFormat>AO{0000000}</displayFormat>
        <label>Assessment Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Business Assessments</relationshipLabel>
    <relationshipName>Assessment_Opportunities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Actual_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Close_Date__c</fullName>
    <inlineHelpText>Date is system generated upon closing of the opportunity, to amend please contact an administrator.</inlineHelpText>
    <label>Actual Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GCCR_Status__c.field-meta.xml
<CustomField>
    <fullName>GCCR_Status__c</fullName>
    <inlineHelpText>Status of the Opportunity with respect to Conflicts Clearance</inlineHelpText>
    <label>GCCR Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted for Conflicts Clearing</fullName>
            </value>
            <value>
                <fullName>Awaiting Response from the Conflicts Control Room</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Not Cleared</fullName>
            </value>
            <value>
                <fullName>Cleared with Conditions</fullName>
            </value>
            <value>
                <fullName>Re-submitted for Conflicts Clearing as Key Information has been Modified</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Sensitive__c.field-meta.xml
<CustomField>
    <fullName>Price_Sensitive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Restrict visibility of the Opportunity</inlineHelpText>
    <label>MNPI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Event_Report_Source__c.field-meta.xml
<CustomField>
    <fullName>Primary_Event_Report_Source__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Event Report where this Opportunity was identified/originated</description>
    <inlineHelpText>The Event Report where this Opportunity was identified/originated</inlineHelpText>
    <label>Primary Event Report Source</label>
    <referenceTo>Call_Report__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reason_Won_Lost_Comments__c.field-meta.xml
<CustomField>
    <fullName>Reason_Won_Lost_Comments__c</fullName>
    <inlineHelpText>A brief description of why the Opportunity was won / lost (255 characters or less)</inlineHelpText>
    <label>Reason Won / Lost Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Short_Summary__c.field-meta.xml
<CustomField>
    <fullName>Short_Summary__c</fullName>
    <description>Devesh : 03sept 2010 - this is a Mandattory field for the user to key in a short description about the opportunity</description>
    <inlineHelpText>The Short Summary is mandatory and is used for Manco / Exco Opportunity reporting  (100 characters or less)</inlineHelpText>
    <label>Short Summary</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SB_Product__c/SB_Product__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Products as Standard Bank have requirements that cannot be met with standard object.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Prod-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SB_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BLD_Opportunity.cls
/**
 * @description Builder class for Opportunity object
 *
 * @author unknown
 * @date unknown
 */
@IsTest
public without sharing class BLD_Opportunity extends ABS_ObjectBuilderBase {

	public static final Date DEF_CLOSED = System.today();
	public static final String DEF_NAME = 'name',
	DEF_STAGE = '2 - Develop',
	DEF_SUMMARY = 'test opportunity',
	DEF_CURRENCY = 'ZAR',
	WON_COMMENTS = 'StdBank is the best.',
	LOST_COMMENTS = 'StdBank is average.';

	public BLD_Opportunity() {
		this(getNewUnitOfWork());
	}

	public BLD_Opportunity(fflib_SObjectUnitOfWork workUnit) {
		super(Opportunity.SObjectType, workUnit);
	}

	private BLD_Opportunity(Opportunity sObj, fflib_SObjectUnitOfWork workUnit) {
		super(sObj, workUnit);
	}

	public BLD_Opportunity currency(String currencyCode) {
		return(BLD_Opportunity) setField(Opportunity.CurrencyIsoCode, currencyCode);
	}

	public BLD_Opportunity isPrivate(Boolean isPrivate) {
		return (BLD_Opportunity) setField(Opportunity.IsPrivate, isPrivate);
	}

	public BLD_Opportunity id(Id oppId){
		return (BLD_Opportunity) setField(Opportunity.Id, oppId);
	}

	public BLD_Opportunity stage(String stageName) {
		return(BLD_Opportunity) setField(Opportunity.StageName, stageName);
	}

	public BLD_Opportunity develop() {
		return(BLD_Opportunity) setField(Opportunity.StageName, DMN_Opportunity.ST_DEVELOP);
	}

	public BLD_Opportunity closedLost() {
		return (BLD_Opportunity) setField(Opportunity.StageName, DMN_Opportunity.ST_CLOSED_LOST)
			.setField(Opportunity.Reason_Won_Lost_Comments__c, LOST_COMMENTS);
	}

	public BLD_Opportunity closedWon() {
		return(BLD_Opportunity) setField(Opportunity.StageName, DMN_Opportunity.ST_CLOSED_WON)
		.setField(Opportunity.Reason_Won_Lost_Comments__c, WON_COMMENTS);
	}
	public BLD_Opportunity closeDate(Date closeDate) {
		return(BLD_Opportunity) setField(Opportunity.CloseDate, closeDate);
	}

	public BLD_Opportunity actualCloseDate(Date actualCloseDate) {
		return(BLD_Opportunity) setField(Opportunity.Actual_Close_Date__c, actualCloseDate);
	}

	public BLD_Opportunity name(String name){
		return (BLD_Opportunity) setField(Opportunity.Name, name);
	}

	public override void setDefaultData() {
		setField(Opportunity.Name, DEF_NAME)
		.setField(Opportunity.CloseDate, DEF_CLOSED)
		.setField(Opportunity.StageName, DEF_STAGE)
		.setField(Opportunity.Short_Summary__c, DEF_SUMMARY)
		.setField(Opportunity.CurrencyIsoCode, DEF_CURRENCY);
	}

	public BLD_Opportunity linkAccountId(Id accId) {
		return(BLD_Opportunity) setField(Opportunity.AccountId, accId);
	}
	public BLD_Opportunity ownerId(Id ownerId) {
		return(BLD_Opportunity) setField(Opportunity.OwnerId, ownerId);
	}
	public BLD_Opportunity client(BLD_Account clientBld) {
		return(BLD_Opportunity) setRelation(Opportunity.AccountId, clientBld);
	}
	public BLD_Opportunity gccrStatus(String gccrStatus){
	  return (BLD_Opportunity) setField(Opportunity.GCCR_Status__c, gccrStatus);
	}

	public BLD_Opportunity eventReportSource(BLD_CallReport callReportBuilder) {
		return (BLD_Opportunity) setRelation(Opportunity.Primary_Event_Report_Source__c, callReportBuilder);
	}

	public BLD_Opportunity priceSensitive(Boolean bool) {
		return (BLD_Opportunity) setField(Opportunity.Price_Sensitive__c, bool);
	}

	public BLD_Opportunity addProduct(BLD_Product productBuilder) {
		return (BLD_Opportunity) addChild(SB_Product__c.Opportunity__c, productBuilder);
	}

	public BLD_Opportunity addTeamMember(BLD_OpportunityTeamMember otmBuilder) {
		return (BLD_Opportunity) addChild(OpportunityTeamMember.OpportunityId, otmBuilder);
	}

	public BLD_Opportunity addAssessmentOpportunity(BLD_Assessment_Opportunity assessOppBuilder) {
		return (BLD_Opportunity) addChild(Assessment_Opportunity__c.Opportunity__c, assessOppBuilder);
	}

	public BLD_Opportunity addTask(BLD_Task taskBuilder) {
		return(BLD_Opportunity) addChild(Task.WhatId, taskBuilder);
	}
}