force-app/main/default/objects/Assessment_Opportunity__c/Assessment_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Assessment Opportunity</label>
    <nameField>
        <displayFormat>AO{0000000}</displayFormat>
        <label>Assessment Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Opportunity__c/fields/Business_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Business_Assessment__c</fullName>
    <label>Business Assessment</label>
    <referenceTo>Business_Assessment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Assessment_Opportunities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Opportunity__c/fields/MNPI__c.field-meta.xml
<CustomField>
    <fullName>MNPI__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether there is an MNPI opportunity included on Assessment Opportunity</description>
    <label>MNPI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assessment_Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Business Assessments</relationshipLabel>
    <relationshipName>Assessment_Opportunities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Business_Assessment__c/Business_Assessment__c.object-meta.xml
<CustomObject>
    <label>Business Assessment</label>
    <nameField>
        <displayFormat>BA{0000000}</displayFormat>
        <label>Business Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Assessment__c/fields/MNPI__c.field-meta.xml
<CustomField>
    <fullName>MNPI__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether there is an MNPI opportunity included on the NBAC</description>
    <inlineHelpText>Indicates whether there is an MNPI opportunity included on the NBAC</inlineHelpText>
    <label>MNPI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Sensitive__c.field-meta.xml
<CustomField>
    <fullName>Price_Sensitive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Restrict visibility of the Opportunity</inlineHelpText>
    <label>MNPI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BCH_PopulateMNPIOnBA_TEST.cls
/**
 * Test class for BCH_PopulateMNPIOnBA class
 *
 * @author		Youssef Ibrahim (yibrahim@deloittece.com)
 * @date		December 2020
 */
@IsTest
public class BCH_PopulateMNPIOnBA_TEST {
    static User testUser;
    static Assessment_Opportunity__c assessmentOpportunity;

    @TestSetup
    static void setup() {
        TEST_DataFactory.generateConfiguration();
        fflib_SObjectUnitOfWork uow;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
            testUser = (User) new BLD_USER(uow).userName('testMNPIBA@test.com').useCib().division('Transactional Products and Services').syncContact().getRecord();
            uow.commitWork();
        }
        System.runAs(testUser) {
             BLD_Opportunity bldOpp = new BLD_Opportunity(uow)
                    .priceSensitive(true)
                    .name('Test populate MNPI')
                    .addAssessmentOpportunity(
                            new BLD_Assessment_Opportunity(uow)
                            .businessAssessment(new BLD_BusinessAssessment(uow).mnpi(false))
                    );
            uow.commitWork();
        }

    }

    static void getData() {
        testUser = [
                SELECT Username, Division, IsActive
                FROM User
                WHERE Username = 'testMNPIBA@test.com'
                LIMIT 1];

        assessmentOpportunity = [
                SELECT Id, Opportunity__r.Price_Sensitive__c,
                        Business_Assessment__r.MNPI__c
                FROM Assessment_Opportunity__c
                WHERE Opportunity__r.Name = 'Test populate MNPI'
                LIMIT 1
        ];
    }


    @IsTest
    static void shouldUpdateBaWithMnpi() {
        getData();
        System.runAs(testUser) {

            System.assert(!assessmentOpportunity.Business_Assessment__r.MNPI__c);

            Test.startTest();
            BCH_PopulateMNPIOnBA populateMNPIonBA = new BCH_PopulateMNPIOnBA(new List<String>{'testMNPIBA@test.com'});
            Database.executeBatch(populateMNPIonBA);
            Test.stopTest();
            Assessment_Opportunity__c resultingAO = [
                    SELECT Id, Opportunity__r.Price_Sensitive__c,
                            Business_Assessment__r.MNPI__c
                    FROM Assessment_Opportunity__c
                    WHERE Id = :assessmentOpportunity.Id
            ];
            System.assert(resultingAO.Business_Assessment__r.MNPI__c);

        }
    }
}