force-app/main/default/objects/OSB_AdobeAnalyticsData__mdt/OSB_AdobeAnalyticsData__mdt.object-meta.xml
<CustomObject>
    <description>US-4233: Used to store data layer for Adobe Analytics. Use Page URL to identify proper data set.</description>
    <label>OSB Adobe Analytics Data</label>
    <pluralLabel>OSB Adobe Analytics Data</pluralLabel>
</CustomObject>

force-app/main/default/objects/OSB_AdobeAnalyticsData__mdt/fields/Page_Category__c.field-meta.xml
<CustomField>
    <fullName>Page_Category__c</fullName>
    <description>Data for pageCategory parameter in Adobe Analytics request</description>
    <label>Page Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OSB_AdobeAnalyticsData__mdt/fields/Page_Section__c.field-meta.xml
<CustomField>
    <fullName>Page_Section__c</fullName>
    <description>Page section name, should be filled in if page is part of a single page application and should be tracked as separate page.</description>
    <label>Page Section</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OSB_AdobeAnalyticsData__mdt/fields/Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Page_URL__c</fullName>
    <description>Stores community page url (after last /)
Used to identify proper data set</description>
    <label>Page URL</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OSB_AdobeAnalyticsData__mdt/fields/Sub_Section_1__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section_1__c</fullName>
    <description>Data for pageSubSection1 parameter in Adobe Analytics request</description>
    <label>Sub Section 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OSB_AdobeAnalyticsData__mdt/fields/Sub_Section_2__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section_2__c</fullName>
    <description>Data for pageSubSection2 parameter in Adobe Analytics request</description>
    <label>Sub Section 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OSB_AdobeAnalyticsData__mdt/fields/Sub_Section_3__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section_3__c</fullName>
    <description>Data for pageSubSection2 parameter in Adobe Analytics request</description>
    <label>Sub Section 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OSB_AdobeAnalyticsData__mdt/fields/Sub_Section_4__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section_4__c</fullName>
    <description>Data for pageSubSection4 parameter in Adobe Analytics request</description>
    <label>Sub Section 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OSB_AdobeAnalyticsData__mdt/fields/Sub_Section_5__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section_5__c</fullName>
    <description>Data for pageSubSection5 parameter in Adobe Analytics request</description>
    <label>Sub Section 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SEL_AdobeAnalyticsData.cls
/**
 * Selector class for OSB_AdobeAnalyticsData__mdt custom metadata
 *
 * @author Wojciech Kowalczyk (wkowalczyk@deloittece.com)
 * @date April 2020
 */
public with sharing class SEL_AdobeAnalyticsData extends fflib_SObjectSelector {

    /**
     * Creates a new instance of the selector via the application class. This is here to allow unit tests to override
	 * and inject a mock instead of this class or to switch out this class for a new version.
     *
     */
    public static SEL_AdobeAnalyticsData newInstance() {
        return (SEL_AdobeAnalyticsData) ORG_Application.selector.newInstance(OSB_AdobeAnalyticsData__mdt.SObjectType);
    }

    /**
     * Returns the SObject type for the selector. This is used to retrieve the sObject name when building the SOQL
     * queries.
     */
    public SObjectType getSObjectType() {
        return OSB_AdobeAnalyticsData__mdt.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                OSB_AdobeAnalyticsData__mdt.Page_Category__c,
                OSB_AdobeAnalyticsData__mdt.Page_Name__c,
                OSB_AdobeAnalyticsData__mdt.Sub_Section_1__c,
                OSB_AdobeAnalyticsData__mdt.Sub_Section_2__c,
                OSB_AdobeAnalyticsData__mdt.Sub_Section_3__c,
                OSB_AdobeAnalyticsData__mdt.Sub_Section_4__c,
                OSB_AdobeAnalyticsData__mdt.Sub_Section_5__c
        };
    }

    /**
     * Selects OSB_AdobeAnalyticsData__mdt based on page url
     *
     * @param pageUrls - url of current page
     *
     * @return list of OSB_AdobeAnalyticsData__mdt
     */
    public List<OSB_AdobeAnalyticsData__mdt> selectByPageUrl(Set<String> pageUrls) {
        return Database.query(
                newQueryFactory(false, false, true)
                        .setCondition('Page_URL__c IN :pageUrls')
                        .toSOQL());
    }

    /**
     * Selects OSB_AdobeAnalyticsData__mdt based on single page application section
     *
     * @param pageSections - name of current single page application section
     *
     * @return list of OSB_AdobeAnalyticsData__mdt
     */
    public List<OSB_AdobeAnalyticsData__mdt> selectByPageSection(Set<String> pageSections) {
        return Database.query(
                newQueryFactory(false, false, true)
                        .setCondition('Page_Section__c IN :pageSections')
                        .toSOQL());
    }
}