force-app/main/default/objects/AOB_ProductAOContent__c/AOB_ProductAOContent__c.object-meta.xml
<CustomObject>
    <label>Product AO Content</label>
    <nameField>
        <label>Product AO Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product AO Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AOB_ProductAOContent__c/fields/AOB_ContentType__c.field-meta.xml
<CustomField>
    <fullName>AOB_ContentType__c</fullName>
    <description>Type of the AO content (indicates where it should be displayed)</description>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NextActions</fullName>
                <label>What happens next?</label>
            </value>
            <value>
                <fullName>AppComplete</fullName>
                <label>Once your application is complete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AOB_ProductAOContent__c/fields/AOB_description__c.field-meta.xml
<CustomField>
    <fullName>AOB_description__c</fullName>
    <description>description of the content ( what to display for customer)</description>
    <label>description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/AOB_ProductAOContent__c/fields/AOB_HelpText__c.field-meta.xml
<CustomField>
    <fullName>AOB_HelpText__c</fullName>
    <description>help text if applicable</description>
    <label>Help Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AOB_ProductAOContent__c/fields/AOB_Product__c.field-meta.xml
<CustomField>
    <fullName>AOB_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent product(show this content is customer selected this product)</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product AO Content</relationshipLabel>
    <relationshipName>Product_AO_Content</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AOB_ProductAOContent__c/fields/AOB_Sequence__c.field-meta.xml
<CustomField>
    <fullName>AOB_Sequence__c</fullName>
    <description>order of the content</description>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AOB_ProductAOContent__c/fields/AOB_ShowIFBPID__c.field-meta.xml
<CustomField>
    <fullName>AOB_ShowIFBPID__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show this content only if the customer has a bpid</description>
    <label>Show only for customers with BPID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AOB_ProductAOContent__c/fields/AOB_ShowIFNOBPID__c.field-meta.xml
<CustomField>
    <fullName>AOB_ShowIFNOBPID__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show this content only if the customer doesn&apos;t have a bpid</description>
    <label>Show only for customers without BPID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SEL_AOBProductContent.cls
/**
 * Field Selector Layer
 * 
 * @author Salesforce
 *
 * @date Oct 29th 2021
 */
public with sharing class SEL_AOBProductContent extends fflib_SObjectSelector {
    private static Set<String> fields=new Set<String>{'Id', 'AOB_Product__c','AOB_Description__c','AOB_HelpText__c','AOB_sequence__c','AOB_ContentType__c'};
	
    /**
     * getSObjectFieldList
     * @return List<Schema.SObjectField>
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
                AOB_ProductAOContent__c.Name,
                AOB_ProductAOContent__c.Id,
                AOB_ProductAOContent__c.AOB_Product__c,
                AOB_ProductAOContent__c.AOB_Description__c,
                AOB_ProductAOContent__c.AOB_HelpText__c,
                AOB_ProductAOContent__c.AOB_sequence__c,
                AOB_ProductAOContent__c.AOB_ContentType__c
        };
    }

    /**
     * selectById
     * @return Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return AOB_ProductAOContent__c.sObjectType;
    }

	/**
	 * @description Creates a new instance of the selector via the application class. This is here to allow unit tests to override
	 * and inject a mock instead of this class or to switch out this class for a new version.
	 * @return SEL_Accounts
	 */
	public static SEL_AOBProductContent newInstance() {
		return(SEL_AOBProductContent) ORG_Application.selector.newInstance(AOB_ProductAOContent__c.SObjectType);
	}
    /**
     * Select without conditions
     *
     * @return List<AOB_ProductAOContent__c>
     */
    public List<AOB_ProductAOContent__c> selectWithoutCondition() {
        return (List<AOB_ProductAOContent__c>) Database.query(
                newQueryFactory()
                        .toSOQL()
        );
    }
    
    /**
     * Select by section
     * @param relatedProductIds Set<Id>
     * @param hasbpId Boolean
     * @return List<AOB_ProductAOContent__c>
     */
    public List<AOB_ProductAOContent__c> selectContentByProduct(Set<Id> relatedProductIds,boolean hasbpId) {
        fflib_QueryFactory fieldQueryFactory = newQueryFactory(false, false, false);
        if(hasbpId){
			fieldQueryFactory.setCondition('AOB_Product__c In :relatedProductIds AND (AOB_ShowIFBPID__c=true OR (AOB_ShowIFBPID__c=false AND AOB_ShowIFNOBPID__c =false))');
        }
        else{ 
			fieldQueryFactory.setCondition('AOB_Product__c In :relatedProductIds AND (AOB_ShowIFNOBPID__c=true OR (AOB_ShowIFBPID__c=false AND AOB_ShowIFNOBPID__c =false))');
        }
		fieldQueryFactory.selectFields(fields);  

        return Database.query(fieldQueryFactory.toSOQL());
        
    }
    
}