force-app/main/default/objects/Option_List_Item__c/Option_List_Item__c.object-meta.xml
<CustomObject>
    <description>Custom object use to store selectable values that are too large for a picklist and will allow users to search based n the named field values using a standard lookup field</description>
    <label>Option List Item</label>
    <nameField>
        <label>Option List Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Option List Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Option_List_Item__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>SGPRT- 3817 Field used to capture Company Code.</description>
    <inlineHelpText>Values found in FMI file mapped to the Legal Entity of Booking values.</inlineHelpText>
    <label>Company Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Option_List_Item__c/fields/Legal_Entity_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_of_Booking__c</fullName>
    <description>SGPRT- 3817 field used in Profit Centre filtering on Product.</description>
    <label>Legal Entity of Booking</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SEL_Option_List_Item.cls
/**
 * Selector layer class for Option List Item SObject
 *
 * @author Joanna Milosz (jmilosz@deloittece.com)
 * @date April 2021
 */
public with sharing class SEL_Option_List_Item extends fflib_SObjectSelector{
    /**
     * This is used to retrieve the sObject name when building the SOQL
     * queries.
     *
     * @return the SObject type for the selector.
    */
    public Schema.SObjectType getSObjectType(){
        return Option_List_Item__c.SObjectType;
    }

    /**
     * Creates a new instance of the selector via the application class. This is here to allow unit tests to override
     * and inject a mock instead of this class or to switch out this class for a new version.
     *
     * @return instance of the class
    */
    public static SEL_Option_List_Item newInstance() {
        return (SEL_Option_List_Item) ORG_Application.selector.newInstance(Option_List_Item__c.SObjectType);
    }

    /**
     * This is used to retrieve a specific set of SObject fields
     *
     * @return List of SObjectField
    */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
                Option_List_Item__c.Id,
                Option_List_Item__c.Name,
                Option_List_Item__c.Legal_Entity_of_Booking__c,
                Option_List_Item__c.Company_Code__c
        };
    }
    /**
     * Select without conditions
     *
     * @return List<Option_List_Item__c>
     */
    public List<Option_List_Item__c> selectWithoutCondition() {
        return (List<Option_List_Item__c>) Database.query(
                newQueryFactory()
                        .toSOQL()
        );
    }
    /**
     * Select by name
     *
     * @param names set record names
     * @return List<Option_List_Item__c>
     */
    public List<Option_List_Item__c> selectByName(Set<String> names) {
        return (List<Option_List_Item__c>) Database.query(
                newQueryFactory(false, false, true).
                        setCondition('Name in :names').
                        toSOQL());
    }

}