force-app/main/default/objects/Option_List_Item__c/Option_List_Item__c.object-meta.xml
<CustomObject>
    <description>Custom object use to store selectable values that are too large for a picklist and will allow users to search based n the named field values using a standard lookup field</description>
    <label>Option List Item</label>
    <nameField>
        <label>Option List Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Option List Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Option_List_Item__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>SGPRT- 3817 Field used to capture Company Code.</description>
    <inlineHelpText>Values found in FMI file mapped to the Legal Entity of Booking values.</inlineHelpText>
    <label>Company Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Option_List_Item__c/fields/Legal_Entity_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_of_Booking__c</fullName>
    <description>SGPRT- 3817 field used in Profit Centre filtering on Product.</description>
    <label>Legal Entity of Booking</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitCentreMatrix__c/ProfitCentreMatrix__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Profit Centre Matrix</label>
</CustomObject>

force-app/main/default/objects/ProfitCentreMatrix__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitCentreMatrix__c/fields/Legal_Entity_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_of_Booking__c</fullName>
    <description>SGPRT- 3817 field used in Profit Centre filtering on Product.</description>
    <inlineHelpText>The general ledger (GL) unit profit centre that the revenue/asset will be allocated to. This value is dependent on the Legal Entity of Booking selected.</inlineHelpText>
    <label>Legal Entity of Booking</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TRH_Option_List_Item_Test.cls
/**
 * Test class for TRH_Option_List_Item class.
 * <br/>SGPRT-3817
 *
 * @author Joanna Milosz (jmilosz@deloittece.com)
 * @date January 2021
 */
@isTest
public with sharing class TRH_Option_List_Item_Test {

    @testSetup static void setupData() {


        ProfitCentreMatrix__c[] profitCenters = TEST_DataFactory.getProfitCentersSettings();
        insert profitCenters;
    }

    @isTest
    public static void handleBeforeInsertTest(){
        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
        new BLD_Option_List_Item(uow).companyCode(4015).name('Profit Center Test 1').proftCenterObject('Products');
        new BLD_Option_List_Item(uow).companyCode(7005).name('Profit Center Test 2').proftCenterObject('Products');
        Test.startTest();
        uow.commitWork();
        SEL_Option_List_Item selOptionListItem = SEL_Option_List_Item.newInstance();
        List<Option_List_Item__c> profitCenters = selOptionListItem.selectWithoutCondition();
        Test.stopTest();

        System.assertEquals('Namibia - Standard Bank Namibia Limited,', profitCenters[0].Legal_Entity_of_Booking__c);
        System.assertEquals('Angola - Standard Bank de Angola S.A.,', profitCenters[1].Legal_Entity_of_Booking__c);
        System.assertEquals(2, profitCenters.size());
    }

    @isTest
    public static void handleBeforeUpdateTest(){
        fflib_SObjectUnitOfWork uow = ABS_ObjectBuilderBase.getNewUnitOfWork();
        new BLD_Option_List_Item(uow).companyCode(4015).name('Profit Center Test 1').proftCenterObject('Products');
        new BLD_Option_List_Item(uow).companyCode(7005).name('Profit Center Test 2').proftCenterObject('Products');
        uow.commitWork();
		SEL_Option_List_Item selOptionListItem = SEL_Option_List_Item.newInstance();
        List<Option_List_Item__c> profitCenters = selOptionListItem.selectWithoutCondition();
        Test.startTest();
        profitCenters[0].Company_Code__c = 7022;
        update profitCenters[0];
        SEL_Option_List_Item selOptionListItemAfterUpdate = SEL_Option_List_Item.newInstance();
        List<Option_List_Item__c> profitCentersAfterUpdate = selOptionListItemAfterUpdate.selectWithoutCondition();
        Test.stopTest();

        System.assertEquals('Mauritius - Standard Bank (Mauritius) Limited,', profitCentersAfterUpdate[0].Legal_Entity_of_Booking__c);
        System.assertEquals(2, profitCenters.size());
    }

}